--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['town']['skill_effect'] = {
	[1] = {
		id = 1,
		type = 1,
		param1 = '5'
	},
	[2] = {
		id = 2,
		type = 1,
		param1 = '5%'
	},
	[3] = {
		id = 3,
		type = 2,
		param1 = '5',
		param3 = 4
	},
	[4] = {
		id = 4,
		type = 3,
		param1 = '50'
	},
	[5] = {
		id = 5,
		type = 4
	},
	[6] = {
		id = 6,
		type = 5,
		param1 = '2'
	},
	[7] = {
		id = 7,
		type = 6,
		param1 = '2',
		param2 = '3',
		param3 = 4
	},
	[8] = {
		id = 8,
		type = 7,
		param1 = '10%'
	},
	[9] = {
		id = 9,
		type = 8,
		param1 = '10%'
	},
	[10] = {
		id = 10,
		type = 9,
		param1 = '5%'
	},
	[11] = {
		id = 11,
		type = 10,
		param1 = '5%',
		param2 = '10%',
		param3 = 2
	},
	[12] = {
		id = 12,
		type = 11,
		param1 = '10%'
	},
	[13] = {
		id = 13,
		type = 12,
		param1 = '5'
	},
	[14] = {
		id = 14,
		type = 13,
		param1 = '5',
		param2 = '10',
		param3 = 1
	},
	[15] = {
		id = 15,
		type = 14,
		param1 = '10%'
	},
	__size = 15,
	__default = {
		__index = {
			type = 0,
			param1 = '”“',
			param2 = '”“',
			param3 = 0
		}
	}
}
return csv.town.skill_effect