--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['yunying']['fightpointaward'] = {
	[1] = {
		id = 1,
		huodongID = 1001,
		fightPointRequire = 80000,
		award = {[951] = 20, ['rmb'] = 1000, [501] = 4, __size = 3}
	},
	[2] = {
		id = 2,
		huodongID = 1001,
		fightPointRequire = 70000,
		award = {[951] = 16, ['rmb'] = 1000, [501] = 3, __size = 3}
	},
	[3] = {
		id = 3,
		huodongID = 1001,
		fightPointRequire = 60000,
		award = {[951] = 12, ['rmb'] = 800, [501] = 3, __size = 3}
	},
	[4] = {
		id = 4,
		huodongID = 1001,
		fightPointRequire = 50000,
		award = {[951] = 8, ['rmb'] = 500, [501] = 2, __size = 3}
	},
	[5] = {
		id = 5,
		huodongID = 1001,
		fightPointRequire = 40000,
		award = {[951] = 5, ['rmb'] = 500, [501] = 2, __size = 3}
	},
	[6] = {
		id = 6,
		huodongID = 1001,
		fightPointRequire = 30000,
		award = {[951] = 3, ['rmb'] = 150, [501] = 1, __size = 3}
	},
	[7] = {
		id = 7,
		huodongID = 1001,
		fightPointRequire = 20000,
		award = {[951] = 1, ['rmb'] = 100, [501] = 1, __size = 3}
	},
	__size = 7,
	__default = {
		__index = {
			huodongID = 0,
			fightPointRequire = 0,
			award = {__size = 0}
		}
	}
}
return csv.yunying.fightpointaward