--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[2] = {[11] = 30, ['gold'] = 200000, ['rmb'] = 160, __size = 3}, 
	[4] = {[519] = 2, ['gold'] = 500000, ['rmb'] = 300, __size = 3}, 
	[6] = {['rmb'] = 300, [452] = 50, [502] = 3, __size = 3}, __size = 3}
local __data_t__award = {
	[123] = __predefine_t__[6],
	[126] = __predefine_t__[6],
	[127] = __predefine_t__[6],
	[122] = __predefine_t__[6],
	[115] = __predefine_t__[4],
	[114] = __predefine_t__[4],
	[117] = __predefine_t__[4],
	[116] = __predefine_t__[4],
	[124] = __predefine_t__[6],
	[125] = __predefine_t__[6],
	[113] = __predefine_t__[4],
	[112] = __predefine_t__[4],
	[102] = __predefine_t__[2],
	[103] = __predefine_t__[2],
	[101] = __predefine_t__[2],
	[106] = __predefine_t__[2],
	[107] = __predefine_t__[2],
	[104] = __predefine_t__[2],
	[105] = __predefine_t__[2]
}

csv['yunying']['weeklycard'] = {
	[101] = {
		id = 101,
		huodongID = 1001,
		day = 1,
		award = __data_t__award[101]
		-- {[11] = 30, ['gold'] = 200000, ['rmb'] = 160, __size = 3}
	},
	[102] = {
		id = 102,
		huodongID = 1001,
		day = 2,
		award = __data_t__award[102]
		-- {[11] = 30, ['gold'] = 200000, ['rmb'] = 160, __size = 3}
	},
	[103] = {
		id = 103,
		huodongID = 1001,
		day = 3,
		award = __data_t__award[103]
		-- {[11] = 30, ['gold'] = 200000, ['rmb'] = 160, __size = 3}
	},
	[104] = {
		id = 104,
		huodongID = 1001,
		day = 4,
		award = __data_t__award[104]
		-- {[11] = 30, ['gold'] = 200000, ['rmb'] = 160, __size = 3}
	},
	[105] = {
		id = 105,
		huodongID = 1001,
		day = 5,
		award = __data_t__award[105]
		-- {[11] = 30, ['gold'] = 200000, ['rmb'] = 160, __size = 3}
	},
	[106] = {
		id = 106,
		huodongID = 1001,
		day = 6,
		award = __data_t__award[106]
		-- {[11] = 30, ['gold'] = 200000, ['rmb'] = 160, __size = 3}
	},
	[107] = {
		id = 107,
		huodongID = 1001,
		day = 7,
		award = __data_t__award[107]
		-- {[11] = 30, ['gold'] = 200000, ['rmb'] = 160, __size = 3}
	},
	[111] = {
		id = 111,
		huodongID = 1002,
		day = 1,
		award = {[519] = 6, ['gold'] = 2000000, ['rmb'] = 980, __size = 3}
	},
	[112] = {
		id = 112,
		huodongID = 1002,
		day = 2,
		award = __data_t__award[112]
		-- {[519] = 2, ['gold'] = 500000, ['rmb'] = 300, __size = 3}
	},
	[113] = {
		id = 113,
		huodongID = 1002,
		day = 3,
		award = __data_t__award[113]
		-- {[519] = 2, ['gold'] = 500000, ['rmb'] = 300, __size = 3}
	},
	[114] = {
		id = 114,
		huodongID = 1002,
		day = 4,
		award = __data_t__award[114]
		-- {[519] = 2, ['gold'] = 500000, ['rmb'] = 300, __size = 3}
	},
	[115] = {
		id = 115,
		huodongID = 1002,
		day = 5,
		award = __data_t__award[115]
		-- {[519] = 2, ['gold'] = 500000, ['rmb'] = 300, __size = 3}
	},
	[116] = {
		id = 116,
		huodongID = 1002,
		day = 6,
		award = __data_t__award[116]
		-- {[519] = 2, ['gold'] = 500000, ['rmb'] = 300, __size = 3}
	},
	[117] = {
		id = 117,
		huodongID = 1002,
		day = 7,
		award = __data_t__award[117]
		-- {[519] = 2, ['gold'] = 500000, ['rmb'] = 300, __size = 3}
	},
	[121] = {
		id = 121,
		huodongID = 1003,
		day = 1,
		award = {['rmb'] = 980, [452] = 200, [502] = 9, __size = 3}
	},
	[122] = {
		id = 122,
		huodongID = 1003,
		day = 2,
		award = __data_t__award[122]
		-- {['rmb'] = 300, [452] = 50, [502] = 3, __size = 3}
	},
	[123] = {
		id = 123,
		huodongID = 1003,
		day = 3,
		award = __data_t__award[123]
		-- {['rmb'] = 300, [452] = 50, [502] = 3, __size = 3}
	},
	[124] = {
		id = 124,
		huodongID = 1003,
		day = 4,
		award = __data_t__award[124]
		-- {['rmb'] = 300, [452] = 50, [502] = 3, __size = 3}
	},
	[125] = {
		id = 125,
		huodongID = 1003,
		day = 5,
		award = __data_t__award[125]
		-- {['rmb'] = 300, [452] = 50, [502] = 3, __size = 3}
	},
	[126] = {
		id = 126,
		huodongID = 1003,
		day = 6,
		award = __data_t__award[126]
		-- {['rmb'] = 300, [452] = 50, [502] = 3, __size = 3}
	},
	[127] = {
		id = 127,
		huodongID = 1003,
		day = 7,
		award = __data_t__award[127]
		-- {['rmb'] = 300, [452] = 50, [502] = 3, __size = 3}
	},
	__size = 21,
	__default = {
		__index = {
			day = 99,
			award = {__size = 0}
		}
	}
}
return csv.yunying.weeklycard