--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[34] = {['gold'] = 10000, __size = 1}, __size = 1}
local __data_t__award = {
	[115] = __predefine_t__[34],
	[114] = __predefine_t__[34],
	[117] = __predefine_t__[34],
	[116] = __predefine_t__[34],
	[111] = __predefine_t__[34],
	[110] = __predefine_t__[34],
	[113] = __predefine_t__[34],
	[112] = __predefine_t__[34],
	[119] = __predefine_t__[34],
	[118] = __predefine_t__[34],
	[130] = __predefine_t__[34],
	[129] = __predefine_t__[34],
	[128] = __predefine_t__[34],
	[120] = __predefine_t__[34],
	[121] = __predefine_t__[34],
	[108] = __predefine_t__[34],
	[109] = __predefine_t__[34],
	[124] = __predefine_t__[34],
	[125] = __predefine_t__[34],
	[126] = __predefine_t__[34],
	[127] = __predefine_t__[34],
	[102] = __predefine_t__[34],
	[103] = __predefine_t__[34],
	[101] = __predefine_t__[34],
	[106] = __predefine_t__[34],
	[107] = __predefine_t__[34],
	[104] = __predefine_t__[34],
	[105] = __predefine_t__[34],
	[132] = __predefine_t__[34],
	[122] = __predefine_t__[34],
	[131] = __predefine_t__[34],
	[123] = __predefine_t__[34]
}

csv['cross']['supremacy']['rank'] = {
	[1] = {
		id = 1,
		range = 1,
		award = {['rmb'] = 2000, [9030] = 1, ['coin8'] = 400000, ['gold'] = 6000000, __size = 4},
		flag = 1
	},
	[2] = {
		id = 2,
		range = 2,
		award = {['rmb'] = 1900, [9030] = 1, ['coin8'] = 390000, ['gold'] = 5800000, __size = 4},
		flag = 1
	},
	[3] = {
		id = 3,
		range = 3,
		award = {['rmb'] = 1800, [9030] = 1, ['coin8'] = 380000, ['gold'] = 5600000, __size = 4},
		flag = 1
	},
	[4] = {
		id = 4,
		range = 4,
		award = {['rmb'] = 1700, ['gold'] = 5400000, [9031] = 1, ['coin8'] = 370000, __size = 4},
		flag = 1
	},
	[5] = {
		id = 5,
		range = 5,
		award = {['rmb'] = 1600, ['gold'] = 5200000, [9031] = 1, ['coin8'] = 360000, __size = 4},
		flag = 1
	},
	[6] = {
		id = 6,
		range = 6,
		award = {['rmb'] = 1500, ['gold'] = 5000000, [9031] = 1, ['coin8'] = 350000, __size = 4},
		flag = 1
	},
	[7] = {
		id = 7,
		range = 7,
		award = {['rmb'] = 1400, ['gold'] = 4800000, [9031] = 1, ['coin8'] = 340000, __size = 4},
		flag = 1
	},
	[8] = {
		id = 8,
		range = 8,
		award = {['rmb'] = 1300, ['gold'] = 4600000, [9031] = 1, ['coin8'] = 330000, __size = 4},
		flag = 1
	},
	[9] = {
		id = 9,
		range = 9,
		award = {['rmb'] = 1200, ['gold'] = 4400000, [9031] = 1, ['coin8'] = 320000, __size = 4},
		flag = 1
	},
	[10] = {
		id = 10,
		range = 10,
		award = {['rmb'] = 1100, ['gold'] = 4200000, [9031] = 1, ['coin8'] = 310000, __size = 4},
		flag = 1
	},
	[11] = {
		id = 11,
		range = 12,
		award = {[9032] = 1, ['rmb'] = 1050, ['gold'] = 4000000, ['coin8'] = 300000, __size = 4},
		flag = 1
	},
	[12] = {
		id = 12,
		range = 15,
		award = {[9032] = 1, ['rmb'] = 1000, ['gold'] = 3800000, ['coin8'] = 290000, __size = 4},
		flag = 1
	},
	[13] = {
		id = 13,
		range = 20,
		award = {[9032] = 1, ['rmb'] = 950, ['gold'] = 3600000, ['coin8'] = 280000, __size = 4},
		flag = 1
	},
	[14] = {
		id = 14,
		range = 30,
		award = {[9033] = 1, ['gold'] = 3400000, ['rmb'] = 900, ['coin8'] = 270000, __size = 4},
		flag = 1
	},
	[15] = {
		id = 15,
		range = 40,
		award = {['rmb'] = 850, ['gold'] = 3200000, ['coin8'] = 260000, [9034] = 1, __size = 4},
		flag = 1
	},
	[16] = {
		id = 16,
		range = 50,
		award = {['rmb'] = 800, ['gold'] = 3000000, ['coin8'] = 250000, [9034] = 1, __size = 4},
		flag = 1
	},
	[17] = {
		id = 17,
		range = 70,
		award = {['rmb'] = 750, ['gold'] = 2800000, ['coin8'] = 240000, __size = 3},
		flag = 1
	},
	[18] = {
		id = 18,
		range = 100,
		award = {['rmb'] = 700, ['gold'] = 2600000, ['coin8'] = 230000, __size = 3},
		flag = 1
	},
	[19] = {
		id = 19,
		range = 150,
		award = {['rmb'] = 650, ['gold'] = 2500000, ['coin8'] = 220000, __size = 3},
		flag = 1
	},
	[20] = {
		id = 20,
		range = 200,
		award = {['rmb'] = 600, ['gold'] = 2400000, ['coin8'] = 210000, __size = 3},
		flag = 1
	},
	[21] = {
		id = 21,
		range = 300,
		award = {['rmb'] = 550, ['gold'] = 2300000, ['coin8'] = 200000, __size = 3},
		flag = 1
	},
	[22] = {
		id = 22,
		range = 400,
		award = {['rmb'] = 500, ['gold'] = 2200000, ['coin8'] = 190000, __size = 3},
		flag = 1
	},
	[23] = {
		id = 23,
		range = 500,
		award = {['rmb'] = 480, ['gold'] = 2100000, ['coin8'] = 180000, __size = 3},
		flag = 1
	},
	[24] = {
		id = 24,
		range = 700,
		award = {['rmb'] = 460, ['gold'] = 2000000, ['coin8'] = 170000, __size = 3},
		flag = 1
	},
	[25] = {
		id = 25,
		range = 1000,
		award = {['rmb'] = 440, ['gold'] = 1900000, ['coin8'] = 160000, __size = 3},
		flag = 1
	},
	[26] = {
		id = 26,
		range = 2000,
		award = {['rmb'] = 420, ['gold'] = 1800000, ['coin8'] = 150000, __size = 3},
		flag = 1
	},
	[27] = {
		id = 27,
		range = 3000,
		award = {['rmb'] = 400, ['gold'] = 1700000, ['coin8'] = 140000, __size = 3},
		flag = 1
	},
	[28] = {
		id = 28,
		range = 4000,
		award = {['rmb'] = 380, ['gold'] = 1600000, ['coin8'] = 130000, __size = 3},
		flag = 1
	},
	[29] = {
		id = 29,
		range = 5000,
		award = {['rmb'] = 360, ['gold'] = 1500000, ['coin8'] = 120000, __size = 3},
		flag = 1
	},
	[30] = {
		id = 30,
		range = 7000,
		award = {['rmb'] = 340, ['gold'] = 1400000, ['coin8'] = 110000, __size = 3},
		flag = 1
	},
	[31] = {
		id = 31,
		range = 10000,
		award = {['rmb'] = 320, ['gold'] = 1300000, ['coin8'] = 100000, __size = 3},
		flag = 1
	},
	[32] = {
		id = 32,
		range = 999999,
		award = {['rmb'] = 300, ['gold'] = 1200000, ['coin8'] = 90000, __size = 3},
		flag = 1
	},
	[101] = {
		id = 101,
		range = 1,
		award = __data_t__award[101]
		-- {['gold'] = 10000, __size = 1}
	},
	[102] = {
		id = 102,
		range = 2,
		award = __data_t__award[102]
		-- {['gold'] = 10000, __size = 1}
	},
	[103] = {
		id = 103,
		range = 3,
		award = __data_t__award[103]
		-- {['gold'] = 10000, __size = 1}
	},
	[104] = {
		id = 104,
		range = 4,
		award = __data_t__award[104]
		-- {['gold'] = 10000, __size = 1}
	},
	[105] = {
		id = 105,
		range = 5,
		award = __data_t__award[105]
		-- {['gold'] = 10000, __size = 1}
	},
	[106] = {
		id = 106,
		range = 6,
		award = __data_t__award[106]
		-- {['gold'] = 10000, __size = 1}
	},
	[107] = {
		id = 107,
		range = 7,
		award = __data_t__award[107]
		-- {['gold'] = 10000, __size = 1}
	},
	[108] = {
		id = 108,
		range = 8,
		award = __data_t__award[108]
		-- {['gold'] = 10000, __size = 1}
	},
	[109] = {
		id = 109,
		range = 9,
		award = __data_t__award[109]
		-- {['gold'] = 10000, __size = 1}
	},
	[110] = {
		id = 110,
		range = 10,
		award = __data_t__award[110]
		-- {['gold'] = 10000, __size = 1}
	},
	[111] = {
		id = 111,
		range = 12,
		award = __data_t__award[111]
		-- {['gold'] = 10000, __size = 1}
	},
	[112] = {
		id = 112,
		range = 15,
		award = __data_t__award[112]
		-- {['gold'] = 10000, __size = 1}
	},
	[113] = {
		id = 113,
		range = 20,
		award = __data_t__award[113]
		-- {['gold'] = 10000, __size = 1}
	},
	[114] = {
		id = 114,
		range = 30,
		award = __data_t__award[114]
		-- {['gold'] = 10000, __size = 1}
	},
	[115] = {
		id = 115,
		range = 40,
		award = __data_t__award[115]
		-- {['gold'] = 10000, __size = 1}
	},
	[116] = {
		id = 116,
		range = 50,
		award = __data_t__award[116]
		-- {['gold'] = 10000, __size = 1}
	},
	[117] = {
		id = 117,
		range = 70,
		award = __data_t__award[117]
		-- {['gold'] = 10000, __size = 1}
	},
	[118] = {
		id = 118,
		range = 100,
		award = __data_t__award[118]
		-- {['gold'] = 10000, __size = 1}
	},
	[119] = {
		id = 119,
		range = 150,
		award = __data_t__award[119]
		-- {['gold'] = 10000, __size = 1}
	},
	[120] = {
		id = 120,
		range = 200,
		award = __data_t__award[120]
		-- {['gold'] = 10000, __size = 1}
	},
	[121] = {
		id = 121,
		range = 300,
		award = __data_t__award[121]
		-- {['gold'] = 10000, __size = 1}
	},
	[122] = {
		id = 122,
		range = 400,
		award = __data_t__award[122]
		-- {['gold'] = 10000, __size = 1}
	},
	[123] = {
		id = 123,
		range = 500,
		award = __data_t__award[123]
		-- {['gold'] = 10000, __size = 1}
	},
	[124] = {
		id = 124,
		range = 700,
		award = __data_t__award[124]
		-- {['gold'] = 10000, __size = 1}
	},
	[125] = {
		id = 125,
		range = 1000,
		award = __data_t__award[125]
		-- {['gold'] = 10000, __size = 1}
	},
	[126] = {
		id = 126,
		range = 2000,
		award = __data_t__award[126]
		-- {['gold'] = 10000, __size = 1}
	},
	[127] = {
		id = 127,
		range = 3000,
		award = __data_t__award[127]
		-- {['gold'] = 10000, __size = 1}
	},
	[128] = {
		id = 128,
		range = 4000,
		award = __data_t__award[128]
		-- {['gold'] = 10000, __size = 1}
	},
	[129] = {
		id = 129,
		range = 5000,
		award = __data_t__award[129]
		-- {['gold'] = 10000, __size = 1}
	},
	[130] = {
		id = 130,
		range = 7000,
		award = __data_t__award[130]
		-- {['gold'] = 10000, __size = 1}
	},
	[131] = {
		id = 131,
		range = 10000,
		award = __data_t__award[131]
		-- {['gold'] = 10000, __size = 1}
	},
	[132] = {
		id = 132,
		range = 999999,
		award = __data_t__award[132]
		-- {['gold'] = 10000, __size = 1}
	},

	__size = 64,
	__default = {
		__index = {
			range = 0,
			award = {__size = 0},
			flag = 0,
			version = 0
		}
	}
}
return csv.cross.supremacy.rank