--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['chip']['strength_cost'] = {
	[1] = {
		id = 1,
		levelExp1 = 25,
		levelExp2 = 25,
		levelExp3 = 38,
		levelExp4 = 55,
		levelExp5 = 85,
		levelExp6 = 125
	},
	[2] = {
		id = 2,
		levelExp1 = 25,
		levelExp2 = 25,
		levelExp3 = 38,
		levelExp4 = 55,
		levelExp5 = 85,
		levelExp6 = 125
	},
	[3] = {
		id = 3,
		levelExp1 = 50,
		levelExp2 = 50,
		levelExp3 = 75,
		levelExp4 = 110,
		levelExp5 = 170,
		levelExp6 = 250
	},
	[4] = {
		id = 4,
		levelExp1 = 50,
		levelExp2 = 50,
		levelExp3 = 75,
		levelExp4 = 110,
		levelExp5 = 170,
		levelExp6 = 250
	},
	[5] = {
		id = 5,
		levelExp1 = 75,
		levelExp2 = 75,
		levelExp3 = 113,
		levelExp4 = 165,
		levelExp5 = 255,
		levelExp6 = 375
	},
	[6] = {
		id = 6,
		levelExp1 = 75,
		levelExp2 = 75,
		levelExp3 = 113,
		levelExp4 = 165,
		levelExp5 = 255,
		levelExp6 = 375
	},
	[7] = {
		id = 7,
		levelExp1 = 100,
		levelExp2 = 100,
		levelExp3 = 150,
		levelExp4 = 220,
		levelExp5 = 340,
		levelExp6 = 500
	},
	[8] = {
		id = 8,
		levelExp1 = 100,
		levelExp2 = 100,
		levelExp3 = 150,
		levelExp4 = 220,
		levelExp5 = 340,
		levelExp6 = 500
	},
	[9] = {
		id = 9,
		levelExp1 = 125,
		levelExp2 = 125,
		levelExp3 = 188,
		levelExp4 = 275,
		levelExp5 = 425,
		levelExp6 = 625
	},
	[10] = {
		id = 10,
		levelExp1 = 145,
		levelExp2 = 145,
		levelExp3 = 218,
		levelExp4 = 319,
		levelExp5 = 493,
		levelExp6 = 725
	},
	[11] = {
		id = 11,
		levelExp1 = 170,
		levelExp2 = 170,
		levelExp3 = 255,
		levelExp4 = 374,
		levelExp5 = 578,
		levelExp6 = 850
	},
	[12] = {
		id = 12,
		levelExp1 = 195,
		levelExp2 = 195,
		levelExp3 = 293,
		levelExp4 = 429,
		levelExp5 = 663,
		levelExp6 = 975
	},
	[13] = {
		id = 13,
		levelExp1 = 240,
		levelExp2 = 240,
		levelExp3 = 360,
		levelExp4 = 528,
		levelExp5 = 816,
		levelExp6 = 1200
	},
	[14] = {
		id = 14,
		levelExp1 = 265,
		levelExp2 = 265,
		levelExp3 = 398,
		levelExp4 = 583,
		levelExp5 = 901,
		levelExp6 = 1325
	},
	[15] = {
		id = 15,
		levelExp1 = 285,
		levelExp2 = 285,
		levelExp3 = 428,
		levelExp4 = 627,
		levelExp5 = 969,
		levelExp6 = 1425
	},
	[16] = {
		id = 16,
		levelExp1 = 330,
		levelExp2 = 330,
		levelExp3 = 495,
		levelExp4 = 726,
		levelExp5 = 1122,
		levelExp6 = 1650
	},
	[17] = {
		id = 17,
		levelExp1 = 355,
		levelExp2 = 355,
		levelExp3 = 533,
		levelExp4 = 781,
		levelExp5 = 1207,
		levelExp6 = 1775
	},
	[18] = {
		id = 18,
		levelExp1 = 375,
		levelExp2 = 375,
		levelExp3 = 563,
		levelExp4 = 825,
		levelExp5 = 1275,
		levelExp6 = 1875
	},
	[19] = {
		id = 19,
		levelExp1 = 375,
		levelExp2 = 375,
		levelExp3 = 563,
		levelExp4 = 825,
		levelExp5 = 1275,
		levelExp6 = 1875
	},
	[20] = {
		id = 20,
		levelExp1 = 395,
		levelExp2 = 395,
		levelExp3 = 593,
		levelExp4 = 869,
		levelExp5 = 1343,
		levelExp6 = 1975
	},
	[21] = {
		id = 21,
		levelExp1 = 415,
		levelExp2 = 415,
		levelExp3 = 623,
		levelExp4 = 913,
		levelExp5 = 1411,
		levelExp6 = 2075
	},
	[22] = {
		id = 22,
		levelExp1 = 415,
		levelExp2 = 415,
		levelExp3 = 623,
		levelExp4 = 913,
		levelExp5 = 1411,
		levelExp6 = 2075
	},
	[23] = {
		id = 23,
		levelExp1 = 435,
		levelExp2 = 435,
		levelExp3 = 653,
		levelExp4 = 957,
		levelExp5 = 1479,
		levelExp6 = 2175
	},
	[24] = {
		id = 24,
		levelExp1 = 435,
		levelExp2 = 435,
		levelExp3 = 653,
		levelExp4 = 957,
		levelExp5 = 1479,
		levelExp6 = 2175
	},
	[25] = {
		id = 25,
		levelExp1 = 430,
		levelExp2 = 430,
		levelExp3 = 645,
		levelExp4 = 946,
		levelExp5 = 1462,
		levelExp6 = 2150
	},
	[26] = {
		id = 26,
		levelExp1 = 430,
		levelExp2 = 430,
		levelExp3 = 645,
		levelExp4 = 946,
		levelExp5 = 1462,
		levelExp6 = 2150
	},
	[27] = {
		id = 27,
		levelExp1 = 450,
		levelExp2 = 450,
		levelExp3 = 675,
		levelExp4 = 990,
		levelExp5 = 1530,
		levelExp6 = 2250
	},
	[28] = {
		id = 28,
		levelExp1 = 450,
		levelExp2 = 450,
		levelExp3 = 675,
		levelExp4 = 990,
		levelExp5 = 1530,
		levelExp6 = 2250
	},
	[29] = {
		id = 29,
		levelExp1 = 445,
		levelExp2 = 445,
		levelExp3 = 668,
		levelExp4 = 979,
		levelExp5 = 1513,
		levelExp6 = 2225
	},
	[30] = {
		id = 30,
		levelExp1 = 445,
		levelExp2 = 445,
		levelExp3 = 668,
		levelExp4 = 979,
		levelExp5 = 1513,
		levelExp6 = 2225
	},
	[31] = {
		id = 31,
		levelExp1 = 440,
		levelExp2 = 440,
		levelExp3 = 660,
		levelExp4 = 968,
		levelExp5 = 1496,
		levelExp6 = 2200
	},
	[32] = {
		id = 32,
		levelExp1 = 440,
		levelExp2 = 440,
		levelExp3 = 660,
		levelExp4 = 968,
		levelExp5 = 1496,
		levelExp6 = 2200
	},
	[33] = {
		id = 33,
		levelExp1 = 440,
		levelExp2 = 440,
		levelExp3 = 660,
		levelExp4 = 968,
		levelExp5 = 1496,
		levelExp6 = 2200
	},
	[34] = {
		id = 34,
		levelExp1 = 460,
		levelExp2 = 460,
		levelExp3 = 690,
		levelExp4 = 1012,
		levelExp5 = 1564,
		levelExp6 = 2300
	},
	[35] = {
		id = 35,
		levelExp1 = 455,
		levelExp2 = 455,
		levelExp3 = 683,
		levelExp4 = 1001,
		levelExp5 = 1547,
		levelExp6 = 2275
	},
	[36] = {
		id = 36,
		levelExp1 = 455,
		levelExp2 = 455,
		levelExp3 = 683,
		levelExp4 = 1001,
		levelExp5 = 1547,
		levelExp6 = 2275
	},
	[37] = {
		id = 37,
		levelExp1 = 450,
		levelExp2 = 450,
		levelExp3 = 675,
		levelExp4 = 990,
		levelExp5 = 1530,
		levelExp6 = 2250
	},
	[38] = {
		id = 38,
		levelExp1 = 470,
		levelExp2 = 470,
		levelExp3 = 705,
		levelExp4 = 1034,
		levelExp5 = 1598,
		levelExp6 = 2350
	},
	[39] = {
		id = 39,
		levelExp1 = 470,
		levelExp2 = 470,
		levelExp3 = 705,
		levelExp4 = 1034,
		levelExp5 = 1598,
		levelExp6 = 2350
	},
	[40] = {
		id = 40,
		levelExp1 = 465,
		levelExp2 = 465,
		levelExp3 = 698,
		levelExp4 = 1023,
		levelExp5 = 1581,
		levelExp6 = 2325
	},
	[41] = {
		id = 41,
		levelExp1 = 465,
		levelExp2 = 465,
		levelExp3 = 698,
		levelExp4 = 1023,
		levelExp5 = 1581,
		levelExp6 = 2325
	},
	[42] = {
		id = 42,
		levelExp1 = 460,
		levelExp2 = 460,
		levelExp3 = 690,
		levelExp4 = 1012,
		levelExp5 = 1564,
		levelExp6 = 2300
	},
	[43] = {
		id = 43,
		levelExp1 = 480,
		levelExp2 = 480,
		levelExp3 = 720,
		levelExp4 = 1056,
		levelExp5 = 1632,
		levelExp6 = 2400
	},
	[44] = {
		id = 44,
		levelExp1 = 480,
		levelExp2 = 480,
		levelExp3 = 720,
		levelExp4 = 1056,
		levelExp5 = 1632,
		levelExp6 = 2400
	},
	[45] = {
		id = 45,
		levelExp1 = 475,
		levelExp2 = 475,
		levelExp3 = 713,
		levelExp4 = 1045,
		levelExp5 = 1615,
		levelExp6 = 2375
	},
	[46] = {
		id = 46,
		levelExp1 = 495,
		levelExp2 = 495,
		levelExp3 = 743,
		levelExp4 = 1089,
		levelExp5 = 1683,
		levelExp6 = 2475
	},
	[47] = {
		id = 47,
		levelExp1 = 490,
		levelExp2 = 490,
		levelExp3 = 735,
		levelExp4 = 1078,
		levelExp5 = 1666,
		levelExp6 = 2450
	},
	[48] = {
		id = 48,
		levelExp1 = 490,
		levelExp2 = 490,
		levelExp3 = 735,
		levelExp4 = 1078,
		levelExp5 = 1666,
		levelExp6 = 2450
	},
	[49] = {
		id = 49,
		levelExp1 = 485,
		levelExp2 = 485,
		levelExp3 = 728,
		levelExp4 = 1067,
		levelExp5 = 1649,
		levelExp6 = 2425
	},
	[50] = {
		id = 50,
		levelExp1 = 505,
		levelExp2 = 505,
		levelExp3 = 758,
		levelExp4 = 1111,
		levelExp5 = 1717,
		levelExp6 = 2525
	},
	[51] = {
		id = 51,
		levelExp1 = 500,
		levelExp2 = 500,
		levelExp3 = 750,
		levelExp4 = 1100,
		levelExp5 = 1700,
		levelExp6 = 2500
	},
	[52] = {
		id = 52,
		levelExp1 = 500,
		levelExp2 = 500,
		levelExp3 = 750,
		levelExp4 = 1100,
		levelExp5 = 1700,
		levelExp6 = 2500
	},
	[53] = {
		id = 53,
		levelExp1 = 515,
		levelExp2 = 515,
		levelExp3 = 773,
		levelExp4 = 1133,
		levelExp5 = 1751,
		levelExp6 = 2575
	},
	[54] = {
		id = 54,
		levelExp1 = 515,
		levelExp2 = 515,
		levelExp3 = 773,
		levelExp4 = 1133,
		levelExp5 = 1751,
		levelExp6 = 2575
	},
	[55] = {
		id = 55,
		levelExp1 = 510,
		levelExp2 = 510,
		levelExp3 = 765,
		levelExp4 = 1122,
		levelExp5 = 1734,
		levelExp6 = 2550
	},
	[56] = {
		id = 56,
		levelExp1 = 530,
		levelExp2 = 530,
		levelExp3 = 795,
		levelExp4 = 1166,
		levelExp5 = 1802,
		levelExp6 = 2650
	},
	[57] = {
		id = 57,
		levelExp1 = 525,
		levelExp2 = 525,
		levelExp3 = 788,
		levelExp4 = 1155,
		levelExp5 = 1785,
		levelExp6 = 2625
	},
	[58] = {
		id = 58,
		levelExp1 = 545,
		levelExp2 = 545,
		levelExp3 = 818,
		levelExp4 = 1199,
		levelExp5 = 1853,
		levelExp6 = 2725
	},
	[59] = {
		id = 59,
		levelExp1 = 540,
		levelExp2 = 540,
		levelExp3 = 810,
		levelExp4 = 1188,
		levelExp5 = 1836,
		levelExp6 = 2700
	},
	[60] = {
		id = 60,
		levelExp1 = 535,
		levelExp2 = 535,
		levelExp3 = 803,
		levelExp4 = 1177,
		levelExp5 = 1819,
		levelExp6 = 2675
	},
	[61] = {
		id = 61,
		levelExp1 = 555,
		levelExp2 = 555,
		levelExp3 = 833,
		levelExp4 = 1221,
		levelExp5 = 1887,
		levelExp6 = 2775
	},
	[62] = {
		id = 62,
		levelExp1 = 550,
		levelExp2 = 550,
		levelExp3 = 825,
		levelExp4 = 1210,
		levelExp5 = 1870,
		levelExp6 = 2750
	},
	[63] = {
		id = 63,
		levelExp1 = 565,
		levelExp2 = 565,
		levelExp3 = 848,
		levelExp4 = 1243,
		levelExp5 = 1921,
		levelExp6 = 2825
	},
	[64] = {
		id = 64,
		levelExp1 = 565,
		levelExp2 = 565,
		levelExp3 = 848,
		levelExp4 = 1243,
		levelExp5 = 1921,
		levelExp6 = 2825
	},
	[65] = {
		id = 65,
		levelExp1 = 560,
		levelExp2 = 560,
		levelExp3 = 840,
		levelExp4 = 1232,
		levelExp5 = 1904,
		levelExp6 = 2800
	},
	[66] = {
		id = 66,
		levelExp1 = 575,
		levelExp2 = 575,
		levelExp3 = 863,
		levelExp4 = 1265,
		levelExp5 = 1955,
		levelExp6 = 2875
	},
	[67] = {
		id = 67,
		levelExp1 = 575,
		levelExp2 = 575,
		levelExp3 = 863,
		levelExp4 = 1265,
		levelExp5 = 1955,
		levelExp6 = 2875
	},
	[68] = {
		id = 68,
		levelExp1 = 590,
		levelExp2 = 590,
		levelExp3 = 885,
		levelExp4 = 1298,
		levelExp5 = 2006,
		levelExp6 = 2950
	},
	[69] = {
		id = 69,
		levelExp1 = 585,
		levelExp2 = 585,
		levelExp3 = 878,
		levelExp4 = 1287,
		levelExp5 = 1989,
		levelExp6 = 2925
	},
	[70] = {
		id = 70,
		levelExp1 = 600,
		levelExp2 = 600,
		levelExp3 = 900,
		levelExp4 = 1320,
		levelExp5 = 2040,
		levelExp6 = 3000
	},
	[71] = {
		id = 71,
		levelExp1 = 595,
		levelExp2 = 595,
		levelExp3 = 893,
		levelExp4 = 1309,
		levelExp5 = 2023,
		levelExp6 = 2975
	},
	[72] = {
		id = 72,
		levelExp1 = 610,
		levelExp2 = 610,
		levelExp3 = 915,
		levelExp4 = 1342,
		levelExp5 = 2074,
		levelExp6 = 3050
	},
	[73] = {
		id = 73,
		levelExp1 = 625,
		levelExp2 = 625,
		levelExp3 = 938,
		levelExp4 = 1375,
		levelExp5 = 2125,
		levelExp6 = 3125
	},
	[74] = {
		id = 74,
		levelExp1 = 640,
		levelExp2 = 640,
		levelExp3 = 960,
		levelExp4 = 1408,
		levelExp5 = 2176,
		levelExp6 = 3200
	},
	[75] = {
		id = 75,
		levelExp1 = 670,
		levelExp2 = 670,
		levelExp3 = 1005,
		levelExp4 = 1474,
		levelExp5 = 2278,
		levelExp6 = 3350
	},
	[76] = {
		id = 76,
		levelExp1 = 705,
		levelExp2 = 705,
		levelExp3 = 1058,
		levelExp4 = 1551,
		levelExp5 = 2397,
		levelExp6 = 3525
	},
	[77] = {
		id = 77,
		levelExp1 = 770,
		levelExp2 = 770,
		levelExp3 = 1155,
		levelExp4 = 1694,
		levelExp5 = 2618,
		levelExp6 = 3850
	},
	[78] = {
		id = 78,
		levelExp1 = 765,
		levelExp2 = 765,
		levelExp3 = 1148,
		levelExp4 = 1683,
		levelExp5 = 2601,
		levelExp6 = 3825
	},
	[79] = {
		id = 79,
		levelExp1 = 830,
		levelExp2 = 830,
		levelExp3 = 1245,
		levelExp4 = 1826,
		levelExp5 = 2822,
		levelExp6 = 4150
	},
	[80] = {
		id = 80,
		levelExp1 = 825,
		levelExp2 = 825,
		levelExp3 = 1238,
		levelExp4 = 1815,
		levelExp5 = 2805,
		levelExp6 = 4125
	},
	[81] = {
		id = 81,
		levelExp1 = 885,
		levelExp2 = 885,
		levelExp3 = 1328,
		levelExp4 = 1947,
		levelExp5 = 3009,
		levelExp6 = 4425
	},
	[82] = {
		id = 82,
		levelExp1 = 950,
		levelExp2 = 950,
		levelExp3 = 1425,
		levelExp4 = 2090,
		levelExp5 = 3230,
		levelExp6 = 4750
	},
	[83] = {
		id = 83,
		levelExp1 = 945,
		levelExp2 = 945,
		levelExp3 = 1418,
		levelExp4 = 2079,
		levelExp5 = 3213,
		levelExp6 = 4725
	},
	[84] = {
		id = 84,
		levelExp1 = 1005,
		levelExp2 = 1005,
		levelExp3 = 1508,
		levelExp4 = 2211,
		levelExp5 = 3417,
		levelExp6 = 5025
	},
	[85] = {
		id = 85,
		levelExp1 = 1065,
		levelExp2 = 1065,
		levelExp3 = 1598,
		levelExp4 = 2343,
		levelExp5 = 3621,
		levelExp6 = 5325
	},
	[86] = {
		id = 86,
		levelExp1 = 1125,
		levelExp2 = 1125,
		levelExp3 = 1688,
		levelExp4 = 2475,
		levelExp5 = 3825,
		levelExp6 = 5625
	},
	[87] = {
		id = 87,
		levelExp1 = 1185,
		levelExp2 = 1185,
		levelExp3 = 1778,
		levelExp4 = 2607,
		levelExp5 = 4029,
		levelExp6 = 5925
	},
	[88] = {
		id = 88,
		levelExp1 = 1240,
		levelExp2 = 1240,
		levelExp3 = 1860,
		levelExp4 = 2728,
		levelExp5 = 4216,
		levelExp6 = 6200
	},
	[89] = {
		id = 89,
		levelExp1 = 1300,
		levelExp2 = 1300,
		levelExp3 = 1950,
		levelExp4 = 2860,
		levelExp5 = 4420,
		levelExp6 = 6500
	},
	[90] = {
		id = 90,
		levelExp1 = 1355,
		levelExp2 = 1355,
		levelExp3 = 2033,
		levelExp4 = 2981,
		levelExp5 = 4607,
		levelExp6 = 6775
	},
	[91] = {
		id = 91,
		levelExp1 = 1410,
		levelExp2 = 1410,
		levelExp3 = 2115,
		levelExp4 = 3102,
		levelExp5 = 4794,
		levelExp6 = 7050
	},
	[92] = {
		id = 92,
		levelExp1 = 1465,
		levelExp2 = 1465,
		levelExp3 = 2198,
		levelExp4 = 3223,
		levelExp5 = 4981,
		levelExp6 = 7325
	},
	[93] = {
		id = 93,
		levelExp1 = 1520,
		levelExp2 = 1520,
		levelExp3 = 2280,
		levelExp4 = 3344,
		levelExp5 = 5168,
		levelExp6 = 7600
	},
	[94] = {
		id = 94,
		levelExp1 = 1575,
		levelExp2 = 1575,
		levelExp3 = 2363,
		levelExp4 = 3465,
		levelExp5 = 5355,
		levelExp6 = 7875
	},
	[95] = {
		id = 95,
		levelExp1 = 1685,
		levelExp2 = 1685,
		levelExp3 = 2528,
		levelExp4 = 3707,
		levelExp5 = 5729,
		levelExp6 = 8425
	},
	[96] = {
		id = 96,
		levelExp1 = 1740,
		levelExp2 = 1740,
		levelExp3 = 2610,
		levelExp4 = 3828,
		levelExp5 = 5916,
		levelExp6 = 8700
	},
	[97] = {
		id = 97,
		levelExp1 = 1790,
		levelExp2 = 1790,
		levelExp3 = 2685,
		levelExp4 = 3938,
		levelExp5 = 6086,
		levelExp6 = 8950
	},
	[98] = {
		id = 98,
		levelExp1 = 1900,
		levelExp2 = 1900,
		levelExp3 = 2850,
		levelExp4 = 4180,
		levelExp5 = 6460,
		levelExp6 = 9500
	},
	[99] = {
		id = 99,
		levelExp1 = 1950,
		levelExp2 = 1950,
		levelExp3 = 2925,
		levelExp4 = 4290,
		levelExp5 = 6630,
		levelExp6 = 9750
	},
	[100] = {
		id = 100,
		levelExp1 = 1995,
		levelExp2 = 1995,
		levelExp3 = 2993,
		levelExp4 = 4389,
		levelExp5 = 6783,
		levelExp6 = 9975
	},
	[101] = {
		id = 101,
		levelExp1 = 2015,
		levelExp2 = 2015,
		levelExp3 = 3023,
		levelExp4 = 4433,
		levelExp5 = 6851,
		levelExp6 = 10075
	},
	[102] = {
		id = 102,
		levelExp1 = 2035,
		levelExp2 = 2035,
		levelExp3 = 3053,
		levelExp4 = 4477,
		levelExp5 = 6919,
		levelExp6 = 10175
	},
	[103] = {
		id = 103,
		levelExp1 = 2055,
		levelExp2 = 2055,
		levelExp3 = 3084,
		levelExp4 = 4522,
		levelExp5 = 6989,
		levelExp6 = 10277
	},
	[104] = {
		id = 104,
		levelExp1 = 2076,
		levelExp2 = 2076,
		levelExp3 = 3115,
		levelExp4 = 4567,
		levelExp5 = 7058,
		levelExp6 = 10380
	},
	[105] = {
		id = 105,
		levelExp1 = 2097,
		levelExp2 = 2097,
		levelExp3 = 3146,
		levelExp4 = 4613,
		levelExp5 = 7129,
		levelExp6 = 10484
	},
	[106] = {
		id = 106,
		levelExp1 = 2118,
		levelExp2 = 2118,
		levelExp3 = 3177,
		levelExp4 = 4659,
		levelExp5 = 7200,
		levelExp6 = 10589
	},
	[107] = {
		id = 107,
		levelExp1 = 2139,
		levelExp2 = 2139,
		levelExp3 = 3209,
		levelExp4 = 4706,
		levelExp5 = 7272,
		levelExp6 = 10695
	},
	[108] = {
		id = 108,
		levelExp1 = 2160,
		levelExp2 = 2160,
		levelExp3 = 3241,
		levelExp4 = 4753,
		levelExp5 = 7345,
		levelExp6 = 10801
	},
	[109] = {
		id = 109,
		levelExp1 = 2182,
		levelExp2 = 2182,
		levelExp3 = 3273,
		levelExp4 = 4800,
		levelExp5 = 7418,
		levelExp6 = 10910
	},
	[110] = {
		id = 110,
		levelExp1 = 2204,
		levelExp2 = 2204,
		levelExp3 = 3306,
		levelExp4 = 4848,
		levelExp5 = 7493,
		levelExp6 = 11019
	},
	[111] = {
		id = 111,
		levelExp1 = 2226,
		levelExp2 = 2226,
		levelExp3 = 3339,
		levelExp4 = 4897,
		levelExp5 = 7568,
		levelExp6 = 11129
	},
	[112] = {
		id = 112,
		levelExp1 = 2248,
		levelExp2 = 2248,
		levelExp3 = 3373,
		levelExp4 = 4946,
		levelExp5 = 7643,
		levelExp6 = 11240
	},
	[113] = {
		id = 113,
		levelExp1 = 2270,
		levelExp2 = 2270,
		levelExp3 = 3406,
		levelExp4 = 4995,
		levelExp5 = 7720,
		levelExp6 = 11352
	},
	[114] = {
		id = 114,
		levelExp1 = 2293,
		levelExp2 = 2293,
		levelExp3 = 3440,
		levelExp4 = 5045,
		levelExp5 = 7797,
		levelExp6 = 11466
	},
	[115] = {
		id = 115,
		levelExp1 = 2316,
		levelExp2 = 2316,
		levelExp3 = 3475,
		levelExp4 = 5095,
		levelExp5 = 7875,
		levelExp6 = 11581
	},
	[116] = {
		id = 116,
		levelExp1 = 2339,
		levelExp2 = 2339,
		levelExp3 = 3510,
		levelExp4 = 5146,
		levelExp5 = 7954,
		levelExp6 = 11696
	},
	[117] = {
		id = 117,
		levelExp1 = 2363,
		levelExp2 = 2363,
		levelExp3 = 3545,
		levelExp4 = 5198,
		levelExp5 = 8033,
		levelExp6 = 11813
	},
	[118] = {
		id = 118,
		levelExp1 = 2386,
		levelExp2 = 2386,
		levelExp3 = 3580,
		levelExp4 = 5250,
		levelExp5 = 8113,
		levelExp6 = 11932
	},
	[119] = {
		id = 119,
		levelExp1 = 2410,
		levelExp2 = 2410,
		levelExp3 = 3616,
		levelExp4 = 5302,
		levelExp5 = 8195,
		levelExp6 = 12051
	},
	[120] = {
		id = 120,
		levelExp1 = 2434,
		levelExp2 = 2434,
		levelExp3 = 3652,
		levelExp4 = 5355,
		levelExp5 = 8277,
		levelExp6 = 12171
	},
	[121] = {
		id = 121,
		levelExp1 = 2459,
		levelExp2 = 2459,
		levelExp3 = 3689,
		levelExp4 = 5409,
		levelExp5 = 8359,
		levelExp6 = 12293
	},
	[122] = {
		id = 122,
		levelExp1 = 2483,
		levelExp2 = 2483,
		levelExp3 = 3725,
		levelExp4 = 5463,
		levelExp5 = 8443,
		levelExp6 = 12416
	},
	[123] = {
		id = 123,
		levelExp1 = 2508,
		levelExp2 = 2508,
		levelExp3 = 3763,
		levelExp4 = 5518,
		levelExp5 = 8527,
		levelExp6 = 12540
	},
	[124] = {
		id = 124,
		levelExp1 = 2533,
		levelExp2 = 2533,
		levelExp3 = 3800,
		levelExp4 = 5573,
		levelExp5 = 8613,
		levelExp6 = 12666
	},
	[125] = {
		id = 125,
		levelExp1 = 2558,
		levelExp2 = 2558,
		levelExp3 = 3838,
		levelExp4 = 5629,
		levelExp5 = 8699,
		levelExp6 = 12792
	},
	[126] = {
		id = 126,
		levelExp1 = 2584,
		levelExp2 = 2584,
		levelExp3 = 3877,
		levelExp4 = 5685,
		levelExp5 = 8786,
		levelExp6 = 12920
	},
	[127] = {
		id = 127,
		levelExp1 = 2610,
		levelExp2 = 2610,
		levelExp3 = 3915,
		levelExp4 = 5742,
		levelExp5 = 8874,
		levelExp6 = 13049
	},
	[128] = {
		id = 128,
		levelExp1 = 2636,
		levelExp2 = 2636,
		levelExp3 = 3955,
		levelExp4 = 5799,
		levelExp5 = 8962,
		levelExp6 = 13180
	},
	[129] = {
		id = 129,
		levelExp1 = 2662,
		levelExp2 = 2662,
		levelExp3 = 3994,
		levelExp4 = 5857,
		levelExp5 = 9052,
		levelExp6 = 13312
	},
	[130] = {
		id = 130,
		levelExp1 = 2689,
		levelExp2 = 2689,
		levelExp3 = 4034,
		levelExp4 = 5916,
		levelExp5 = 9142,
		levelExp6 = 13445
	},
	[131] = {
		id = 131,
		levelExp1 = 2716,
		levelExp2 = 2716,
		levelExp3 = 4074,
		levelExp4 = 5975,
		levelExp5 = 9234,
		levelExp6 = 13579
	},
	[132] = {
		id = 132,
		levelExp1 = 2743,
		levelExp2 = 2743,
		levelExp3 = 4115,
		levelExp4 = 6035,
		levelExp5 = 9326,
		levelExp6 = 13715
	},
	[133] = {
		id = 133,
		levelExp1 = 2770,
		levelExp2 = 2770,
		levelExp3 = 4156,
		levelExp4 = 6095,
		levelExp5 = 9419,
		levelExp6 = 13852
	},
	[134] = {
		id = 134,
		levelExp1 = 2798,
		levelExp2 = 2798,
		levelExp3 = 4198,
		levelExp4 = 6156,
		levelExp5 = 9514,
		levelExp6 = 13991
	},
	[135] = {
		id = 135,
		levelExp1 = 2826,
		levelExp2 = 2826,
		levelExp3 = 4240,
		levelExp4 = 6217,
		levelExp5 = 9609,
		levelExp6 = 14131
	},
	[136] = {
		id = 136,
		levelExp1 = 2854,
		levelExp2 = 2854,
		levelExp3 = 4282,
		levelExp4 = 6280,
		levelExp5 = 9705,
		levelExp6 = 14272
	},
	[137] = {
		id = 137,
		levelExp1 = 2883,
		levelExp2 = 2883,
		levelExp3 = 4325,
		levelExp4 = 6342,
		levelExp5 = 9802,
		levelExp6 = 14415
	},
	[138] = {
		id = 138,
		levelExp1 = 2912,
		levelExp2 = 2912,
		levelExp3 = 4368,
		levelExp4 = 6406,
		levelExp5 = 9900,
		levelExp6 = 14559
	},
	[139] = {
		id = 139,
		levelExp1 = 2941,
		levelExp2 = 2941,
		levelExp3 = 4412,
		levelExp4 = 6470,
		levelExp5 = 9999,
		levelExp6 = 14704
	},
	[140] = {
		id = 140,
		levelExp1 = 2970,
		levelExp2 = 2970,
		levelExp3 = 4456,
		levelExp4 = 6535,
		levelExp5 = 10099,
		levelExp6 = 14851
	},
	[141] = {
		id = 141,
		levelExp1 = 3000,
		levelExp2 = 3000,
		levelExp3 = 4501,
		levelExp4 = 6600,
		levelExp5 = 10200,
		levelExp6 = 15000
	},
	[142] = {
		id = 142,
		levelExp1 = 3030,
		levelExp2 = 3030,
		levelExp3 = 4546,
		levelExp4 = 6666,
		levelExp5 = 10302,
		levelExp6 = 15150
	},
	[143] = {
		id = 143,
		levelExp1 = 3060,
		levelExp2 = 3060,
		levelExp3 = 4591,
		levelExp4 = 6733,
		levelExp5 = 10405,
		levelExp6 = 15301
	},
	[144] = {
		id = 144,
		levelExp1 = 3091,
		levelExp2 = 3091,
		levelExp3 = 4637,
		levelExp4 = 6800,
		levelExp5 = 10509,
		levelExp6 = 15454
	},
	[145] = {
		id = 145,
		levelExp1 = 3122,
		levelExp2 = 3122,
		levelExp3 = 4683,
		levelExp4 = 6868,
		levelExp5 = 10614,
		levelExp6 = 15609
	},
	[146] = {
		id = 146,
		levelExp1 = 3153,
		levelExp2 = 3153,
		levelExp3 = 4730,
		levelExp4 = 6937,
		levelExp5 = 10720,
		levelExp6 = 15765
	},
	[147] = {
		id = 147,
		levelExp1 = 3185,
		levelExp2 = 3185,
		levelExp3 = 4778,
		levelExp4 = 7006,
		levelExp5 = 10827,
		levelExp6 = 15923
	},
	[148] = {
		id = 148,
		levelExp1 = 3216,
		levelExp2 = 3216,
		levelExp3 = 4825,
		levelExp4 = 7076,
		levelExp5 = 10936,
		levelExp6 = 16082
	},
	[149] = {
		id = 149,
		levelExp1 = 3249,
		levelExp2 = 3249,
		levelExp3 = 4874,
		levelExp4 = 7147,
		levelExp5 = 11045,
		levelExp6 = 16243
	},
	[150] = {
		id = 150,
		levelExp1 = 3281,
		levelExp2 = 3281,
		levelExp3 = 4922,
		levelExp4 = 7218,
		levelExp5 = 11156,
		levelExp6 = 16405
	},
	[151] = {
		id = 151,
		levelExp1 = 3314,
		levelExp2 = 3314,
		levelExp3 = 4972,
		levelExp4 = 7290,
		levelExp5 = 11267,
		levelExp6 = 16569
	},
	[152] = {
		id = 152,
		levelExp1 = 3347,
		levelExp2 = 3347,
		levelExp3 = 5021,
		levelExp4 = 7363,
		levelExp5 = 11380,
		levelExp6 = 16735
	},
	[153] = {
		id = 153,
		levelExp1 = 3380,
		levelExp2 = 3380,
		levelExp3 = 5072,
		levelExp4 = 7437,
		levelExp5 = 11494,
		levelExp6 = 16902
	},
	[154] = {
		id = 154,
		levelExp1 = 3414,
		levelExp2 = 3414,
		levelExp3 = 5122,
		levelExp4 = 7511,
		levelExp5 = 11608,
		levelExp6 = 17071
	},
	[155] = {
		id = 155,
		levelExp1 = 3448,
		levelExp2 = 3448,
		levelExp3 = 5173,
		levelExp4 = 7586,
		levelExp5 = 11725,
		levelExp6 = 17242
	},
	[156] = {
		id = 156,
		levelExp1 = 3483,
		levelExp2 = 3483,
		levelExp3 = 5225,
		levelExp4 = 7662,
		levelExp5 = 11842,
		levelExp6 = 17414
	},
	[157] = {
		id = 157,
		levelExp1 = 3518,
		levelExp2 = 3518,
		levelExp3 = 5277,
		levelExp4 = 7739,
		levelExp5 = 11960,
		levelExp6 = 17589
	},
	[158] = {
		id = 158,
		levelExp1 = 3553,
		levelExp2 = 3553,
		levelExp3 = 5330,
		levelExp4 = 7816,
		levelExp5 = 12080,
		levelExp6 = 17764
	},
	[159] = {
		id = 159,
		levelExp1 = 3588,
		levelExp2 = 3588,
		levelExp3 = 5384,
		levelExp4 = 7895,
		levelExp5 = 12201,
		levelExp6 = 17942
	},
	[160] = {
		id = 160,
		levelExp1 = 3624,
		levelExp2 = 3624,
		levelExp3 = 5437,
		levelExp4 = 7973,
		levelExp5 = 12323,
		levelExp6 = 18122
	},
	[161] = {
		id = 161,
		levelExp1 = 3661,
		levelExp2 = 3661,
		levelExp3 = 5492,
		levelExp4 = 8053,
		levelExp5 = 12446,
		levelExp6 = 18303
	},
	[162] = {
		id = 162,
		levelExp1 = 3697,
		levelExp2 = 3697,
		levelExp3 = 5547,
		levelExp4 = 8134,
		levelExp5 = 12570,
		levelExp6 = 18486
	},
	[163] = {
		id = 163,
		levelExp1 = 3734,
		levelExp2 = 3734,
		levelExp3 = 5602,
		levelExp4 = 8215,
		levelExp5 = 12696,
		levelExp6 = 18671
	},
	[164] = {
		id = 164,
		levelExp1 = 3771,
		levelExp2 = 3771,
		levelExp3 = 5658,
		levelExp4 = 8297,
		levelExp5 = 12823,
		levelExp6 = 18857
	},
	[165] = {
		id = 165,
		levelExp1 = 3809,
		levelExp2 = 3809,
		levelExp3 = 5715,
		levelExp4 = 8380,
		levelExp5 = 12951,
		levelExp6 = 19046
	},
	[166] = {
		id = 166,
		levelExp1 = 3847,
		levelExp2 = 3847,
		levelExp3 = 5772,
		levelExp4 = 8464,
		levelExp5 = 13081,
		levelExp6 = 19236
	},
	[167] = {
		id = 167,
		levelExp1 = 3886,
		levelExp2 = 3886,
		levelExp3 = 5830,
		levelExp4 = 8549,
		levelExp5 = 13212,
		levelExp6 = 19429
	},
	[168] = {
		id = 168,
		levelExp1 = 3925,
		levelExp2 = 3925,
		levelExp3 = 5888,
		levelExp4 = 8634,
		levelExp5 = 13344,
		levelExp6 = 19623
	},
	[169] = {
		id = 169,
		levelExp1 = 3964,
		levelExp2 = 3964,
		levelExp3 = 5947,
		levelExp4 = 8720,
		levelExp5 = 13477,
		levelExp6 = 19819
	},
	[170] = {
		id = 170,
		levelExp1 = 4003,
		levelExp2 = 4003,
		levelExp3 = 6006,
		levelExp4 = 8808,
		levelExp5 = 13612,
		levelExp6 = 20017
	},
	[171] = {
		id = 171,
		levelExp1 = 4044,
		levelExp2 = 4044,
		levelExp3 = 6066,
		levelExp4 = 8896,
		levelExp5 = 13748,
		levelExp6 = 20218
	},
	[172] = {
		id = 172,
		levelExp1 = 4084,
		levelExp2 = 4084,
		levelExp3 = 6127,
		levelExp4 = 8985,
		levelExp5 = 13885,
		levelExp6 = 20420
	},
	[173] = {
		id = 173,
		levelExp1 = 4125,
		levelExp2 = 4125,
		levelExp3 = 6188,
		levelExp4 = 9075,
		levelExp5 = 14024,
		levelExp6 = 20624
	},
	[174] = {
		id = 174,
		levelExp1 = 4166,
		levelExp2 = 4166,
		levelExp3 = 6250,
		levelExp4 = 9165,
		levelExp5 = 14165,
		levelExp6 = 20830
	},
	[175] = {
		id = 175,
		levelExp1 = 4208,
		levelExp2 = 4208,
		levelExp3 = 6313,
		levelExp4 = 9257,
		levelExp5 = 14306,
		levelExp6 = 21039
	},
	[176] = {
		id = 176,
		levelExp1 = 4250,
		levelExp2 = 4250,
		levelExp3 = 6376,
		levelExp4 = 9350,
		levelExp5 = 14449,
		levelExp6 = 21249
	},
	[177] = {
		id = 177,
		levelExp1 = 4292,
		levelExp2 = 4292,
		levelExp3 = 6440,
		levelExp4 = 9443,
		levelExp5 = 14594,
		levelExp6 = 21461
	},
	[178] = {
		id = 178,
		levelExp1 = 4335,
		levelExp2 = 4335,
		levelExp3 = 6504,
		levelExp4 = 9537,
		levelExp5 = 14740,
		levelExp6 = 21676
	},
	[179] = {
		id = 179,
		levelExp1 = 4379,
		levelExp2 = 4379,
		levelExp3 = 6569,
		levelExp4 = 9633,
		levelExp5 = 14887,
		levelExp6 = 21893
	},
	[180] = {
		id = 180,
		levelExp1 = 4422,
		levelExp2 = 4422,
		levelExp3 = 6635,
		levelExp4 = 9729,
		levelExp5 = 15036,
		levelExp6 = 22112
	},
	[181] = {
		id = 181,
		levelExp1 = 4467,
		levelExp2 = 4467,
		levelExp3 = 6701,
		levelExp4 = 9826,
		levelExp5 = 15186,
		levelExp6 = 22333
	},
	[182] = {
		id = 182,
		levelExp1 = 4511,
		levelExp2 = 4511,
		levelExp3 = 6768,
		levelExp4 = 9925,
		levelExp5 = 15338,
		levelExp6 = 22556
	},
	[183] = {
		id = 183,
		levelExp1 = 4556,
		levelExp2 = 4556,
		levelExp3 = 6836,
		levelExp4 = 10024,
		levelExp5 = 15492,
		levelExp6 = 22782
	},
	[184] = {
		id = 184,
		levelExp1 = 4602,
		levelExp2 = 4602,
		levelExp3 = 6904,
		levelExp4 = 10124,
		levelExp5 = 15647,
		levelExp6 = 23010
	},
	[185] = {
		id = 185,
		levelExp1 = 4648,
		levelExp2 = 4648,
		levelExp3 = 6973,
		levelExp4 = 10225,
		levelExp5 = 15803,
		levelExp6 = 23240
	},
	[186] = {
		id = 186,
		levelExp1 = 4694,
		levelExp2 = 4694,
		levelExp3 = 7043,
		levelExp4 = 10328,
		levelExp5 = 15961,
		levelExp6 = 23472
	},
	[187] = {
		id = 187,
		levelExp1 = 4741,
		levelExp2 = 4741,
		levelExp3 = 7113,
		levelExp4 = 10431,
		levelExp5 = 16121,
		levelExp6 = 23707
	},
	[188] = {
		id = 188,
		levelExp1 = 4789,
		levelExp2 = 4789,
		levelExp3 = 7184,
		levelExp4 = 10535,
		levelExp5 = 16282,
		levelExp6 = 23944
	},
	[189] = {
		id = 189,
		levelExp1 = 4837,
		levelExp2 = 4837,
		levelExp3 = 7256,
		levelExp4 = 10641,
		levelExp5 = 16445,
		levelExp6 = 24183
	},
	[190] = {
		id = 190,
		levelExp1 = 4885,
		levelExp2 = 4885,
		levelExp3 = 7329,
		levelExp4 = 10747,
		levelExp5 = 16609,
		levelExp6 = 24425
	},
	[191] = {
		id = 191,
		levelExp1 = 4934,
		levelExp2 = 4934,
		levelExp3 = 7402,
		levelExp4 = 10855,
		levelExp5 = 16775,
		levelExp6 = 24669
	},
	[192] = {
		id = 192,
		levelExp1 = 4983,
		levelExp2 = 4983,
		levelExp3 = 7476,
		levelExp4 = 10963,
		levelExp5 = 16943,
		levelExp6 = 24916
	},
	[193] = {
		id = 193,
		levelExp1 = 5033,
		levelExp2 = 5033,
		levelExp3 = 7551,
		levelExp4 = 11073,
		levelExp5 = 17112,
		levelExp6 = 25165
	},
	[194] = {
		id = 194,
		levelExp1 = 5083,
		levelExp2 = 5083,
		levelExp3 = 7626,
		levelExp4 = 11183,
		levelExp5 = 17283,
		levelExp6 = 25417
	},
	[195] = {
		id = 195,
		levelExp1 = 5134,
		levelExp2 = 5134,
		levelExp3 = 7703,
		levelExp4 = 11295,
		levelExp5 = 17456,
		levelExp6 = 25671
	},
	[196] = {
		id = 196,
		levelExp1 = 5186,
		levelExp2 = 5186,
		levelExp3 = 7780,
		levelExp4 = 11408,
		levelExp5 = 17631,
		levelExp6 = 25928
	},
	[197] = {
		id = 197,
		levelExp1 = 5237,
		levelExp2 = 5237,
		levelExp3 = 7857,
		levelExp4 = 11522,
		levelExp5 = 17807,
		levelExp6 = 26187
	},
	[198] = {
		id = 198,
		levelExp1 = 5290,
		levelExp2 = 5290,
		levelExp3 = 7936,
		levelExp4 = 11638,
		levelExp5 = 17985,
		levelExp6 = 26449
	},
	[199] = {
		id = 199,
		levelExp1 = 5343,
		levelExp2 = 5343,
		levelExp3 = 8015,
		levelExp4 = 11754,
		levelExp5 = 18165,
		levelExp6 = 26713
	},
	[200] = {
		id = 200,
		levelExp1 = 5396,
		levelExp2 = 5396,
		levelExp3 = 8096,
		levelExp4 = 11871,
		levelExp5 = 18347,
		levelExp6 = 26981
	},

	__size = 200,
	__default = {
		__index = {
			levelExp1 = 0,
			levelExp2 = 0,
			levelExp3 = 0,
			levelExp4 = 0,
			levelExp5 = 0,
			levelExp6 = 0
		}
	}
}
return csv.chip.strength_cost