--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {}, 
	[10] = {{__size = 0}, {['gold'] = 6000000, ['rmb'] = 1500, [521] = 30, [501] = 5, __size = 4}}, 
	[12] = {{__size = 0}}, __size = 3}
local __data_t__cost = {
	[11] = __predefine_t__[12],
	[10] = __predefine_t__[10],
	[13] = __predefine_t__[12],
	[12] = __predefine_t__[12],
	[15] = __predefine_t__[12],
	[14] = __predefine_t__[12],
	[16] = __predefine_t__[12],
	["default"] = __predefine_t__[1],
	[9] = __predefine_t__[10]
}
local __data_t__conditionCards = {
	["default"] = __predefine_t__[1]
}

csv['cards_branch_cost'] = {
	[1] = {
		id = 1,
		cost = {{['rmb'] = 100, __size = 1}}
	},
	[2] = {
		id = 2,
		developType = 2,
		cost = {{['rmb'] = 300, __size = 1}}
	},
	[3] = {
		id = 3,
		developType = 3,
		cost = {{['rmb'] = 500, __size = 1}}
	},
	[4] = {
		id = 4,
		developType = 4,
		cost = {{['rmb'] = 800, __size = 1}}
	},
	[5] = {
		id = 5,
		developType = 5,
		cost = {{['rmb'] = 100, __size = 1}, {['rmb'] = 0, __size = 1}}
	},
	[6] = {
		id = 6,
		developType = 6,
		cost = {{['rmb'] = 300, __size = 1}, {['rmb'] = 0, __size = 1}}
	},
	[7] = {
		id = 7,
		developType = 7,
		cost = {{['rmb'] = 500, __size = 1}, {['rmb'] = 0, __size = 1}},
		switchCD = 432000
	},
	[8] = {
		id = 8,
		developType = 8,
		cost = __data_t__cost[9],
		switchCD = 432000
	},
	[9] = {
		id = 9,
		developType = 9,
		cost = __data_t__cost[9],
		-- {{__size = 0}, {['gold'] = 6000000, ['rmb'] = 1500, [521] = 30, [501] = 5, __size = 4}}
		conditionMain = true
	},
	[10] = {
		id = 10,
		developType = 10,
		cost = __data_t__cost[10],
		-- {{__size = 0}, {['gold'] = 6000000, ['rmb'] = 1500, [521] = 30, [501] = 5, __size = 4}}
		conditionCards = {{1911, 8}}
	},
	[11] = {
		id = 11,
		developType = 11,
		cost = __data_t__cost[11],
		-- {{__size = 0}}
		conditionCards = {{1921, 8}}
	},
	[12] = {
		id = 12,
		developType = 12,
		cost = __data_t__cost[12],
		-- {{__size = 0}}
		conditionCards = {{1931, 8}}
	},
	[13] = {
		id = 13,
		developType = 13,
		cost = __data_t__cost[13],
		-- {{__size = 0}}
		conditionCards = {{4651, 8}}
	},
	[14] = {
		id = 14,
		developType = 14,
		cost = __data_t__cost[14],
		-- {{__size = 0}}
		conditionCards = {{4641, 8}}
	},
	[15] = {
		id = 15,
		developType = 15,
		cost = __data_t__cost[15]
		-- {{__size = 0}}
	},
	[16] = {
		id = 16,
		developType = 16,
		cost = __data_t__cost[16]
		-- {{__size = 0}}
	},
	__size = 16,
	__default = {
		__index = {
			developType = 1,
			cost = __data_t__cost["default"]	--[[ {}]],
			switchCD = 0,
			conditionMain = false,
			conditionCards = __data_t__conditionCards["default"]	--[[ {}]]
		}
	}
}
return csv.cards_branch_cost