--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {__size = 0}, 
	[4] = {'cn'}, 
	[7] = {['rmb'] = 998, __size = 1}, 
	[20] = {'cn', 'tw', 'en', 'en_us', 'en_eu', 'kr'}, 
	[29] = {'cn', 'tw', 'kr', 'en', 'en_us', 'en_eu'}, 
	[37] = {'cn', 'kr', 'tw', 'en', 'en_us', 'en_eu'}, 
	[50] = {'cn', 'kr', 'en', 'en_us', 'en_eu', 'tw'}, 
	[67] = {'cn', 'kr'}, __size = 8}
local __data_t__extraItem = {
	["default"] = __predefine_t__[1]
}
local __data_t__costMap = {
	["default"] = __predefine_t__[1],
	[103] = __predefine_t__[7],
	[107] = __predefine_t__[7]
}
local __data_t__unitIDs = {
	["default"] = __predefine_t__[1]
}
local __data_t__languages = {
	[151] = __predefine_t__[20],
	[150] = __predefine_t__[50],
	[153] = __predefine_t__[67],
	[152] = __predefine_t__[50],
	[155] = __predefine_t__[67],
	[135] = __predefine_t__[29],
	[157] = __predefine_t__[4],
	[156] = __predefine_t__[50],
	[159] = __predefine_t__[4],
	[158] = __predefine_t__[4],
	[134] = __predefine_t__[29],
	[115] = __predefine_t__[20],
	[114] = __predefine_t__[20],
	[117] = __predefine_t__[20],
	[116] = __predefine_t__[20],
	[111] = __predefine_t__[4],
	[110] = __predefine_t__[4],
	[113] = __predefine_t__[20],
	[112] = __predefine_t__[4],
	[139] = __predefine_t__[29],
	[138] = __predefine_t__[50],
	[119] = __predefine_t__[20],
	[165] = __predefine_t__[4],
	[154] = __predefine_t__[4],
	[161] = __predefine_t__[4],
	[162] = __predefine_t__[4],
	[128] = __predefine_t__[37],
	[163] = __predefine_t__[4],
	[146] = __predefine_t__[37],
	[147] = __predefine_t__[37],
	[144] = __predefine_t__[29],
	[145] = __predefine_t__[37],
	[142] = __predefine_t__[29],
	[143] = __predefine_t__[29],
	[140] = __predefine_t__[29],
	[148] = __predefine_t__[37],
	[149] = __predefine_t__[50],
	[120] = __predefine_t__[29],
	[121] = __predefine_t__[20],
	[122] = __predefine_t__[20],
	[109] = __predefine_t__[4],
	[124] = __predefine_t__[29],
	[125] = __predefine_t__[29],
	[126] = __predefine_t__[37],
	[127] = __predefine_t__[37],
	[102] = __predefine_t__[4],
	[103] = __predefine_t__[4],
	[101] = __predefine_t__[4],
	[160] = __predefine_t__[4],
	[107] = __predefine_t__[4],
	[129] = __predefine_t__[37],
	[105] = __predefine_t__[4],
	[133] = __predefine_t__[29],
	[132] = __predefine_t__[29],
	[108] = __predefine_t__[4],
	[131] = __predefine_t__[37],
	[130] = __predefine_t__[37],
	[137] = __predefine_t__[29],
	[164] = __predefine_t__[4],
	[136] = __predefine_t__[29]
}

csv['card_skin'] = {
	[101] = {
		id = 101,
		name = '圣诞魔影',
		desc = '可通过参与2020年圣诞活动获得',
		unitIDs = {[3021] = 3022, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 3021,
		attrType1 = 9,
		attrNum1 = '3%',
		attrType2 = 10,
		attrNum2 = '3%',
		isOpen = true,
		languages = __data_t__languages[101]
		-- {'cn'}
	},
	[102] = {
		id = 102,
		name = '冰雪公主',
		desc = '可通过参与2020年圣诞活动获得',
		unitIDs = {[3631] = 3632, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 3631,
		attrType1 = 16,
		attrNum1 = '300',
		attrType2 = 9,
		attrNum2 = '5%',
		attrType3 = 10,
		attrNum3 = '5%',
		isOpen = true,
		languages = __data_t__languages[102]
		-- {'cn'}
	},
	[103] = {
		id = 103,
		name = '封印之力',
		unitIDs = {[3642] = 3643, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 3641,
		costMap = __data_t__costMap[103],
		-- {['rmb'] = 998, __size = 1}
		isOpen = true,
		languages = __data_t__languages[103]
		-- {'cn'}
	},
	[104] = {
		id = 104,
		name = '偷心怪盗',
		desc = '可通过参与2021年新年活动获得',
		unitIDs = {[2431] = 2432, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 2431,
		attrType1 = 8,
		attrNum1 = '5%',
		attrType2 = 22,
		attrNum2 = '300',
		isOpen = true,
		languages = {'cn', 'tw', 'en', 'kr'}
	},
	[105] = {
		id = 105,
		name = '街头拳手',
		desc = '可通过参与2021年新年活动获得',
		unitIDs = {[572] = 573, [574] = 575, __size = 2},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 571,
		attrType1 = 7,
		attrNum1 = '2%',
		attrType2 = 14,
		attrNum2 = '100',
		isOpen = true,
		languages = __data_t__languages[105]
		-- {'cn'}
	},
	[106] = {
		id = 106,
		name = '鱼龙夜舞',
		desc = '可通过参与2021年元宵活动获得',
		unitIDs = {[1396] = 1397, [1393] = 1395, __size = 2},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 1391,
		attrType1 = 8,
		attrNum1 = '2%',
		attrType2 = 24,
		attrNum2 = '100',
		isOpen = true,
		languages = {'cn', 'tw'}
	},
	[107] = {
		id = 107,
		name = '守卫恒心',
		unitIDs = {[4172] = 4173, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 4171,
		costMap = __data_t__costMap[107],
		-- {['rmb'] = 998, __size = 1}
		isOpen = true,
		languages = __data_t__languages[107]
		-- {'cn'}
	},
	[108] = {
		id = 108,
		name = '西域魔灵',
		desc = '可通过参与2021年618活动获得',
		unitIDs = {[3642] = 3644, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 3641,
		attrType1 = 1,
		attrNum1 = '5%',
		attrType2 = 24,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[108]
		-- {'cn'}
	},
	[109] = {
		id = 109,
		name = '街头滑板',
		desc = '可通过参与2021年国庆活动获得',
		unitIDs = {[2242] = 2243, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 2241,
		attrType1 = 7,
		attrNum1 = '2%',
		attrType2 = 8,
		attrNum2 = '2%',
		attrType3 = 24,
		attrNum3 = '100',
		isOpen = true,
		languages = __data_t__languages[109]
		-- {'cn'}
	},
	[110] = {
		id = 110,
		name = '时间侠盗',
		unitIDs = {[1281] = 1282, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 1281,
		attrType1 = 1,
		attrNum1 = '5%',
		attrType2 = 16,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[110]
		-- {'cn'}
	},
	[111] = {
		id = 111,
		name = '银霄战甲',
		unitIDs = {[1982] = 1984, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_r.png',
		markID = 1981,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 8,
		attrNum2 = '5%',
		attrType3 = 14,
		attrNum3 = '500',
		isOpen = true,
		languages = __data_t__languages[111]
		-- {'cn'}
	},
	[112] = {
		id = 112,
		name = '幽灵船长',
		desc = '可通过参与2021年万圣节活动获得',
		unitIDs = {[393] = 395, [394] = 396, __size = 2},
		skinFrameRes = 'city/drawcard/draw/panel_card_r.png',
		markID = 391,
		attrType1 = 8,
		attrNum1 = '2%',
		attrType2 = 24,
		attrNum2 = '100',
		isOpen = true,
		languages = __data_t__languages[112]
		-- {'cn'}
	},
	[113] = {
		id = 113,
		name = '魔法星使',
		desc = '可通过活动获得',
		unitIDs = {[1991] = 1992, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 1991,
		attrType1 = 1,
		attrNum1 = '5%',
		attrType2 = 16,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[113]
		-- {'cn', 'tw', 'en', 'en_us', 'en_eu', 'kr'}
	},
	[114] = {
		id = 114,
		name = '圣诞老人',
		desc = '可通过活动获得',
		unitIDs = {[263] = 265, [264] = 266, __size = 2},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 261,
		attrType1 = 90,
		attrNum1 = '100',
		attrType2 = 13,
		attrNum2 = '1%',
		isOpen = true,
		languages = __data_t__languages[114]
		-- {'cn', 'tw', 'en', 'en_us', 'en_eu', 'kr'}
	},
	[115] = {
		id = 115,
		name = '九色鹿鸣',
		desc = '可通过活动获得',
		unitIDs = {[3601] = 3603, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 3601,
		attrType1 = 1,
		attrNum1 = '5%',
		attrType2 = 25,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[115]
		-- {'cn', 'tw', 'en', 'en_us', 'en_eu', 'kr'}
	},
	[116] = {
		id = 116,
		name = '霓虹闪电',
		desc = '可通过活动获得',
		unitIDs = {[4161] = 4162, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 4161,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 24,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[116]
		-- {'cn', 'tw', 'en', 'en_us', 'en_eu', 'kr'}
	},
	[117] = {
		id = 117,
		name = '圣翼红莲',
		desc = '可通过活动获得',
		unitIDs = {[7001] = 7002, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 7001,
		attrType1 = 8,
		attrNum1 = '2%',
		attrType2 = 90,
		attrNum2 = '100',
		isOpen = true,
		languages = __data_t__languages[117]
		-- {'cn', 'tw', 'en', 'en_us', 'en_eu', 'kr'}
	},
	[118] = {
		id = 118,
		name = '月下蔷薇',
		desc = '可通过活动获得',
		unitIDs = {[1397] = 1390, [1394] = 1399, __size = 2},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 1391,
		attrType1 = 24,
		attrNum1 = '150',
		isOpen = true,
		languages = {'cn', 'en', 'tw', 'kr', 'en_us'}
	},
	[119] = {
		id = 119,
		name = '胜利武装',
		desc = '可通过活动获得',
		unitIDs = {[2461] = 2463, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 2461,
		attrType1 = 13,
		attrNum1 = '3%',
		attrType2 = 16,
		attrNum2 = '350',
		isOpen = true,
		languages = __data_t__languages[119]
		-- {'cn', 'tw', 'en', 'en_us', 'en_eu', 'kr'}
	},
	[120] = {
		id = 120,
		name = '烈焰机甲',
		desc = '可通过活动获得',
		unitIDs = {[1972] = 1973, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_r.png',
		markID = 1971,
		attrType1 = 9,
		attrNum1 = '5%',
		attrType2 = 10,
		attrNum2 = '5%',
		attrType3 = 16,
		attrNum3 = '500',
		isOpen = true,
		languages = __data_t__languages[120]
		-- {'cn', 'tw', 'kr', 'en', 'en_us', 'en_eu'}
	},
	[121] = {
		id = 121,
		name = '夜幕影忍',
		desc = '可通过活动获得',
		unitIDs = {[4121] = 4122, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 4121,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 22,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[121]
		-- {'cn', 'tw', 'en', 'en_us', 'en_eu', 'kr'}
	},
	[122] = {
		id = 122,
		name = '乐动星使',
		desc = '可通过活动获得',
		unitIDs = {[4111] = 4112, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 4111,
		attrType1 = 1,
		attrNum1 = '5%',
		attrType2 = 25,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[122]
		-- {'cn', 'tw', 'en', 'en_us', 'en_eu', 'kr'}
	},
	[123] = {
		id = 123,
		name = '梦华秋月',
		desc = '可通过活动获得',
		unitIDs = {[2401] = 2402, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 2401,
		attrType1 = 1,
		attrNum1 = '2%',
		attrType2 = 23,
		attrNum2 = '100',
		isOpen = true,
		languages = {'cn', 'tw', 'kr'}
	},
	[124] = {
		id = 124,
		name = '甜心守护',
		desc = '可通过活动获得',
		unitIDs = {[4172] = 4174, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 4171,
		attrType1 = 9,
		attrNum1 = '5%',
		attrType2 = 10,
		attrNum2 = '5%',
		attrType3 = 17,
		attrNum3 = '300',
		isOpen = true,
		languages = __data_t__languages[124]
		-- {'cn', 'tw', 'kr', 'en', 'en_us', 'en_eu'}
	},
	[125] = {
		id = 125,
		name = '鱼咎于形',
		desc = '可通过活动获得',
		unitIDs = {[1962] = 1963, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_r.png',
		markID = 1961,
		attrType1 = 9,
		attrNum1 = '5%',
		attrType2 = 10,
		attrNum2 = '5%',
		attrType3 = 23,
		attrNum3 = '500',
		isOpen = true,
		languages = __data_t__languages[125]
		-- {'cn', 'tw', 'kr', 'en', 'en_us', 'en_eu'}
	},
	[126] = {
		id = 126,
		name = '歌剧魅影',
		desc = '可通过活动获得',
		unitIDs = {[2421] = 2424, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 2421,
		attrType1 = 1,
		attrNum1 = '5%',
		attrType2 = 16,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[126]
		-- {'cn', 'kr', 'tw', 'en', 'en_us', 'en_eu'}
	},
	[127] = {
		id = 127,
		name = '阿拉丁',
		desc = '可通过活动获得',
		unitIDs = {[1813] = 1814, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 1811,
		attrType1 = 1,
		attrNum1 = '2%',
		attrType2 = 13,
		attrNum2 = '1%',
		isOpen = true,
		languages = __data_t__languages[127]
		-- {'cn', 'kr', 'tw', 'en', 'en_us', 'en_eu'}
	},
	[128] = {
		id = 128,
		name = '般若鬼武',
		desc = '可通过活动获得',
		unitIDs = {[7021] = 7022, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 7021,
		attrType1 = 8,
		attrNum1 = '5%',
		attrType2 = 5,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[128]
		-- {'cn', 'kr', 'tw', 'en', 'en_us', 'en_eu'}
	},
	[129] = {
		id = 129,
		name = '暗曜磁暴',
		desc = '可通过2022年圣诞活动获得',
		unitIDs = {[4023] = 4123, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 4023,
		attrType1 = 9,
		attrNum1 = '5%',
		attrType2 = 10,
		attrNum2 = '5%',
		attrType3 = 16,
		attrNum3 = '300',
		isOpen = true,
		languages = __data_t__languages[129]
		-- {'cn', 'kr', 'tw', 'en', 'en_us', 'en_eu'}
	},
	[130] = {
		id = 130,
		name = '杀戮电锯',
		desc = '可通过活动获得',
		unitIDs = {[4081] = 4082, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 4081,
		attrType1 = 7,
		attrNum1 = '2%',
		attrType2 = 14,
		attrNum2 = '100',
		isOpen = true,
		languages = __data_t__languages[130]
		-- {'cn', 'kr', 'tw', 'en', 'en_us', 'en_eu'}
	},
	[131] = {
		id = 131,
		name = '煞行破邪',
		desc = '可通过活动获得',
		unitIDs = {[7031] = 7034, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 7031,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 24,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[131]
		-- {'cn', 'kr', 'tw', 'en', 'en_us', 'en_eu'}
	},
	[132] = {
		id = 132,
		name = '雷电祥云',
		desc = '可通过活动获得',
		unitIDs = {[731] = 732, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 731,
		attrType1 = 8,
		attrNum1 = '2%',
		attrType2 = 5,
		attrNum2 = '100',
		isOpen = true,
		languages = __data_t__languages[132]
		-- {'cn', 'tw', 'kr', 'en', 'en_us', 'en_eu'}
	},
	[133] = {
		id = 133,
		name = '偶像歌姬',
		desc = '可通过活动获得',
		unitIDs = {[3261] = 3265, [3262] = 3266, __size = 2},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 3261,
		attrType1 = 13,
		attrNum1 = '3%',
		attrType2 = 24,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[133]
		-- {'cn', 'tw', 'kr', 'en', 'en_us', 'en_eu'}
	},
	[134] = {
		id = 134,
		name = '沙漠死神',
		desc = '可通过活动获得',
		unitIDs = {[4101] = 4102, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 4101,
		attrType1 = 8,
		attrNum1 = '5%',
		attrType2 = 14,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[134]
		-- {'cn', 'tw', 'kr', 'en', 'en_us', 'en_eu'}
	},
	[135] = {
		id = 135,
		name = '月满花繁',
		desc = '可通过活动获得',
		unitIDs = {[4024] = 4124, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 4024,
		attrType1 = 1,
		attrNum1 = '5%',
		attrType2 = 25,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[135]
		-- {'cn', 'tw', 'kr', 'en', 'en_us', 'en_eu'}
	},
	[136] = {
		id = 136,
		name = '誓约之剑',
		desc = '可通过活动获得',
		unitIDs = {[3632] = 3634, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_r.png',
		markID = 3631,
		attrType1 = 1,
		attrNum1 = '5%',
		attrType2 = 17,
		attrNum2 = '500',
		isOpen = true,
		languages = __data_t__languages[136]
		-- {'cn', 'tw', 'kr', 'en', 'en_us', 'en_eu'}
	},
	[137] = {
		id = 137,
		name = '玄音余韵',
		desc = '可通过活动获得',
		unitIDs = {[4071] = 4072, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 4071,
		attrType1 = 1,
		attrNum1 = '2%',
		attrType2 = 23,
		attrNum2 = '100',
		isOpen = true,
		languages = __data_t__languages[137]
		-- {'cn', 'tw', 'kr', 'en', 'en_us', 'en_eu'}
	},
	[138] = {
		id = 138,
		name = '恶魔女王',
		desc = '可通过活动获得',
		unitIDs = {[7051] = 7053, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 7051,
		attrType1 = 8,
		attrNum1 = '5%',
		attrType2 = 5,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[138]
		-- {'cn', 'kr', 'en', 'en_us', 'en_eu', 'tw'}
	},
	[139] = {
		id = 139,
		name = '星际追击',
		desc = '可通过活动获得',
		unitIDs = {[7041] = 7049, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 7041,
		attrType1 = 1,
		attrNum1 = '5%',
		attrType2 = 25,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[139]
		-- {'cn', 'tw', 'kr', 'en', 'en_us', 'en_eu'}
	},
	[140] = {
		id = 140,
		name = '流夏清梦',
		desc = '可通过活动获得',
		unitIDs = {[7051] = 7055, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 7051,
		attrType1 = 8,
		attrNum1 = '5%',
		attrType2 = 90,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[140]
		-- {'cn', 'tw', 'kr', 'en', 'en_us', 'en_eu'}
	},
	[141] = {
		id = 141,
		name = '太极如御',
		desc = '可通过活动获得',
		unitIDs = {[4601] = 4602, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 4601,
		attrType1 = 9,
		attrNum1 = '5%',
		attrType2 = 10,
		attrNum2 = '5%',
		attrType3 = 17,
		attrNum3 = '300',
		isOpen = true,
		languages = {'cn', 'kr', 'tw', 'en', 'en_us'}
	},
	[142] = {
		id = 142,
		name = '星际制裁者',
		desc = '可通过活动获得',
		unitIDs = {[762] = 759, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_r.png',
		markID = 761,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 8,
		attrNum2 = '5%',
		attrType3 = 14,
		attrNum3 = '500',
		isOpen = true,
		languages = __data_t__languages[142]
		-- {'cn', 'tw', 'kr', 'en', 'en_us', 'en_eu'}
	},
	[143] = {
		id = 143,
		name = '摩诃伽罗',
		desc = '可通过活动获得',
		unitIDs = {[3642] = 3645, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 3641,
		attrType1 = 8,
		attrNum1 = '5%',
		attrType2 = 24,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[143]
		-- {'cn', 'tw', 'kr', 'en', 'en_us', 'en_eu'}
	},
	[144] = {
		id = 144,
		name = '深渊祭坛',
		desc = '可通过活动获得',
		unitIDs = {[4141] = 4142, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 4141,
		attrType1 = 1,
		attrNum1 = '2%',
		attrType2 = 23,
		attrNum2 = '100',
		isOpen = true,
		languages = __data_t__languages[144]
		-- {'cn', 'tw', 'kr', 'en', 'en_us', 'en_eu'}
	},
	[145] = {
		id = 145,
		name = '沧海明珠',
		desc = '可通过活动获得',
		unitIDs = {[7071] = 7073, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 7071,
		attrType1 = 8,
		attrNum1 = '5%',
		attrType2 = 18,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[145]
		-- {'cn', 'kr', 'tw', 'en', 'en_us', 'en_eu'}
	},
	[146] = {
		id = 146,
		name = '复仇魔女',
		desc = '可通过活动获得',
		unitIDs = {[3632] = 3639, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_r.png',
		markID = 3631,
		attrType1 = 9,
		attrNum1 = '5%',
		attrType2 = 10,
		attrNum2 = '5%',
		attrType3 = 16,
		attrNum3 = '500',
		isOpen = true,
		languages = __data_t__languages[146]
		-- {'cn', 'kr', 'tw', 'en', 'en_us', 'en_eu'}
	},
	[147] = {
		id = 147,
		name = '星际吞噬',
		desc = '可通过活动获得',
		unitIDs = {[3623] = 3626, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 3621,
		attrType1 = 1,
		attrNum1 = '5%',
		attrType2 = 23,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[147],
		-- {'cn', 'kr', 'tw', 'en', 'en_us', 'en_eu'}
		sign = '灵感来源：Crystal'
	},
	[148] = {
		id = 148,
		name = '皇家骑士',
		desc = '可通过活动获得',
		unitIDs = {[2411] = 2413, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 2411,
		attrType1 = 1,
		attrNum1 = '2%',
		attrType2 = 13,
		attrNum2 = '2%',
		isOpen = true,
		languages = __data_t__languages[148]
		-- {'cn', 'kr', 'tw', 'en', 'en_us', 'en_eu'}
	},
	[149] = {
		id = 149,
		name = '太极离火',
		desc = '可通过活动获得',
		unitIDs = {[4591] = 4592, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 4591,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 22,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[149]
		-- {'cn', 'kr', 'en', 'en_us', 'en_eu', 'tw'}
	},
	[150] = {
		id = 150,
		name = '幻梦试剂',
		desc = '可通过活动获得',
		unitIDs = {[992] = 993, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 991,
		attrType1 = 1,
		attrNum1 = '2%',
		attrType2 = 27,
		attrNum2 = '100',
		isOpen = true,
		languages = __data_t__languages[150]
		-- {'cn', 'kr', 'en', 'en_us', 'en_eu', 'tw'}
	},
	[151] = {
		id = 151,
		name = '恶魔侍卫',
		desc = '可通过活动获得',
		unitIDs = {[7061] = 7062, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 7061,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 18,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[151]
		-- {'cn', 'tw', 'en', 'en_us', 'en_eu', 'kr'}
	},
	[152] = {
		id = 152,
		name = '奶爸拳魂',
		desc = '可通过活动获得',
		unitIDs = {[4631] = 4633, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 4631,
		attrType1 = 1,
		attrNum1 = '5%',
		attrType2 = 28,
		attrNum2 = '400',
		isOpen = true,
		languages = __data_t__languages[152]
		-- {'cn', 'kr', 'en', 'en_us', 'en_eu', 'tw'}
	},
	[153] = {
		id = 153,
		name = '次元骇客',
		desc = '可通过活动获得',
		unitIDs = {[763] = 767, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_r.png',
		markID = 761,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 8,
		attrNum2 = '5%',
		attrType3 = 24,
		attrNum3 = '500',
		isOpen = true,
		languages = __data_t__languages[153]
		-- {'cn', 'kr'}
	},
	[154] = {
		id = 154,
		name = '电音狂想',
		desc = '可通过活动获得',
		unitIDs = {[4061] = 4062, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 4061,
		attrType1 = 8,
		attrNum1 = '2%',
		attrType2 = 14,
		attrNum2 = '100',
		isOpen = true,
		languages = __data_t__languages[154]
		-- {'cn'}
	},
	[155] = {
		id = 155,
		name = '白羽圣骑',
		desc = '可通过活动获得',
		unitIDs = {[4682] = 4684, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 4682,
		attrType1 = 1,
		attrNum1 = '5%',
		attrType2 = 27,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[155]
		-- {'cn', 'kr'}
	},
	[156] = {
		id = 156,
		name = '义海军魂',
		desc = '可通过活动获得',
		unitIDs = {[4161] = 4163, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 4161,
		attrType1 = 13,
		attrNum1 = '3%',
		attrType2 = 24,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[156]
		-- {'cn', 'kr', 'en', 'en_us', 'en_eu', 'tw'}
	},
	[157] = {
		id = 157,
		name = '释天龙王',
		desc = '可通过活动获得',
		unitIDs = {[3243] = 3247, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_r.png',
		markID = 3242,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 8,
		attrNum2 = '5%',
		attrType3 = 14,
		attrNum3 = '500',
		isOpen = true,
		languages = __data_t__languages[157]
		-- {'cn'}
	},
	[158] = {
		id = 158,
		name = '多闻天王',
		desc = '可通过活动获得',
		unitIDs = {[3191] = 3192, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 3191,
		attrType1 = 8,
		attrNum1 = '2%',
		attrType2 = 5,
		attrNum2 = '100',
		isOpen = true,
		languages = __data_t__languages[158]
		-- {'cn'}
	},
	[159] = {
		id = 159,
		name = '亢金龙',
		desc = '可通过活动获得',
		unitIDs = {[5391] = 5392, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 5391,
		attrType1 = 13,
		attrNum1 = '3%',
		attrType2 = 24,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[159]
		-- {'cn'}
	},
	[160] = {
		id = 160,
		name = '幻海潮生',
		desc = '可通过活动获得',
		unitIDs = {[2421] = 2437, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 2421,
		attrType1 = 9,
		attrNum1 = '5%',
		attrType2 = 10,
		attrNum2 = '5%',
		attrType3 = 23,
		attrNum3 = '300',
		isOpen = true,
		languages = __data_t__languages[160]
		-- {'cn'}
	},
	[161] = {
		id = 161,
		name = '天命猴',
		desc = '可通过活动获得',
		unitIDs = {[2023] = 2024, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 2021,
		attrType1 = 7,
		attrNum1 = '2%',
		attrType2 = 14,
		attrNum2 = '100',
		isOpen = true,
		languages = __data_t__languages[161]
		-- {'cn'}
	},
	[162] = {
		id = 162,
		name = '梵天烈焰',
		desc = '可通过活动获得',
		unitIDs = {[3242] = 3248, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_r.png',
		markID = 3242,
		attrType1 = 9,
		attrNum1 = '5%',
		attrType2 = 10,
		attrNum2 = '5%',
		attrType3 = 25,
		attrNum3 = '500',
		isOpen = true,
		languages = __data_t__languages[162]
		-- {'cn'}
	},
	[163] = {
		id = 163,
		name = '持国天王',
		desc = '可通过活动获得',
		unitIDs = {[3201] = 3202, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 3201,
		attrType1 = 8,
		attrNum1 = '5%',
		attrType2 = 22,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[163]
		-- {'cn'}
	},
	[164] = {
		id = 164,
		name = '竹林刀影',
		desc = '可通过活动获得',
		unitIDs = {[7141] = 7142, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_c.png',
		markID = 7141,
		attrType1 = 8,
		attrNum1 = '5%',
		attrType2 = 24,
		attrNum2 = '300',
		isOpen = true,
		languages = __data_t__languages[164]
		-- {'cn'}
	},
	[165] = {
		id = 165,
		name = '虎先锋',
		desc = '可通过活动获得',
		unitIDs = {[3673] = 3674, __size = 1},
		skinFrameRes = 'city/drawcard/draw/panel_card_h.png',
		markID = 3673,
		attrType1 = 7,
		attrNum1 = '2%',
		attrType2 = 14,
		attrNum2 = '100',
		languages = __data_t__languages[165]
		-- {'cn'}
	},
	__size = 65,
	__default = {
		__index = {
			name = '',
			desc = '',
			unitIDs = __data_t__unitIDs["default"]	--[[ {__size = 0}]],
			activeType = 2,
			skinFrameRes = 'common/icon/panel_card_7.png',
			markID = 0,
			attrAddType = 1,
			attrType1 = 0,
			attrNum1 = '',
			attrType2 = 0,
			attrNum2 = '',
			attrType3 = 0,
			attrNum3 = '',
			attrType4 = 0,
			attrNum4 = '',
			rank = 1,
			costMap = __data_t__costMap["default"]	--[[ {__size = 0}]],
			extraItem = __data_t__extraItem["default"]	--[[ {__size = 0}]],
			isOpen = false,
			languages = {'cn', 'tw', 'en', 'vn', 'th', 'kr'},
			extraTip = '',
			sign = ''
		}
	}
}
return csv.card_skin