--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {}, __size = 1}
local __data_t__cfgIds = {
	["default"] = __predefine_t__[1]
}
local __data_t__limitBuff = {
	["default"] = __predefine_t__[1]
}
local __data_t__forbiddenBuff = {
	["default"] = __predefine_t__[1]
}
local __data_t__forbiddenPassiveSkill = {
	["default"] = __predefine_t__[1]
}

csv['extra_round_trigger'] = {
	[1] = {
		id = 1,
		forbiddenBuff = {5, 24, 25},
		forbiddenPassiveSkill = {2, 23},
		disableBattleState = 1,
		cfgIds = {4161681}
	},
	[2] = {
		id = 2,
		forbiddenBuff = {6, 42},
		forbiddenPassiveSkill = {9, 18, 24, 25, 28},
		disableBattleState = 2
	},
	[1000] = {
		id = 1000,
		limitBuff = {5, 6, 7, 8, 10, 14, 15, 24, 25, 40}
	},
	__size = 3,
	__default = {
		__index = {
			limitBuff = __data_t__limitBuff["default"]	--[[ {}]],
			forbiddenBuff = __data_t__forbiddenBuff["default"]	--[[ {}]],
			forbiddenPassiveSkill = __data_t__forbiddenPassiveSkill["default"]	--[[ {}]],
			disableBattleState = 0,
			cfgIds = __data_t__cfgIds["default"]	--[[ {}]]
		}
	}
}
return csv.extra_round_trigger