--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['achievement']['achievement'] = {
	[1] = {
		id = 1,
		name = '人物成长',
		name_tw = '人物成長',
		name_en = 'Growth',
		name_vn = 'Tăng trưởng nhân vật',
		name_kr = '캐릭터 성장',
		name_pt = 'Crescimento',
		name_th = 'การเติบโต',
		icon = 'city/task/achievement/icon_rucz.png'
	},
	[2] = {
		id = 2,
		name = '精灵收集',
		name_tw = '精靈收集',
		name_en = 'Collection',
		name_vn = 'Bộ sưu tập yêu tinh',
		name_kr = '포켓몬 수집',
		name_pt = 'Coleção',
		name_th = 'คอลเลกชัน',
		icon = 'city/task/achievement/icon_jlsj.png'
	},
	[3] = {
		id = 3,
		name = '精灵培养',
		name_tw = '精靈培養',
		name_en = 'Training',
		name_vn = 'Tinh linh bồi dưỡng',
		name_kr = '포켓몬 육성',
		name_pt = 'Treinamento',
		name_th = 'การฝึกฝน',
		icon = 'city/task/achievement/icon_jlpy.png'
	},
	[4] = {
		id = 4,
		name = '副本活动',
		name_tw = '副本活動',
		name_en = 'Dungeon',
		name_vn = 'Sao chép hoạt động',
		name_kr = '던전 이벤트',
		name_pt = 'Masmorra',
		name_th = 'ดันเจี้ยน',
		icon = 'city/task/achievement/icon_fbhd.png'
	},
	[5] = {
		id = 5,
		name = '竞技挑战',
		name_tw = '競技挑戰',
		name_en = 'Arena',
		name_vn = 'Thách thức cạnh tranh',
		name_kr = '아레나 도전',
		name_pt = 'Arena',
		name_th = 'สนามประลอง',
		icon = 'city/task/achievement/icon_jjtz.png'
	},
	[6] = {
		id = 6,
		name = '社交',
		name_tw = '社交',
		name_en = 'Social',
		name_vn = 'Xã hội',
		name_kr = '소셜',
		name_pt = 'Social',
		name_th = 'สังคม',
		icon = 'city/task/achievement/icon_sj.png'
	},
	[7] = {
		id = 7,
		name = '隐藏成就',
		name_tw = '隱藏成就',
		name_en = 'Hidden',
		name_vn = 'Ẩn thành tích',
		name_kr = '히든 업적',
		name_pt = 'Oculto',
		name_th = 'ซ่อนเร้น'
	},

	__size = 7,
	__default = {
		__index = {
			name = '',
			name_tw = '',
			name_en = '',
			name_vn = '',
			name_kr = '',
			name_pt = '',
			name_th = '',
			icon = ''
		}
	}
}
return csv.achievement.achievement