--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['capture']['probability'] = {
	[1] = {
		id = 1,
		probability = 100,
		desc = '肯定成功',
		desc_tw = '肯定成功',
		desc_en = 'Guarantee success',
		desc_vn = 'Đảm bảo thành công',
		desc_kr = '100% 성공',
		desc_pt = 'Garantir sucesso',
		desc_th = 'รับประกันความสำเร็จ'
	},
	[2] = {
		id = 2,
		probability = 90,
		desc = '基本上是稳了',
		desc_tw = '基本上是穩了',
		desc_en = 'It\'s basically stable',
		desc_vn = 'Về cơ bản nó ổn định',
		desc_kr = '매우 안정적',
		desc_pt = 'É basicamente estável',
		desc_th = 'โดยพื้นฐานแล้วมีเสถียรภาพ'
	},
	[3] = {
		id = 3,
		probability = 80,
		desc = '成功率极高',
		desc_tw = '成功率極高',
		desc_en = 'Extremely high success rate',
		desc_vn = 'Tỷ lệ thành công cực cao',
		desc_kr = '성공률 극도로 높음',
		desc_pt = 'Taxa de sucesso extremamente alta',
		desc_th = 'อัตราความสำเร็จสูงมาก'
	},
	[4] = {
		id = 4,
		probability = 70,
		desc = '成功率很高',
		desc_tw = '成功率很高',
		desc_en = 'High success rate',
		desc_vn = 'Tỷ lệ thành công cao',
		desc_kr = '성공률 무척 높음',
		desc_pt = 'Taxa de sucesso alta',
		desc_th = 'อัตราความสำเร็จสูง'
	},
	[5] = {
		id = 5,
		probability = 50,
		desc = '成功率高',
		desc_tw = '成功率高',
		desc_en = 'Success rate',
		desc_vn = 'Tỉ lệ thành công',
		desc_kr = '성공률 높음',
		desc_pt = 'Taxa de sucesso',
		desc_th = 'อัตราความสำเร็จ'
	},
	[6] = {
		id = 6,
		probability = 40,
		desc = '成功率中上',
		desc_tw = '成功率中上',
		desc_en = 'Above average success rate',
		desc_vn = 'Tỷ lệ thành công trên trung bình',
		desc_kr = '성공률 중상',
		desc_pt = 'Taxa de sucesso acima da média',
		desc_th = 'อัตราความสำเร็จสูงกว่าค่าเฉลี่ย'
	},
	[7] = {
		id = 7,
		probability = 20,
		desc = '成功率中等',
		desc_tw = '成功率中等',
		desc_en = 'Average success rate',
		desc_vn = 'Tỷ lệ thành công trung bình',
		desc_kr = '성공률 보통',
		desc_pt = 'Taxa de sucesso média',
		desc_th = 'อัตราความสำเร็จเฉลี่ย'
	},
	[8] = {
		id = 8,
		probability = 10,
		desc = '成功率低',
		desc_tw = '成功率低',
		desc_en = 'Low success rate',
		desc_vn = 'Tỷ lệ thành công thấp',
		desc_kr = '성공률 낮음',
		desc_pt = 'Taxa de sucesso baixa',
		desc_th = 'อัตราความสำเร็จต่ำ'
	},
	[9] = {
		id = 9,
		probability = 5,
		desc = '成功率很低',
		desc_tw = '成功率很低',
		desc_en = 'Low success rate',
		desc_vn = 'Tỷ lệ thành công thấp',
		desc_kr = '성공률 무척 낮음',
		desc_pt = 'Taxa de sucesso baixa',
		desc_th = 'อัตราความสำเร็จต่ำ'
	},
	[10] = {
		id = 10,
		desc = '成功率极低',
		desc_tw = '成功率極低',
		desc_en = 'Extremely low success rate',
		desc_vn = 'Tỷ lệ thành công cực kỳ thấp',
		desc_kr = '성공률 극도로 낮음',
		desc_pt = 'Taxa de sucesso extremamente baixa',
		desc_th = 'อัตราความสำเร็จต่ำมาก'
	},

	__size = 10,
	__default = {
		__index = {
			probability = 0,
			desc = '',
			desc_tw = '',
			desc_en = '',
			desc_vn = '',
			desc_kr = '',
			desc_pt = '',
			desc_th = ''
		}
	}
}
return csv.capture.probability