--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {__size = 0}, 
	[2] = {[11] = 1, __size = 1}, 
	[3] = {[12] = 1, __size = 1}, 
	[4] = {[13] = 1, __size = 1}, 
	[5] = {[22] = 1, __size = 1}, 
	[6] = {[31] = 1, __size = 1}, 
	[7] = {[32] = 1, __size = 1}, 
	[8] = {[33] = 1, __size = 1}, 
	[9] = {[41] = 1, __size = 1}, 
	[10] = {[42] = 1, __size = 1}, 
	[11] = {[43] = 1, __size = 1}, 
	[12] = {[5] = 5, __size = 1}, __size = 12}
local __data_t__randLib1 = {
	[11] = __predefine_t__[6],
	[1] = __predefine_t__[2],
	[13] = __predefine_t__[8],
	[12] = __predefine_t__[7],
	[14] = __predefine_t__[8],
	[22] = __predefine_t__[10],
	[23] = __predefine_t__[11],
	[33] = __predefine_t__[12],
	[32] = __predefine_t__[12],
	[31] = __predefine_t__[12],
	["default"] = __predefine_t__[1],
	[3] = __predefine_t__[4],
	[2] = __predefine_t__[3],
	[4] = __predefine_t__[5],
	[24] = __predefine_t__[11],
	[21] = __predefine_t__[9]
}
local __data_t__randLib2 = {
	[11] = __predefine_t__[6],
	[1] = __predefine_t__[2],
	[13] = __predefine_t__[8],
	[12] = __predefine_t__[7],
	[14] = __predefine_t__[8],
	[22] = __predefine_t__[10],
	[23] = __predefine_t__[11],
	[33] = __predefine_t__[12],
	[32] = __predefine_t__[12],
	[31] = __predefine_t__[12],
	["default"] = __predefine_t__[1],
	[3] = __predefine_t__[4],
	[2] = __predefine_t__[3],
	[4] = __predefine_t__[5],
	[24] = __predefine_t__[11],
	[21] = __predefine_t__[9]
}

csv['cross']['mine']['event_times'] = {
	[1] = {
		id = 1,
		day = 1,
		time = 1230,
		weight1 = 90,
		randLib1 = __data_t__randLib1[1],
		-- {[11] = 1, __size = 1}
		weight2 = 90,
		randLib2 = __data_t__randLib2[1]
		-- {[11] = 1, __size = 1}
	},
	[2] = {
		id = 2,
		day = 1,
		time = 1530,
		weight1 = 90,
		randLib1 = __data_t__randLib1[2],
		-- {[12] = 1, __size = 1}
		weight2 = 90,
		randLib2 = __data_t__randLib2[2]
		-- {[12] = 1, __size = 1}
	},
	[3] = {
		id = 3,
		day = 1,
		time = 1830,
		weight1 = 90,
		randLib1 = __data_t__randLib1[3],
		-- {[13] = 1, __size = 1}
		weight2 = 90,
		randLib2 = __data_t__randLib2[3]
		-- {[13] = 1, __size = 1}
	},
	[4] = {
		id = 4,
		day = 1,
		time = 2130,
		weight1 = 90,
		randLib1 = __data_t__randLib1[4],
		-- {[22] = 1, __size = 1}
		weight2 = 90,
		randLib2 = __data_t__randLib2[4]
		-- {[22] = 1, __size = 1}
	},
	[11] = {
		id = 11,
		day = 2,
		time = 1230,
		weight1 = 90,
		randLib1 = __data_t__randLib1[11],
		-- {[31] = 1, __size = 1}
		weight2 = 90,
		randLib2 = __data_t__randLib2[11]
		-- {[31] = 1, __size = 1}
	},
	[12] = {
		id = 12,
		day = 2,
		time = 1530,
		weight1 = 90,
		randLib1 = __data_t__randLib1[12],
		-- {[32] = 1, __size = 1}
		weight2 = 90,
		randLib2 = __data_t__randLib2[12]
		-- {[32] = 1, __size = 1}
	},
	[13] = {
		id = 13,
		day = 2,
		time = 1830,
		weight1 = 90,
		randLib1 = __data_t__randLib1[13],
		-- {[33] = 1, __size = 1}
		weight2 = 90,
		randLib2 = __data_t__randLib2[13]
		-- {[33] = 1, __size = 1}
	},
	[14] = {
		id = 14,
		day = 2,
		time = 2130,
		weight1 = 90,
		randLib1 = __data_t__randLib1[14],
		-- {[33] = 1, __size = 1}
		weight2 = 90,
		randLib2 = __data_t__randLib2[14]
		-- {[33] = 1, __size = 1}
	},
	[21] = {
		id = 21,
		day = 3,
		time = 1230,
		weight1 = 90,
		randLib1 = __data_t__randLib1[21],
		-- {[41] = 1, __size = 1}
		weight2 = 90,
		randLib2 = __data_t__randLib2[21]
		-- {[41] = 1, __size = 1}
	},
	[22] = {
		id = 22,
		day = 3,
		time = 1530,
		weight1 = 90,
		randLib1 = __data_t__randLib1[22],
		-- {[42] = 1, __size = 1}
		weight2 = 90,
		randLib2 = __data_t__randLib2[22]
		-- {[42] = 1, __size = 1}
	},
	[23] = {
		id = 23,
		day = 3,
		time = 1830,
		weight1 = 90,
		randLib1 = __data_t__randLib1[23],
		-- {[43] = 1, __size = 1}
		weight2 = 90,
		randLib2 = __data_t__randLib2[23]
		-- {[43] = 1, __size = 1}
	},
	[24] = {
		id = 24,
		day = 3,
		time = 2130,
		weight1 = 90,
		randLib1 = __data_t__randLib1[24],
		-- {[43] = 1, __size = 1}
		weight2 = 90,
		randLib2 = __data_t__randLib2[24]
		-- {[43] = 1, __size = 1}
	},
	[31] = {
		id = 31,
		day = 1,
		time = 500,
		weight1 = 90,
		randLib1 = __data_t__randLib1[31],
		-- {[5] = 5, __size = 1}
		weight2 = 90,
		randLib2 = __data_t__randLib2[31]
		-- {[5] = 5, __size = 1}
	},
	[32] = {
		id = 32,
		day = 2,
		time = 500,
		weight1 = 90,
		randLib1 = __data_t__randLib1[32],
		-- {[5] = 5, __size = 1}
		weight2 = 90,
		randLib2 = __data_t__randLib2[32]
		-- {[5] = 5, __size = 1}
	},
	[33] = {
		id = 33,
		day = 3,
		time = 500,
		weight1 = 90,
		randLib1 = __data_t__randLib1[33],
		-- {[5] = 5, __size = 1}
		weight2 = 90,
		randLib2 = __data_t__randLib2[33]
		-- {[5] = 5, __size = 1}
	},

	__size = 15,
	__default = {
		__index = {
			day = 0,
			time = 0,
			weight1 = 0,
			randLib1 = __data_t__randLib1["default"]	--[[ {__size = 0}]],
			weight2 = 0,
			randLib2 = __data_t__randLib2["default"]	--[[ {__size = 0}]]
		}
	}
}
return csv.cross.mine.event_times