--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['gem']['quality_attrs'] = {
	[1] = {
		id = 1,
		attrType1 = 1,
		attrNum1 = '1%'
	},
	[2] = {
		id = 2,
		qualityNum = 200,
		attrType1 = 7,
		attrNum1 = '1%',
		attrType2 = 8,
		attrNum2 = '1%'
	},
	[3] = {
		id = 3,
		qualityNum = 300,
		attrType1 = 1,
		attrNum1 = '1%',
		attrType2 = 13,
		attrNum2 = '1%',
		attrType3 = 7,
		attrNum3 = '1%',
		attrType4 = 9,
		attrNum4 = '1%',
		attrType5 = 8,
		attrNum5 = '1%',
		attrType6 = 10,
		attrNum6 = '1%'
	},
	[4] = {
		id = 4,
		qualityNum = 400,
		attrType1 = 1,
		attrNum1 = '2%'
	},
	[5] = {
		id = 5,
		qualityNum = 500,
		attrType1 = 7,
		attrNum1 = '2%',
		attrType2 = 8,
		attrNum2 = '2%'
	},
	[6] = {
		id = 6,
		qualityNum = 600,
		attrType1 = 1,
		attrNum1 = '2%',
		attrType2 = 13,
		attrNum2 = '2%',
		attrType3 = 7,
		attrNum3 = '2%',
		attrType4 = 9,
		attrNum4 = '2%',
		attrType5 = 8,
		attrNum5 = '2%',
		attrType6 = 10,
		attrNum6 = '2%'
	},
	[7] = {
		id = 7,
		qualityNum = 750,
		attrType1 = 1,
		attrNum1 = '2%'
	},
	[8] = {
		id = 8,
		qualityNum = 900,
		attrType1 = 7,
		attrNum1 = '2%',
		attrType2 = 8,
		attrNum2 = '2%'
	},
	[9] = {
		id = 9,
		qualityNum = 1050,
		attrType1 = 1,
		attrNum1 = '2%',
		attrType2 = 13,
		attrNum2 = '2%',
		attrType3 = 7,
		attrNum3 = '2%',
		attrType4 = 9,
		attrNum4 = '2%',
		attrType5 = 8,
		attrNum5 = '2%',
		attrType6 = 10,
		attrNum6 = '2%'
	},
	[10] = {
		id = 10,
		qualityNum = 1200,
		attrType1 = 1,
		attrNum1 = '3%'
	},
	[11] = {
		id = 11,
		qualityNum = 1350,
		attrType1 = 7,
		attrNum1 = '3%',
		attrType2 = 8,
		attrNum2 = '3%'
	},
	[12] = {
		id = 12,
		qualityNum = 1500,
		attrType1 = 1,
		attrNum1 = '3%',
		attrType2 = 13,
		attrNum2 = '3%',
		attrType3 = 7,
		attrNum3 = '3%',
		attrType4 = 9,
		attrNum4 = '3%',
		attrType5 = 8,
		attrNum5 = '3%',
		attrType6 = 10,
		attrNum6 = '3%'
	},
	[13] = {
		id = 13,
		qualityNum = 1650,
		attrType1 = 1,
		attrNum1 = '4%'
	},
	[14] = {
		id = 14,
		qualityNum = 1800,
		attrType1 = 7,
		attrNum1 = '4%',
		attrType2 = 8,
		attrNum2 = '4%'
	},
	[15] = {
		id = 15,
		qualityNum = 1950,
		attrType1 = 1,
		attrNum1 = '4%',
		attrType2 = 13,
		attrNum2 = '4%',
		attrType3 = 7,
		attrNum3 = '4%',
		attrType4 = 9,
		attrNum4 = '4%',
		attrType5 = 8,
		attrNum5 = '4%',
		attrType6 = 10,
		attrNum6 = '4%'
	},
	[16] = {
		id = 16,
		qualityNum = 2200,
		attrType1 = 1,
		attrNum1 = '5%'
	},
	[17] = {
		id = 17,
		qualityNum = 2450,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 8,
		attrNum2 = '5%'
	},
	[18] = {
		id = 18,
		qualityNum = 2700,
		attrType1 = 1,
		attrNum1 = '5%',
		attrType2 = 13,
		attrNum2 = '5%',
		attrType3 = 7,
		attrNum3 = '5%',
		attrType4 = 9,
		attrNum4 = '5%',
		attrType5 = 8,
		attrNum5 = '5%',
		attrType6 = 10,
		attrNum6 = '5%'
	},
	[19] = {
		id = 19,
		qualityNum = 2950,
		attrType1 = 1,
		attrNum1 = '5%'
	},
	[20] = {
		id = 20,
		qualityNum = 3200,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 8,
		attrNum2 = '5%'
	},
	[21] = {
		id = 21,
		qualityNum = 3450,
		attrType1 = 1,
		attrNum1 = '6%'
	},
	[22] = {
		id = 22,
		qualityNum = 3700,
		attrType1 = 7,
		attrNum1 = '6%',
		attrType2 = 8,
		attrNum2 = '6%'
	},
	[23] = {
		id = 23,
		qualityNum = 3950,
		attrType1 = 1,
		attrNum1 = '6%',
		attrType2 = 13,
		attrNum2 = '6%',
		attrType3 = 7,
		attrNum3 = '6%',
		attrType4 = 9,
		attrNum4 = '6%',
		attrType5 = 8,
		attrNum5 = '6%',
		attrType6 = 10,
		attrNum6 = '6%'
	},
	[24] = {
		id = 24,
		qualityNum = 4200,
		attrType1 = 1,
		attrNum1 = '6%'
	},
	[25] = {
		id = 25,
		qualityNum = 4450,
		attrType1 = 7,
		attrNum1 = '6%',
		attrType2 = 8,
		attrNum2 = '6%'
	},
	[26] = {
		id = 26,
		qualityNum = 4700,
		attrType1 = 1,
		attrNum1 = '7%'
	},
	[27] = {
		id = 27,
		qualityNum = 4950,
		attrType1 = 7,
		attrNum1 = '7%',
		attrType2 = 8,
		attrNum2 = '7%'
	},
	[28] = {
		id = 28,
		qualityNum = 5200,
		attrType1 = 1,
		attrNum1 = '7%',
		attrType2 = 13,
		attrNum2 = '7%',
		attrType3 = 7,
		attrNum3 = '7%',
		attrType4 = 9,
		attrNum4 = '7%',
		attrType5 = 8,
		attrNum5 = '7%',
		attrType6 = 10,
		attrNum6 = '7%'
	},
	[29] = {
		id = 29,
		qualityNum = 5450,
		attrType1 = 1,
		attrNum1 = '7%'
	},
	[30] = {
		id = 30,
		qualityNum = 5700,
		attrType1 = 7,
		attrNum1 = '7%',
		attrType2 = 8,
		attrNum2 = '7%'
	},
	[31] = {
		id = 31,
		qualityNum = 5950,
		attrType1 = 1,
		attrNum1 = '8%'
	},
	[32] = {
		id = 32,
		qualityNum = 6200,
		attrType1 = 7,
		attrNum1 = '8%',
		attrType2 = 8,
		attrNum2 = '8%'
	},
	[33] = {
		id = 33,
		qualityNum = 6450,
		attrType1 = 1,
		attrNum1 = '8%',
		attrType2 = 13,
		attrNum2 = '8%',
		attrType3 = 7,
		attrNum3 = '8%',
		attrType4 = 9,
		attrNum4 = '8%',
		attrType5 = 8,
		attrNum5 = '8%',
		attrType6 = 10,
		attrNum6 = '8%'
	},
	[34] = {
		id = 34,
		qualityNum = 6700,
		attrType1 = 1,
		attrNum1 = '8%'
	},
	[35] = {
		id = 35,
		qualityNum = 6950,
		attrType1 = 7,
		attrNum1 = '8%',
		attrType2 = 8,
		attrNum2 = '8%'
	},
	[36] = {
		id = 36,
		qualityNum = 7200,
		attrType1 = 1,
		attrNum1 = '9%'
	},
	[37] = {
		id = 37,
		qualityNum = 7450,
		attrType1 = 7,
		attrNum1 = '9%',
		attrType2 = 8,
		attrNum2 = '9%'
	},
	[38] = {
		id = 38,
		qualityNum = 7700,
		attrType1 = 1,
		attrNum1 = '9%',
		attrType2 = 13,
		attrNum2 = '9%',
		attrType3 = 7,
		attrNum3 = '9%',
		attrType4 = 9,
		attrNum4 = '9%',
		attrType5 = 8,
		attrNum5 = '9%',
		attrType6 = 10,
		attrNum6 = '9%'
	},
	[39] = {
		id = 39,
		qualityNum = 7950,
		attrType1 = 1,
		attrNum1 = '9%'
	},
	[40] = {
		id = 40,
		qualityNum = 8200,
		attrType1 = 7,
		attrNum1 = '9%',
		attrType2 = 8,
		attrNum2 = '9%'
	},
	[41] = {
		id = 41,
		qualityNum = 8450,
		attrType1 = 1,
		attrNum1 = '10%'
	},
	[42] = {
		id = 42,
		qualityNum = 8700,
		attrType1 = 7,
		attrNum1 = '10%',
		attrType2 = 8,
		attrNum2 = '10%'
	},
	[43] = {
		id = 43,
		qualityNum = 8950,
		attrType1 = 1,
		attrNum1 = '10%',
		attrType2 = 13,
		attrNum2 = '10%',
		attrType3 = 7,
		attrNum3 = '10%',
		attrType4 = 9,
		attrNum4 = '10%',
		attrType5 = 8,
		attrNum5 = '10%',
		attrType6 = 10,
		attrNum6 = '10%'
	},
	[44] = {
		id = 44,
		qualityNum = 9200,
		attrType1 = 1,
		attrNum1 = '10%'
	},
	[45] = {
		id = 45,
		qualityNum = 9450,
		attrType1 = 7,
		attrNum1 = '10%',
		attrType2 = 8,
		attrNum2 = '10%'
	},
	[46] = {
		id = 46,
		gemQualitySeqID = 2,
		attrType1 = 1,
		attrNum1 = '1%'
	},
	[47] = {
		id = 47,
		gemQualitySeqID = 2,
		qualityNum = 200,
		attrType1 = 7,
		attrNum1 = '1%',
		attrType2 = 8,
		attrNum2 = '1%'
	},
	[48] = {
		id = 48,
		gemQualitySeqID = 2,
		qualityNum = 300,
		attrType1 = 1,
		attrNum1 = '1%',
		attrType2 = 13,
		attrNum2 = '1%',
		attrType3 = 7,
		attrNum3 = '1%',
		attrType4 = 9,
		attrNum4 = '1%',
		attrType5 = 8,
		attrNum5 = '1%',
		attrType6 = 10,
		attrNum6 = '1%'
	},
	[49] = {
		id = 49,
		gemQualitySeqID = 2,
		qualityNum = 400,
		attrType1 = 1,
		attrNum1 = '2%'
	},
	[50] = {
		id = 50,
		gemQualitySeqID = 2,
		qualityNum = 500,
		attrType1 = 7,
		attrNum1 = '2%',
		attrType2 = 8,
		attrNum2 = '2%'
	},
	[51] = {
		id = 51,
		gemQualitySeqID = 2,
		qualityNum = 600,
		attrType1 = 1,
		attrNum1 = '2%',
		attrType2 = 13,
		attrNum2 = '2%',
		attrType3 = 7,
		attrNum3 = '2%',
		attrType4 = 9,
		attrNum4 = '2%',
		attrType5 = 8,
		attrNum5 = '2%',
		attrType6 = 10,
		attrNum6 = '2%'
	},
	[52] = {
		id = 52,
		gemQualitySeqID = 2,
		qualityNum = 750,
		attrType1 = 1,
		attrNum1 = '2%'
	},
	[53] = {
		id = 53,
		gemQualitySeqID = 2,
		qualityNum = 900,
		attrType1 = 7,
		attrNum1 = '2%',
		attrType2 = 8,
		attrNum2 = '2%'
	},
	[54] = {
		id = 54,
		gemQualitySeqID = 2,
		qualityNum = 1050,
		attrType1 = 1,
		attrNum1 = '2%',
		attrType2 = 13,
		attrNum2 = '2%',
		attrType3 = 7,
		attrNum3 = '2%',
		attrType4 = 9,
		attrNum4 = '2%',
		attrType5 = 8,
		attrNum5 = '2%',
		attrType6 = 10,
		attrNum6 = '2%'
	},
	[55] = {
		id = 55,
		gemQualitySeqID = 2,
		qualityNum = 1200,
		attrType1 = 1,
		attrNum1 = '3%'
	},
	[56] = {
		id = 56,
		gemQualitySeqID = 2,
		qualityNum = 1350,
		attrType1 = 7,
		attrNum1 = '3%',
		attrType2 = 8,
		attrNum2 = '3%'
	},
	[57] = {
		id = 57,
		gemQualitySeqID = 2,
		qualityNum = 1500,
		attrType1 = 1,
		attrNum1 = '3%',
		attrType2 = 13,
		attrNum2 = '3%',
		attrType3 = 7,
		attrNum3 = '3%',
		attrType4 = 9,
		attrNum4 = '3%',
		attrType5 = 8,
		attrNum5 = '3%',
		attrType6 = 10,
		attrNum6 = '3%'
	},
	[58] = {
		id = 58,
		gemQualitySeqID = 2,
		qualityNum = 1650,
		attrType1 = 1,
		attrNum1 = '4%'
	},
	[59] = {
		id = 59,
		gemQualitySeqID = 2,
		qualityNum = 1800,
		attrType1 = 7,
		attrNum1 = '4%',
		attrType2 = 8,
		attrNum2 = '4%'
	},
	[60] = {
		id = 60,
		gemQualitySeqID = 2,
		qualityNum = 1950,
		attrType1 = 1,
		attrNum1 = '4%',
		attrType2 = 13,
		attrNum2 = '4%',
		attrType3 = 7,
		attrNum3 = '4%',
		attrType4 = 9,
		attrNum4 = '4%',
		attrType5 = 8,
		attrNum5 = '4%',
		attrType6 = 10,
		attrNum6 = '4%'
	},
	[61] = {
		id = 61,
		gemQualitySeqID = 2,
		qualityNum = 2200,
		attrType1 = 1,
		attrNum1 = '5%'
	},
	[62] = {
		id = 62,
		gemQualitySeqID = 2,
		qualityNum = 2450,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 8,
		attrNum2 = '5%'
	},
	[63] = {
		id = 63,
		gemQualitySeqID = 2,
		qualityNum = 2700,
		attrType1 = 1,
		attrNum1 = '5%',
		attrType2 = 13,
		attrNum2 = '5%',
		attrType3 = 7,
		attrNum3 = '5%',
		attrType4 = 9,
		attrNum4 = '5%',
		attrType5 = 8,
		attrNum5 = '5%',
		attrType6 = 10,
		attrNum6 = '5%'
	},
	[64] = {
		id = 64,
		gemQualitySeqID = 2,
		qualityNum = 2950,
		attrType1 = 1,
		attrNum1 = '5%'
	},
	[65] = {
		id = 65,
		gemQualitySeqID = 2,
		qualityNum = 3200,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 8,
		attrNum2 = '5%'
	},
	[66] = {
		id = 66,
		gemQualitySeqID = 2,
		qualityNum = 3450,
		attrType1 = 1,
		attrNum1 = '6%'
	},
	[67] = {
		id = 67,
		gemQualitySeqID = 2,
		qualityNum = 3700,
		attrType1 = 7,
		attrNum1 = '6%',
		attrType2 = 8,
		attrNum2 = '6%'
	},
	[68] = {
		id = 68,
		gemQualitySeqID = 2,
		qualityNum = 3950,
		attrType1 = 1,
		attrNum1 = '6%',
		attrType2 = 13,
		attrNum2 = '6%',
		attrType3 = 7,
		attrNum3 = '6%',
		attrType4 = 9,
		attrNum4 = '6%',
		attrType5 = 8,
		attrNum5 = '6%',
		attrType6 = 10,
		attrNum6 = '6%'
	},
	[69] = {
		id = 69,
		gemQualitySeqID = 2,
		qualityNum = 4200,
		attrType1 = 1,
		attrNum1 = '6%'
	},
	[70] = {
		id = 70,
		gemQualitySeqID = 2,
		qualityNum = 4450,
		attrType1 = 7,
		attrNum1 = '6%',
		attrType2 = 8,
		attrNum2 = '6%'
	},
	[71] = {
		id = 71,
		gemQualitySeqID = 2,
		qualityNum = 4700,
		attrType1 = 1,
		attrNum1 = '7%'
	},
	[72] = {
		id = 72,
		gemQualitySeqID = 2,
		qualityNum = 4950,
		attrType1 = 7,
		attrNum1 = '7%',
		attrType2 = 8,
		attrNum2 = '7%'
	},
	[73] = {
		id = 73,
		gemQualitySeqID = 2,
		qualityNum = 5200,
		attrType1 = 1,
		attrNum1 = '7%',
		attrType2 = 13,
		attrNum2 = '7%',
		attrType3 = 7,
		attrNum3 = '7%',
		attrType4 = 9,
		attrNum4 = '7%',
		attrType5 = 8,
		attrNum5 = '7%',
		attrType6 = 10,
		attrNum6 = '7%'
	},
	[74] = {
		id = 74,
		gemQualitySeqID = 2,
		qualityNum = 5450,
		attrType1 = 1,
		attrNum1 = '7%'
	},
	[75] = {
		id = 75,
		gemQualitySeqID = 2,
		qualityNum = 5700,
		attrType1 = 7,
		attrNum1 = '7%',
		attrType2 = 8,
		attrNum2 = '7%'
	},
	[76] = {
		id = 76,
		gemQualitySeqID = 2,
		qualityNum = 5950,
		attrType1 = 1,
		attrNum1 = '8%'
	},
	[77] = {
		id = 77,
		gemQualitySeqID = 2,
		qualityNum = 6200,
		attrType1 = 7,
		attrNum1 = '8%',
		attrType2 = 8,
		attrNum2 = '8%'
	},
	[78] = {
		id = 78,
		gemQualitySeqID = 2,
		qualityNum = 6450,
		attrType1 = 1,
		attrNum1 = '8%',
		attrType2 = 13,
		attrNum2 = '8%',
		attrType3 = 7,
		attrNum3 = '8%',
		attrType4 = 9,
		attrNum4 = '8%',
		attrType5 = 8,
		attrNum5 = '8%',
		attrType6 = 10,
		attrNum6 = '8%'
	},
	[79] = {
		id = 79,
		gemQualitySeqID = 2,
		qualityNum = 6700,
		attrType1 = 1,
		attrNum1 = '8%'
	},
	[80] = {
		id = 80,
		gemQualitySeqID = 2,
		qualityNum = 6950,
		attrType1 = 7,
		attrNum1 = '8%',
		attrType2 = 8,
		attrNum2 = '8%'
	},
	[81] = {
		id = 81,
		gemQualitySeqID = 2,
		qualityNum = 7200,
		attrType1 = 1,
		attrNum1 = '9%'
	},
	[82] = {
		id = 82,
		gemQualitySeqID = 2,
		qualityNum = 7450,
		attrType1 = 7,
		attrNum1 = '9%',
		attrType2 = 8,
		attrNum2 = '9%'
	},
	[83] = {
		id = 83,
		gemQualitySeqID = 2,
		qualityNum = 7700,
		attrType1 = 1,
		attrNum1 = '9%',
		attrType2 = 13,
		attrNum2 = '9%',
		attrType3 = 7,
		attrNum3 = '9%',
		attrType4 = 9,
		attrNum4 = '9%',
		attrType5 = 8,
		attrNum5 = '9%',
		attrType6 = 10,
		attrNum6 = '9%'
	},
	[84] = {
		id = 84,
		gemQualitySeqID = 2,
		qualityNum = 7950,
		attrType1 = 1,
		attrNum1 = '9%'
	},
	[85] = {
		id = 85,
		gemQualitySeqID = 2,
		qualityNum = 8200,
		attrType1 = 7,
		attrNum1 = '9%',
		attrType2 = 8,
		attrNum2 = '9%'
	},
	[86] = {
		id = 86,
		gemQualitySeqID = 2,
		qualityNum = 8450,
		attrType1 = 1,
		attrNum1 = '10%'
	},
	[87] = {
		id = 87,
		gemQualitySeqID = 2,
		qualityNum = 8700,
		attrType1 = 7,
		attrNum1 = '10%',
		attrType2 = 8,
		attrNum2 = '10%'
	},
	[88] = {
		id = 88,
		gemQualitySeqID = 2,
		qualityNum = 8950,
		attrType1 = 1,
		attrNum1 = '10%',
		attrType2 = 13,
		attrNum2 = '10%',
		attrType3 = 7,
		attrNum3 = '10%',
		attrType4 = 9,
		attrNum4 = '10%',
		attrType5 = 8,
		attrNum5 = '10%',
		attrType6 = 10,
		attrNum6 = '10%'
	},
	[89] = {
		id = 89,
		gemQualitySeqID = 2,
		qualityNum = 9200,
		attrType1 = 1,
		attrNum1 = '10%'
	},
	[90] = {
		id = 90,
		gemQualitySeqID = 2,
		qualityNum = 9450,
		attrType1 = 7,
		attrNum1 = '10%',
		attrType2 = 8,
		attrNum2 = '10%'
	},
	[91] = {
		id = 91,
		gemQualitySeqID = 3,
		attrType1 = 1,
		attrNum1 = '1%'
	},
	[92] = {
		id = 92,
		gemQualitySeqID = 3,
		qualityNum = 200,
		attrType1 = 7,
		attrNum1 = '1%',
		attrType2 = 8,
		attrNum2 = '1%'
	},
	[93] = {
		id = 93,
		gemQualitySeqID = 3,
		qualityNum = 300,
		attrType1 = 1,
		attrNum1 = '1%',
		attrType2 = 13,
		attrNum2 = '1%',
		attrType3 = 7,
		attrNum3 = '1%',
		attrType4 = 9,
		attrNum4 = '1%',
		attrType5 = 8,
		attrNum5 = '1%',
		attrType6 = 10,
		attrNum6 = '1%'
	},
	[94] = {
		id = 94,
		gemQualitySeqID = 3,
		qualityNum = 400,
		attrType1 = 1,
		attrNum1 = '2%'
	},
	[95] = {
		id = 95,
		gemQualitySeqID = 3,
		qualityNum = 500,
		attrType1 = 7,
		attrNum1 = '2%',
		attrType2 = 8,
		attrNum2 = '2%'
	},
	[96] = {
		id = 96,
		gemQualitySeqID = 3,
		qualityNum = 600,
		attrType1 = 1,
		attrNum1 = '2%',
		attrType2 = 13,
		attrNum2 = '2%',
		attrType3 = 7,
		attrNum3 = '2%',
		attrType4 = 9,
		attrNum4 = '2%',
		attrType5 = 8,
		attrNum5 = '2%',
		attrType6 = 10,
		attrNum6 = '2%'
	},
	[97] = {
		id = 97,
		gemQualitySeqID = 3,
		qualityNum = 750,
		attrType1 = 1,
		attrNum1 = '2%'
	},
	[98] = {
		id = 98,
		gemQualitySeqID = 3,
		qualityNum = 900,
		attrType1 = 7,
		attrNum1 = '2%',
		attrType2 = 8,
		attrNum2 = '2%'
	},
	[99] = {
		id = 99,
		gemQualitySeqID = 3,
		qualityNum = 1050,
		attrType1 = 1,
		attrNum1 = '2%',
		attrType2 = 13,
		attrNum2 = '2%',
		attrType3 = 7,
		attrNum3 = '2%',
		attrType4 = 9,
		attrNum4 = '2%',
		attrType5 = 8,
		attrNum5 = '2%',
		attrType6 = 10,
		attrNum6 = '2%'
	},
	[100] = {
		id = 100,
		gemQualitySeqID = 3,
		qualityNum = 1200,
		attrType1 = 1,
		attrNum1 = '3%'
	},
	[101] = {
		id = 101,
		gemQualitySeqID = 3,
		qualityNum = 1350,
		attrType1 = 7,
		attrNum1 = '3%',
		attrType2 = 8,
		attrNum2 = '3%'
	},
	[102] = {
		id = 102,
		gemQualitySeqID = 3,
		qualityNum = 1500,
		attrType1 = 1,
		attrNum1 = '3%',
		attrType2 = 13,
		attrNum2 = '3%',
		attrType3 = 7,
		attrNum3 = '3%',
		attrType4 = 9,
		attrNum4 = '3%',
		attrType5 = 8,
		attrNum5 = '3%',
		attrType6 = 10,
		attrNum6 = '3%'
	},
	[103] = {
		id = 103,
		gemQualitySeqID = 3,
		qualityNum = 1650,
		attrType1 = 1,
		attrNum1 = '4%'
	},
	[104] = {
		id = 104,
		gemQualitySeqID = 3,
		qualityNum = 1800,
		attrType1 = 7,
		attrNum1 = '4%',
		attrType2 = 8,
		attrNum2 = '4%'
	},
	[105] = {
		id = 105,
		gemQualitySeqID = 3,
		qualityNum = 1950,
		attrType1 = 1,
		attrNum1 = '4%',
		attrType2 = 13,
		attrNum2 = '4%',
		attrType3 = 7,
		attrNum3 = '4%',
		attrType4 = 9,
		attrNum4 = '4%',
		attrType5 = 8,
		attrNum5 = '4%',
		attrType6 = 10,
		attrNum6 = '4%'
	},
	[106] = {
		id = 106,
		gemQualitySeqID = 3,
		qualityNum = 2200,
		attrType1 = 1,
		attrNum1 = '5%'
	},
	[107] = {
		id = 107,
		gemQualitySeqID = 3,
		qualityNum = 2450,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 8,
		attrNum2 = '5%'
	},
	[108] = {
		id = 108,
		gemQualitySeqID = 3,
		qualityNum = 2700,
		attrType1 = 1,
		attrNum1 = '5%',
		attrType2 = 13,
		attrNum2 = '5%',
		attrType3 = 7,
		attrNum3 = '5%',
		attrType4 = 9,
		attrNum4 = '5%',
		attrType5 = 8,
		attrNum5 = '5%',
		attrType6 = 10,
		attrNum6 = '5%'
	},
	[109] = {
		id = 109,
		gemQualitySeqID = 3,
		qualityNum = 2950,
		attrType1 = 1,
		attrNum1 = '5%'
	},
	[110] = {
		id = 110,
		gemQualitySeqID = 3,
		qualityNum = 3200,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 8,
		attrNum2 = '5%'
	},
	[111] = {
		id = 111,
		gemQualitySeqID = 3,
		qualityNum = 3450,
		attrType1 = 1,
		attrNum1 = '6%'
	},
	[112] = {
		id = 112,
		gemQualitySeqID = 3,
		qualityNum = 3700,
		attrType1 = 7,
		attrNum1 = '6%',
		attrType2 = 8,
		attrNum2 = '6%'
	},
	[113] = {
		id = 113,
		gemQualitySeqID = 3,
		qualityNum = 3950,
		attrType1 = 1,
		attrNum1 = '6%',
		attrType2 = 13,
		attrNum2 = '6%',
		attrType3 = 7,
		attrNum3 = '6%',
		attrType4 = 9,
		attrNum4 = '6%',
		attrType5 = 8,
		attrNum5 = '6%',
		attrType6 = 10,
		attrNum6 = '6%'
	},
	[114] = {
		id = 114,
		gemQualitySeqID = 3,
		qualityNum = 4200,
		attrType1 = 1,
		attrNum1 = '6%'
	},
	[115] = {
		id = 115,
		gemQualitySeqID = 3,
		qualityNum = 4450,
		attrType1 = 7,
		attrNum1 = '6%',
		attrType2 = 8,
		attrNum2 = '6%'
	},
	[116] = {
		id = 116,
		gemQualitySeqID = 3,
		qualityNum = 4700,
		attrType1 = 1,
		attrNum1 = '7%'
	},
	[117] = {
		id = 117,
		gemQualitySeqID = 3,
		qualityNum = 4950,
		attrType1 = 7,
		attrNum1 = '7%',
		attrType2 = 8,
		attrNum2 = '7%'
	},
	[118] = {
		id = 118,
		gemQualitySeqID = 3,
		qualityNum = 5200,
		attrType1 = 1,
		attrNum1 = '7%',
		attrType2 = 13,
		attrNum2 = '7%',
		attrType3 = 7,
		attrNum3 = '7%',
		attrType4 = 9,
		attrNum4 = '7%',
		attrType5 = 8,
		attrNum5 = '7%',
		attrType6 = 10,
		attrNum6 = '7%'
	},
	[119] = {
		id = 119,
		gemQualitySeqID = 3,
		qualityNum = 5450,
		attrType1 = 1,
		attrNum1 = '7%'
	},
	[120] = {
		id = 120,
		gemQualitySeqID = 3,
		qualityNum = 5700,
		attrType1 = 7,
		attrNum1 = '7%',
		attrType2 = 8,
		attrNum2 = '7%'
	},
	[121] = {
		id = 121,
		gemQualitySeqID = 3,
		qualityNum = 5950,
		attrType1 = 1,
		attrNum1 = '8%'
	},
	[122] = {
		id = 122,
		gemQualitySeqID = 3,
		qualityNum = 6200,
		attrType1 = 7,
		attrNum1 = '8%',
		attrType2 = 8,
		attrNum2 = '8%'
	},
	[123] = {
		id = 123,
		gemQualitySeqID = 3,
		qualityNum = 6450,
		attrType1 = 1,
		attrNum1 = '8%',
		attrType2 = 13,
		attrNum2 = '8%',
		attrType3 = 7,
		attrNum3 = '8%',
		attrType4 = 9,
		attrNum4 = '8%',
		attrType5 = 8,
		attrNum5 = '8%',
		attrType6 = 10,
		attrNum6 = '8%'
	},
	[124] = {
		id = 124,
		gemQualitySeqID = 3,
		qualityNum = 6700,
		attrType1 = 1,
		attrNum1 = '8%'
	},
	[125] = {
		id = 125,
		gemQualitySeqID = 3,
		qualityNum = 6950,
		attrType1 = 7,
		attrNum1 = '8%',
		attrType2 = 8,
		attrNum2 = '8%'
	},
	[126] = {
		id = 126,
		gemQualitySeqID = 3,
		qualityNum = 7200,
		attrType1 = 1,
		attrNum1 = '9%'
	},
	[127] = {
		id = 127,
		gemQualitySeqID = 3,
		qualityNum = 7450,
		attrType1 = 7,
		attrNum1 = '9%',
		attrType2 = 8,
		attrNum2 = '9%'
	},
	[128] = {
		id = 128,
		gemQualitySeqID = 3,
		qualityNum = 7700,
		attrType1 = 1,
		attrNum1 = '9%',
		attrType2 = 13,
		attrNum2 = '9%',
		attrType3 = 7,
		attrNum3 = '9%',
		attrType4 = 9,
		attrNum4 = '9%',
		attrType5 = 8,
		attrNum5 = '9%',
		attrType6 = 10,
		attrNum6 = '9%'
	},
	[129] = {
		id = 129,
		gemQualitySeqID = 3,
		qualityNum = 7950,
		attrType1 = 1,
		attrNum1 = '9%'
	},
	[130] = {
		id = 130,
		gemQualitySeqID = 3,
		qualityNum = 8200,
		attrType1 = 7,
		attrNum1 = '9%',
		attrType2 = 8,
		attrNum2 = '9%'
	},
	[131] = {
		id = 131,
		gemQualitySeqID = 3,
		qualityNum = 8450,
		attrType1 = 1,
		attrNum1 = '10%'
	},
	[132] = {
		id = 132,
		gemQualitySeqID = 3,
		qualityNum = 8700,
		attrType1 = 7,
		attrNum1 = '10%',
		attrType2 = 8,
		attrNum2 = '10%'
	},
	[133] = {
		id = 133,
		gemQualitySeqID = 3,
		qualityNum = 8950,
		attrType1 = 1,
		attrNum1 = '10%',
		attrType2 = 13,
		attrNum2 = '10%',
		attrType3 = 7,
		attrNum3 = '10%',
		attrType4 = 9,
		attrNum4 = '10%',
		attrType5 = 8,
		attrNum5 = '10%',
		attrType6 = 10,
		attrNum6 = '10%'
	},
	[134] = {
		id = 134,
		gemQualitySeqID = 3,
		qualityNum = 9200,
		attrType1 = 1,
		attrNum1 = '10%'
	},
	[135] = {
		id = 135,
		gemQualitySeqID = 3,
		qualityNum = 9450,
		attrType1 = 7,
		attrNum1 = '10%',
		attrType2 = 8,
		attrNum2 = '10%'
	},
	[136] = {
		id = 136,
		gemQualitySeqID = 4,
		attrType1 = 1,
		attrNum1 = '1%'
	},
	[137] = {
		id = 137,
		gemQualitySeqID = 4,
		qualityNum = 200,
		attrType1 = 7,
		attrNum1 = '1%',
		attrType2 = 8,
		attrNum2 = '1%'
	},
	[138] = {
		id = 138,
		gemQualitySeqID = 4,
		qualityNum = 300,
		attrType1 = 1,
		attrNum1 = '1%',
		attrType2 = 13,
		attrNum2 = '1%',
		attrType3 = 7,
		attrNum3 = '1%',
		attrType4 = 9,
		attrNum4 = '1%',
		attrType5 = 8,
		attrNum5 = '1%',
		attrType6 = 10,
		attrNum6 = '1%'
	},
	[139] = {
		id = 139,
		gemQualitySeqID = 4,
		qualityNum = 400,
		attrType1 = 1,
		attrNum1 = '2%'
	},
	[140] = {
		id = 140,
		gemQualitySeqID = 4,
		qualityNum = 500,
		attrType1 = 7,
		attrNum1 = '2%',
		attrType2 = 8,
		attrNum2 = '2%'
	},
	[141] = {
		id = 141,
		gemQualitySeqID = 4,
		qualityNum = 600,
		attrType1 = 1,
		attrNum1 = '2%',
		attrType2 = 13,
		attrNum2 = '2%',
		attrType3 = 7,
		attrNum3 = '2%',
		attrType4 = 9,
		attrNum4 = '2%',
		attrType5 = 8,
		attrNum5 = '2%',
		attrType6 = 10,
		attrNum6 = '2%'
	},
	[142] = {
		id = 142,
		gemQualitySeqID = 4,
		qualityNum = 750,
		attrType1 = 1,
		attrNum1 = '2%'
	},
	[143] = {
		id = 143,
		gemQualitySeqID = 4,
		qualityNum = 900,
		attrType1 = 7,
		attrNum1 = '2%',
		attrType2 = 8,
		attrNum2 = '2%'
	},
	[144] = {
		id = 144,
		gemQualitySeqID = 4,
		qualityNum = 1050,
		attrType1 = 1,
		attrNum1 = '2%',
		attrType2 = 13,
		attrNum2 = '2%',
		attrType3 = 7,
		attrNum3 = '2%',
		attrType4 = 9,
		attrNum4 = '2%',
		attrType5 = 8,
		attrNum5 = '2%',
		attrType6 = 10,
		attrNum6 = '2%'
	},
	[145] = {
		id = 145,
		gemQualitySeqID = 4,
		qualityNum = 1200,
		attrType1 = 1,
		attrNum1 = '3%'
	},
	[146] = {
		id = 146,
		gemQualitySeqID = 4,
		qualityNum = 1350,
		attrType1 = 7,
		attrNum1 = '3%',
		attrType2 = 8,
		attrNum2 = '3%'
	},
	[147] = {
		id = 147,
		gemQualitySeqID = 4,
		qualityNum = 1500,
		attrType1 = 1,
		attrNum1 = '3%',
		attrType2 = 13,
		attrNum2 = '3%',
		attrType3 = 7,
		attrNum3 = '3%',
		attrType4 = 9,
		attrNum4 = '3%',
		attrType5 = 8,
		attrNum5 = '3%',
		attrType6 = 10,
		attrNum6 = '3%'
	},
	[148] = {
		id = 148,
		gemQualitySeqID = 4,
		qualityNum = 1650,
		attrType1 = 1,
		attrNum1 = '4%'
	},
	[149] = {
		id = 149,
		gemQualitySeqID = 4,
		qualityNum = 1800,
		attrType1 = 7,
		attrNum1 = '4%',
		attrType2 = 8,
		attrNum2 = '4%'
	},
	[150] = {
		id = 150,
		gemQualitySeqID = 4,
		qualityNum = 1950,
		attrType1 = 1,
		attrNum1 = '4%',
		attrType2 = 13,
		attrNum2 = '4%',
		attrType3 = 7,
		attrNum3 = '4%',
		attrType4 = 9,
		attrNum4 = '4%',
		attrType5 = 8,
		attrNum5 = '4%',
		attrType6 = 10,
		attrNum6 = '4%'
	},
	[151] = {
		id = 151,
		gemQualitySeqID = 4,
		qualityNum = 2200,
		attrType1 = 1,
		attrNum1 = '5%'
	},
	[152] = {
		id = 152,
		gemQualitySeqID = 4,
		qualityNum = 2450,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 8,
		attrNum2 = '5%'
	},
	[153] = {
		id = 153,
		gemQualitySeqID = 4,
		qualityNum = 2700,
		attrType1 = 1,
		attrNum1 = '5%',
		attrType2 = 13,
		attrNum2 = '5%',
		attrType3 = 7,
		attrNum3 = '5%',
		attrType4 = 9,
		attrNum4 = '5%',
		attrType5 = 8,
		attrNum5 = '5%',
		attrType6 = 10,
		attrNum6 = '5%'
	},
	[154] = {
		id = 154,
		gemQualitySeqID = 4,
		qualityNum = 2950,
		attrType1 = 1,
		attrNum1 = '5%'
	},
	[155] = {
		id = 155,
		gemQualitySeqID = 4,
		qualityNum = 3200,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 8,
		attrNum2 = '5%'
	},
	[156] = {
		id = 156,
		gemQualitySeqID = 4,
		qualityNum = 3450,
		attrType1 = 1,
		attrNum1 = '6%'
	},
	[157] = {
		id = 157,
		gemQualitySeqID = 4,
		qualityNum = 3700,
		attrType1 = 7,
		attrNum1 = '6%',
		attrType2 = 8,
		attrNum2 = '6%'
	},
	[158] = {
		id = 158,
		gemQualitySeqID = 4,
		qualityNum = 3950,
		attrType1 = 1,
		attrNum1 = '6%',
		attrType2 = 13,
		attrNum2 = '6%',
		attrType3 = 7,
		attrNum3 = '6%',
		attrType4 = 9,
		attrNum4 = '6%',
		attrType5 = 8,
		attrNum5 = '6%',
		attrType6 = 10,
		attrNum6 = '6%'
	},
	[159] = {
		id = 159,
		gemQualitySeqID = 4,
		qualityNum = 4200,
		attrType1 = 1,
		attrNum1 = '6%'
	},
	[160] = {
		id = 160,
		gemQualitySeqID = 4,
		qualityNum = 4450,
		attrType1 = 7,
		attrNum1 = '6%',
		attrType2 = 8,
		attrNum2 = '6%'
	},
	[161] = {
		id = 161,
		gemQualitySeqID = 4,
		qualityNum = 4700,
		attrType1 = 1,
		attrNum1 = '7%'
	},
	[162] = {
		id = 162,
		gemQualitySeqID = 4,
		qualityNum = 4950,
		attrType1 = 7,
		attrNum1 = '7%',
		attrType2 = 8,
		attrNum2 = '7%'
	},
	[163] = {
		id = 163,
		gemQualitySeqID = 4,
		qualityNum = 5200,
		attrType1 = 1,
		attrNum1 = '7%',
		attrType2 = 13,
		attrNum2 = '7%',
		attrType3 = 7,
		attrNum3 = '7%',
		attrType4 = 9,
		attrNum4 = '7%',
		attrType5 = 8,
		attrNum5 = '7%',
		attrType6 = 10,
		attrNum6 = '7%'
	},
	[164] = {
		id = 164,
		gemQualitySeqID = 4,
		qualityNum = 5450,
		attrType1 = 1,
		attrNum1 = '7%'
	},
	[165] = {
		id = 165,
		gemQualitySeqID = 4,
		qualityNum = 5700,
		attrType1 = 7,
		attrNum1 = '7%',
		attrType2 = 8,
		attrNum2 = '7%'
	},
	[166] = {
		id = 166,
		gemQualitySeqID = 4,
		qualityNum = 5950,
		attrType1 = 1,
		attrNum1 = '8%'
	},
	[167] = {
		id = 167,
		gemQualitySeqID = 4,
		qualityNum = 6200,
		attrType1 = 7,
		attrNum1 = '8%',
		attrType2 = 8,
		attrNum2 = '8%'
	},
	[168] = {
		id = 168,
		gemQualitySeqID = 4,
		qualityNum = 6450,
		attrType1 = 1,
		attrNum1 = '8%',
		attrType2 = 13,
		attrNum2 = '8%',
		attrType3 = 7,
		attrNum3 = '8%',
		attrType4 = 9,
		attrNum4 = '8%',
		attrType5 = 8,
		attrNum5 = '8%',
		attrType6 = 10,
		attrNum6 = '8%'
	},
	[169] = {
		id = 169,
		gemQualitySeqID = 4,
		qualityNum = 6700,
		attrType1 = 1,
		attrNum1 = '8%'
	},
	[170] = {
		id = 170,
		gemQualitySeqID = 4,
		qualityNum = 6950,
		attrType1 = 7,
		attrNum1 = '8%',
		attrType2 = 8,
		attrNum2 = '8%'
	},
	[171] = {
		id = 171,
		gemQualitySeqID = 4,
		qualityNum = 7200,
		attrType1 = 1,
		attrNum1 = '9%'
	},
	[172] = {
		id = 172,
		gemQualitySeqID = 4,
		qualityNum = 7450,
		attrType1 = 7,
		attrNum1 = '9%',
		attrType2 = 8,
		attrNum2 = '9%'
	},
	[173] = {
		id = 173,
		gemQualitySeqID = 4,
		qualityNum = 7700,
		attrType1 = 1,
		attrNum1 = '9%',
		attrType2 = 13,
		attrNum2 = '9%',
		attrType3 = 7,
		attrNum3 = '9%',
		attrType4 = 9,
		attrNum4 = '9%',
		attrType5 = 8,
		attrNum5 = '9%',
		attrType6 = 10,
		attrNum6 = '9%'
	},
	[174] = {
		id = 174,
		gemQualitySeqID = 4,
		qualityNum = 7950,
		attrType1 = 1,
		attrNum1 = '9%'
	},
	[175] = {
		id = 175,
		gemQualitySeqID = 4,
		qualityNum = 8200,
		attrType1 = 7,
		attrNum1 = '9%',
		attrType2 = 8,
		attrNum2 = '9%'
	},
	[176] = {
		id = 176,
		gemQualitySeqID = 4,
		qualityNum = 8450,
		attrType1 = 1,
		attrNum1 = '10%'
	},
	[177] = {
		id = 177,
		gemQualitySeqID = 4,
		qualityNum = 8700,
		attrType1 = 7,
		attrNum1 = '10%',
		attrType2 = 8,
		attrNum2 = '10%'
	},
	[178] = {
		id = 178,
		gemQualitySeqID = 4,
		qualityNum = 8950,
		attrType1 = 1,
		attrNum1 = '10%',
		attrType2 = 13,
		attrNum2 = '10%',
		attrType3 = 7,
		attrNum3 = '10%',
		attrType4 = 9,
		attrNum4 = '10%',
		attrType5 = 8,
		attrNum5 = '10%',
		attrType6 = 10,
		attrNum6 = '10%'
	},
	[179] = {
		id = 179,
		gemQualitySeqID = 4,
		qualityNum = 9200,
		attrType1 = 1,
		attrNum1 = '10%'
	},
	[180] = {
		id = 180,
		gemQualitySeqID = 4,
		qualityNum = 9450,
		attrType1 = 7,
		attrNum1 = '10%',
		attrType2 = 8,
		attrNum2 = '10%'
	},
	[181] = {
		id = 181,
		gemQualitySeqID = 5,
		attrType1 = 1,
		attrNum1 = '1%'
	},
	[182] = {
		id = 182,
		gemQualitySeqID = 5,
		qualityNum = 200,
		attrType1 = 7,
		attrNum1 = '1%',
		attrType2 = 8,
		attrNum2 = '1%'
	},
	[183] = {
		id = 183,
		gemQualitySeqID = 5,
		qualityNum = 300,
		attrType1 = 1,
		attrNum1 = '1%',
		attrType2 = 13,
		attrNum2 = '1%',
		attrType3 = 7,
		attrNum3 = '1%',
		attrType4 = 9,
		attrNum4 = '1%',
		attrType5 = 8,
		attrNum5 = '1%',
		attrType6 = 10,
		attrNum6 = '1%'
	},
	[184] = {
		id = 184,
		gemQualitySeqID = 5,
		qualityNum = 400,
		attrType1 = 1,
		attrNum1 = '2%'
	},
	[185] = {
		id = 185,
		gemQualitySeqID = 5,
		qualityNum = 500,
		attrType1 = 7,
		attrNum1 = '2%',
		attrType2 = 8,
		attrNum2 = '2%'
	},
	[186] = {
		id = 186,
		gemQualitySeqID = 5,
		qualityNum = 600,
		attrType1 = 1,
		attrNum1 = '2%',
		attrType2 = 13,
		attrNum2 = '2%',
		attrType3 = 7,
		attrNum3 = '2%',
		attrType4 = 9,
		attrNum4 = '2%',
		attrType5 = 8,
		attrNum5 = '2%',
		attrType6 = 10,
		attrNum6 = '2%'
	},
	[187] = {
		id = 187,
		gemQualitySeqID = 5,
		qualityNum = 750,
		attrType1 = 1,
		attrNum1 = '2%'
	},
	[188] = {
		id = 188,
		gemQualitySeqID = 5,
		qualityNum = 900,
		attrType1 = 7,
		attrNum1 = '2%',
		attrType2 = 8,
		attrNum2 = '2%'
	},
	[189] = {
		id = 189,
		gemQualitySeqID = 5,
		qualityNum = 1050,
		attrType1 = 1,
		attrNum1 = '2%',
		attrType2 = 13,
		attrNum2 = '2%',
		attrType3 = 7,
		attrNum3 = '2%',
		attrType4 = 9,
		attrNum4 = '2%',
		attrType5 = 8,
		attrNum5 = '2%',
		attrType6 = 10,
		attrNum6 = '2%'
	},
	[190] = {
		id = 190,
		gemQualitySeqID = 5,
		qualityNum = 1200,
		attrType1 = 1,
		attrNum1 = '3%'
	},
	[191] = {
		id = 191,
		gemQualitySeqID = 5,
		qualityNum = 1350,
		attrType1 = 7,
		attrNum1 = '3%',
		attrType2 = 8,
		attrNum2 = '3%'
	},
	[192] = {
		id = 192,
		gemQualitySeqID = 5,
		qualityNum = 1500,
		attrType1 = 1,
		attrNum1 = '3%',
		attrType2 = 13,
		attrNum2 = '3%',
		attrType3 = 7,
		attrNum3 = '3%',
		attrType4 = 9,
		attrNum4 = '3%',
		attrType5 = 8,
		attrNum5 = '3%',
		attrType6 = 10,
		attrNum6 = '3%'
	},
	[193] = {
		id = 193,
		gemQualitySeqID = 5,
		qualityNum = 1650,
		attrType1 = 1,
		attrNum1 = '4%'
	},
	[194] = {
		id = 194,
		gemQualitySeqID = 5,
		qualityNum = 1800,
		attrType1 = 7,
		attrNum1 = '4%',
		attrType2 = 8,
		attrNum2 = '4%'
	},
	[195] = {
		id = 195,
		gemQualitySeqID = 5,
		qualityNum = 1950,
		attrType1 = 1,
		attrNum1 = '4%',
		attrType2 = 13,
		attrNum2 = '4%',
		attrType3 = 7,
		attrNum3 = '4%',
		attrType4 = 9,
		attrNum4 = '4%',
		attrType5 = 8,
		attrNum5 = '4%',
		attrType6 = 10,
		attrNum6 = '4%'
	},
	[196] = {
		id = 196,
		gemQualitySeqID = 5,
		qualityNum = 2200,
		attrType1 = 1,
		attrNum1 = '5%'
	},
	[197] = {
		id = 197,
		gemQualitySeqID = 5,
		qualityNum = 2450,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 8,
		attrNum2 = '5%'
	},
	[198] = {
		id = 198,
		gemQualitySeqID = 5,
		qualityNum = 2700,
		attrType1 = 1,
		attrNum1 = '5%',
		attrType2 = 13,
		attrNum2 = '5%',
		attrType3 = 7,
		attrNum3 = '5%',
		attrType4 = 9,
		attrNum4 = '5%',
		attrType5 = 8,
		attrNum5 = '5%',
		attrType6 = 10,
		attrNum6 = '5%'
	},
	[199] = {
		id = 199,
		gemQualitySeqID = 5,
		qualityNum = 2950,
		attrType1 = 1,
		attrNum1 = '5%'
	},
	[200] = {
		id = 200,
		gemQualitySeqID = 5,
		qualityNum = 3200,
		attrType1 = 7,
		attrNum1 = '5%',
		attrType2 = 8,
		attrNum2 = '5%'
	},
	[201] = {
		id = 201,
		gemQualitySeqID = 5,
		qualityNum = 3450,
		attrType1 = 1,
		attrNum1 = '6%'
	},
	[202] = {
		id = 202,
		gemQualitySeqID = 5,
		qualityNum = 3700,
		attrType1 = 7,
		attrNum1 = '6%',
		attrType2 = 8,
		attrNum2 = '6%'
	},
	[203] = {
		id = 203,
		gemQualitySeqID = 5,
		qualityNum = 3950,
		attrType1 = 1,
		attrNum1 = '6%',
		attrType2 = 13,
		attrNum2 = '6%',
		attrType3 = 7,
		attrNum3 = '6%',
		attrType4 = 9,
		attrNum4 = '6%',
		attrType5 = 8,
		attrNum5 = '6%',
		attrType6 = 10,
		attrNum6 = '6%'
	},
	[204] = {
		id = 204,
		gemQualitySeqID = 5,
		qualityNum = 4200,
		attrType1 = 1,
		attrNum1 = '6%'
	},
	[205] = {
		id = 205,
		gemQualitySeqID = 5,
		qualityNum = 4450,
		attrType1 = 7,
		attrNum1 = '6%',
		attrType2 = 8,
		attrNum2 = '6%'
	},
	[206] = {
		id = 206,
		gemQualitySeqID = 5,
		qualityNum = 4700,
		attrType1 = 1,
		attrNum1 = '7%'
	},
	[207] = {
		id = 207,
		gemQualitySeqID = 5,
		qualityNum = 4950,
		attrType1 = 7,
		attrNum1 = '7%',
		attrType2 = 8,
		attrNum2 = '7%'
	},
	[208] = {
		id = 208,
		gemQualitySeqID = 5,
		qualityNum = 5200,
		attrType1 = 1,
		attrNum1 = '7%',
		attrType2 = 13,
		attrNum2 = '7%',
		attrType3 = 7,
		attrNum3 = '7%',
		attrType4 = 9,
		attrNum4 = '7%',
		attrType5 = 8,
		attrNum5 = '7%',
		attrType6 = 10,
		attrNum6 = '7%'
	},
	[209] = {
		id = 209,
		gemQualitySeqID = 5,
		qualityNum = 5450,
		attrType1 = 1,
		attrNum1 = '7%'
	},
	[210] = {
		id = 210,
		gemQualitySeqID = 5,
		qualityNum = 5700,
		attrType1 = 7,
		attrNum1 = '7%',
		attrType2 = 8,
		attrNum2 = '7%'
	},
	[211] = {
		id = 211,
		gemQualitySeqID = 5,
		qualityNum = 5950,
		attrType1 = 1,
		attrNum1 = '8%'
	},
	[212] = {
		id = 212,
		gemQualitySeqID = 5,
		qualityNum = 6200,
		attrType1 = 7,
		attrNum1 = '8%',
		attrType2 = 8,
		attrNum2 = '8%'
	},
	[213] = {
		id = 213,
		gemQualitySeqID = 5,
		qualityNum = 6450,
		attrType1 = 1,
		attrNum1 = '8%',
		attrType2 = 13,
		attrNum2 = '8%',
		attrType3 = 7,
		attrNum3 = '8%',
		attrType4 = 9,
		attrNum4 = '8%',
		attrType5 = 8,
		attrNum5 = '8%',
		attrType6 = 10,
		attrNum6 = '8%'
	},
	[214] = {
		id = 214,
		gemQualitySeqID = 5,
		qualityNum = 6700,
		attrType1 = 1,
		attrNum1 = '8%'
	},
	[215] = {
		id = 215,
		gemQualitySeqID = 5,
		qualityNum = 6950,
		attrType1 = 7,
		attrNum1 = '8%',
		attrType2 = 8,
		attrNum2 = '8%'
	},
	[216] = {
		id = 216,
		gemQualitySeqID = 5,
		qualityNum = 7200,
		attrType1 = 1,
		attrNum1 = '9%'
	},
	[217] = {
		id = 217,
		gemQualitySeqID = 5,
		qualityNum = 7450,
		attrType1 = 7,
		attrNum1 = '9%',
		attrType2 = 8,
		attrNum2 = '9%'
	},
	[218] = {
		id = 218,
		gemQualitySeqID = 5,
		qualityNum = 7700,
		attrType1 = 1,
		attrNum1 = '9%',
		attrType2 = 13,
		attrNum2 = '9%',
		attrType3 = 7,
		attrNum3 = '9%',
		attrType4 = 9,
		attrNum4 = '9%',
		attrType5 = 8,
		attrNum5 = '9%',
		attrType6 = 10,
		attrNum6 = '9%'
	},
	[219] = {
		id = 219,
		gemQualitySeqID = 5,
		qualityNum = 7950,
		attrType1 = 1,
		attrNum1 = '9%'
	},
	[220] = {
		id = 220,
		gemQualitySeqID = 5,
		qualityNum = 8200,
		attrType1 = 7,
		attrNum1 = '9%',
		attrType2 = 8,
		attrNum2 = '9%'
	},
	[221] = {
		id = 221,
		gemQualitySeqID = 5,
		qualityNum = 8450,
		attrType1 = 1,
		attrNum1 = '10%'
	},
	[222] = {
		id = 222,
		gemQualitySeqID = 5,
		qualityNum = 8700,
		attrType1 = 7,
		attrNum1 = '10%',
		attrType2 = 8,
		attrNum2 = '10%'
	},
	[223] = {
		id = 223,
		gemQualitySeqID = 5,
		qualityNum = 8950,
		attrType1 = 1,
		attrNum1 = '10%',
		attrType2 = 13,
		attrNum2 = '10%',
		attrType3 = 7,
		attrNum3 = '10%',
		attrType4 = 9,
		attrNum4 = '10%',
		attrType5 = 8,
		attrNum5 = '10%',
		attrType6 = 10,
		attrNum6 = '10%'
	},
	[224] = {
		id = 224,
		gemQualitySeqID = 5,
		qualityNum = 9200,
		attrType1 = 1,
		attrNum1 = '10%'
	},
	[225] = {
		id = 225,
		gemQualitySeqID = 5,
		qualityNum = 9450,
		attrType1 = 7,
		attrNum1 = '10%',
		attrType2 = 8,
		attrNum2 = '10%'
	},

	__size = 225,
	__default = {
		__index = {
			gemQualitySeqID = 1,
			qualityNum = 100,
			attrType1 = 0,
			attrType2 = 0,
			attrType3 = 0,
			attrType4 = 0,
			attrType5 = 0,
			attrType6 = 0
		}
	}
}
return csv.gem.quality_attrs