--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['card_bag'] = {
	[1] = {
		id = 1,
		fragID = 20001,
		cardID = 1
	},
	[2] = {
		id = 2,
		fragID = 20001,
		cardID = 2
	},
	[3] = {
		id = 3,
		fragID = 20001,
		cardID = 3
	},
	[4] = {
		id = 4,
		fragID = 20001,
		cardID = 4
	},
	[11] = {
		id = 11,
		fragID = 20011,
		cardID = 11
	},
	[12] = {
		id = 12,
		fragID = 20011,
		cardID = 12
	},
	[13] = {
		id = 13,
		fragID = 20011,
		cardID = 13
	},
	[14] = {
		id = 14,
		fragID = 20011,
		cardID = 14
	},
	[15] = {
		id = 15,
		fragID = 20011,
		cardID = 15
	},
	[21] = {
		id = 21,
		fragID = 20021,
		cardID = 21
	},
	[22] = {
		id = 22,
		fragID = 20021,
		cardID = 22
	},
	[23] = {
		id = 23,
		fragID = 20021,
		cardID = 23
	},
	[24] = {
		id = 24,
		fragID = 20021,
		cardID = 24
	},
	[31] = {
		id = 31,
		fragID = 20031,
		cardID = 31
	},
	[33] = {
		id = 33,
		fragID = 20031,
		cardID = 33
	},
	[41] = {
		id = 41,
		fragID = 20041,
		cardID = 41
	},
	[44] = {
		id = 44,
		fragID = 20041,
		cardID = 44
	},
	[51] = {
		id = 51,
		fragID = 20051,
		cardID = 51
	},
	[52] = {
		id = 52,
		fragID = 20051,
		cardID = 52
	},
	[53] = {
		id = 53,
		fragID = 20051,
		cardID = 53
	},
	[54] = {
		id = 54,
		fragID = 20051,
		cardID = 54
	},
	[61] = {
		id = 61,
		fragID = 20061,
		cardID = 61
	},
	[62] = {
		id = 62,
		fragID = 20061,
		cardID = 62
	},
	[71] = {
		id = 71,
		fragID = 20071,
		cardID = 71
	},
	[72] = {
		id = 72,
		fragID = 20071,
		cardID = 72
	},
	[81] = {
		id = 81,
		fragID = 20081,
		cardID = 81
	},
	[82] = {
		id = 82,
		fragID = 20081,
		cardID = 82
	},
	[91] = {
		id = 91,
		fragID = 20091,
		cardID = 91
	},
	[92] = {
		id = 92,
		fragID = 20091,
		cardID = 92
	},
	[93] = {
		id = 93,
		fragID = 20091,
		cardID = 93
	},
	[101] = {
		id = 101,
		fragID = 20101,
		cardID = 101
	},
	[102] = {
		id = 102,
		fragID = 20101,
		cardID = 102
	},
	[111] = {
		id = 111,
		fragID = 20111,
		cardID = 111
	},
	[112] = {
		id = 112,
		fragID = 20111,
		cardID = 112
	},
	[113] = {
		id = 113,
		fragID = 20111,
		cardID = 113
	},
	[121] = {
		id = 121,
		fragID = 20121,
		cardID = 121
	},
	[122] = {
		id = 122,
		fragID = 20121,
		cardID = 122
	},
	[123] = {
		id = 123,
		fragID = 20121,
		cardID = 123
	},
	[131] = {
		id = 131,
		fragID = 20131,
		cardID = 131
	},
	[132] = {
		id = 132,
		fragID = 20131,
		cardID = 132
	},
	[133] = {
		id = 133,
		fragID = 20131,
		cardID = 133
	},
	[151] = {
		id = 151,
		fragID = 20151,
		cardID = 151
	},
	[152] = {
		id = 152,
		fragID = 20151,
		cardID = 152
	},
	[153] = {
		id = 153,
		fragID = 20151,
		cardID = 153
	},
	[161] = {
		id = 161,
		fragID = 20161,
		cardID = 161
	},
	[162] = {
		id = 162,
		fragID = 20161,
		cardID = 162
	},
	[163] = {
		id = 163,
		fragID = 20161,
		cardID = 163
	},
	[171] = {
		id = 171,
		fragID = 20171,
		cardID = 171
	},
	[172] = {
		id = 172,
		fragID = 20171,
		cardID = 172
	},
	[173] = {
		id = 173,
		fragID = 20171,
		cardID = 173
	},
	[191] = {
		id = 191,
		fragID = 20191,
		cardID = 191
	},
	[192] = {
		id = 192,
		fragID = 20191,
		cardID = 192
	},
	[211] = {
		id = 211,
		fragID = 20211,
		cardID = 211
	},
	[212] = {
		id = 212,
		fragID = 20211,
		cardID = 212
	},
	[221] = {
		id = 221,
		fragID = 20221,
		cardID = 221
	},
	[222] = {
		id = 222,
		fragID = 20221,
		cardID = 222
	},
	[231] = {
		id = 231,
		fragID = 20231,
		cardID = 231
	},
	[232] = {
		id = 232,
		fragID = 20231,
		cardID = 232
	},
	[241] = {
		id = 241,
		fragID = 20241,
		cardID = 241
	},
	[242] = {
		id = 242,
		fragID = 20241,
		cardID = 242
	},
	[251] = {
		id = 251,
		fragID = 20251,
		cardID = 251
	},
	[261] = {
		id = 261,
		fragID = 20261,
		cardID = 261
	},
	[262] = {
		id = 262,
		fragID = 20261,
		cardID = 262
	},
	[263] = {
		id = 263,
		fragID = 20261,
		cardID = 263
	},
	[264] = {
		id = 264,
		fragID = 20261,
		cardID = 264
	},
	[271] = {
		id = 271,
		fragID = 20271,
		cardID = 271
	},
	[272] = {
		id = 272,
		fragID = 20271,
		cardID = 272
	},
	[273] = {
		id = 273,
		fragID = 20271,
		cardID = 273
	},
	[281] = {
		id = 281,
		fragID = 20281,
		cardID = 281
	},
	[282] = {
		id = 282,
		fragID = 20281,
		cardID = 282
	},
	[283] = {
		id = 283,
		fragID = 20281,
		cardID = 283
	},
	[301] = {
		id = 301,
		fragID = 20301,
		cardID = 301
	},
	[302] = {
		id = 302,
		fragID = 20301,
		cardID = 302
	},
	[303] = {
		id = 303,
		fragID = 20301,
		cardID = 303
	},
	[321] = {
		id = 321,
		fragID = 20321,
		cardID = 321
	},
	[331] = {
		id = 331,
		fragID = 20331,
		cardID = 331
	},
	[332] = {
		id = 332,
		fragID = 20331,
		cardID = 332
	},
	[333] = {
		id = 333,
		fragID = 20331,
		cardID = 333
	},
	[341] = {
		id = 341,
		fragID = 20341,
		cardID = 341
	},
	[351] = {
		id = 351,
		fragID = 20351,
		cardID = 351
	},
	[352] = {
		id = 352,
		fragID = 20351,
		cardID = 352
	},
	[371] = {
		id = 371,
		fragID = 20371,
		cardID = 371
	},
	[372] = {
		id = 372,
		fragID = 20371,
		cardID = 372
	},
	[381] = {
		id = 381,
		fragID = 20381,
		cardID = 381
	},
	[382] = {
		id = 382,
		fragID = 20381,
		cardID = 382
	},
	[391] = {
		id = 391,
		fragID = 20391,
		cardID = 391
	},
	[392] = {
		id = 392,
		fragID = 20391,
		cardID = 392
	},
	[393] = {
		id = 393,
		fragID = 20391,
		cardID = 393
	},
	[394] = {
		id = 394,
		fragID = 20391,
		cardID = 394
	},
	[401] = {
		id = 401,
		fragID = 20401,
		cardID = 401
	},
	[402] = {
		id = 402,
		fragID = 20401,
		cardID = 402
	},
	[403] = {
		id = 403,
		fragID = 20401,
		cardID = 403
	},
	[411] = {
		id = 411,
		fragID = 20411,
		cardID = 411
	},
	[431] = {
		id = 431,
		fragID = 20431,
		cardID = 431
	},
	[441] = {
		id = 441,
		fragID = 20441,
		cardID = 441
	},
	[451] = {
		id = 451,
		fragID = 20451,
		cardID = 451
	},
	[452] = {
		id = 452,
		fragID = 20451,
		cardID = 452
	},
	[461] = {
		id = 461,
		fragID = 20461,
		cardID = 461
	},
	[462] = {
		id = 462,
		fragID = 20461,
		cardID = 462
	},
	[463] = {
		id = 463,
		fragID = 20461,
		cardID = 463
	},
	[464] = {
		id = 464,
		fragID = 20461,
		cardID = 464
	},
	[471] = {
		id = 471,
		fragID = 20471,
		cardID = 471
	},
	[472] = {
		id = 472,
		fragID = 20471,
		cardID = 472
	},
	[481] = {
		id = 481,
		fragID = 20481,
		cardID = 481
	},
	[482] = {
		id = 482,
		fragID = 20481,
		cardID = 482
	},
	[491] = {
		id = 491,
		fragID = 20491,
		cardID = 491
	},
	[492] = {
		id = 492,
		fragID = 20491,
		cardID = 492
	},
	[493] = {
		id = 493,
		fragID = 20491,
		cardID = 493
	},
	[501] = {
		id = 501,
		fragID = 20501,
		cardID = 501
	},
	[502] = {
		id = 502,
		fragID = 20501,
		cardID = 502
	},
	[503] = {
		id = 503,
		fragID = 20501,
		cardID = 503
	},
	[541] = {
		id = 541,
		fragID = 20541,
		cardID = 541
	},
	[542] = {
		id = 542,
		fragID = 20541,
		cardID = 542
	},
	[551] = {
		id = 551,
		fragID = 20551,
		cardID = 551
	},
	[552] = {
		id = 552,
		fragID = 20551,
		cardID = 552
	},
	[561] = {
		id = 561,
		fragID = 20561,
		cardID = 561
	},
	[571] = {
		id = 571,
		fragID = 20571,
		cardID = 571
	},
	[572] = {
		id = 572,
		fragID = 20571,
		cardID = 572
	},
	[574] = {
		id = 574,
		fragID = 20571,
		cardID = 574
	},
	[591] = {
		id = 591,
		fragID = 20591,
		cardID = 591
	},
	[592] = {
		id = 592,
		fragID = 20591,
		cardID = 592
	},
	[593] = {
		id = 593,
		fragID = 20591,
		cardID = 593
	},
	[601] = {
		id = 601,
		fragID = 20601,
		cardID = 601
	},
	[602] = {
		id = 602,
		fragID = 20601,
		cardID = 602
	},
	[603] = {
		id = 603,
		fragID = 20601,
		cardID = 603
	},
	[611] = {
		id = 611,
		fragID = 20611,
		cardID = 611
	},
	[631] = {
		id = 631,
		fragID = 20631,
		cardID = 631
	},
	[632] = {
		id = 632,
		fragID = 20631,
		cardID = 632
	},
	[641] = {
		id = 641,
		fragID = 20641,
		cardID = 641
	},
	[691] = {
		id = 691,
		fragID = 20691,
		cardID = 691
	},
	[692] = {
		id = 692,
		fragID = 20691,
		cardID = 692
	},
	[701] = {
		id = 701,
		fragID = 20701,
		cardID = 701
	},
	[711] = {
		id = 711,
		fragID = 20711,
		cardID = 711
	},
	[712] = {
		id = 712,
		fragID = 20711,
		cardID = 712
	},
	[721] = {
		id = 721,
		fragID = 20721,
		cardID = 721
	},
	[731] = {
		id = 731,
		fragID = 20731,
		cardID = 731
	},
	[741] = {
		id = 741,
		fragID = 20741,
		cardID = 741
	},
	[751] = {
		id = 751,
		fragID = 20751,
		cardID = 751
	},
	[752] = {
		id = 752,
		fragID = 20751,
		cardID = 752
	},
	[753] = {
		id = 753,
		fragID = 20751,
		cardID = 753
	},
	[761] = {
		id = 761,
		fragID = 20761,
		cardID = 761
	},
	[762] = {
		id = 762,
		fragID = 20761,
		cardID = 762
	},
	[763] = {
		id = 763,
		fragID = 20761,
		cardID = 763
	},
	[771] = {
		id = 771,
		fragID = 20771,
		cardID = 771
	},
	[781] = {
		id = 781,
		fragID = 20781,
		cardID = 781
	},
	[782] = {
		id = 782,
		fragID = 20781,
		cardID = 782
	},
	[783] = {
		id = 783,
		fragID = 20781,
		cardID = 783
	},
	[791] = {
		id = 791,
		fragID = 20791,
		cardID = 791
	},
	[792] = {
		id = 792,
		fragID = 20791,
		cardID = 792
	},
	[793] = {
		id = 793,
		fragID = 20791,
		cardID = 793
	},
	[801] = {
		id = 801,
		fragID = 20801,
		cardID = 801
	},
	[802] = {
		id = 802,
		fragID = 20801,
		cardID = 802
	},
	[803] = {
		id = 803,
		fragID = 20801,
		cardID = 803
	},
	[861] = {
		id = 861,
		fragID = 20861,
		cardID = 861
	},
	[862] = {
		id = 862,
		fragID = 20861,
		cardID = 862
	},
	[863] = {
		id = 863,
		fragID = 20861,
		cardID = 863
	},
	[881] = {
		id = 881,
		fragID = 20881,
		cardID = 881
	},
	[882] = {
		id = 882,
		fragID = 20881,
		cardID = 882
	},
	[883] = {
		id = 883,
		fragID = 20881,
		cardID = 883
	},
	[884] = {
		id = 884,
		fragID = 20881,
		cardID = 884
	},
	[891] = {
		id = 891,
		fragID = 20891,
		cardID = 891
	},
	[892] = {
		id = 892,
		fragID = 20891,
		cardID = 892
	},
	[893] = {
		id = 893,
		fragID = 20891,
		cardID = 893
	},
	[901] = {
		id = 901,
		fragID = 20901,
		cardID = 901
	},
	[971] = {
		id = 971,
		fragID = 20971,
		cardID = 971
	},
	[972] = {
		id = 972,
		fragID = 20971,
		cardID = 972
	},
	[1031] = {
		id = 1031,
		fragID = 21031,
		cardID = 1031
	},
	[1032] = {
		id = 1032,
		fragID = 21031,
		cardID = 1032
	},
	[1071] = {
		id = 1071,
		fragID = 21071,
		cardID = 1071
	},
	[1072] = {
		id = 1072,
		fragID = 21071,
		cardID = 1072
	},
	[1081] = {
		id = 1081,
		fragID = 21081,
		cardID = 1081
	},
	[1082] = {
		id = 1082,
		fragID = 21081,
		cardID = 1082
	},
	[1171] = {
		id = 1171,
		fragID = 21171,
		cardID = 1171
	},
	[1172] = {
		id = 1172,
		fragID = 21171,
		cardID = 1172
	},
	[1173] = {
		id = 1173,
		fragID = 21171,
		cardID = 1173
	},
	[1221] = {
		id = 1221,
		fragID = 21221,
		cardID = 1221
	},
	[1231] = {
		id = 1231,
		fragID = 21231,
		cardID = 1231
	},
	[1241] = {
		id = 1241,
		fragID = 21241,
		cardID = 1241
	},
	[1251] = {
		id = 1251,
		fragID = 21251,
		cardID = 1251
	},
	[1252] = {
		id = 1252,
		fragID = 21251,
		cardID = 1252
	},
	[1253] = {
		id = 1253,
		fragID = 21251,
		cardID = 1253
	},
	[1254] = {
		id = 1254,
		fragID = 21254,
		cardID = 1254
	},
	[1261] = {
		id = 1261,
		fragID = 21261,
		cardID = 1261
	},
	[1271] = {
		id = 1271,
		fragID = 21271,
		cardID = 1271
	},
	[1281] = {
		id = 1281,
		fragID = 21281,
		cardID = 1281
	},
	[1291] = {
		id = 1291,
		fragID = 21291,
		cardID = 1291
	},
	[1292] = {
		id = 1292,
		fragID = 21291,
		cardID = 1292
	},
	[1293] = {
		id = 1293,
		fragID = 21291,
		cardID = 1293
	},
	[1301] = {
		id = 1301,
		fragID = 21301,
		cardID = 1301
	},
	[1302] = {
		id = 1302,
		fragID = 21301,
		cardID = 1302
	},
	[1303] = {
		id = 1303,
		fragID = 21301,
		cardID = 1303
	},
	[1304] = {
		id = 1304,
		fragID = 21301,
		cardID = 1304
	},
	[1311] = {
		id = 1311,
		fragID = 21311,
		cardID = 1311
	},
	[1312] = {
		id = 1312,
		fragID = 21311,
		cardID = 1312
	},
	[1313] = {
		id = 1313,
		fragID = 21311,
		cardID = 1313
	},
	[1314] = {
		id = 1314,
		fragID = 21311,
		cardID = 1314
	},
	[1351] = {
		id = 1351,
		fragID = 21351,
		cardID = 1351
	},
	[1352] = {
		id = 1352,
		fragID = 21351,
		cardID = 1352
	},
	[1353] = {
		id = 1353,
		fragID = 21351,
		cardID = 1353
	},
	[1391] = {
		id = 1391,
		fragID = 21391,
		cardID = 1391
	},
	[1392] = {
		id = 1392,
		fragID = 21391,
		cardID = 1392
	},
	[1393] = {
		id = 1393,
		fragID = 21391,
		cardID = 1393
	},
	[1394] = {
		id = 1394,
		fragID = 21391,
		cardID = 1394
	},
	[1396] = {
		id = 1396,
		fragID = 21391,
		cardID = 1396
	},
	[1397] = {
		id = 1397,
		fragID = 21391,
		cardID = 1397
	},
	[1421] = {
		id = 1421,
		fragID = 21421,
		cardID = 1421
	},
	[1422] = {
		id = 1422,
		fragID = 21421,
		cardID = 1422
	},
	[1423] = {
		id = 1423,
		fragID = 21421,
		cardID = 1423
	},
	[1441] = {
		id = 1441,
		fragID = 21441,
		cardID = 1441
	},
	[1442] = {
		id = 1442,
		fragID = 21441,
		cardID = 1442
	},
	[1443] = {
		id = 1443,
		fragID = 21441,
		cardID = 1443
	},
	[1481] = {
		id = 1481,
		fragID = 21481,
		cardID = 1481
	},
	[1501] = {
		id = 1501,
		fragID = 21501,
		cardID = 1501
	},
	[1502] = {
		id = 1502,
		fragID = 21501,
		cardID = 1502
	},
	[1503] = {
		id = 1503,
		fragID = 21501,
		cardID = 1503
	},
	[1504] = {
		id = 1504,
		fragID = 21501,
		cardID = 1504
	},
	[1511] = {
		id = 1511,
		fragID = 21511,
		cardID = 1511
	},
	[1611] = {
		id = 1611,
		fragID = 21611,
		cardID = 1611
	},
	[1612] = {
		id = 1612,
		fragID = 21611,
		cardID = 1612
	},
	[1641] = {
		id = 1641,
		fragID = 21641,
		cardID = 1641
	},
	[1671] = {
		id = 1671,
		fragID = 21671,
		cardID = 1671
	},
	[1771] = {
		id = 1771,
		fragID = 21771,
		cardID = 1771
	},
	[1772] = {
		id = 1772,
		fragID = 21771,
		cardID = 1772
	},
	[1801] = {
		id = 1801,
		fragID = 21801,
		cardID = 1801
	},
	[1802] = {
		id = 1802,
		fragID = 21801,
		cardID = 1802
	},
	[1811] = {
		id = 1811,
		fragID = 21811,
		cardID = 1811
	},
	[1812] = {
		id = 1812,
		fragID = 21811,
		cardID = 1812
	},
	[1813] = {
		id = 1813,
		fragID = 21811,
		cardID = 1813
	},
	[1841] = {
		id = 1841,
		fragID = 21841,
		cardID = 1841
	},
	[1851] = {
		id = 1851,
		fragID = 21851,
		cardID = 1851
	},
	[1852] = {
		id = 1852,
		fragID = 21851,
		cardID = 1852
	},
	[1853] = {
		id = 1853,
		fragID = 21851,
		cardID = 1853
	},
	[1861] = {
		id = 1861,
		fragID = 21861,
		cardID = 1861
	},
	[1862] = {
		id = 1862,
		fragID = 21861,
		cardID = 1862
	},
	[1863] = {
		id = 1863,
		fragID = 21861,
		cardID = 1863
	},
	[1891] = {
		id = 1891,
		fragID = 21891,
		cardID = 1891
	},
	[1892] = {
		id = 1892,
		fragID = 21891,
		cardID = 1892
	},
	[1893] = {
		id = 1893,
		fragID = 21891,
		cardID = 1893
	},
	[1901] = {
		id = 1901,
		fragID = 21901,
		cardID = 1901
	},
	[1902] = {
		id = 1902,
		fragID = 21901,
		cardID = 1902
	},
	[1903] = {
		id = 1903,
		fragID = 21901,
		cardID = 1903
	},
	[1911] = {
		id = 1911,
		fragID = 21911,
		cardID = 1911
	},
	[1921] = {
		id = 1921,
		fragID = 21921,
		cardID = 1921
	},
	[1931] = {
		id = 1931,
		fragID = 21931,
		cardID = 1931
	},
	[1941] = {
		id = 1941,
		fragID = 21941,
		cardID = 1941
	},
	[1951] = {
		id = 1951,
		fragID = 21951,
		cardID = 1951
	},
	[1961] = {
		id = 1961,
		fragID = 21961,
		cardID = 1961
	},
	[1962] = {
		id = 1962,
		fragID = 21961,
		cardID = 1962
	},
	[1971] = {
		id = 1971,
		fragID = 21971,
		cardID = 1971
	},
	[1972] = {
		id = 1972,
		fragID = 21971,
		cardID = 1972
	},
	[1981] = {
		id = 1981,
		fragID = 21981,
		cardID = 1981
	},
	[1982] = {
		id = 1982,
		fragID = 21981,
		cardID = 1982
	},
	[1991] = {
		id = 1991,
		fragID = 21991,
		cardID = 1991
	},
	[2011] = {
		id = 2011,
		fragID = 22011,
		cardID = 2011
	},
	[2012] = {
		id = 2012,
		fragID = 22011,
		cardID = 2012
	},
	[2013] = {
		id = 2013,
		fragID = 22011,
		cardID = 2013
	},
	[2021] = {
		id = 2021,
		fragID = 22021,
		cardID = 2021
	},
	[2022] = {
		id = 2022,
		fragID = 22021,
		cardID = 2022
	},
	[2023] = {
		id = 2023,
		fragID = 22021,
		cardID = 2023
	},
	[2031] = {
		id = 2031,
		fragID = 22031,
		cardID = 2031
	},
	[2032] = {
		id = 2032,
		fragID = 22031,
		cardID = 2032
	},
	[2033] = {
		id = 2033,
		fragID = 22031,
		cardID = 2033
	},
	[2041] = {
		id = 2041,
		fragID = 22041,
		cardID = 2041
	},
	[2071] = {
		id = 2071,
		fragID = 22071,
		cardID = 2071
	},
	[2072] = {
		id = 2072,
		fragID = 22071,
		cardID = 2072
	},
	[2073] = {
		id = 2073,
		fragID = 22071,
		cardID = 2073
	},
	[2121] = {
		id = 2121,
		fragID = 22121,
		cardID = 2121
	},
	[2131] = {
		id = 2131,
		fragID = 22131,
		cardID = 2131
	},
	[2231] = {
		id = 2231,
		fragID = 22231,
		cardID = 2231
	},
	[2232] = {
		id = 2232,
		fragID = 22231,
		cardID = 2232
	},
	[2233] = {
		id = 2233,
		fragID = 22231,
		cardID = 2233
	},
	[2241] = {
		id = 2241,
		fragID = 22241,
		cardID = 2241
	},
	[2242] = {
		id = 2242,
		fragID = 22241,
		cardID = 2242
	},
	[2243] = {
		id = 2243,
		fragID = 22241,
		cardID = 2243
	},
	[2271] = {
		id = 2271,
		fragID = 22271,
		cardID = 2271
	},
	[2272] = {
		id = 2272,
		fragID = 22271,
		cardID = 2272
	},
	[2301] = {
		id = 2301,
		fragID = 22301,
		cardID = 2301
	},
	[2302] = {
		id = 2302,
		fragID = 22301,
		cardID = 2302
	},
	[2303] = {
		id = 2303,
		fragID = 22301,
		cardID = 2303
	},
	[2351] = {
		id = 2351,
		fragID = 22351,
		cardID = 2351
	},
	[2361] = {
		id = 2361,
		fragID = 22361,
		cardID = 2361
	},
	[2371] = {
		id = 2371,
		fragID = 22371,
		cardID = 2371
	},
	[2381] = {
		id = 2381,
		fragID = 22381,
		cardID = 2381
	},
	[2391] = {
		id = 2391,
		fragID = 22391,
		cardID = 2391
	},
	[2401] = {
		id = 2401,
		fragID = 22401,
		cardID = 2401
	},
	[2411] = {
		id = 2411,
		fragID = 22411,
		cardID = 2411
	},
	[2421] = {
		id = 2421,
		fragID = 22421,
		cardID = 2421
	},
	[2431] = {
		id = 2431,
		fragID = 22431,
		cardID = 2431
	},
	[2441] = {
		id = 2441,
		fragID = 22441,
		cardID = 2441
	},
	[2442] = {
		id = 2442,
		fragID = 22441,
		cardID = 2442
	},
	[2461] = {
		id = 2461,
		fragID = 22461,
		cardID = 2461
	},
	[2471] = {
		id = 2471,
		fragID = 22471,
		cardID = 2471
	},
	[2472] = {
		id = 2472,
		fragID = 22471,
		cardID = 2472
	},
	[2473] = {
		id = 2473,
		fragID = 22471,
		cardID = 2473
	},
	[2481] = {
		id = 2481,
		fragID = 22481,
		cardID = 2481
	},
	[2482] = {
		id = 2482,
		fragID = 22481,
		cardID = 2482
	},
	[2483] = {
		id = 2483,
		fragID = 22481,
		cardID = 2483
	},
	[2491] = {
		id = 2491,
		fragID = 22491,
		cardID = 2491
	},
	[2492] = {
		id = 2492,
		fragID = 22491,
		cardID = 2492
	},
	[2493] = {
		id = 2493,
		fragID = 22491,
		cardID = 2493
	},
	[2591] = {
		id = 2591,
		fragID = 22591,
		cardID = 2591
	},
	[2592] = {
		id = 2592,
		fragID = 22591,
		cardID = 2592
	},
	[2593] = {
		id = 2593,
		fragID = 22591,
		cardID = 2593
	},
	[2611] = {
		id = 2611,
		fragID = 22611,
		cardID = 2611
	},
	[2612] = {
		id = 2612,
		fragID = 22611,
		cardID = 2612
	},
	[2631] = {
		id = 2631,
		fragID = 22631,
		cardID = 2631
	},
	[2632] = {
		id = 2632,
		fragID = 22631,
		cardID = 2632
	},
	[2633] = {
		id = 2633,
		fragID = 22631,
		cardID = 2633
	},
	[2681] = {
		id = 2681,
		fragID = 22681,
		cardID = 2681
	},
	[2682] = {
		id = 2682,
		fragID = 22681,
		cardID = 2682
	},
	[2683] = {
		id = 2683,
		fragID = 22681,
		cardID = 2683
	},
	[2721] = {
		id = 2721,
		fragID = 22721,
		cardID = 2721
	},
	[2722] = {
		id = 2722,
		fragID = 22721,
		cardID = 2722
	},
	[2723] = {
		id = 2723,
		fragID = 22721,
		cardID = 2723
	},
	[2821] = {
		id = 2821,
		fragID = 22821,
		cardID = 2821
	},
	[2822] = {
		id = 2822,
		fragID = 22821,
		cardID = 2822
	},
	[2831] = {
		id = 2831,
		fragID = 22831,
		cardID = 2831
	},
	[2832] = {
		id = 2832,
		fragID = 22831,
		cardID = 2832
	},
	[2841] = {
		id = 2841,
		fragID = 22841,
		cardID = 2841
	},
	[2842] = {
		id = 2842,
		fragID = 22841,
		cardID = 2842
	},
	[2843] = {
		id = 2843,
		fragID = 22841,
		cardID = 2843
	},
	[2871] = {
		id = 2871,
		fragID = 22871,
		cardID = 2871
	},
	[2872] = {
		id = 2872,
		fragID = 22871,
		cardID = 2872
	},
	[2873] = {
		id = 2873,
		fragID = 22871,
		cardID = 2873
	},
	[2891] = {
		id = 2891,
		fragID = 22891,
		cardID = 2891
	},
	[2921] = {
		id = 2921,
		fragID = 22921,
		cardID = 2921
	},
	[2922] = {
		id = 2922,
		fragID = 22922,
		cardID = 2922
	},
	[2923] = {
		id = 2923,
		fragID = 22921,
		cardID = 2923
	},
	[2924] = {
		id = 2924,
		fragID = 22922,
		cardID = 2924
	},
	[2961] = {
		id = 2961,
		fragID = 22961,
		cardID = 2961
	},
	[2962] = {
		id = 2962,
		fragID = 22961,
		cardID = 2962
	},
	[2963] = {
		id = 2963,
		fragID = 22961,
		cardID = 2963
	},
	[2991] = {
		id = 2991,
		fragID = 22991,
		cardID = 2991
	},
	[2992] = {
		id = 2992,
		fragID = 22991,
		cardID = 2992
	},
	[2993] = {
		id = 2993,
		fragID = 22991,
		cardID = 2993
	},
	[3001] = {
		id = 3001,
		fragID = 23001,
		cardID = 3001
	},
	[3002] = {
		id = 3002,
		fragID = 23001,
		cardID = 3002
	},
	[3003] = {
		id = 3003,
		fragID = 23001,
		cardID = 3003
	},
	[3011] = {
		id = 3011,
		fragID = 23011,
		cardID = 3011
	},
	[3012] = {
		id = 3012,
		fragID = 23011,
		cardID = 3012
	},
	[3021] = {
		id = 3021,
		fragID = 23021,
		cardID = 3021
	},
	[3051] = {
		id = 3051,
		fragID = 23051,
		cardID = 3051
	},
	[3141] = {
		id = 3141,
		fragID = 23141,
		cardID = 3141
	},
	[3142] = {
		id = 3142,
		fragID = 23141,
		cardID = 3142
	},
	[3143] = {
		id = 3143,
		fragID = 23141,
		cardID = 3143
	},
	[3151] = {
		id = 3151,
		fragID = 23151,
		cardID = 3151
	},
	[3152] = {
		id = 3152,
		fragID = 23151,
		cardID = 3152
	},
	[3161] = {
		id = 3161,
		fragID = 23161,
		cardID = 3161
	},
	[3171] = {
		id = 3171,
		fragID = 23171,
		cardID = 3171
	},
	[3181] = {
		id = 3181,
		fragID = 23181,
		cardID = 3181
	},
	[3191] = {
		id = 3191,
		fragID = 23191,
		cardID = 3191
	},
	[3201] = {
		id = 3201,
		fragID = 23201,
		cardID = 3201
	},
	[3211] = {
		id = 3211,
		fragID = 23211,
		cardID = 3211
	},
	[3221] = {
		id = 3221,
		fragID = 23221,
		cardID = 3221
	},
	[3231] = {
		id = 3231,
		fragID = 23231,
		cardID = 3231
	},
	[3241] = {
		id = 3241,
		fragID = 23241,
		cardID = 3241
	},
	[3242] = {
		id = 3242,
		fragID = 23241,
		cardID = 3242
	},
	[3244] = {
		id = 3244,
		fragID = 23244,
		cardID = 3244
	},
	[3251] = {
		id = 3251,
		fragID = 23251,
		cardID = 3251
	},
	[3261] = {
		id = 3261,
		fragID = 23261,
		cardID = 3261
	},
	[3262] = {
		id = 3262,
		fragID = 23261,
		cardID = 3262
	},
	[3271] = {
		id = 3271,
		fragID = 23271,
		cardID = 3271
	},
	[3281] = {
		id = 3281,
		fragID = 23281,
		cardID = 3281
	},
	[3282] = {
		id = 3282,
		fragID = 23281,
		cardID = 3282
	},
	[3283] = {
		id = 3283,
		fragID = 23281,
		cardID = 3283
	},
	[3291] = {
		id = 3291,
		fragID = 23291,
		cardID = 3291
	},
	[3292] = {
		id = 3292,
		fragID = 23291,
		cardID = 3292
	},
	[3293] = {
		id = 3293,
		fragID = 23291,
		cardID = 3293
	},
	[3301] = {
		id = 3301,
		fragID = 23301,
		cardID = 3301
	},
	[3302] = {
		id = 3302,
		fragID = 23301,
		cardID = 3302
	},
	[3303] = {
		id = 3303,
		fragID = 23301,
		cardID = 3303
	},
	[3304] = {
		id = 3304,
		fragID = 23301,
		cardID = 3304
	},
	[3341] = {
		id = 3341,
		fragID = 23341,
		cardID = 3341
	},
	[3342] = {
		id = 3342,
		fragID = 23341,
		cardID = 3342
	},
	[3351] = {
		id = 3351,
		fragID = 23351,
		cardID = 3351
	},
	[3352] = {
		id = 3352,
		fragID = 23351,
		cardID = 3352
	},
	[3353] = {
		id = 3353,
		fragID = 23351,
		cardID = 3353
	},
	[3411] = {
		id = 3411,
		fragID = 23411,
		cardID = 3411
	},
	[3412] = {
		id = 3412,
		fragID = 23411,
		cardID = 3412
	},
	[3413] = {
		id = 3413,
		fragID = 23411,
		cardID = 3413
	},
	[3431] = {
		id = 3431,
		fragID = 23431,
		cardID = 3431
	},
	[3432] = {
		id = 3432,
		fragID = 23431,
		cardID = 3432
	},
	[3471] = {
		id = 3471,
		fragID = 23471,
		cardID = 3471
	},
	[3472] = {
		id = 3472,
		fragID = 23471,
		cardID = 3472
	},
	[3501] = {
		id = 3501,
		fragID = 23501,
		cardID = 3501
	},
	[3502] = {
		id = 3502,
		fragID = 23501,
		cardID = 3502
	},
	[3511] = {
		id = 3511,
		fragID = 23511,
		cardID = 3511
	},
	[3541] = {
		id = 3541,
		fragID = 23541,
		cardID = 3541
	},
	[3542] = {
		id = 3542,
		fragID = 23541,
		cardID = 3542
	},
	[3543] = {
		id = 3543,
		fragID = 23541,
		cardID = 3543
	},
	[3561] = {
		id = 3561,
		fragID = 23561,
		cardID = 3561
	},
	[3562] = {
		id = 3562,
		fragID = 23561,
		cardID = 3562
	},
	[3591] = {
		id = 3591,
		fragID = 23591,
		cardID = 3591
	},
	[3592] = {
		id = 3592,
		fragID = 23591,
		cardID = 3592
	},
	[3601] = {
		id = 3601,
		fragID = 23601,
		cardID = 3601
	},
	[3611] = {
		id = 3611,
		fragID = 23611,
		cardID = 3611
	},
	[3621] = {
		id = 3621,
		fragID = 23621,
		cardID = 3621
	},
	[3622] = {
		id = 3622,
		fragID = 23621,
		cardID = 3622
	},
	[3623] = {
		id = 3623,
		fragID = 23621,
		cardID = 3623
	},
	[3631] = {
		id = 3631,
		fragID = 23631,
		cardID = 3631
	},
	[3632] = {
		id = 3632,
		fragID = 23631,
		cardID = 3632
	},
	[3641] = {
		id = 3641,
		fragID = 23641,
		cardID = 3641
	},
	[3642] = {
		id = 3642,
		fragID = 23641,
		cardID = 3642
	},
	[3651] = {
		id = 3651,
		fragID = 23651,
		cardID = 3651
	},
	[3661] = {
		id = 3661,
		fragID = 23661,
		cardID = 3661
	},
	[3662] = {
		id = 3662,
		fragID = 23661,
		cardID = 3662
	},
	[3663] = {
		id = 3663,
		fragID = 23661,
		cardID = 3663
	},
	[3671] = {
		id = 3671,
		fragID = 23671,
		cardID = 3671
	},
	[3681] = {
		id = 3681,
		fragID = 23681,
		cardID = 3681
	},
	[3682] = {
		id = 3682,
		fragID = 23681,
		cardID = 3682
	},
	[3683] = {
		id = 3683,
		fragID = 23681,
		cardID = 3683
	},
	[3771] = {
		id = 3771,
		fragID = 23771,
		cardID = 3771
	},
	[3772] = {
		id = 3772,
		fragID = 23771,
		cardID = 3772
	},
	[3841] = {
		id = 3841,
		fragID = 23841,
		cardID = 3841
	},
	[3842] = {
		id = 3842,
		fragID = 23841,
		cardID = 3842
	},
	[3843] = {
		id = 3843,
		fragID = 23841,
		cardID = 3843
	},
	[3951] = {
		id = 3951,
		fragID = 23951,
		cardID = 3951
	},
	[3961] = {
		id = 3961,
		fragID = 23961,
		cardID = 3961
	},
	[4024] = {
		id = 4024,
		fragID = 24024,
		cardID = 4024
	},
	[4031] = {
		id = 4031,
		fragID = 24031,
		cardID = 4031
	},
	[4051] = {
		id = 4051,
		fragID = 24051,
		cardID = 4051
	},
	[4071] = {
		id = 4071,
		fragID = 24071,
		cardID = 4071
	},
	[4081] = {
		id = 4081,
		fragID = 24081,
		cardID = 4081
	},
	[4101] = {
		id = 4101,
		fragID = 24101,
		cardID = 4101
	},
	[4111] = {
		id = 4111,
		fragID = 24111,
		cardID = 4111
	},
	[4121] = {
		id = 4121,
		fragID = 24121,
		cardID = 4121
	},
	[4131] = {
		id = 4131,
		fragID = 24131,
		cardID = 4131
	},
	[4132] = {
		id = 4132,
		fragID = 24131,
		cardID = 4132
	},
	[4141] = {
		id = 4141,
		fragID = 24141,
		cardID = 4141
	},
	[4151] = {
		id = 4151,
		fragID = 24151,
		cardID = 4151
	},
	[4161] = {
		id = 4161,
		fragID = 24161,
		cardID = 4161
	},
	[4171] = {
		id = 4171,
		fragID = 24171,
		cardID = 4171
	},
	[4172] = {
		id = 4172,
		fragID = 24171,
		cardID = 4172
	},
	[4181] = {
		id = 4181,
		fragID = 24181,
		cardID = 4181
	},
	[4191] = {
		id = 4191,
		fragID = 24191,
		cardID = 4191
	},
	[4201] = {
		id = 4201,
		fragID = 24201,
		cardID = 4201
	},
	[4211] = {
		id = 4211,
		fragID = 24211,
		cardID = 4211
	},
	[4221] = {
		id = 4221,
		fragID = 24221,
		cardID = 4221
	},
	[4231] = {
		id = 4231,
		fragID = 24231,
		cardID = 4231
	},
	[4241] = {
		id = 4241,
		fragID = 24241,
		cardID = 4241
	},
	[4251] = {
		id = 4251,
		fragID = 24251,
		cardID = 4251
	},
	[4261] = {
		id = 4261,
		fragID = 24261,
		cardID = 4261
	},
	[4271] = {
		id = 4271,
		fragID = 24271,
		cardID = 4271
	},
	[4291] = {
		id = 4291,
		fragID = 24291,
		cardID = 4291
	},
	[4301] = {
		id = 4301,
		fragID = 24301,
		cardID = 4301
	},
	[4311] = {
		id = 4311,
		fragID = 24311,
		cardID = 4311
	},
	[4321] = {
		id = 4321,
		fragID = 24321,
		cardID = 4321
	},
	[4331] = {
		id = 4331,
		fragID = 24331,
		cardID = 4331
	},
	[4341] = {
		id = 4341,
		fragID = 24341,
		cardID = 4341
	},
	[4351] = {
		id = 4351,
		fragID = 24351,
		cardID = 4351
	},
	[4361] = {
		id = 4361,
		fragID = 24361,
		cardID = 4361
	},
	[4371] = {
		id = 4371,
		fragID = 24371,
		cardID = 4371
	},
	[4381] = {
		id = 4381,
		fragID = 24381,
		cardID = 4381
	},
	[4391] = {
		id = 4391,
		fragID = 24391,
		cardID = 4391
	},
	[4401] = {
		id = 4401,
		fragID = 24401,
		cardID = 4401
	},
	[4411] = {
		id = 4411,
		fragID = 24411,
		cardID = 4411
	},
	[4421] = {
		id = 4421,
		fragID = 24421,
		cardID = 4421
	},
	[4431] = {
		id = 4431,
		fragID = 24431,
		cardID = 4431
	},
	[4441] = {
		id = 4441,
		fragID = 24441,
		cardID = 4441
	},
	[4451] = {
		id = 4451,
		fragID = 24451,
		cardID = 4451
	},
	[4461] = {
		id = 4461,
		fragID = 24461,
		cardID = 4461
	},
	[4481] = {
		id = 4481,
		fragID = 24481,
		cardID = 4481
	},
	[4491] = {
		id = 4491,
		fragID = 24491,
		cardID = 4491
	},
	[7001] = {
		id = 7001,
		fragID = 27001,
		cardID = 7001
	},
	[7021] = {
		id = 7021,
		fragID = 27021,
		cardID = 7021
	},
	[7031] = {
		id = 7031,
		fragID = 27031,
		cardID = 7031
	},
	[7041] = {
		id = 7041,
		fragID = 27041,
		cardID = 7041
	},
	[7051] = {
		id = 7051,
		fragID = 27051,
		cardID = 7051
	},
	[7061] = {
		id = 7061,
		fragID = 27061,
		cardID = 7061
	},
	[7071] = {
		id = 7071,
		fragID = 27071,
		cardID = 7071
	},
	[7081] = {
		id = 7081,
		fragID = 27081,
		cardID = 7081
	},
	[7091] = {
		id = 7091,
		fragID = 27091,
		cardID = 7091
	},
	[7101] = {
		id = 7101,
		fragID = 27101,
		cardID = 7101
	},
	[7111] = {
		id = 7111,
		fragID = 27111,
		cardID = 7111
	},
	[7121] = {
		id = 7121,
		fragID = 27121,
		cardID = 7121
	},
	[8101] = {
		id = 8101,
		fragID = 29061,
		cardID = 8101
	},
	[8102] = {
		id = 8102,
		fragID = 29071,
		cardID = 8102
	},
	[8103] = {
		id = 8103,
		fragID = 29081,
		cardID = 8103
	},
	[8104] = {
		id = 8104,
		fragID = 29091,
		cardID = 8104
	},
	[8105] = {
		id = 8105,
		fragID = 29101,
		cardID = 8105
	},
	[8106] = {
		id = 8106,
		fragID = 29111,
		cardID = 8106
	},
	[8107] = {
		id = 8107,
		fragID = 29121,
		cardID = 8107
	},
	[9001] = {
		id = 9001,
		fragID = 29001,
		cardID = 9001
	},
	[9002] = {
		id = 9002,
		fragID = 29002,
		cardID = 9002
	},
	[9003] = {
		id = 9003,
		fragID = 29003,
		cardID = 9003
	},
	[9011] = {
		id = 9011,
		fragID = 29011,
		cardID = 9011
	},
	[9012] = {
		id = 9012,
		fragID = 29011,
		cardID = 9011
	},
	[9013] = {
		id = 9013,
		fragID = 29013,
		cardID = 9013
	},
	[9014] = {
		id = 9014,
		fragID = 29013,
		cardID = 9011
	},
	[9021] = {
		id = 9021,
		fragID = 29021,
		cardID = 9021
	},
	[9041] = {
		id = 9041,
		fragID = 29072,
		cardID = 9041
	},
	[9051] = {
		id = 9051,
		fragID = 29073,
		cardID = 9051
	},
	[9061] = {
		id = 9061,
		fragID = 29074,
		cardID = 9061
	},
	[9071] = {
		id = 9071,
		fragID = 29075,
		cardID = 9071
	},
	[9081] = {
		id = 9081,
		fragID = 29076,
		cardID = 9081
	},
	[9091] = {
		id = 9091,
		fragID = 29077,
		cardID = 9091
	},
	[9101] = {
		id = 9101,
		fragID = 29078,
		cardID = 9101
	},
	[9111] = {
		id = 9111,
		fragID = 29079,
		cardID = 9111
	},
	[9121] = {
		id = 9121,
		fragID = 29080,
		cardID = 9121
	},
	[9131] = {
		id = 9131,
		fragID = 29081,
		cardID = 9131
	},
	[9141] = {
		id = 9141,
		fragID = 29082,
		cardID = 9141
	},
	[9151] = {
		id = 9151,
		fragID = 29083,
		cardID = 9151
	},
	[9161] = {
		id = 9161,
		fragID = 29084,
		cardID = 9161
	},
	[9171] = {
		id = 9171,
		fragID = 29085,
		cardID = 9171
	},
	[9181] = {
		id = 9181,
		fragID = 29086,
		cardID = 9181
	},
	[9191] = {
		id = 9191,
		fragID = 29087,
		cardID = 9191
	},
	[9201] = {
		id = 9201,
		fragID = 29088,
		cardID = 9201
	},
	[9211] = {
		id = 9211,
		fragID = 29089,
		cardID = 9211
	},
	[9221] = {
		id = 9221,
		fragID = 29090,
		cardID = 9221
	},
	[9231] = {
		id = 9231,
		fragID = 29091,
		cardID = 9231
	},

	__size = 510,
	__default = {
		__index = {
			languages = {'cn', 'tw', 'en', 'vn', 'th', 'kr', 'pt'}
		}
	}
}
return csv.card_bag