--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[2] = {['gold'] = 200000, [529] = 1000, ['coin1'] = 60, __size = 3}, 
	[3] = {[2103] = 10, ['gold'] = 200000, [529] = 1000, __size = 3}, __size = 2}
local __data_t__award = {
	[1] = __predefine_t__[2],
	[3] = __predefine_t__[3],
	[2] = __predefine_t__[2],
	[4] = __predefine_t__[2],
	[6] = __predefine_t__[2],
	[9] = __predefine_t__[2],
	[8] = __predefine_t__[3]
}

csv['cross']['arena']['daily_award'] = {
	[1] = {
		id = 1,
		pwTime = 1,
		award = __data_t__award[1]
		-- {['gold'] = 200000, [529] = 1000, ['coin1'] = 60, __size = 3}
	},
	[2] = {
		id = 2,
		pwTime = 2,
		award = __data_t__award[2]
		-- {['gold'] = 200000, [529] = 1000, ['coin1'] = 60, __size = 3}
	},
	[3] = {
		id = 3,
		pwTime = 3,
		award = __data_t__award[3]
		-- {[2103] = 10, ['gold'] = 200000, [529] = 1000, __size = 3}
	},
	[4] = {
		id = 4,
		pwTime = 4,
		award = __data_t__award[4]
		-- {['gold'] = 200000, [529] = 1000, ['coin1'] = 60, __size = 3}
	},
	[5] = {
		id = 5,
		pwTime = 5,
		award = {['gold'] = 600000, ['talent_point'] = 10, [529] = 2000, __size = 3}
	},
	[6] = {
		id = 6,
		pwTime = 6,
		award = __data_t__award[6]
		-- {['gold'] = 200000, [529] = 1000, ['coin1'] = 60, __size = 3}
	},
	[7] = {
		id = 7,
		pwTime = 7,
		award = {['gold'] = 200000, [502] = 10, [529] = 1000, __size = 3}
	},
	[8] = {
		id = 8,
		pwTime = 8,
		award = __data_t__award[8]
		-- {[2103] = 10, ['gold'] = 200000, [529] = 1000, __size = 3}
	},
	[9] = {
		id = 9,
		pwTime = 9,
		award = __data_t__award[9]
		-- {['gold'] = 200000, [529] = 1000, ['coin1'] = 60, __size = 3}
	},
	[10] = {
		id = 10,
		pwTime = 10,
		award = {['gold'] = 600000, [521] = 10, [529] = 2000, __size = 3}
	},

	__size = 10,
	__default = {
		__index = {
			award = {__size = 0}
		}
	}
}
return csv.cross.arena.daily_award