--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {['y'] = 0, ['x'] = 0, __size = 2}, 
	[2] = {['y'] = 0, ['x'] = 0, __size = 2}, __size = 2}
local __data_t__resPos2 = {
	[42] = __predefine_t__[2],
	[48] = __predefine_t__[2],
	[43] = __predefine_t__[2],
	["default"] = __predefine_t__[1],
	[49] = __predefine_t__[2],
	[52] = __predefine_t__[2],
	[53] = __predefine_t__[2],
	[24] = __predefine_t__[2],
	[25] = __predefine_t__[2],
	[26] = __predefine_t__[2],
	[27] = __predefine_t__[2],
	[20] = __predefine_t__[2],
	[21] = __predefine_t__[2],
	[22] = __predefine_t__[2],
	[23] = __predefine_t__[2],
	[46] = __predefine_t__[2],
	[47] = __predefine_t__[2],
	[44] = __predefine_t__[2],
	[45] = __predefine_t__[2],
	[28] = __predefine_t__[2],
	[29] = __predefine_t__[2],
	[40] = __predefine_t__[2],
	[41] = __predefine_t__[2],
	[1] = __predefine_t__[2],
	[3] = __predefine_t__[2],
	[2] = __predefine_t__[2],
	[5] = __predefine_t__[2],
	[4] = __predefine_t__[2],
	[7] = __predefine_t__[2],
	[6] = __predefine_t__[2],
	[9] = __predefine_t__[2],
	[8] = __predefine_t__[2],
	[51] = __predefine_t__[2],
	[39] = __predefine_t__[2],
	[38] = __predefine_t__[2],
	[11] = __predefine_t__[2],
	[10] = __predefine_t__[2],
	[13] = __predefine_t__[2],
	[12] = __predefine_t__[2],
	[15] = __predefine_t__[2],
	[14] = __predefine_t__[2],
	[17] = __predefine_t__[2],
	[16] = __predefine_t__[2],
	[19] = __predefine_t__[2],
	[18] = __predefine_t__[2],
	[31] = __predefine_t__[2],
	[30] = __predefine_t__[2],
	[37] = __predefine_t__[2],
	[36] = __predefine_t__[2],
	[35] = __predefine_t__[2],
	[34] = __predefine_t__[2],
	[33] = __predefine_t__[2],
	[32] = __predefine_t__[2],
	[50] = __predefine_t__[2]
}
local __data_t__resPos1 = {
	[42] = __predefine_t__[2],
	[48] = __predefine_t__[2],
	[43] = __predefine_t__[2],
	["default"] = __predefine_t__[1],
	[49] = __predefine_t__[2],
	[52] = __predefine_t__[2],
	[53] = __predefine_t__[2],
	[24] = __predefine_t__[2],
	[25] = __predefine_t__[2],
	[26] = __predefine_t__[2],
	[27] = __predefine_t__[2],
	[20] = __predefine_t__[2],
	[21] = __predefine_t__[2],
	[22] = __predefine_t__[2],
	[23] = __predefine_t__[2],
	[46] = __predefine_t__[2],
	[47] = __predefine_t__[2],
	[44] = __predefine_t__[2],
	[45] = __predefine_t__[2],
	[28] = __predefine_t__[2],
	[29] = __predefine_t__[2],
	[40] = __predefine_t__[2],
	[41] = __predefine_t__[2],
	[1] = __predefine_t__[2],
	[3] = __predefine_t__[2],
	[2] = __predefine_t__[2],
	[5] = __predefine_t__[2],
	[4] = __predefine_t__[2],
	[7] = __predefine_t__[2],
	[6] = __predefine_t__[2],
	[9] = __predefine_t__[2],
	[8] = __predefine_t__[2],
	[51] = __predefine_t__[2],
	[39] = __predefine_t__[2],
	[38] = __predefine_t__[2],
	[11] = __predefine_t__[2],
	[10] = __predefine_t__[2],
	[13] = __predefine_t__[2],
	[12] = __predefine_t__[2],
	[15] = __predefine_t__[2],
	[14] = __predefine_t__[2],
	[17] = __predefine_t__[2],
	[16] = __predefine_t__[2],
	[19] = __predefine_t__[2],
	[18] = __predefine_t__[2],
	[31] = __predefine_t__[2],
	[30] = __predefine_t__[2],
	[37] = __predefine_t__[2],
	[36] = __predefine_t__[2],
	[35] = __predefine_t__[2],
	[34] = __predefine_t__[2],
	[33] = __predefine_t__[2],
	[32] = __predefine_t__[2],
	[50] = __predefine_t__[2]
}

csv['yunying']['draw_limit'] = {
	[1] = {
		id = 1,
		card1 = 1971,
		res1 = 'config/big_hero/normal/img_383_gld@.png',
		resScale1 = 2.618,
		resPos1 = __data_t__resPos1[1],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_gld.png',
		posRes1 = 'common/txt/txt_dw_gld.png',
		resPos2 = __data_t__resPos2[1]
		-- {['y'] = 0, ['x'] = 0, __size = 2}
	},
	[2] = {
		id = 2,
		card1 = 1971,
		res1 = 'config/big_hero/normal/img_383_gld@.png',
		resScale1 = 2.618,
		resPos1 = __data_t__resPos1[2],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_gld.png',
		posRes1 = 'common/txt/txt_dw_gld.png',
		card2 = 1961,
		resScale2 = 2,
		resPos2 = __data_t__resPos2[2],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_gok.png',
		posRes2 = 'common/txt/txt_dw_gok.png'
	},
	[3] = {
		id = 3,
		card1 = 1971,
		res1 = 'config/big_hero/normal/img_383_gld@.png',
		resPos1 = __data_t__resPos1[3],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_gld.png',
		posRes1 = 'common/txt/txt_dw_gld.png',
		resPos2 = __data_t__resPos2[3]
		-- {['y'] = 0, ['x'] = 0, __size = 2}
	},
	[4] = {
		id = 4,
		card1 = 1261,
		res1 = 'config/big_hero/normal/img_249_lqy@.png',
		resScale1 = 2.618,
		resPos1 = __data_t__resPos1[4],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_lqy.png',
		posRes1 = 'common/txt/txt_dw_lqy.png',
		resPos2 = __data_t__resPos2[4]
		-- {['y'] = 0, ['x'] = 0, __size = 2}
	},
	[5] = {
		id = 5,
		card1 = 3631,
		res1 = 'config/big_hero/standby/img_719_dax@.png',
		resScale1 = 2.33,
		resPos1 = __data_t__resPos1[5],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_dax.png',
		posRes1 = 'common/txt/txt_dw_dax.png',
		resPos2 = __data_t__resPos2[5]
		-- {['y'] = 0, ['x'] = 0, __size = 2}
	},
	[6] = {
		id = 6,
		card1 = 1971,
		res1 = 'config/big_hero/normal/img_383_gld@.png',
		resScale1 = 2.618,
		resPos1 = __data_t__resPos1[6],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_gld.png',
		posRes1 = 'common/txt/txt_dw_gld.png',
		resPos2 = __data_t__resPos2[6]
		-- {['y'] = 0, ['x'] = 0, __size = 2}
	},
	[7] = {
		id = 7,
		card1 = 1981,
		res1 = 'config/big_hero/normal/img_384_lkz@.png',
		resScale1 = 2.618,
		resPos1 = __data_t__resPos1[7],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_lkz.png',
		posRes1 = 'common/txt/txt_dw_lkz.png',
		resPos2 = __data_t__resPos2[7]
		-- {['y'] = 0, ['x'] = 0, __size = 2}
	},
	[8] = {
		id = 8,
		card1 = 1261,
		res1 = 'config/big_hero/normal/img_249_lqy@.png',
		resScale1 = 2.618,
		resPos1 = __data_t__resPos1[8],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_lqy.png',
		posRes1 = 'common/txt/txt_dw_lqy.png',
		resPos2 = __data_t__resPos2[8]
		-- {['y'] = 0, ['x'] = 0, __size = 2}
	},
	[9] = {
		id = 9,
		card1 = 2431,
		res1 = 'config/big_hero/normal/img_491_dkly@.png',
		resScale1 = 1.6,
		resPos1 = __data_t__resPos1[9],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_dkly.png',
		posRes1 = 'common/txt/txt_dw_dkly.png',
		card2 = 3631,
		res2 = 'config/big_hero/standby/img_719_dax@.png',
		resScale2 = 2.33,
		resPos2 = __data_t__resPos2[9],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_dax.png',
		posRes2 = 'common/txt/txt_dw_dax.png'
	},
	[10] = {
		id = 10,
		card1 = 2381,
		res1 = 'config/big_hero/normal/img_486_ljqks@.png',
		resScale1 = 2.33,
		resPos1 = __data_t__resPos1[10],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_ljqks.png',
		posRes1 = 'common/txt/txt_dw_ljqks.png',
		card2 = 1261,
		res2 = 'config/big_hero/normal/img_249_lqy@.png',
		resScale2 = 2.14,
		resPos2 = __data_t__resPos2[10],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_lqy.png',
		posRes2 = 'common/txt/txt_dw_lqy.png'
	},
	[11] = {
		id = 11,
		card1 = 1981,
		res1 = 'config/big_hero/normal/img_384_lkz@.png',
		resScale1 = 2.33,
		resPos1 = __data_t__resPos1[11],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_lkz.png',
		posRes1 = 'common/txt/txt_dw_lkz.png',
		card2 = 2351,
		res2 = 'config/big_hero/normal/img_483_dylk@.png',
		resScale2 = 2.33,
		resPos2 = __data_t__resPos2[11],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_dylk.png',
		posRes2 = 'common/txt/txt_dw_dylk.png'
	},
	[12] = {
		id = 12,
		card1 = 1961,
		res1 = 'config/big_hero/normal/img_382_gok@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[12],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_gok.png',
		posRes1 = 'common/txt/txt_dw_gok.png',
		card2 = 2361,
		res2 = 'config/big_hero/normal/img_484_plqy@.png',
		resScale2 = 2.33,
		resPos2 = __data_t__resPos2[12],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_plqy.png',
		posRes2 = 'common/txt/txt_dw_plqy.png'
	},
	[13] = {
		id = 13,
		card1 = 1971,
		res1 = 'config/big_hero/normal/img_383_gld@.png',
		resScale1 = 2.618,
		resPos1 = __data_t__resPos1[13],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_gld.png',
		posRes1 = 'common/txt/txt_dw_gld.png',
		card2 = 3631,
		res2 = 'config/big_hero/standby/img_719_dax@.png',
		resScale2 = 2.33,
		resPos2 = __data_t__resPos2[13],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_dax.png',
		posRes2 = 'common/txt/txt_dw_dax.png'
	},
	[14] = {
		id = 14,
		card1 = 2391,
		res1 = 'config/big_hero/normal/img_487_qldnsxt@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[14],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_qldn.png',
		posRes1 = 'common/txt/txt_dw_qldn.png',
		card2 = 2431,
		res2 = 'config/big_hero/normal/img_491_dkly@.png',
		resScale2 = 1.6,
		resPos2 = __data_t__resPos2[14],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_dkly.png',
		posRes2 = 'common/txt/txt_dw_dkly.png'
	},
	[15] = {
		id = 15,
		card1 = 2441,
		res1 = 'config/big_hero/normal/img_492_xm@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[15],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_xm.png',
		posRes1 = 'common/txt/txt_dw_xm.png',
		card2 = 2381,
		res2 = 'config/big_hero/normal/img_486_ljqks@.png',
		resScale2 = 2.33,
		resPos2 = __data_t__resPos2[15],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_ljqks.png',
		posRes2 = 'common/txt/txt_dw_ljqks.png'
	},
	[16] = {
		id = 16,
		card1 = 1981,
		res1 = 'config/big_hero/normal/img_384_lkz@.png',
		resScale1 = 2.33,
		resPos1 = __data_t__resPos1[16],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_lkz.png',
		posRes1 = 'common/txt/txt_dw_lkz.png',
		card2 = 1261,
		res2 = 'config/big_hero/normal/img_249_lqy@.png',
		resScale2 = 2.618,
		resPos2 = __data_t__resPos2[16],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_lqy.png',
		posRes2 = 'common/txt/txt_dw_lqy.png'
	},
	[17] = {
		id = 17,
		card1 = 3641,
		res1 = 'config/big_hero/normal/img_720_cjhp@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[17],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_cjhp.png',
		posRes1 = 'common/txt/txt_dw_hp.png',
		card2 = 2351,
		res2 = 'config/big_hero/normal/img_483_dylk@.png',
		resScale2 = 2.33,
		resPos2 = __data_t__resPos2[17],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_dylk.png',
		posRes2 = 'common/txt/txt_dw_dylk.png'
	},
	[18] = {
		id = 18,
		card1 = 3211,
		res1 = 'config/big_hero/normal/img_643_lxlm@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[18],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_lxlm.png',
		posRes1 = 'common/txt/txt_dw_lxlm.png',
		card2 = 2361,
		res2 = 'config/big_hero/normal/img_484_plqy@.png',
		resScale2 = 2.33,
		resPos2 = __data_t__resPos2[18],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_plqy.png',
		posRes2 = 'common/txt/txt_dw_plqy.png'
	},
	[19] = {
		id = 19,
		card1 = 1981,
		res1 = 'config/big_hero/normal/img_384_lkz@.png',
		resScale1 = 2.33,
		resPos1 = __data_t__resPos1[19],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_lkz.png',
		posRes1 = 'common/txt/txt_dw_lkz.png',
		card2 = 2431,
		res2 = 'config/big_hero/normal/img_491_dkly@.png',
		resScale2 = 1.6,
		resPos2 = __data_t__resPos2[19],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_dkly.png',
		posRes2 = 'common/txt/txt_dw_dkly.png'
	},
	[20] = {
		id = 20,
		card1 = 3221,
		res1 = 'config/big_hero/normal/img_644_jklm@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[20],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_jklm.png',
		posRes1 = 'common/txt/txt_dw_jklm.png',
		card2 = 2391,
		res2 = 'config/big_hero/normal/img_487_qldnsxt@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[20],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_qldn.png',
		posRes2 = 'common/txt/txt_dw_qldn.png'
	},
	[21] = {
		id = 21,
		card1 = 2431,
		res1 = 'config/big_hero/normal/img_491_dkly@.png',
		resScale1 = 1.6,
		resPos1 = __data_t__resPos1[21],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_dkly.png',
		posRes1 = 'common/txt/txt_dw_dkly.png',
		card2 = 1971,
		res2 = 'config/big_hero/normal/img_383_gld@.png',
		resScale2 = 2.618,
		resPos2 = __data_t__resPos2[21],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_gld.png',
		posRes2 = 'common/txt/txt_dw_gld.png'
	},
	[22] = {
		id = 22,
		card1 = 1961,
		res1 = 'config/big_hero/normal/img_382_gok@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[22],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_gok.png',
		posRes1 = 'common/txt/txt_dw_gok.png',
		card2 = 2381,
		res2 = 'config/big_hero/normal/img_486_ljqks@.png',
		resScale2 = 2.33,
		resPos2 = __data_t__resPos2[22],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_ljqks.png',
		posRes2 = 'common/txt/txt_dw_ljqks.png'
	},
	[23] = {
		id = 23,
		card1 = 3241,
		res1 = 'config/big_hero/normal/img_646_qlm@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[23],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_qlm.png',
		posRes1 = 'common/txt/txt_dw_qlm.png',
		card2 = 2441,
		res2 = 'config/big_hero/normal/img_492_xm@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[23],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_xm.png',
		posRes2 = 'common/txt/txt_dw_xm.png'
	},
	[24] = {
		id = 24,
		card1 = 2381,
		res1 = 'config/big_hero/normal/img_486_ljqks@.png',
		resScale1 = 2.33,
		resPos1 = __data_t__resPos1[24],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_ljqks.png',
		posRes1 = 'common/txt/txt_dw_ljqks.png',
		card2 = 3631,
		res2 = 'config/big_hero/standby/img_719_dax@.png',
		resScale2 = 2.33,
		resPos2 = __data_t__resPos2[24],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_dax.png',
		posRes2 = 'common/txt/txt_dw_dax.png'
	},
	[25] = {
		id = 25,
		card1 = 1961,
		res1 = 'config/big_hero/normal/img_382_gok@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[25],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_gok.png',
		posRes1 = 'common/txt/txt_dw_gok.png',
		card2 = 1261,
		res2 = 'config/big_hero/normal/img_249_lqy@.png',
		resScale2 = 2.618,
		resPos2 = __data_t__resPos2[25],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_lqy.png',
		posRes2 = 'common/txt/txt_dw_lqy.png'
	},
	[26] = {
		id = 26,
		card1 = 3261,
		res1 = 'config/big_hero/normal/img_648_mlyt@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[26],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_mlyt.png',
		posRes1 = 'common/txt/txt_dw_mlyt.png',
		card2 = 3641,
		res2 = 'config/big_hero/normal/img_720_cjhp@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[26],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_cjhp.png',
		posRes2 = 'common/txt/txt_dw_hp.png'
	},
	[27] = {
		id = 27,
		card1 = 1991,
		res1 = 'config/big_hero/normal/img_385_jlq@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[27],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_jlq.png',
		posRes1 = 'common/txt/txt_dw_jlq.png',
		card2 = 3211,
		res2 = 'config/big_hero/normal/img_643_lxlm@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[27],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_lxlm.png',
		posRes2 = 'common/txt/txt_dw_lxlm.png'
	},
	[28] = {
		id = 28,
		card1 = 3631,
		res1 = 'config/big_hero/standby/img_719_dax@.png',
		resScale1 = 2.33,
		resPos1 = __data_t__resPos1[28],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_dax.png',
		posRes1 = 'common/txt/txt_dw_dax.png',
		card2 = 1261,
		res2 = 'config/big_hero/normal/img_249_lqy@.png',
		resScale2 = 2.14,
		resPos2 = __data_t__resPos2[28],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_lqy.png',
		posRes2 = 'common/txt/txt_dw_lqy.png'
	},
	[29] = {
		id = 29,
		card1 = 2361,
		res1 = 'config/big_hero/normal/img_484_plqy@.png',
		resScale1 = 2.33,
		resPos1 = __data_t__resPos1[29],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_plqy.png',
		posRes1 = 'common/txt/txt_dw_plqy.png',
		card2 = 2431,
		res2 = 'config/big_hero/normal/img_491_dkly@.png',
		resScale2 = 1.6,
		resPos2 = __data_t__resPos2[29],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_dkly.png',
		posRes2 = 'common/txt/txt_dw_dkly.png'
	},
	[30] = {
		id = 30,
		card1 = 4171,
		res1 = 'config/big_hero/normal/img_809_mlmt@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[30],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_mlmt.png',
		posRes1 = 'common/txt/txt_dw_mlmt.png',
		card2 = 3221,
		res2 = 'config/big_hero/normal/img_644_jklm@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[30],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_jklm.png',
		posRes2 = 'common/txt/txt_dw_jklm.png'
	},
	[31] = {
		id = 31,
		card1 = 1981,
		res1 = 'config/big_hero/normal/img_384_lkz@.png',
		resScale1 = 2.33,
		resPos1 = __data_t__resPos1[31],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_lkz.png',
		posRes1 = 'common/txt/txt_dw_lkz.png',
		card2 = 1971,
		res2 = 'config/big_hero/normal/img_383_gld@.png',
		resScale2 = 2.618,
		resPos2 = __data_t__resPos2[31],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_gld.png',
		posRes2 = 'common/txt/txt_dw_gld.png'
	},
	[32] = {
		id = 32,
		card1 = 2391,
		res1 = 'config/big_hero/normal/img_487_qldnsxt@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[32],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_qldn.png',
		posRes1 = 'common/txt/txt_dw_qldn.png',
		card2 = 2381,
		res2 = 'config/big_hero/normal/img_486_ljqks@.png',
		resScale2 = 2.33,
		resPos2 = __data_t__resPos2[32],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_ljqks.png',
		posRes2 = 'common/txt/txt_dw_ljqks.png'
	},
	[33] = {
		id = 33,
		card1 = 3611,
		res1 = 'config/big_hero/normal/img_717_ypete@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[33],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_ypete.png',
		posRes1 = 'common/txt/txt_dw_ypete.png',
		card2 = 3241,
		res2 = 'config/big_hero/normal/img_646_qlm@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[33],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_qlm.png',
		posRes2 = 'common/txt/txt_dw_qlm.png'
	},
	[34] = {
		id = 34,
		card1 = 1961,
		res1 = 'config/big_hero/normal/img_382_gok@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[34],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_gok.png',
		posRes1 = 'common/txt/txt_dw_gok.png',
		card2 = 3631,
		res2 = 'config/big_hero/standby/img_719_dax@.png',
		resScale2 = 2.33,
		resPos2 = __data_t__resPos2[34],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_dax.png',
		posRes2 = 'common/txt/txt_dw_dax.png'
	},
	[35] = {
		id = 35,
		card1 = 2441,
		res1 = 'config/big_hero/normal/img_492_xm@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[35],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_xm.png',
		posRes1 = 'common/txt/txt_dw_xm.png',
		card2 = 2351,
		res2 = 'config/big_hero/normal/img_483_dylk@.png',
		resScale2 = 2.33,
		resPos2 = __data_t__resPos2[35],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_dylk.png',
		posRes2 = 'common/txt/txt_dw_dylk.png'
	},
	[36] = {
		id = 36,
		card1 = 1281,
		res1 = 'config/big_hero/normal/img_251_slb@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[36],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_slb.png',
		posRes1 = 'common/txt/txt_dw_slb.png',
		card2 = 3261,
		res2 = 'config/big_hero/normal/img_648_mlyt@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[36],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_mlyt.png',
		posRes2 = 'common/txt/txt_dw_mlyt.png'
	},
	[37] = {
		id = 37,
		card1 = 2431,
		res1 = 'config/big_hero/normal/img_491_dkly@.png',
		resScale1 = 1.6,
		resPos1 = __data_t__resPos1[37],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_dkly.png',
		posRes1 = 'common/txt/txt_dw_dkly.png',
		resPos2 = __data_t__resPos2[37]
		-- {['y'] = 0, ['x'] = 0, __size = 2}
	},
	[38] = {
		id = 38,
		card1 = 2461,
		res1 = 'config/big_hero/normal/img_494_bktn@.png',
		resScale1 = 1.6,
		resPos1 = __data_t__resPos1[38],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_bktn.png',
		posRes1 = 'common/txt/txt_dw_bktn.png',
		card2 = 2421,
		res2 = 'config/big_hero/normal/img_490_mnf@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[38],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_mnf.png',
		posRes2 = 'common/txt/txt_dw_mnf.png'
	},
	[39] = {
		id = 39,
		card1 = 4111,
		res1 = 'config/big_hero/normal/img_801_mjyn@.png',
		resScale1 = 1.6,
		resPos1 = __data_t__resPos1[39],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_mjyn.png',
		posRes1 = 'common/txt/txt_dw_mjyn.png',
		card2 = 4121,
		res2 = 'config/big_hero/normal/img_802_mxd@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[39],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_mxd.png',
		posRes2 = 'common/txt/txt_dw_mxd.png'
	},
	[40] = {
		id = 40,
		card1 = 3621,
		res1 = 'config/big_hero/normal/img_718_jged100@.png',
		resScale1 = 1.6,
		resPos1 = __data_t__resPos1[40],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_jged.png',
		posRes1 = 'common/txt/txt_dw_jged.png',
		resPos2 = __data_t__resPos2[40]
		-- {['y'] = 0, ['x'] = 0, __size = 2}
	},
	[41] = {
		id = 41,
		card1 = 4161,
		res1 = 'config/big_hero/normal/img_807_jlal@.png',
		resScale1 = 1.6,
		resPos1 = __data_t__resPos1[41],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_jlal.png',
		posRes1 = 'common/txt/txt_dw_jlal.png',
		card2 = 4023,
		res2 = 'config/big_hero/normal/img_791_sejlo@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[41],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_sejlo.png',
		posRes2 = 'common/txt/txt_dw_sejlo.png'
	},
	[42] = {
		id = 42,
		card1 = 4024,
		res1 = 'config/big_hero/normal/img_792_lnyl@.png',
		resScale1 = 1.6,
		resPos1 = __data_t__resPos1[42],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_lnyl.png',
		posRes1 = 'common/txt/txt_dw_lnyl.png',
		card2 = 7101,
		res2 = 'config/big_hero/normal/img_889_zmrt@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[42],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_zmrt.png',
		posRes2 = 'common/txt/txt_dw_zmrt.png'
	},
	[43] = {
		id = 43,
		card1 = 2351,
		res1 = 'config/big_hero/normal/img_483_dylk@.png',
		resScale1 = 2.33,
		resPos1 = __data_t__resPos1[43],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_dylk.png',
		posRes1 = 'common/txt/txt_dw_dylk.png',
		card2 = 1281,
		res2 = 'config/big_hero/normal/img_251_slb@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[43],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_slb.png',
		posRes2 = 'common/txt/txt_dw_slb.png'
	},
	[44] = {
		id = 44,
		card1 = 2381,
		res1 = 'config/big_hero/normal/img_486_ljqks@.png',
		resScale1 = 2.33,
		resPos1 = __data_t__resPos1[44],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_ljqks.png',
		posRes1 = 'common/txt/txt_dw_ljqks.png',
		card2 = 2441,
		res2 = 'config/big_hero/normal/img_492_xm@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[44],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_xm.png',
		posRes2 = 'common/txt/txt_dw_xm.png'
	},
	[45] = {
		id = 45,
		card1 = 1981,
		res1 = 'config/big_hero/normal/img_384_lkz@.png',
		resScale1 = 2.33,
		resPos1 = __data_t__resPos1[45],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_lkz.png',
		posRes1 = 'common/txt/txt_dw_lkz.png',
		card2 = 1961,
		res2 = 'config/big_hero/normal/img_382_gok@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[45],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_gok.png',
		posRes2 = 'common/txt/txt_dw_gok.png'
	},
	[46] = {
		id = 46,
		card1 = 3221,
		res1 = 'config/big_hero/normal/img_644_jklm@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[46],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_jklm.png',
		posRes1 = 'common/txt/txt_dw_jklm.png',
		card2 = 3241,
		res2 = 'config/big_hero/normal/img_646_qlm@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[46],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_qlm.png',
		posRes2 = 'common/txt/txt_dw_qlm.png'
	},
	[47] = {
		id = 47,
		card1 = 3211,
		res1 = 'config/big_hero/normal/img_643_lxlm@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[47],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_lxlm.png',
		posRes1 = 'common/txt/txt_dw_lxlm.png',
		card2 = 1991,
		res2 = 'config/big_hero/normal/img_385_jlq@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[47],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_jlq.png',
		posRes2 = 'common/txt/txt_dw_jlq.png'
	},
	[48] = {
		id = 48,
		card1 = 1261,
		res1 = 'config/big_hero/normal/img_249_lqy@.png',
		resScale1 = 2.618,
		resPos1 = __data_t__resPos1[48],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_lqy.png',
		posRes1 = 'common/txt/txt_dw_lqy.png',
		card2 = 3601,
		res2 = 'config/big_hero/normal/img_716_zenys@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[48],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_zenys.png',
		posRes2 = 'common/txt/txt_dw_zenys.png'
	},
	[49] = {
		id = 49,
		card1 = 1971,
		res1 = 'config/big_hero/normal/img_383_gld@.png',
		resScale1 = 2.618,
		resPos1 = __data_t__resPos1[49],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_gld.png',
		posRes1 = 'common/txt/txt_dw_gld.png',
		card2 = 2461,
		res2 = 'config/big_hero/normal/img_494_bktn@.png',
		resScale2 = 1.6,
		resPos2 = __data_t__resPos2[49],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_bktn.png',
		posRes2 = 'common/txt/txt_dw_bktn.png'
	},
	[50] = {
		id = 50,
		card1 = 3261,
		res1 = 'config/big_hero/normal/img_648_mlyt@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[50],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_mlyt.png',
		posRes1 = 'common/txt/txt_dw_mlyt.png',
		card2 = 3641,
		res2 = 'config/big_hero/normal/img_720_cjhp@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[50],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_cjhp.png',
		posRes2 = 'common/txt/txt_dw_hp.png'
	},
	[51] = {
		id = 51,
		card1 = 4171,
		res1 = 'config/big_hero/normal/img_809_mlmt@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[51],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_mlmt.png',
		posRes1 = 'common/txt/txt_dw_mlmt.png',
		card2 = 3611,
		res2 = 'config/big_hero/normal/img_717_ypete@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[51],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_ypete.png',
		posRes2 = 'common/txt/txt_dw_ypete.png'
	},
	[52] = {
		id = 52,
		card1 = 3631,
		res1 = 'config/big_hero/standby/img_719_dax@.png',
		resScale1 = 2.33,
		resPos1 = __data_t__resPos1[52],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_dax.png',
		posRes1 = 'common/txt/txt_dw_dax.png',
		card2 = 3271,
		res2 = 'config/big_hero/normal/img_649_gnskt@.png',
		resScale2 = 2,
		resPos2 = __data_t__resPos2[52],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_gnskt.png',
		posRes2 = 'common/txt/txt_dw_gnskt.png'
	},
	[53] = {
		id = 53,
		card1 = 2391,
		res1 = 'config/big_hero/normal/img_487_qldnsxt@.png',
		resScale1 = 2,
		resPos1 = __data_t__resPos1[53],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes1 = 'common/txt/txt_qldn.png',
		posRes1 = 'common/txt/txt_dw_qldn.png',
		card2 = 2431,
		res2 = 'config/big_hero/normal/img_491_dkly@.png',
		resScale2 = 1.6,
		resPos2 = __data_t__resPos2[53],
		-- {['y'] = 0, ['x'] = 0, __size = 2}
		titleRes2 = 'common/txt/txt_dkly.png',
		posRes2 = 'common/txt/txt_dw_dkly.png'
	},

	__size = 53,
	__default = {
		__index = {
			resScale1 = 1,
			resPos1 = __data_t__resPos1["default"]	--[[ {['y'] = 0, ['x'] = 0, __size = 2}]],
			titleRes1 = '',
			posRes1 = '',
			resScale2 = 1,
			resPos2 = __data_t__resPos2["default"]	--[[ {['y'] = 0, ['x'] = 0, __size = 2}]],
			titleRes2 = '',
			posRes2 = ''
		}
	}
}
return csv.yunying.draw_limit