--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['server']['merge'] = {
	[1] = {
		id = 1,
		destServer = 'gamemerge.dev.1',
		servers = {'game.dev.19', 'game.dev.20'},
		serverID = 1,
		pwAwardVer = 101,
		randomTowerAwardVer = 101,
		craftAwardVer = 101,
		realityMerge = 1
	},
	[2] = {
		id = 2,
		destServer = 'gamemerge.dev.2',
		servers = {'game.dev.21', 'game.dev.22', 'game.dev.23', 'game.dev.24', 'game.dev.25', 'game.dev.26', 'game.dev.27', 'game.dev.28', 'game.dev.29', 'game.dev.30', 'game.dev.31', 'game.dev.32', 'game.dev.33', 'game.dev.34', 'game.dev.35'},
		serverID = 2,
		pwAwardVer = 101,
		randomTowerAwardVer = 101,
		craftAwardVer = 101,
		realityMerge = 1
	},

	__size = 2,
	__default = {
		__index = {
			servers = {},
			pwAwardVer = 0,
			randomTowerAwardVer = 0,
			craftAwardVer = 0,
			realityMerge = 0
		}
	}
}
return csv.server.merge