--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['gift'] = {
	[1001] = {
		id = 1001,
		name = 'vip111',
		giftType = 1,
		award = {[9205] = 1, ['rmb'] = 5000, [521] = 15, ['card'] = {['id'] = 9003, __size = 1}, __size = 4},
		type = 1001,
		endDate = 20280101
	},
	[1002] = {
		id = 1002,
		name = 'vip222',
		giftType = 1,
		award = {[502] = 30, [30301] = 1, ['rmb'] = 5000, ['card'] = {['id'] = 7001, __size = 1}, __size = 4},
		type = 1002,
		endDate = 20280101
	},
	[1003] = {
		id = 1003,
		name = 'vip333',
		giftType = 1,
		award = {['gold'] = 5000000, [30401] = 1, ['rmb'] = 200000, [521] = 30, ['card'] = {['id'] = 9131, __size = 1}, __size = 5},
		type = 1003,
		endDate = 20280101
	},
	[1004] = {
		id = 1004,
		name = 'vip444',
		giftType = 1,
		award = {[8051] = 1, [501] = 20, ['rmb'] = 5000, ['gold'] = 5000000, [521] = 20, __size = 5},
		type = 1004,
		endDate = 20280101
	},
	[1005] = {
		id = 1005,
		name = 'vip555',
		giftType = 1,
		award = {[519] = 100, ['gold'] = 10000000, ['rmb'] = 5000, [503] = 100, ['card'] = {['id'] = 3304, __size = 1}, __size = 5},
		type = 1005,
		endDate = 20280101
	},
	[1006] = {
		id = 1006,
		name = 'vip666',
		giftType = 1,
		award = {[3031] = 20, [501] = 20, [521] = 80, ['card'] = {['id'] = 9003, __size = 1}, [2153] = 2, __size = 5},
		type = 1006,
		endDate = 20280101
	},
	[1007] = {
		id = 1007,
		name = 'vip777',
		giftType = 1,
		award = {['gold'] = 10000000, ['rmb'] = 5000, [521] = 15, [14] = 500, [6232] = 1, __size = 5},
		type = 1007,
		endDate = 20280101
	},
	[1008] = {
		id = 1008,
		name = 'vip888',
		giftType = 1,
		award = {[7325] = 5, [8161] = 5, ['rmb'] = 10000, [3031] = 10, [521] = 20, __size = 5},
		type = 1008,
		endDate = 20280101
	},
	[1009] = {
		id = 1009,
		name = 'vip999',
		giftType = 1,
		award = {[902] = 50, [14] = 200, ['gold'] = 5000000, [520] = 50, [521] = 10, ['rmb'] = 5000, [500] = 10, __size = 7},
		type = 1009,
		endDate = 20280101
	},
	[1010] = {
		id = 1010,
		name = 'richang',
		award = {['rmb'] = 2000, [521] = 5, [500] = 1, __size = 3},
		numMax = 99999,
		type = 1010,
		typeMax = 99999,
		endDate = 20280101
	},

	__size = 10,
	__default = {
		__index = {
			name = '',
			giftType = 0,
			award = {__size = 0},
			numMax = 1,
			type = 1,
			typeMax = 1,
			endDate = 20170101,
			languages = {'cn', 'tw', 'en', 'vn', 'th', 'kr', 'pt'},
			validRoleCreatedDateRange = {20160101, 20990101}
		}
	}
}
return csv.gift