--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['pwpoint_award'] = {
	[1] = {
		id = 1,
		needPoint = 20,
		award = {['gold'] = 30000, [521] = 10, ['coin1'] = 100, __size = 3}
	},
	[2] = {
		id = 2,
		needPoint = 18,
		award = {['gold'] = 24000, [515] = 5, ['coin1'] = 80, __size = 3}
	},
	[3] = {
		id = 3,
		needPoint = 16,
		award = {['gold'] = 21000, [515] = 5, ['coin1'] = 60, __size = 3}
	},
	[4] = {
		id = 4,
		needPoint = 14,
		award = {['gold'] = 18000, [502] = 20, ['coin1'] = 60, __size = 3}
	},
	[5] = {
		id = 5,
		needPoint = 12,
		award = {['gold'] = 15000, [515] = 5, ['coin1'] = 60, __size = 3}
	},
	[6] = {
		id = 6,
		needPoint = 10,
		award = {['gold'] = 30000, ['talent_point'] = 2, ['coin1'] = 100, __size = 3}
	},
	[7] = {
		id = 7,
		needPoint = 8,
		award = {['gold'] = 24000, [515] = 2, ['coin1'] = 80, __size = 3}
	},
	[8] = {
		id = 8,
		needPoint = 6,
		award = {['gold'] = 21000, [515] = 2, ['coin1'] = 60, __size = 3}
	},
	[9] = {
		id = 9,
		needPoint = 4,
		award = {['gold'] = 18000, [515] = 2, ['coin1'] = 60, __size = 3}
	},
	[10] = {
		id = 10,
		needPoint = 2,
		award = {['gold'] = 15000, [515] = 2, ['coin1'] = 60, __size = 3}
	},

	__size = 10,
	__default = {
		__index = {
			award = {__size = 0}
		}
	}
}
return csv.pwpoint_award