--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['yunying']['levelfund'] = {
	[1] = {
		id = 1,
		huodongID = 22001,
		needLevel = 15,
		desc = '等级到达15级',
		desc_tw = '等級達到15級',
		desc_en = 'Reach level 15',
		desc_vn = 'Đạt cấp 15',
		desc_kr = '레벨 15 달성',
		desc_pt = 'Nível 15',
		desc_th = 'ถึงเลเวล 15',
		award = {['gold'] = 100000, [12] = 10, ['rmb'] = 200, __size = 3}
	},
	[2] = {
		id = 2,
		huodongID = 22001,
		needLevel = 20,
		desc = '等级到达20级',
		desc_tw = '等級達到20級',
		desc_en = 'Reach level 20',
		desc_vn = 'Đạt cấp 20',
		desc_kr = '레벨 20 달성',
		desc_pt = 'Nível 20',
		desc_th = 'ถึงเลเวล 20',
		award = {['gold'] = 100000, [12] = 10, ['rmb'] = 300, __size = 3}
	},
	[3] = {
		id = 3,
		huodongID = 22001,
		needLevel = 25,
		desc = '等级到达25级',
		desc_tw = '等級達到25級',
		desc_en = 'Reach level 25',
		desc_vn = 'Đạt cấp 25',
		desc_kr = '레벨 25 달성',
		desc_pt = 'Nível 25',
		desc_th = 'ถึงเลเวล 25',
		award = {['gold'] = 100000, [12] = 10, ['rmb'] = 400, __size = 3}
	},
	[4] = {
		id = 4,
		huodongID = 22001,
		needLevel = 30,
		desc = '等级到达30级',
		desc_tw = '等級達到30級',
		desc_en = 'Reach level 30',
		desc_vn = 'Đạt cấp 30',
		desc_kr = '레벨 30 달성',
		desc_pt = 'Nível 30',
		desc_th = 'ถึงเลเวล 30',
		award = {[13] = 10, ['rmb'] = 500, ['gold'] = 100000, __size = 3}
	},
	[5] = {
		id = 5,
		huodongID = 22001,
		needLevel = 35,
		desc = '等级到达35级',
		desc_tw = '等級達到35級',
		desc_en = 'Reach level 35',
		desc_vn = 'Đạt cấp 35',
		desc_kr = '레벨 35 달성',
		desc_pt = 'Nível 35',
		desc_th = 'ถึงเลเวล 35',
		award = {[13] = 10, ['rmb'] = 600, ['gold'] = 100000, __size = 3}
	},
	[6] = {
		id = 6,
		huodongID = 22001,
		needLevel = 40,
		desc = '等级到达40级',
		desc_tw = '等級達到40級',
		desc_en = 'Reach level 40',
		desc_vn = 'Đạt cấp 40',
		desc_kr = '레벨 40 달성',
		desc_pt = 'Nível 40',
		desc_th = 'ถึงเลเวล 40',
		award = {[13] = 10, ['rmb'] = 700, ['gold'] = 200000, __size = 3}
	},
	[7] = {
		id = 7,
		huodongID = 22001,
		needLevel = 45,
		desc = '等级到达45级',
		desc_tw = '等級達到45級',
		desc_en = 'Reach level 45',
		desc_vn = 'Đạt cấp 45',
		desc_kr = '레벨 45 달성',
		desc_pt = 'Nível 45',
		desc_th = 'ถึงเลเวล 45',
		award = {[13] = 10, ['rmb'] = 800, ['gold'] = 200000, __size = 3}
	},
	[8] = {
		id = 8,
		huodongID = 22001,
		needLevel = 50,
		desc = '等级到达50级',
		desc_tw = '等級達到50級',
		desc_en = 'Reach level 50',
		desc_vn = 'Đạt cấp 50',
		desc_kr = '레벨 50 달성',
		desc_pt = 'Nível 50',
		desc_th = 'ถึงเลเวล 50',
		award = {[13] = 10, ['rmb'] = 1900, ['gold'] = 200000, __size = 3}
	},
	[9] = {
		id = 9,
		huodongID = 22001,
		needLevel = 55,
		desc = '等级到达55级',
		desc_tw = '等級達到55級',
		desc_en = 'Reach level 55',
		desc_vn = 'Đạt cấp 55',
		desc_kr = '레벨 55 달성',
		desc_pt = 'Nível 55',
		desc_th = 'ถึงเลเวล 55',
		award = {['gold'] = 200000, ['rmb'] = 2500, [14] = 10, __size = 3}
	},
	[10] = {
		id = 10,
		huodongID = 22001,
		needLevel = 60,
		desc = '等级到达60级',
		desc_tw = '等級達到60級',
		desc_en = 'Reach level 60',
		desc_vn = 'Đạt cấp 60',
		desc_kr = '레벨 60 달성',
		desc_pt = 'Nível 60',
		desc_th = 'ถึงเลเวล 60',
		award = {['gold'] = 200000, ['rmb'] = 3000, [14] = 10, __size = 3}
	},
	[11] = {
		id = 11,
		huodongID = 22001,
		needLevel = 70,
		desc = '等级到达70级',
		desc_tw = '等級達到70級',
		desc_en = 'Reach level 70',
		desc_vn = 'Đạt cấp 70',
		desc_kr = '레벨 70 달성',
		desc_pt = 'Nível 70',
		desc_th = 'ถึงเลเวล 70',
		award = {['gold'] = 300000, ['rmb'] = 4200, [14] = 10, __size = 3}
	},
	[12] = {
		id = 12,
		huodongID = 22001,
		needLevel = 80,
		desc = '等级到达80级',
		desc_tw = '等級達到80級',
		desc_en = 'Reach level 80',
		desc_vn = 'Đạt cấp 80',
		desc_kr = '레벨 80 달성',
		desc_pt = 'Nível 80',
		desc_th = 'ถึงเลเวล 80',
		award = {['gold'] = 300000, ['rmb'] = 5200, [14] = 10, __size = 3}
	},
	[13] = {
		id = 13,
		huodongID = 22001,
		needLevel = 90,
		desc = '等级到达90级',
		desc_tw = '等級達到90級',
		desc_en = 'Reach level 90',
		desc_vn = 'Đạt cấp 90',
		desc_kr = '레벨 90 달성',
		desc_pt = 'Nível 90',
		desc_th = 'ถึงเลเวล 90',
		award = {['gold'] = 300000, ['rmb'] = 7200, [14] = 10, __size = 3}
	},

	__size = 13,
	__default = {
		__index = {
			huodongID = 0,
			needLevel = 1,
			desc = '',
			desc_tw = '',
			desc_en = '',
			desc_vn = '',
			desc_kr = '',
			desc_pt = '',
			desc_th = '',
			award = {__size = 0}
		}
	}
}
return csv.yunying.levelfund