--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['dispatch_task']['fighting_point'] = {
	[1] = {
		id = 1,
		fightingPoint = 500
	},
	[2] = {
		id = 2,
		fightingPoint = 900
	},
	[3] = {
		id = 3,
		fightingPoint = 1200
	},
	[4] = {
		id = 4,
		fightingPoint = 1500
	},
	[5] = {
		id = 5,
		fightingPoint = 1800
	},
	[6] = {
		id = 6,
		fightingPoint = 2100
	},
	[7] = {
		id = 7,
		fightingPoint = 2400
	},
	[8] = {
		id = 8,
		fightingPoint = 2700
	},
	[9] = {
		id = 9,
		fightingPoint = 3000
	},
	[10] = {
		id = 10,
		fightingPoint = 3300
	},
	[11] = {
		id = 11,
		fightingPoint = 3600
	},
	[12] = {
		id = 12,
		fightingPoint = 3900
	},
	[13] = {
		id = 13,
		fightingPoint = 4200
	},
	[14] = {
		id = 14,
		fightingPoint = 4500
	},
	[15] = {
		id = 15,
		fightingPoint = 4800
	},
	[16] = {
		id = 16,
		fightingPoint = 5100
	},
	[17] = {
		id = 17,
		fightingPoint = 5400
	},
	[18] = {
		id = 18,
		fightingPoint = 5700
	},
	[19] = {
		id = 19,
		fightingPoint = 6000
	},
	[20] = {
		id = 20,
		fightingPoint = 6300
	},
	[21] = {
		id = 21,
		fightingPoint = 6600
	},
	[22] = {
		id = 22,
		fightingPoint = 6900
	},
	[23] = {
		id = 23,
		fightingPoint = 7200
	},
	[24] = {
		id = 24,
		fightingPoint = 7500
	},
	[25] = {
		id = 25,
		fightingPoint = 7800
	},
	[26] = {
		id = 26,
		fightingPoint = 8100
	},
	[27] = {
		id = 27,
		fightingPoint = 8400
	},
	[28] = {
		id = 28,
		fightingPoint = 8700
	},
	[29] = {
		id = 29,
		fightingPoint = 9000
	},
	[30] = {
		id = 30,
		fightingPoint = 9300
	},
	[31] = {
		id = 31,
		fightingPoint = 9600
	},
	[32] = {
		id = 32,
		fightingPoint = 9900
	},
	[33] = {
		id = 33,
		fightingPoint = 10200
	},
	[34] = {
		id = 34,
		fightingPoint = 10500
	},
	[35] = {
		id = 35,
		fightingPoint = 10800
	},
	[36] = {
		id = 36,
		fightingPoint = 11100
	},
	[37] = {
		id = 37,
		fightingPoint = 11400
	},
	[38] = {
		id = 38,
		fightingPoint = 11700
	},
	[39] = {
		id = 39,
		fightingPoint = 12000
	},
	[40] = {
		id = 40,
		fightingPoint = 12300
	},
	[41] = {
		id = 41,
		fightingPoint = 12600
	},
	[42] = {
		id = 42,
		fightingPoint = 12900
	},
	[43] = {
		id = 43,
		fightingPoint = 13200
	},
	[44] = {
		id = 44,
		fightingPoint = 13500
	},
	[45] = {
		id = 45,
		fightingPoint = 13800
	},
	[46] = {
		id = 46,
		fightingPoint = 14100
	},
	[47] = {
		id = 47,
		fightingPoint = 14400
	},
	[48] = {
		id = 48,
		fightingPoint = 14700
	},
	[49] = {
		id = 49,
		fightingPoint = 15000
	},
	[50] = {
		id = 50,
		fightingPoint = 15300
	},
	[51] = {
		id = 51,
		fightingPoint = 15600
	},
	[52] = {
		id = 52,
		fightingPoint = 15900
	},
	[53] = {
		id = 53,
		fightingPoint = 16200
	},
	[54] = {
		id = 54,
		fightingPoint = 16500
	},
	[55] = {
		id = 55,
		fightingPoint = 16800
	},
	[56] = {
		id = 56,
		fightingPoint = 17100
	},
	[57] = {
		id = 57,
		fightingPoint = 17400
	},
	[58] = {
		id = 58,
		fightingPoint = 17700
	},
	[59] = {
		id = 59,
		fightingPoint = 18000
	},
	[60] = {
		id = 60,
		fightingPoint = 18300
	},
	[61] = {
		id = 61,
		fightingPoint = 18600
	},
	[62] = {
		id = 62,
		fightingPoint = 18900
	},
	[63] = {
		id = 63,
		fightingPoint = 19200
	},
	[64] = {
		id = 64,
		fightingPoint = 19500
	},
	[65] = {
		id = 65,
		fightingPoint = 19800
	},
	[66] = {
		id = 66,
		fightingPoint = 20100
	},
	[67] = {
		id = 67,
		fightingPoint = 20400
	},
	[68] = {
		id = 68,
		fightingPoint = 20700
	},
	[69] = {
		id = 69,
		fightingPoint = 21000
	},
	[70] = {
		id = 70,
		fightingPoint = 21300
	},
	[71] = {
		id = 71,
		fightingPoint = 21600
	},
	[72] = {
		id = 72,
		fightingPoint = 21900
	},
	[73] = {
		id = 73,
		fightingPoint = 22200
	},
	[74] = {
		id = 74,
		fightingPoint = 22500
	},
	[75] = {
		id = 75,
		fightingPoint = 22800
	},
	[76] = {
		id = 76,
		fightingPoint = 23100
	},
	[77] = {
		id = 77,
		fightingPoint = 23400
	},
	[78] = {
		id = 78,
		fightingPoint = 23700
	},
	[79] = {
		id = 79,
		fightingPoint = 24000
	},
	[80] = {
		id = 80,
		fightingPoint = 24300
	},
	[81] = {
		id = 81,
		fightingPoint = 24600
	},
	[82] = {
		id = 82,
		fightingPoint = 24900
	},
	[83] = {
		id = 83,
		fightingPoint = 25200
	},
	[84] = {
		id = 84,
		fightingPoint = 25500
	},
	[85] = {
		id = 85,
		fightingPoint = 25800
	},
	[86] = {
		id = 86,
		fightingPoint = 26100
	},
	[87] = {
		id = 87,
		fightingPoint = 26400
	},
	[88] = {
		id = 88,
		fightingPoint = 26700
	},
	[89] = {
		id = 89,
		fightingPoint = 27000
	},
	[90] = {
		id = 90,
		fightingPoint = 27300
	},
	[91] = {
		id = 91,
		fightingPoint = 27600
	},
	[92] = {
		id = 92,
		fightingPoint = 27900
	},
	[93] = {
		id = 93,
		fightingPoint = 28200
	},
	[94] = {
		id = 94,
		fightingPoint = 28500
	},
	[95] = {
		id = 95,
		fightingPoint = 28800
	},
	[96] = {
		id = 96,
		fightingPoint = 29100
	},
	[97] = {
		id = 97,
		fightingPoint = 29400
	},
	[98] = {
		id = 98,
		fightingPoint = 29700
	},
	[99] = {
		id = 99,
		fightingPoint = 30000
	},
	[100] = {
		id = 100,
		fightingPoint = 36000
	},
	[101] = {
		id = 101,
		fightingPoint = 42000
	},
	[102] = {
		id = 102,
		fightingPoint = 48000
	},
	[103] = {
		id = 103,
		fightingPoint = 54000
	},
	[104] = {
		id = 104,
		fightingPoint = 60000
	},
	[105] = {
		id = 105,
		fightingPoint = 66000
	},
	[106] = {
		id = 106,
		fightingPoint = 72000
	},
	[107] = {
		id = 107,
		fightingPoint = 78000
	},
	[108] = {
		id = 108,
		fightingPoint = 84000
	},
	[109] = {
		id = 109,
		fightingPoint = 90000
	},
	[110] = {
		id = 110,
		fightingPoint = 96000
	},
	[111] = {
		id = 111,
		fightingPoint = 102000
	},
	[112] = {
		id = 112,
		fightingPoint = 108000
	},
	[113] = {
		id = 113,
		fightingPoint = 114000
	},
	[114] = {
		id = 114,
		fightingPoint = 120000
	},
	[115] = {
		id = 115,
		fightingPoint = 126000
	},
	[116] = {
		id = 116,
		fightingPoint = 132000
	},
	[117] = {
		id = 117,
		fightingPoint = 138000
	},
	[118] = {
		id = 118,
		fightingPoint = 144000
	},
	[119] = {
		id = 119,
		fightingPoint = 150000
	},
	[120] = {
		id = 120,
		fightingPoint = 156000
	},
	[121] = {
		id = 121,
		fightingPoint = 162000
	},
	[122] = {
		id = 122,
		fightingPoint = 168000
	},
	[123] = {
		id = 123,
		fightingPoint = 174000
	},
	[124] = {
		id = 124,
		fightingPoint = 180000
	},
	[125] = {
		id = 125,
		fightingPoint = 186000
	},
	[126] = {
		id = 126,
		fightingPoint = 192000
	},
	[127] = {
		id = 127,
		fightingPoint = 198000
	},
	[128] = {
		id = 128,
		fightingPoint = 204000
	},
	[129] = {
		id = 129,
		fightingPoint = 210000
	},
	[130] = {
		id = 130,
		fightingPoint = 216000
	},
	[131] = {
		id = 131,
		fightingPoint = 222000
	},
	[132] = {
		id = 132,
		fightingPoint = 228000
	},
	[133] = {
		id = 133,
		fightingPoint = 234000
	},
	[134] = {
		id = 134,
		fightingPoint = 240000
	},
	[135] = {
		id = 135,
		fightingPoint = 246000
	},
	[136] = {
		id = 136,
		fightingPoint = 252000
	},
	[137] = {
		id = 137,
		fightingPoint = 258000
	},
	[138] = {
		id = 138,
		fightingPoint = 264000
	},
	[139] = {
		id = 139,
		fightingPoint = 270000
	},
	[140] = {
		id = 140,
		fightingPoint = 276000
	},
	[141] = {
		id = 141,
		fightingPoint = 282000
	},
	[142] = {
		id = 142,
		fightingPoint = 288000
	},
	[143] = {
		id = 143,
		fightingPoint = 294000
	},
	[144] = {
		id = 144,
		fightingPoint = 300000
	},
	[145] = {
		id = 145,
		fightingPoint = 306000
	},
	[146] = {
		id = 146,
		fightingPoint = 312000
	},
	[147] = {
		id = 147,
		fightingPoint = 318000
	},
	[148] = {
		id = 148,
		fightingPoint = 324000
	},
	[149] = {
		id = 149,
		fightingPoint = 330000
	},
	[150] = {
		id = 150,
		fightingPoint = 336000
	},
	[151] = {
		id = 151,
		fightingPoint = 342000
	},
	[152] = {
		id = 152,
		fightingPoint = 348000
	},
	[153] = {
		id = 153,
		fightingPoint = 354000
	},
	[154] = {
		id = 154,
		fightingPoint = 360000
	},
	[155] = {
		id = 155,
		fightingPoint = 366000
	},
	[156] = {
		id = 156,
		fightingPoint = 372000
	},
	[157] = {
		id = 157,
		fightingPoint = 378000
	},
	[158] = {
		id = 158,
		fightingPoint = 384000
	},
	[159] = {
		id = 159,
		fightingPoint = 390000
	},
	[160] = {
		id = 160,
		fightingPoint = 396000
	},
	[161] = {
		id = 161,
		fightingPoint = 402000
	},
	[162] = {
		id = 162,
		fightingPoint = 408000
	},
	[163] = {
		id = 163,
		fightingPoint = 414000
	},
	[164] = {
		id = 164,
		fightingPoint = 420000
	},
	[165] = {
		id = 165,
		fightingPoint = 426000
	},
	[166] = {
		id = 166,
		fightingPoint = 432000
	},
	[167] = {
		id = 167,
		fightingPoint = 438000
	},
	[168] = {
		id = 168,
		fightingPoint = 444000
	},
	[169] = {
		id = 169,
		fightingPoint = 450000
	},
	[170] = {
		id = 170,
		fightingPoint = 456000
	},
	[171] = {
		id = 171,
		fightingPoint = 462000
	},
	[172] = {
		id = 172,
		fightingPoint = 468000
	},
	[173] = {
		id = 173,
		fightingPoint = 474000
	},
	[174] = {
		id = 174,
		fightingPoint = 480000
	},
	[175] = {
		id = 175,
		fightingPoint = 486000
	},
	[176] = {
		id = 176,
		fightingPoint = 492000
	},
	[177] = {
		id = 177,
		fightingPoint = 498000
	},
	[178] = {
		id = 178,
		fightingPoint = 504000
	},
	[179] = {
		id = 179,
		fightingPoint = 510000
	},
	[180] = {
		id = 180,
		fightingPoint = 516000
	},
	[181] = {
		id = 181,
		fightingPoint = 522000
	},
	[182] = {
		id = 182,
		fightingPoint = 528000
	},
	[183] = {
		id = 183,
		fightingPoint = 534000
	},
	[184] = {
		id = 184,
		fightingPoint = 540000
	},
	[185] = {
		id = 185,
		fightingPoint = 546000
	},
	[186] = {
		id = 186,
		fightingPoint = 552000
	},
	[187] = {
		id = 187,
		fightingPoint = 558000
	},
	[188] = {
		id = 188,
		fightingPoint = 564000
	},
	[189] = {
		id = 189,
		fightingPoint = 570000
	},
	[190] = {
		id = 190,
		fightingPoint = 576000
	},
	[191] = {
		id = 191,
		fightingPoint = 582000
	},
	[192] = {
		id = 192,
		fightingPoint = 588000
	},
	[193] = {
		id = 193,
		fightingPoint = 594000
	},
	[194] = {
		id = 194,
		fightingPoint = 600000
	},
	[195] = {
		id = 195,
		fightingPoint = 606000
	},
	[196] = {
		id = 196,
		fightingPoint = 612000
	},
	[197] = {
		id = 197,
		fightingPoint = 618000
	},
	[198] = {
		id = 198,
		fightingPoint = 624000
	},
	[199] = {
		id = 199,
		fightingPoint = 630000
	},
	[200] = {
		id = 200,
		fightingPoint = 636000
	},
	[201] = {
		id = 201,
		fightingPoint = 642000
	},
	[202] = {
		id = 202,
		fightingPoint = 648000
	},
	[203] = {
		id = 203,
		fightingPoint = 654000
	},
	[204] = {
		id = 204,
		fightingPoint = 660000
	},
	[205] = {
		id = 205,
		fightingPoint = 666000
	},
	[206] = {
		id = 206,
		fightingPoint = 672000
	},
	[207] = {
		id = 207,
		fightingPoint = 678000
	},
	[208] = {
		id = 208,
		fightingPoint = 684000
	},
	[209] = {
		id = 209,
		fightingPoint = 690000
	},
	[210] = {
		id = 210,
		fightingPoint = 696000
	},
	[211] = {
		id = 211,
		fightingPoint = 702000
	},
	[212] = {
		id = 212,
		fightingPoint = 708000
	},
	[213] = {
		id = 213,
		fightingPoint = 714000
	},
	[214] = {
		id = 214,
		fightingPoint = 720000
	},
	[215] = {
		id = 215,
		fightingPoint = 726000
	},
	[216] = {
		id = 216,
		fightingPoint = 732000
	},
	[217] = {
		id = 217,
		fightingPoint = 738000
	},
	[218] = {
		id = 218,
		fightingPoint = 744000
	},
	[219] = {
		id = 219,
		fightingPoint = 750000
	},
	[220] = {
		id = 220,
		fightingPoint = 756000
	},
	[221] = {
		id = 221,
		fightingPoint = 762000
	},
	[222] = {
		id = 222,
		fightingPoint = 768000
	},
	[223] = {
		id = 223,
		fightingPoint = 774000
	},
	[224] = {
		id = 224,
		fightingPoint = 780000
	},
	[225] = {
		id = 225,
		fightingPoint = 786000
	},
	[226] = {
		id = 226,
		fightingPoint = 792000
	},
	[227] = {
		id = 227,
		fightingPoint = 798000
	},
	[228] = {
		id = 228,
		fightingPoint = 804000
	},
	[229] = {
		id = 229,
		fightingPoint = 810000
	},
	[230] = {
		id = 230,
		fightingPoint = 816000
	},
	[231] = {
		id = 231,
		fightingPoint = 822000
	},
	[232] = {
		id = 232,
		fightingPoint = 828000
	},
	[233] = {
		id = 233,
		fightingPoint = 834000
	},
	[234] = {
		id = 234,
		fightingPoint = 840000
	},
	[235] = {
		id = 235,
		fightingPoint = 846000
	},
	[236] = {
		id = 236,
		fightingPoint = 852000
	},
	[237] = {
		id = 237,
		fightingPoint = 858000
	},
	[238] = {
		id = 238,
		fightingPoint = 864000
	},
	[239] = {
		id = 239,
		fightingPoint = 870000
	},
	[240] = {
		id = 240,
		fightingPoint = 876000
	},
	[241] = {
		id = 241,
		fightingPoint = 882000
	},
	[242] = {
		id = 242,
		fightingPoint = 888000
	},
	[243] = {
		id = 243,
		fightingPoint = 894000
	},
	[244] = {
		id = 244,
		fightingPoint = 900000
	},
	[245] = {
		id = 245,
		fightingPoint = 906000
	},
	[246] = {
		id = 246,
		fightingPoint = 912000
	},
	[247] = {
		id = 247,
		fightingPoint = 918000
	},
	[248] = {
		id = 248,
		fightingPoint = 924000
	},
	[249] = {
		id = 249,
		fightingPoint = 930000
	},
	[250] = {
		id = 250,
		fightingPoint = 936000
	},

	__size = 250,
	__default = {
		__index = {
			fightingPoint = 10000
		}
	}
}
return csv.dispatch_task.fighting_point