--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['time_speeder'] = {
	[1] = {
		id = 1,
		arg = 30,
		speedAdd = 3
	},
	[2] = {
		id = 2,
		arg = 70,
		speedAdd = 5
	},
	[3] = {
		id = 3,
		arg = 12,
		speedAdd = 9,
		type = 2
	},

	__size = 3,
	__default = {
		__index = {
			arg = 1,
			speedAdd = 0,
			type = 1
		}
	}
}
return csv.time_speeder