--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {__size = 0}, 
	[6] = {1, 250}, 
	[7] = {'cn'}, 
	[21] = {['gold'] = 1002, __size = 1}, 
	[23] = {['rmb'] = 102, __size = 1}, 
	[25] = {['rmb'] = 13, __size = 1}, 
	[27] = {['gold'] = 1003, __size = 1}, 
	[29] = {['rmb'] = 103, __size = 1}, __size = 8}
local __data_t__languages = {
	[24] = __predefine_t__[7],
	[25] = __predefine_t__[7],
	[26] = __predefine_t__[7],
	[27] = __predefine_t__[7],
	[20] = __predefine_t__[7],
	[21] = __predefine_t__[7],
	[22] = __predefine_t__[7],
	[23] = __predefine_t__[7],
	[28] = __predefine_t__[7],
	[29] = __predefine_t__[7],
	[1] = __predefine_t__[7],
	[3] = __predefine_t__[7],
	[2] = __predefine_t__[7],
	[5] = __predefine_t__[7],
	[4] = __predefine_t__[7],
	[7] = __predefine_t__[7],
	[6] = __predefine_t__[7],
	[9] = __predefine_t__[7],
	[8] = __predefine_t__[7],
	[11] = __predefine_t__[7],
	[10] = __predefine_t__[7],
	[13] = __predefine_t__[7],
	[12] = __predefine_t__[7],
	[15] = __predefine_t__[7],
	[14] = __predefine_t__[7],
	[17] = __predefine_t__[7],
	[16] = __predefine_t__[7],
	[19] = __predefine_t__[7],
	[18] = __predefine_t__[7]
}
local __data_t__levelRange = {
	[24] = __predefine_t__[6],
	[25] = __predefine_t__[6],
	[26] = __predefine_t__[6],
	[27] = __predefine_t__[6],
	[20] = __predefine_t__[6],
	[21] = __predefine_t__[6],
	[22] = __predefine_t__[6],
	[23] = __predefine_t__[6],
	[28] = __predefine_t__[6],
	[29] = __predefine_t__[6],
	[1] = __predefine_t__[6],
	[3] = __predefine_t__[6],
	[2] = __predefine_t__[6],
	[5] = __predefine_t__[6],
	[4] = __predefine_t__[6],
	[7] = __predefine_t__[6],
	[6] = __predefine_t__[6],
	[9] = __predefine_t__[6],
	[8] = __predefine_t__[6],
	[11] = __predefine_t__[6],
	[10] = __predefine_t__[6],
	[13] = __predefine_t__[6],
	[12] = __predefine_t__[6],
	[15] = __predefine_t__[6],
	[14] = __predefine_t__[6],
	[17] = __predefine_t__[6],
	[16] = __predefine_t__[6],
	[19] = __predefine_t__[6],
	[18] = __predefine_t__[6]
}
local __data_t__costMap = {
	[11] = __predefine_t__[27],
	[10] = __predefine_t__[25],
	[26] = __predefine_t__[29],
	[12] = __predefine_t__[29],
	[20] = __predefine_t__[25],
	[21] = __predefine_t__[27],
	[22] = __predefine_t__[21],
	[23] = __predefine_t__[23],
	[19] = __predefine_t__[23],
	[18] = __predefine_t__[21],
	[28] = __predefine_t__[27],
	[29] = __predefine_t__[29],
	["default"] = __predefine_t__[1],
	[27] = __predefine_t__[25],
	[25] = __predefine_t__[27],
	[24] = __predefine_t__[25],
	[9] = __predefine_t__[23],
	[8] = __predefine_t__[21]
}
local __data_t__itemMap = {
	["default"] = __predefine_t__[1]
}

csv['town']['home_shop'] = {
	[1] = {
		id = 1,
		itemMap = {[70001] = 1, __size = 1},
		costMap = {['rmb'] = 10, __size = 1},
		levelRange = __data_t__levelRange[1],
		-- {1, 250}
		languages = __data_t__languages[1]
		-- {'cn'}
	},
	[2] = {
		id = 2,
		itemMap = {[70501] = 1, __size = 1},
		costMap = {['gold'] = 1000, __size = 1},
		levelRange = __data_t__levelRange[2],
		-- {1, 250}
		languages = __data_t__languages[2]
		-- {'cn'}
	},
	[3] = {
		id = 3,
		itemMap = {[70502] = 1, __size = 1},
		costMap = {['rmb'] = 100, __size = 1},
		levelRange = __data_t__levelRange[3],
		-- {1, 250}
		languages = __data_t__languages[3]
		-- {'cn'}
	},
	[4] = {
		id = 4,
		itemMap = {[70503] = 1, __size = 1},
		costMap = {['rmb'] = 11, __size = 1},
		levelRange = __data_t__levelRange[4],
		-- {1, 250}
		languages = __data_t__languages[4]
		-- {'cn'}
	},
	[5] = {
		id = 5,
		itemMap = {[75004] = 1, __size = 1},
		costMap = {['gold'] = 1001, __size = 1},
		levelRange = __data_t__levelRange[5],
		-- {1, 250}
		languages = __data_t__languages[5]
		-- {'cn'}
	},
	[6] = {
		id = 6,
		itemMap = {[71001] = 1, __size = 1},
		costMap = {['rmb'] = 101, __size = 1},
		levelRange = __data_t__levelRange[6],
		-- {1, 250}
		languages = __data_t__languages[6]
		-- {'cn'}
	},
	[7] = {
		id = 7,
		itemMap = {[71501] = 1, __size = 1},
		costMap = {['rmb'] = 12, __size = 1},
		levelRange = __data_t__levelRange[7],
		-- {1, 250}
		languages = __data_t__languages[7]
		-- {'cn'}
	},
	[8] = {
		id = 8,
		itemMap = {[71502] = 1, __size = 1},
		costMap = __data_t__costMap[8],
		-- {['gold'] = 1002, __size = 1}
		levelRange = __data_t__levelRange[8],
		-- {1, 250}
		languages = __data_t__languages[8]
		-- {'cn'}
	},
	[9] = {
		id = 9,
		itemMap = {[72001] = 1, __size = 1},
		costMap = __data_t__costMap[9],
		-- {['rmb'] = 102, __size = 1}
		levelRange = __data_t__levelRange[9],
		-- {1, 250}
		languages = __data_t__languages[9]
		-- {'cn'}
	},
	[10] = {
		id = 10,
		itemMap = {[72002] = 1, __size = 1},
		costMap = __data_t__costMap[10],
		-- {['rmb'] = 13, __size = 1}
		levelRange = __data_t__levelRange[10],
		-- {1, 250}
		languages = __data_t__languages[10]
		-- {'cn'}
	},
	[11] = {
		id = 11,
		itemMap = {[72501] = 1, __size = 1},
		costMap = __data_t__costMap[11],
		-- {['gold'] = 1003, __size = 1}
		levelRange = __data_t__levelRange[11],
		-- {1, 250}
		languages = __data_t__languages[11]
		-- {'cn'}
	},
	[12] = {
		id = 12,
		itemMap = {[74001] = 1, __size = 1},
		costMap = __data_t__costMap[12],
		-- {['rmb'] = 103, __size = 1}
		levelRange = __data_t__levelRange[12],
		-- {1, 250}
		languages = __data_t__languages[12]
		-- {'cn'}
	},
	[13] = {
		id = 13,
		itemMap = {[74002] = 1, __size = 1},
		costMap = {['rmb'] = 14, __size = 1},
		levelRange = __data_t__levelRange[13],
		-- {1, 250}
		languages = __data_t__languages[13]
		-- {'cn'}
	},
	[14] = {
		id = 14,
		itemMap = {[74501] = 1, __size = 1},
		costMap = {['gold'] = 1004, __size = 1},
		levelRange = __data_t__levelRange[14],
		-- {1, 250}
		languages = __data_t__languages[14]
		-- {'cn'}
	},
	[15] = {
		id = 15,
		itemMap = {[74502] = 1, __size = 1},
		costMap = {['rmb'] = 104, __size = 1},
		levelRange = __data_t__levelRange[15],
		-- {1, 250}
		languages = __data_t__languages[15]
		-- {'cn'}
	},
	[16] = {
		id = 16,
		itemMap = {[74503] = 1, __size = 1},
		costMap = {['rmb'] = 15, __size = 1},
		levelRange = __data_t__levelRange[16],
		-- {1, 250}
		languages = __data_t__languages[16]
		-- {'cn'}
	},
	[17] = {
		id = 17,
		itemMap = {[75001] = 1, __size = 1},
		costMap = {['gold'] = 1005, __size = 1},
		levelRange = __data_t__levelRange[17],
		-- {1, 250}
		languages = __data_t__languages[17]
		-- {'cn'}
	},
	[18] = {
		id = 18,
		itemMap = {[75002] = 1, __size = 1},
		costMap = __data_t__costMap[18],
		-- {['gold'] = 1002, __size = 1}
		levelRange = __data_t__levelRange[18],
		-- {1, 250}
		languages = __data_t__languages[18]
		-- {'cn'}
	},
	[19] = {
		id = 19,
		itemMap = {[75501] = 1, __size = 1},
		costMap = __data_t__costMap[19],
		-- {['rmb'] = 102, __size = 1}
		levelRange = __data_t__levelRange[19],
		-- {1, 250}
		languages = __data_t__languages[19]
		-- {'cn'}
	},
	[20] = {
		id = 20,
		itemMap = {[75502] = 1, __size = 1},
		costMap = __data_t__costMap[20],
		-- {['rmb'] = 13, __size = 1}
		levelRange = __data_t__levelRange[20],
		-- {1, 250}
		languages = __data_t__languages[20]
		-- {'cn'}
	},
	[21] = {
		id = 21,
		itemMap = {[75503] = 1, __size = 1},
		costMap = __data_t__costMap[21],
		-- {['gold'] = 1003, __size = 1}
		levelRange = __data_t__levelRange[21],
		-- {1, 250}
		languages = __data_t__languages[21]
		-- {'cn'}
	},
	[22] = {
		id = 22,
		itemMap = {[75504] = 1, __size = 1},
		costMap = __data_t__costMap[22],
		-- {['gold'] = 1002, __size = 1}
		levelRange = __data_t__levelRange[22],
		-- {1, 250}
		languages = __data_t__languages[22]
		-- {'cn'}
	},
	[23] = {
		id = 23,
		itemMap = {[76001] = 1, __size = 1},
		costMap = __data_t__costMap[23],
		-- {['rmb'] = 102, __size = 1}
		levelRange = __data_t__levelRange[23],
		-- {1, 250}
		languages = __data_t__languages[23]
		-- {'cn'}
	},
	[24] = {
		id = 24,
		itemMap = {[76002] = 1, __size = 1},
		costMap = __data_t__costMap[24],
		-- {['rmb'] = 13, __size = 1}
		levelRange = __data_t__levelRange[24],
		-- {1, 250}
		languages = __data_t__languages[24]
		-- {'cn'}
	},
	[25] = {
		id = 25,
		itemMap = {[76501] = 1, __size = 1},
		costMap = __data_t__costMap[25],
		-- {['gold'] = 1003, __size = 1}
		levelRange = __data_t__levelRange[25],
		-- {1, 250}
		languages = __data_t__languages[25]
		-- {'cn'}
	},
	[26] = {
		id = 26,
		itemMap = {[76502] = 1, __size = 1},
		costMap = __data_t__costMap[26],
		-- {['rmb'] = 103, __size = 1}
		levelRange = __data_t__levelRange[26],
		-- {1, 250}
		languages = __data_t__languages[26]
		-- {'cn'}
	},
	[27] = {
		id = 27,
		itemMap = {[72003] = 1, __size = 1},
		costMap = __data_t__costMap[27],
		-- {['rmb'] = 13, __size = 1}
		levelRange = __data_t__levelRange[27],
		-- {1, 250}
		languages = __data_t__languages[27]
		-- {'cn'}
	},
	[28] = {
		id = 28,
		itemMap = {[74003] = 1, __size = 1},
		costMap = __data_t__costMap[28],
		-- {['gold'] = 1003, __size = 1}
		levelRange = __data_t__levelRange[28],
		-- {1, 250}
		languages = __data_t__languages[28]
		-- {'cn'}
	},
	[29] = {
		id = 29,
		itemMap = {[75003] = 1, __size = 1},
		costMap = __data_t__costMap[29],
		-- {['rmb'] = 103, __size = 1}
		levelRange = __data_t__levelRange[29],
		-- {1, 250}
		languages = __data_t__languages[29]
		-- {'cn'}
	},

	__size = 29,
	__default = {
		__index = {
			itemMap = __data_t__itemMap["default"]	--[[ {__size = 0}]],
			costMap = __data_t__costMap["default"]	--[[ {__size = 0}]],
			exchangeLimit = -1,
			regainHour = 0,
			beginDate = 0,
			endDate = 20990101,
			vipStart = 0,
			levelRange = {1, 150},
			limitType = 0,
			limitTimes = 0,
			showUnable = false,
			languages = {}
		}
	}
}
return csv.town.home_shop