--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['cross']['craft']['rank'] = {
	[1] = {
		id = 1,
		rankMax = 1,
		award = {[9075] = 1, [6017] = 8, [21971] = 3, ['gold'] = 3000000, [521] = 15, [2260] = 1, [529] = 4888, __size = 7}
	},
	[2] = {
		id = 2,
		rankMax = 2,
		award = {[6017] = 7, [21971] = 2, ['gold'] = 2500000, [521] = 13, [9053] = 1, [529] = 2888, __size = 6}
	},
	[3] = {
		id = 3,
		rankMax = 3,
		award = {[6017] = 6, [21971] = 2, ['gold'] = 2000000, [521] = 10, [9050] = 1, [529] = 1888, __size = 6}
	},
	[4] = {
		id = 4,
		rankMax = 4,
		award = {[521] = 1, ['gold'] = 400000, [529] = 1600, [6017] = 6, [21971] = 2, __size = 5}
	},
	[5] = {
		id = 5,
		rankMax = 8,
		award = {[521] = 1, ['gold'] = 380000, [529] = 1450, [6017] = 5, [21971] = 1, __size = 5}
	},
	[6] = {
		id = 6,
		rankMax = 16,
		award = {[6018] = 1, ['gold'] = 360000, [529] = 1300, [6017] = 4, [521] = 1, __size = 5}
	},
	[7] = {
		id = 7,
		rankMax = 32,
		award = {[6018] = 2, ['gold'] = 340000, [502] = 1, [529] = 1200, [6017] = 3, __size = 5}
	},
	[8] = {
		id = 8,
		rankMax = 64,
		award = {[6018] = 3, ['gold'] = 320000, [502] = 1, [529] = 1100, [6017] = 2, __size = 5}
	},
	[9] = {
		id = 9,
		rankMax = 100,
		award = {[6018] = 4, ['gold'] = 300000, [529] = 1000, [6017] = 1, __size = 4}
	},
	[10] = {
		id = 10,
		rankMax = 200,
		award = {[6018] = 5, ['gold'] = 280000, [529] = 950, __size = 3}
	},
	[11] = {
		id = 11,
		rankMax = 300,
		award = {[6018] = 5, ['gold'] = 260000, [529] = 900, __size = 3}
	},
	[12] = {
		id = 12,
		rankMax = 500,
		award = {[6018] = 5, ['gold'] = 240000, [529] = 850, __size = 3}
	},
	[13] = {
		id = 13,
		rankMax = 1000,
		award = {[6018] = 5, ['gold'] = 220000, [529] = 800, __size = 3}
	},
	[14] = {
		id = 14,
		rankMax = 2000,
		award = {[6018] = 5, ['gold'] = 200000, [529] = 750, __size = 3}
	},
	[15] = {
		id = 15,
		rankMax = 99999,
		award = {[6018] = 5, ['gold'] = 180000, [529] = 700, __size = 3}
	},

	__size = 15,
	__default = {
		__index = {
			award = {__size = 0},
			version = 0
		}
	}
}
return csv.cross.craft.rank