--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['town']['production_base'] = {
	[1] = {
		id = 1,
		baseID = 3,
		level = 1,
		baseType = 1,
		efficient = 2,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 1,
		slotStockAdd = 10,
		slotTimeAdd = '卡槽时间加成'
	},
	[2] = {
		id = 2,
		baseID = 3,
		level = 2,
		baseType = 1,
		efficient = 3,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 1,
		slotStockAdd = 20
	},
	[3] = {
		id = 3,
		baseID = 3,
		level = 3,
		baseType = 1,
		efficient = 4,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 2,
		slotStockAdd = 30
	},
	[4] = {
		id = 4,
		baseID = 3,
		level = 4,
		baseType = 1,
		efficient = 5,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 2,
		slotStockAdd = 40
	},
	[5] = {
		id = 5,
		baseID = 3,
		level = 5,
		baseType = 1,
		efficient = 6,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 3,
		slotStockAdd = 50
	},
	[6] = {
		id = 6,
		baseID = 3,
		level = 6,
		baseType = 1,
		efficient = 7,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 3,
		slotStockAdd = 60
	},
	[7] = {
		id = 7,
		baseID = 3,
		level = 7,
		baseType = 1,
		efficient = 8,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 4,
		slotStockAdd = 70
	},
	[8] = {
		id = 8,
		baseID = 3,
		level = 8,
		baseType = 1,
		efficient = 9,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 4,
		slotStockAdd = 80
	},
	[9] = {
		id = 9,
		baseID = 3,
		level = 9,
		baseType = 1,
		efficient = 10,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 5,
		slotStockAdd = 90
	},
	[10] = {
		id = 10,
		baseID = 3,
		level = 10,
		baseType = 1,
		efficient = 11,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 5,
		slotStockAdd = 100
	},
	[11] = {
		id = 11,
		baseID = 4,
		level = 1,
		baseType = 1,
		efficient = 2,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 1,
		slotStockAdd = 10
	},
	[12] = {
		id = 12,
		baseID = 4,
		level = 2,
		baseType = 1,
		efficient = 3,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 1,
		slotStockAdd = 20
	},
	[13] = {
		id = 13,
		baseID = 4,
		level = 3,
		baseType = 1,
		efficient = 4,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 2,
		slotStockAdd = 30
	},
	[14] = {
		id = 14,
		baseID = 4,
		level = 4,
		baseType = 1,
		efficient = 5,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 2,
		slotStockAdd = 40
	},
	[15] = {
		id = 15,
		baseID = 4,
		level = 5,
		baseType = 1,
		efficient = 6,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 3,
		slotStockAdd = 50
	},
	[16] = {
		id = 16,
		baseID = 4,
		level = 6,
		baseType = 1,
		efficient = 7,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 3,
		slotStockAdd = 60
	},
	[17] = {
		id = 17,
		baseID = 4,
		level = 7,
		baseType = 1,
		efficient = 8,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 4,
		slotStockAdd = 70
	},
	[18] = {
		id = 18,
		baseID = 4,
		level = 8,
		baseType = 1,
		efficient = 9,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 4,
		slotStockAdd = 80
	},
	[19] = {
		id = 19,
		baseID = 4,
		level = 9,
		baseType = 1,
		efficient = 10,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 5,
		slotStockAdd = 90
	},
	[20] = {
		id = 20,
		baseID = 4,
		level = 10,
		baseType = 1,
		efficient = 11,
		inventory = 100,
		energyExpend = 5,
		item = 11,
		slotCapacityAdd = 5,
		slotStockAdd = 100
	},

	__size = 20,
	__default = {
		__index = {
			baseID = 0,
			level = 0,
			baseType = 0,
			efficient = 0,
			inventory = 0,
			energyExpend = 999,
			item = 0,
			orderCostItem = {__size = 0},
			orderCostTime = 99999,
			unlockSeat = 3,
			slotCapacityAdd = 0,
			slotStockAdd = 0,
			slotTimeAdd = ''
		}
	}
}
return csv.town.production_base