--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {__size = 0}, 
	[25] = {['card'] = {['id'] = 9002, __size = 1}, __size = 1}, 
	[71] = {[2103] = 2, ['gold'] = 60000, [21231] = 10, __size = 3}, 
	[208] = {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}, __size = 4}
local __data_t__special = {
	[1165] = __predefine_t__[25],
	[1085] = __predefine_t__[25],
	[215] = __predefine_t__[25],
	[1145] = __predefine_t__[25],
	[1125] = __predefine_t__[25],
	["default"] = __predefine_t__[1],
	[1055] = __predefine_t__[25],
	[1075] = __predefine_t__[25],
	[2035] = __predefine_t__[25],
	[1115] = __predefine_t__[25],
	[2015] = __predefine_t__[25],
	[1015] = __predefine_t__[25],
	[1035] = __predefine_t__[25],
	[1095] = __predefine_t__[25],
	[1175] = __predefine_t__[25],
	[205] = __predefine_t__[25],
	[1155] = __predefine_t__[25],
	[1135] = __predefine_t__[25],
	[225] = __predefine_t__[25],
	[105] = __predefine_t__[25],
	[1025] = __predefine_t__[25],
	[2045] = __predefine_t__[25],
	[1045] = __predefine_t__[25],
	[1185] = __predefine_t__[25],
	[1065] = __predefine_t__[25],
	[2025] = __predefine_t__[25],
	[1105] = __predefine_t__[25],
	[2005] = __predefine_t__[25],
	[1005] = __predefine_t__[25]
}
local __data_t__award = {
	[2903] = __predefine_t__[208],
	[2902] = __predefine_t__[208],
	[2901] = __predefine_t__[208],
	[2900] = __predefine_t__[208],
	[3503] = __predefine_t__[208],
	["default"] = __predefine_t__[1],
	[3001] = __predefine_t__[208],
	[3000] = __predefine_t__[208],
	[3003] = __predefine_t__[208],
	[3002] = __predefine_t__[208],
	[2802] = __predefine_t__[208],
	[2803] = __predefine_t__[208],
	[2800] = __predefine_t__[208],
	[2801] = __predefine_t__[208],
	[3302] = __predefine_t__[208],
	[3303] = __predefine_t__[208],
	[3300] = __predefine_t__[208],
	[3301] = __predefine_t__[208],
	[3100] = __predefine_t__[208],
	[3101] = __predefine_t__[208],
	[3102] = __predefine_t__[208],
	[3103] = __predefine_t__[208],
	[2402] = __predefine_t__[208],
	[2403] = __predefine_t__[208],
	[2400] = __predefine_t__[208],
	[2401] = __predefine_t__[208],
	[2503] = __predefine_t__[208],
	[2502] = __predefine_t__[208],
	[2501] = __predefine_t__[208],
	[2500] = __predefine_t__[208],
	[2600] = __predefine_t__[208],
	[2601] = __predefine_t__[208],
	[2602] = __predefine_t__[208],
	[2603] = __predefine_t__[208],
	[2701] = __predefine_t__[208],
	[2700] = __predefine_t__[208],
	[2703] = __predefine_t__[208],
	[2702] = __predefine_t__[208],
	[3401] = __predefine_t__[208],
	[3400] = __predefine_t__[208],
	[3403] = __predefine_t__[208],
	[3402] = __predefine_t__[208],
	[3203] = __predefine_t__[208],
	[3202] = __predefine_t__[208],
	[3201] = __predefine_t__[208],
	[3200] = __predefine_t__[208],
	[1061] = __predefine_t__[71],
	[3501] = __predefine_t__[208],
	[1063] = __predefine_t__[71],
	[1062] = __predefine_t__[71],
	[1064] = __predefine_t__[71],
	[3500] = __predefine_t__[208],
	[3502] = __predefine_t__[208]
}

csv['yunying']['rechargegift'] = {
	[1] = {
		id = 1,
		huodongID = 4003,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[13] = 6, ['gold'] = 60000, [20261] = 10, __size = 3}
	},
	[2] = {
		id = 2,
		huodongID = 4003,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[13] = 6, ['gold'] = 70000, [20261] = 10, __size = 3}
	},
	[3] = {
		id = 3,
		huodongID = 4003,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[13] = 6, ['gold'] = 80000, [20261] = 10, __size = 3}
	},
	[4] = {
		id = 4,
		huodongID = 4003,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[13] = 6, ['gold'] = 90000, [20261] = 10, __size = 3}
	},
	[5] = {
		id = 5,
		huodongID = 4003,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[13] = 6, ['rmb'] = 10, ['gold'] = 100000, [20261] = 100, __size = 4},
		special = {[20261] = 100, __size = 1}
	},
	[6] = {
		id = 6,
		huodongID = 4004,
		daySum = 1,
		amount = 600,
		desc = '累计充值300钻石',
		award = {[20011] = 10, [13] = 6, ['gold'] = 60000, __size = 3}
	},
	[7] = {
		id = 7,
		huodongID = 4004,
		daySum = 2,
		amount = 600,
		desc = '累计充值300钻石',
		award = {[20011] = 10, [13] = 6, ['gold'] = 70000, __size = 3}
	},
	[8] = {
		id = 8,
		huodongID = 4004,
		daySum = 3,
		amount = 600,
		desc = '累计充值300钻石',
		award = {[20011] = 10, [13] = 6, ['gold'] = 80000, __size = 3}
	},
	[9] = {
		id = 9,
		huodongID = 4004,
		daySum = 4,
		amount = 600,
		desc = '累计充值300钻石',
		award = {[20011] = 10, [13] = 6, ['gold'] = 90000, __size = 3}
	},
	[10] = {
		id = 10,
		huodongID = 4004,
		daySum = 5,
		amount = 600,
		desc = '累计充值300钻石',
		award = {[20011] = 10, [13] = 6, ['gold'] = 90000, ['card'] = {['id'] = 11, __size = 1}, __size = 4},
		special = {['card'] = {['id'] = 11, __size = 1}, __size = 1}
	},
	[11] = {
		id = 11,
		huodongID = 4005,
		daySum = 1,
		amount = 60,
		desc = '累计充值300钻石',
		award = {[13] = 6, [20031] = 10, ['gold'] = 60000, __size = 3}
	},
	[12] = {
		id = 12,
		huodongID = 4005,
		daySum = 2,
		amount = 60,
		desc = '累计充值300钻石',
		award = {[13] = 6, [20031] = 10, ['gold'] = 70000, __size = 3}
	},
	[13] = {
		id = 13,
		huodongID = 4005,
		daySum = 3,
		amount = 60,
		desc = '累计充值300钻石',
		award = {[13] = 6, [20031] = 10, ['gold'] = 80000, __size = 3}
	},
	[14] = {
		id = 14,
		huodongID = 4005,
		daySum = 4,
		amount = 60,
		desc = '累计充值300钻石',
		award = {[13] = 6, [20031] = 10, ['gold'] = 90000, __size = 3}
	},
	[15] = {
		id = 15,
		huodongID = 4005,
		daySum = 5,
		amount = 60,
		desc = '累计充值300钻石',
		award = {[13] = 6, [20031] = 100, ['rmb'] = 10, ['gold'] = 100000, __size = 4},
		special = {[20031] = 100, __size = 1}
	},
	[101] = {
		id = 101,
		huodongID = 4011,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[20591] = 10, ['gold'] = 60000, [516] = 6, __size = 3}
	},
	[102] = {
		id = 102,
		huodongID = 4011,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[20591] = 10, ['gold'] = 70000, [516] = 6, __size = 3}
	},
	[103] = {
		id = 103,
		huodongID = 4011,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[20591] = 10, ['gold'] = 80000, [516] = 6, __size = 3}
	},
	[104] = {
		id = 104,
		huodongID = 4011,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[20591] = 10, ['gold'] = 90000, [516] = 6, __size = 3}
	},
	[105] = {
		id = 105,
		huodongID = 4011,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[20591] = 10, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, [516] = 6, __size = 4},
		special = __data_t__special[105]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[201] = {
		id = 201,
		huodongID = 4012,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[21291] = 10, [2103] = 2, ['gold'] = 60000, __size = 3}
	},
	[202] = {
		id = 202,
		huodongID = 4012,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[21291] = 10, [2103] = 2, ['gold'] = 70000, __size = 3}
	},
	[203] = {
		id = 203,
		huodongID = 4012,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[21291] = 10, [2103] = 2, ['gold'] = 80000, __size = 3}
	},
	[204] = {
		id = 204,
		huodongID = 4012,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[21291] = 10, [2103] = 2, ['gold'] = 90000, __size = 3}
	},
	[205] = {
		id = 205,
		huodongID = 4012,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[21291] = 10, [2103] = 2, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[205]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[211] = {
		id = 211,
		huodongID = 4013,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 60000, [21421] = 10, __size = 3}
	},
	[212] = {
		id = 212,
		huodongID = 4013,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 70000, [21421] = 10, __size = 3}
	},
	[213] = {
		id = 213,
		huodongID = 4013,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 80000, [21421] = 10, __size = 3}
	},
	[214] = {
		id = 214,
		huodongID = 4013,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 90000, [21421] = 10, __size = 3}
	},
	[215] = {
		id = 215,
		huodongID = 4013,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, [21421] = 10, __size = 4},
		special = __data_t__special[215]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[221] = {
		id = 221,
		huodongID = 4014,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['gold'] = 60000, [21311] = 10, [516] = 6, __size = 3}
	},
	[222] = {
		id = 222,
		huodongID = 4014,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['gold'] = 70000, [21311] = 10, [516] = 6, __size = 3}
	},
	[223] = {
		id = 223,
		huodongID = 4014,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['gold'] = 80000, [21311] = 10, [516] = 6, __size = 3}
	},
	[224] = {
		id = 224,
		huodongID = 4014,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['gold'] = 90000, [21311] = 10, [516] = 6, __size = 3}
	},
	[225] = {
		id = 225,
		huodongID = 4014,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['gold'] = 100000, [21311] = 10, ['card'] = {['id'] = 9002, __size = 1}, [516] = 6, __size = 4},
		special = __data_t__special[225]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1001] = {
		id = 1001,
		huodongID = 4101,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[20731] = 10, [2103] = 2, ['gold'] = 60000, __size = 3}
	},
	[1002] = {
		id = 1002,
		huodongID = 4101,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[20731] = 10, [2103] = 2, ['gold'] = 70000, __size = 3}
	},
	[1003] = {
		id = 1003,
		huodongID = 4101,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[20731] = 10, [2103] = 2, ['gold'] = 80000, __size = 3}
	},
	[1004] = {
		id = 1004,
		huodongID = 4101,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[20731] = 10, [2103] = 2, ['gold'] = 90000, __size = 3}
	},
	[1005] = {
		id = 1005,
		huodongID = 4101,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[20731] = 10, [2103] = 2, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[1005]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1011] = {
		id = 1011,
		huodongID = 4102,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [23541] = 10, ['gold'] = 60000, __size = 3}
	},
	[1012] = {
		id = 1012,
		huodongID = 4102,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [23541] = 10, ['gold'] = 70000, __size = 3}
	},
	[1013] = {
		id = 1013,
		huodongID = 4102,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [23541] = 10, ['gold'] = 80000, __size = 3}
	},
	[1014] = {
		id = 1014,
		huodongID = 4102,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [23541] = 10, ['gold'] = 90000, __size = 3}
	},
	[1015] = {
		id = 1015,
		huodongID = 4102,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [23541] = 10, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[1015]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1021] = {
		id = 1021,
		huodongID = 4103,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20391] = 10, ['gold'] = 60000, __size = 3}
	},
	[1022] = {
		id = 1022,
		huodongID = 4103,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20391] = 10, ['gold'] = 70000, __size = 3}
	},
	[1023] = {
		id = 1023,
		huodongID = 4103,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20391] = 10, ['gold'] = 80000, __size = 3}
	},
	[1024] = {
		id = 1024,
		huodongID = 4103,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20391] = 10, ['gold'] = 90000, __size = 3}
	},
	[1025] = {
		id = 1025,
		huodongID = 4103,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20391] = 10, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[1025]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1031] = {
		id = 1031,
		huodongID = 4104,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 60000, [21241] = 10, __size = 3}
	},
	[1032] = {
		id = 1032,
		huodongID = 4104,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 70000, [21241] = 10, __size = 3}
	},
	[1033] = {
		id = 1033,
		huodongID = 4104,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 80000, [21241] = 10, __size = 3}
	},
	[1034] = {
		id = 1034,
		huodongID = 4104,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 90000, [21241] = 10, __size = 3}
	},
	[1035] = {
		id = 1035,
		huodongID = 4104,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, [21241] = 10, __size = 4},
		special = __data_t__special[1035]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1041] = {
		id = 1041,
		huodongID = 4105,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 60000, [21391] = 10, __size = 3}
	},
	[1042] = {
		id = 1042,
		huodongID = 4105,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 70000, [21391] = 10, __size = 3}
	},
	[1043] = {
		id = 1043,
		huodongID = 4105,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 80000, [21391] = 10, __size = 3}
	},
	[1044] = {
		id = 1044,
		huodongID = 4105,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 90000, [21391] = 10, __size = 3}
	},
	[1045] = {
		id = 1045,
		huodongID = 4105,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, [21391] = 10, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[1045]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1051] = {
		id = 1051,
		huodongID = 4106,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 60000, [20721] = 10, __size = 3}
	},
	[1052] = {
		id = 1052,
		huodongID = 4106,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 70000, [20721] = 10, __size = 3}
	},
	[1053] = {
		id = 1053,
		huodongID = 4106,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 80000, [20721] = 10, __size = 3}
	},
	[1054] = {
		id = 1054,
		huodongID = 4106,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 90000, [20721] = 10, __size = 3}
	},
	[1055] = {
		id = 1055,
		huodongID = 4106,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, [20721] = 10, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[1055]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1061] = {
		id = 1061,
		huodongID = 4107,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[1061]
		-- {[2103] = 2, ['gold'] = 60000, [21231] = 10, __size = 3}
	},
	[1062] = {
		id = 1062,
		huodongID = 4107,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[1062]
		-- {[2103] = 2, ['gold'] = 60000, [21231] = 10, __size = 3}
	},
	[1063] = {
		id = 1063,
		huodongID = 4107,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[1063]
		-- {[2103] = 2, ['gold'] = 60000, [21231] = 10, __size = 3}
	},
	[1064] = {
		id = 1064,
		huodongID = 4107,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[1064]
		-- {[2103] = 2, ['gold'] = 60000, [21231] = 10, __size = 3}
	},
	[1065] = {
		id = 1065,
		huodongID = 4107,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, [21231] = 10, __size = 4},
		special = __data_t__special[1065]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1071] = {
		id = 1071,
		huodongID = 4108,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20601] = 10, ['gold'] = 60000, __size = 3}
	},
	[1072] = {
		id = 1072,
		huodongID = 4108,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20601] = 10, ['gold'] = 70000, __size = 3}
	},
	[1073] = {
		id = 1073,
		huodongID = 4108,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20601] = 10, ['gold'] = 80000, __size = 3}
	},
	[1074] = {
		id = 1074,
		huodongID = 4108,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20601] = 10, ['gold'] = 90000, __size = 3}
	},
	[1075] = {
		id = 1075,
		huodongID = 4108,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20601] = 10, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[1075]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1081] = {
		id = 1081,
		huodongID = 4109,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20571] = 10, ['gold'] = 60000, __size = 3}
	},
	[1082] = {
		id = 1082,
		huodongID = 4109,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20571] = 10, ['gold'] = 70000, __size = 3}
	},
	[1083] = {
		id = 1083,
		huodongID = 4109,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20571] = 10, ['gold'] = 80000, __size = 3}
	},
	[1084] = {
		id = 1084,
		huodongID = 4109,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20571] = 10, ['gold'] = 90000, __size = 3}
	},
	[1085] = {
		id = 1085,
		huodongID = 4109,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20571] = 10, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[1085]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1091] = {
		id = 1091,
		huodongID = 4110,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[20241] = 10, [2103] = 2, ['gold'] = 60000, __size = 3}
	},
	[1092] = {
		id = 1092,
		huodongID = 4110,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[20241] = 10, [2103] = 2, ['gold'] = 70000, __size = 3}
	},
	[1093] = {
		id = 1093,
		huodongID = 4110,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[20241] = 10, [2103] = 2, ['gold'] = 80000, __size = 3}
	},
	[1094] = {
		id = 1094,
		huodongID = 4110,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[20241] = 10, [2103] = 2, ['gold'] = 90000, __size = 3}
	},
	[1095] = {
		id = 1095,
		huodongID = 4110,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[20241] = 10, [2103] = 2, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[1095]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1101] = {
		id = 1101,
		huodongID = 4111,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 60000, [20741] = 10, __size = 3}
	},
	[1102] = {
		id = 1102,
		huodongID = 4111,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 70000, [20741] = 10, __size = 3}
	},
	[1103] = {
		id = 1103,
		huodongID = 4111,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 80000, [20741] = 10, __size = 3}
	},
	[1104] = {
		id = 1104,
		huodongID = 4111,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 90000, [20741] = 10, __size = 3}
	},
	[1105] = {
		id = 1105,
		huodongID = 4111,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, [20741] = 10, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[1105]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1111] = {
		id = 1111,
		huodongID = 4112,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [21081] = 10, ['gold'] = 60000, __size = 3}
	},
	[1112] = {
		id = 1112,
		huodongID = 4112,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [21081] = 10, ['gold'] = 70000, __size = 3}
	},
	[1113] = {
		id = 1113,
		huodongID = 4112,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [21081] = 10, ['gold'] = 80000, __size = 3}
	},
	[1114] = {
		id = 1114,
		huodongID = 4112,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [21081] = 10, ['gold'] = 90000, __size = 3}
	},
	[1115] = {
		id = 1115,
		huodongID = 4112,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [21081] = 10, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[1115]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1121] = {
		id = 1121,
		huodongID = 4113,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [21221] = 10, ['gold'] = 60000, __size = 3}
	},
	[1122] = {
		id = 1122,
		huodongID = 4113,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [21221] = 10, ['gold'] = 70000, __size = 3}
	},
	[1123] = {
		id = 1123,
		huodongID = 4113,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [21221] = 10, ['gold'] = 80000, __size = 3}
	},
	[1124] = {
		id = 1124,
		huodongID = 4113,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [21221] = 10, ['gold'] = 90000, __size = 3}
	},
	[1125] = {
		id = 1125,
		huodongID = 4113,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [21221] = 10, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[1125]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1131] = {
		id = 1131,
		huodongID = 4114,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 60000, [20491] = 10, __size = 3}
	},
	[1132] = {
		id = 1132,
		huodongID = 4114,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 70000, [20491] = 10, __size = 3}
	},
	[1133] = {
		id = 1133,
		huodongID = 4114,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 80000, [20491] = 10, __size = 3}
	},
	[1134] = {
		id = 1134,
		huodongID = 4114,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 90000, [20491] = 10, __size = 3}
	},
	[1135] = {
		id = 1135,
		huodongID = 4114,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, [20491] = 10, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[1135]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1141] = {
		id = 1141,
		huodongID = 4115,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 60000, [21501] = 10, __size = 3}
	},
	[1142] = {
		id = 1142,
		huodongID = 4115,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 70000, [21501] = 10, __size = 3}
	},
	[1143] = {
		id = 1143,
		huodongID = 4115,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 80000, [21501] = 10, __size = 3}
	},
	[1144] = {
		id = 1144,
		huodongID = 4115,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 90000, [21501] = 10, __size = 3}
	},
	[1145] = {
		id = 1145,
		huodongID = 4115,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, [21501] = 10, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[1145]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1151] = {
		id = 1151,
		huodongID = 4116,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 60000, [23001] = 10, __size = 3}
	},
	[1152] = {
		id = 1152,
		huodongID = 4116,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 70000, [23001] = 10, __size = 3}
	},
	[1153] = {
		id = 1153,
		huodongID = 4116,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 80000, [23001] = 10, __size = 3}
	},
	[1154] = {
		id = 1154,
		huodongID = 4116,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 90000, [23001] = 10, __size = 3}
	},
	[1155] = {
		id = 1155,
		huodongID = 4116,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, [23001] = 10, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[1155]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1161] = {
		id = 1161,
		huodongID = 4117,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 60000, [21251] = 10, __size = 3}
	},
	[1162] = {
		id = 1162,
		huodongID = 4117,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 70000, [21251] = 10, __size = 3}
	},
	[1163] = {
		id = 1163,
		huodongID = 4117,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 80000, [21251] = 10, __size = 3}
	},
	[1164] = {
		id = 1164,
		huodongID = 4117,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 90000, [21251] = 10, __size = 3}
	},
	[1165] = {
		id = 1165,
		huodongID = 4117,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, [21251] = 10, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[1165]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1171] = {
		id = 1171,
		huodongID = 4118,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [23021] = 10, ['gold'] = 60000, __size = 3}
	},
	[1172] = {
		id = 1172,
		huodongID = 4118,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [23021] = 10, ['gold'] = 70000, __size = 3}
	},
	[1173] = {
		id = 1173,
		huodongID = 4118,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [23021] = 10, ['gold'] = 80000, __size = 3}
	},
	[1174] = {
		id = 1174,
		huodongID = 4118,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [23021] = 10, ['gold'] = 90000, __size = 3}
	},
	[1175] = {
		id = 1175,
		huodongID = 4118,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [23021] = 10, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[1175]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[1181] = {
		id = 1181,
		huodongID = 4119,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20631] = 10, ['gold'] = 60000, __size = 3}
	},
	[1182] = {
		id = 1182,
		huodongID = 4119,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20631] = 10, ['gold'] = 70000, __size = 3}
	},
	[1183] = {
		id = 1183,
		huodongID = 4119,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20631] = 10, ['gold'] = 80000, __size = 3}
	},
	[1184] = {
		id = 1184,
		huodongID = 4119,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20631] = 10, ['gold'] = 90000, __size = 3}
	},
	[1185] = {
		id = 1185,
		huodongID = 4119,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [20631] = 10, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[1185]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[2001] = {
		id = 2001,
		huodongID = 4201,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 60000, [7400] = 10, __size = 3}
	},
	[2002] = {
		id = 2002,
		huodongID = 4201,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 70000, [7400] = 10, __size = 3}
	},
	[2003] = {
		id = 2003,
		huodongID = 4201,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 80000, [7400] = 10, __size = 3}
	},
	[2004] = {
		id = 2004,
		huodongID = 4201,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 90000, [7400] = 10, __size = 3}
	},
	[2005] = {
		id = 2005,
		huodongID = 4201,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, [7400] = 10, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[2005]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[2011] = {
		id = 2011,
		huodongID = 4202,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 60000, [7401] = 10, __size = 3}
	},
	[2012] = {
		id = 2012,
		huodongID = 4202,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 70000, [7401] = 10, __size = 3}
	},
	[2013] = {
		id = 2013,
		huodongID = 4202,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 80000, [7401] = 10, __size = 3}
	},
	[2014] = {
		id = 2014,
		huodongID = 4202,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 90000, [7401] = 10, __size = 3}
	},
	[2015] = {
		id = 2015,
		huodongID = 4202,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, [7401] = 10, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[2015]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[2021] = {
		id = 2021,
		huodongID = 4203,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 60000, [7402] = 10, __size = 3}
	},
	[2022] = {
		id = 2022,
		huodongID = 4203,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 70000, [7402] = 10, __size = 3}
	},
	[2023] = {
		id = 2023,
		huodongID = 4203,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 80000, [7402] = 10, __size = 3}
	},
	[2024] = {
		id = 2024,
		huodongID = 4203,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 90000, [7402] = 10, __size = 3}
	},
	[2025] = {
		id = 2025,
		huodongID = 4203,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, [7402] = 10, __size = 4},
		special = __data_t__special[2025]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[2031] = {
		id = 2031,
		huodongID = 4204,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 60000, [7403] = 10, __size = 3}
	},
	[2032] = {
		id = 2032,
		huodongID = 4204,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 70000, [7403] = 10, __size = 3}
	},
	[2033] = {
		id = 2033,
		huodongID = 4204,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 80000, [7403] = 10, __size = 3}
	},
	[2034] = {
		id = 2034,
		huodongID = 4204,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 90000, [7403] = 10, __size = 3}
	},
	[2035] = {
		id = 2035,
		huodongID = 4204,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, [7403] = 10, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[2035]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[2041] = {
		id = 2041,
		huodongID = 4205,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [7404] = 10, ['gold'] = 60000, __size = 3}
	},
	[2042] = {
		id = 2042,
		huodongID = 4205,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [7404] = 10, ['gold'] = 70000, __size = 3}
	},
	[2043] = {
		id = 2043,
		huodongID = 4205,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [7404] = 10, ['gold'] = 80000, __size = 3}
	},
	[2044] = {
		id = 2044,
		huodongID = 4205,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [7404] = 10, ['gold'] = 90000, __size = 3}
	},
	[2045] = {
		id = 2045,
		huodongID = 4205,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [7404] = 10, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, __size = 4},
		special = __data_t__special[2045]
		-- {['card'] = {['id'] = 9002, __size = 1}, __size = 1}
	},
	[2051] = {
		id = 2051,
		huodongID = 4206,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[7405] = 10, [2103] = 2, ['gold'] = 60000, __size = 3}
	},
	[2052] = {
		id = 2052,
		huodongID = 4206,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[7405] = 10, [2103] = 2, ['gold'] = 70000, __size = 3}
	},
	[2053] = {
		id = 2053,
		huodongID = 4206,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[7405] = 10, [2103] = 2, ['gold'] = 80000, __size = 3}
	},
	[2054] = {
		id = 2054,
		huodongID = 4206,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[7405] = 10, [2103] = 2, ['gold'] = 90000, __size = 3}
	},
	[2055] = {
		id = 2055,
		huodongID = 4206,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[7405] = 10, [2103] = 2, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, __size = 4}
	},
	[2061] = {
		id = 2061,
		huodongID = 4207,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 60000, [7406] = 10, __size = 3}
	},
	[2062] = {
		id = 2062,
		huodongID = 4207,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 70000, [7406] = 10, __size = 3}
	},
	[2063] = {
		id = 2063,
		huodongID = 4207,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 80000, [7406] = 10, __size = 3}
	},
	[2064] = {
		id = 2064,
		huodongID = 4207,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 90000, [7406] = 10, __size = 3}
	},
	[2065] = {
		id = 2065,
		huodongID = 4207,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, [7406] = 10, ['card'] = {['id'] = 9002, __size = 1}, __size = 4}
	},
	[2071] = {
		id = 2071,
		huodongID = 4208,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [7407] = 10, ['gold'] = 60000, __size = 3}
	},
	[2072] = {
		id = 2072,
		huodongID = 4208,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [7407] = 10, ['gold'] = 70000, __size = 3}
	},
	[2073] = {
		id = 2073,
		huodongID = 4208,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [7407] = 10, ['gold'] = 80000, __size = 3}
	},
	[2074] = {
		id = 2074,
		huodongID = 4208,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [7407] = 10, ['gold'] = 90000, __size = 3}
	},
	[2075] = {
		id = 2075,
		huodongID = 4208,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [7407] = 10, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, __size = 4}
	},
	[2081] = {
		id = 2081,
		huodongID = 4209,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 60000, [7408] = 10, __size = 3}
	},
	[2082] = {
		id = 2082,
		huodongID = 4209,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 70000, [7408] = 10, __size = 3}
	},
	[2083] = {
		id = 2083,
		huodongID = 4209,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 80000, [7408] = 10, __size = 3}
	},
	[2084] = {
		id = 2084,
		huodongID = 4209,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 90000, [7408] = 10, __size = 3}
	},
	[2085] = {
		id = 2085,
		huodongID = 4209,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, [7408] = 10, ['card'] = {['id'] = 9002, __size = 1}, __size = 4}
	},
	[2091] = {
		id = 2091,
		huodongID = 4210,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 60000, [7409] = 10, __size = 3}
	},
	[2092] = {
		id = 2092,
		huodongID = 4210,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 70000, [7409] = 10, __size = 3}
	},
	[2093] = {
		id = 2093,
		huodongID = 4210,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 80000, [7409] = 10, __size = 3}
	},
	[2094] = {
		id = 2094,
		huodongID = 4210,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 90000, [7409] = 10, __size = 3}
	},
	[2095] = {
		id = 2095,
		huodongID = 4210,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, [7409] = 10, ['card'] = {['id'] = 9002, __size = 1}, __size = 4}
	},
	[2101] = {
		id = 2101,
		huodongID = 4211,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [7410] = 10, ['gold'] = 60000, __size = 3}
	},
	[2102] = {
		id = 2102,
		huodongID = 4211,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [7410] = 10, ['gold'] = 70000, __size = 3}
	},
	[2103] = {
		id = 2103,
		huodongID = 4211,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [7410] = 10, ['gold'] = 80000, __size = 3}
	},
	[2104] = {
		id = 2104,
		huodongID = 4211,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [7410] = 10, ['gold'] = 90000, __size = 3}
	},
	[2105] = {
		id = 2105,
		huodongID = 4211,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, [7410] = 10, ['gold'] = 100000, ['card'] = {['id'] = 9002, __size = 1}, __size = 4}
	},
	[2111] = {
		id = 2111,
		huodongID = 4212,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 60000, [7411] = 10, __size = 3}
	},
	[2112] = {
		id = 2112,
		huodongID = 4212,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 70000, [7411] = 10, __size = 3}
	},
	[2113] = {
		id = 2113,
		huodongID = 4212,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 80000, [7411] = 10, __size = 3}
	},
	[2114] = {
		id = 2114,
		huodongID = 4212,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 90000, [7411] = 10, __size = 3}
	},
	[2115] = {
		id = 2115,
		huodongID = 4212,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 2, ['gold'] = 100000, [7411] = 10, ['card'] = {['id'] = 9002, __size = 1}, __size = 4}
	},
	[2116] = {
		id = 2116,
		huodongID = 4213,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 20, [6200] = 1, [521] = 20, [539] = 20, __size = 4}
	},
	[2117] = {
		id = 2117,
		huodongID = 4213,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 30, [6200] = 1, [521] = 30, [539] = 30, __size = 4}
	},
	[2118] = {
		id = 2118,
		huodongID = 4213,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 40, [6200] = 1, [521] = 40, [539] = 40, __size = 4}
	},
	[2119] = {
		id = 2119,
		huodongID = 4213,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 50, [6200] = 1, [521] = 50, [539] = 50, __size = 4}
	},
	[2120] = {
		id = 2120,
		huodongID = 4213,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['card'] = {['id'] = 9002, __size = 1}, [521] = 50, [539] = 50, [6199] = 1, __size = 4}
	},
	[2200] = {
		id = 2200,
		huodongID = 4214,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 20, [9100] = 2, [521] = 20, [539] = 20, __size = 4}
	},
	[2201] = {
		id = 2201,
		huodongID = 4214,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 30, [9100] = 2, [521] = 30, [539] = 30, __size = 4}
	},
	[2202] = {
		id = 2202,
		huodongID = 4214,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 40, [9100] = 2, [521] = 40, [539] = 40, __size = 4}
	},
	[2203] = {
		id = 2203,
		huodongID = 4214,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 50, [9100] = 2, [521] = 50, [539] = 50, __size = 4}
	},
	[2204] = {
		id = 2204,
		huodongID = 4214,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['card'] = {['id'] = 9002, __size = 1}, [9100] = 5, [521] = 50, [539] = 50, __size = 4}
	},
	[2300] = {
		id = 2300,
		huodongID = 4215,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 20, [521] = 20, [539] = 20, [9101] = 1, __size = 4}
	},
	[2301] = {
		id = 2301,
		huodongID = 4215,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 30, [521] = 30, [539] = 30, [9101] = 2, __size = 4}
	},
	[2302] = {
		id = 2302,
		huodongID = 4215,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 40, [521] = 40, [539] = 40, [9101] = 3, __size = 4}
	},
	[2303] = {
		id = 2303,
		huodongID = 4215,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 50, [521] = 50, [539] = 50, [9101] = 4, __size = 4}
	},
	[2304] = {
		id = 2304,
		huodongID = 4215,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {[2103] = 80, [521] = 80, [539] = 100, [9101] = 5, __size = 4}
	},
	[2400] = {
		id = 2400,
		huodongID = 4216,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2400]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2401] = {
		id = 2401,
		huodongID = 4216,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2401]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2402] = {
		id = 2402,
		huodongID = 4216,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2402]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2403] = {
		id = 2403,
		huodongID = 4216,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2403]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2404] = {
		id = 2404,
		huodongID = 4216,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['talent_point'] = 100, [6059] = 4, ['card'] = {['id'] = 9121, __size = 1}, [501] = 50, __size = 4},
		special = {['card'] = {['id'] = 9121, __size = 1}, __size = 1}
	},
	[2500] = {
		id = 2500,
		huodongID = 4217,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2500]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2501] = {
		id = 2501,
		huodongID = 4217,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2501]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2502] = {
		id = 2502,
		huodongID = 4217,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2502]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2503] = {
		id = 2503,
		huodongID = 4217,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2503]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2504] = {
		id = 2504,
		huodongID = 4217,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['talent_point'] = 100, [6059] = 4, ['card'] = {['id'] = 9101, __size = 1}, [501] = 50, __size = 4},
		special = {['card'] = {['id'] = 9101, __size = 1}, __size = 1}
	},
	[2600] = {
		id = 2600,
		huodongID = 4218,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2600]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2601] = {
		id = 2601,
		huodongID = 4218,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2601]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2602] = {
		id = 2602,
		huodongID = 4218,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2602]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2603] = {
		id = 2603,
		huodongID = 4218,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2603]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2604] = {
		id = 2604,
		huodongID = 4218,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['talent_point'] = 100, [6059] = 4, ['card'] = {['id'] = 9111, __size = 1}, [501] = 50, __size = 4},
		special = {['card'] = {['id'] = 9111, __size = 1}, __size = 1}
	},
	[2700] = {
		id = 2700,
		huodongID = 4219,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2700]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2701] = {
		id = 2701,
		huodongID = 4219,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2701]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2702] = {
		id = 2702,
		huodongID = 4219,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2702]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2703] = {
		id = 2703,
		huodongID = 4219,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2703]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2704] = {
		id = 2704,
		huodongID = 4219,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['talent_point'] = 100, [6059] = 4, ['card'] = {['id'] = 9131, __size = 1}, [501] = 50, __size = 4},
		special = {['card'] = {['id'] = 9131, __size = 1}, __size = 1}
	},
	[2800] = {
		id = 2800,
		huodongID = 4220,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2800]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2801] = {
		id = 2801,
		huodongID = 4220,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2801]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2802] = {
		id = 2802,
		huodongID = 4220,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2802]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2803] = {
		id = 2803,
		huodongID = 4220,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2803]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2804] = {
		id = 2804,
		huodongID = 4220,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['talent_point'] = 100, [6059] = 4, ['card'] = {['id'] = 9141, __size = 1}, [501] = 50, __size = 4},
		special = {['card'] = {['id'] = 9141, __size = 1}, __size = 1}
	},
	[2900] = {
		id = 2900,
		huodongID = 4221,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2900]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2901] = {
		id = 2901,
		huodongID = 4221,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2901]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2902] = {
		id = 2902,
		huodongID = 4221,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2902]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2903] = {
		id = 2903,
		huodongID = 4221,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[2903]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[2904] = {
		id = 2904,
		huodongID = 4221,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['talent_point'] = 100, [6059] = 4, ['card'] = {['id'] = 3601, __size = 1}, [501] = 50, __size = 4},
		special = {['card'] = {['id'] = 3601, __size = 1}, __size = 1}
	},
	[3000] = {
		id = 3000,
		huodongID = 4222,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3000]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3001] = {
		id = 3001,
		huodongID = 4222,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3001]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3002] = {
		id = 3002,
		huodongID = 4222,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3002]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3003] = {
		id = 3003,
		huodongID = 4222,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3003]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3004] = {
		id = 3004,
		huodongID = 4222,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['talent_point'] = 100, [6059] = 4, ['card'] = {['id'] = 7081, __size = 1}, [501] = 50, __size = 4},
		special = {['card'] = {['id'] = 7081, __size = 1}, __size = 1}
	},
	[3100] = {
		id = 3100,
		huodongID = 4223,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3100]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3101] = {
		id = 3101,
		huodongID = 4223,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3101]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3102] = {
		id = 3102,
		huodongID = 4223,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3102]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3103] = {
		id = 3103,
		huodongID = 4223,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3103]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3104] = {
		id = 3104,
		huodongID = 4223,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['talent_point'] = 100, [6059] = 4, ['card'] = {['id'] = 7091, __size = 1}, [501] = 50, __size = 4},
		special = {['card'] = {['id'] = 7091, __size = 1}, __size = 1}
	},
	[3200] = {
		id = 3200,
		huodongID = 4224,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3200]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3201] = {
		id = 3201,
		huodongID = 4224,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3201]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3202] = {
		id = 3202,
		huodongID = 4224,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3202]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3203] = {
		id = 3203,
		huodongID = 4224,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3203]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3204] = {
		id = 3204,
		huodongID = 4224,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['talent_point'] = 100, [6059] = 4, ['card'] = {['id'] = 9081, __size = 1}, [501] = 50, __size = 4},
		special = {['card'] = {['id'] = 9081, __size = 1}, __size = 1}
	},
	[3300] = {
		id = 3300,
		huodongID = 4225,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3300]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3301] = {
		id = 3301,
		huodongID = 4225,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3301]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3302] = {
		id = 3302,
		huodongID = 4225,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3302]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3303] = {
		id = 3303,
		huodongID = 4225,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3303]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3304] = {
		id = 3304,
		huodongID = 4225,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['talent_point'] = 100, [6059] = 4, ['card'] = {['id'] = 9051, __size = 1}, [501] = 50, __size = 4},
		special = {['card'] = {['id'] = 9051, __size = 1}, __size = 1}
	},
	[3400] = {
		id = 3400,
		huodongID = 4226,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3400]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3401] = {
		id = 3401,
		huodongID = 4226,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3401]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3402] = {
		id = 3402,
		huodongID = 4226,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3402]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3403] = {
		id = 3403,
		huodongID = 4226,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3403]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3404] = {
		id = 3404,
		huodongID = 4226,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['talent_point'] = 100, [6059] = 4, ['card'] = {['id'] = 9061, __size = 1}, [501] = 50, __size = 4},
		special = {['card'] = {['id'] = 9061, __size = 1}, __size = 1}
	},
	[3500] = {
		id = 3500,
		huodongID = 4227,
		daySum = 1,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3500]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3501] = {
		id = 3501,
		huodongID = 4227,
		daySum = 2,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3501]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3502] = {
		id = 3502,
		huodongID = 4227,
		daySum = 3,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3502]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3503] = {
		id = 3503,
		huodongID = 4227,
		daySum = 4,
		amount = 300,
		desc = '累计充值300钻石',
		award = __data_t__award[3503]
		-- {[9016] = 10, ['talent_point'] = 100, [6059] = 4, [501] = 50, __size = 4}
	},
	[3504] = {
		id = 3504,
		huodongID = 4227,
		daySum = 5,
		amount = 300,
		desc = '累计充值300钻石',
		award = {['talent_point'] = 100, [6059] = 4, ['card'] = {['id'] = 9071, __size = 1}, [501] = 50, __size = 4},
		special = {['card'] = {['id'] = 9071, __size = 1}, __size = 1}
	},

	__size = 265,
	__default = {
		__index = {
			huodongID = 0,
			daySum = -1,
			amount = 0,
			desc = '',
			desc_tw = '',
			desc_en = '',
			desc_vn = '',
			desc_kr = '',
			award = __data_t__award["default"]	--[[ {__size = 0}]],
			special = __data_t__special["default"]	--[[ {__size = 0}]]
		}
	}
}
return csv.yunying.rechargegift