--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {__size = 0}, 
	[5] = {['coin14'] = 2000, __size = 1}, 
	[6] = {1, 210}, 
	[11] = {['coin14'] = 5000, __size = 1}, 
	[23] = {['coin14'] = 1000, __size = 1}, 
	[29] = {['coin14'] = 1500, __size = 1}, __size = 6}
local __data_t__levelRange = {
	[1110] = __predefine_t__[6],
	[1108] = __predefine_t__[6],
	[1014] = __predefine_t__[6],
	[1015] = __predefine_t__[6],
	[1016] = __predefine_t__[6],
	[1017] = __predefine_t__[6],
	[1010] = __predefine_t__[6],
	[1011] = __predefine_t__[6],
	[1012] = __predefine_t__[6],
	[1013] = __predefine_t__[6],
	[1008] = __predefine_t__[6],
	[1106] = __predefine_t__[6],
	[1107] = __predefine_t__[6],
	[1104] = __predefine_t__[6],
	[1105] = __predefine_t__[6],
	[1102] = __predefine_t__[6],
	[1103] = __predefine_t__[6],
	[1009] = __predefine_t__[6],
	[1101] = __predefine_t__[6],
	[1007] = __predefine_t__[6],
	[1006] = __predefine_t__[6],
	[1005] = __predefine_t__[6],
	[1004] = __predefine_t__[6],
	[1003] = __predefine_t__[6],
	[1002] = __predefine_t__[6],
	[1001] = __predefine_t__[6],
	[1109] = __predefine_t__[6]
}
local __data_t__costMap = {
	["default"] = __predefine_t__[1],
	[1111] = __predefine_t__[11],
	[1110] = __predefine_t__[29],
	[1014] = __predefine_t__[5],
	[1015] = __predefine_t__[5],
	[1016] = __predefine_t__[23],
	[1017] = __predefine_t__[23],
	[1010] = __predefine_t__[5],
	[1011] = __predefine_t__[5],
	[1012] = __predefine_t__[5],
	[1013] = __predefine_t__[5],
	[1008] = __predefine_t__[5],
	[1107] = __predefine_t__[29],
	[1104] = __predefine_t__[23],
	[1105] = __predefine_t__[11],
	[1103] = __predefine_t__[29],
	[1009] = __predefine_t__[5],
	[1101] = __predefine_t__[5],
	[1007] = __predefine_t__[5],
	[1006] = __predefine_t__[5],
	[1005] = __predefine_t__[11],
	[1004] = __predefine_t__[5],
	[1003] = __predefine_t__[5],
	[1002] = __predefine_t__[5],
	[1001] = __predefine_t__[5]
}
local __data_t__itemMap = {
	["default"] = __predefine_t__[1]
}

csv['cross']['hunting']['shop'] = {
	[1001] = {
		id = 1001,
		itemMap = {[27001] = 2, __size = 1},
		costMap = __data_t__costMap[1001],
		-- {['coin14'] = 2000, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1001]
		-- {1, 210}
	},
	[1002] = {
		id = 1002,
		itemMap = {[23771] = 2, __size = 1},
		costMap = __data_t__costMap[1002],
		-- {['coin14'] = 2000, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1002]
		-- {1, 210}
	},
	[1003] = {
		id = 1003,
		itemMap = {[23251] = 2, __size = 1},
		costMap = __data_t__costMap[1003],
		-- {['coin14'] = 2000, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1003]
		-- {1, 210}
	},
	[1004] = {
		id = 1004,
		itemMap = {[23841] = 2, __size = 1},
		costMap = __data_t__costMap[1004],
		-- {['coin14'] = 2000, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1004]
		-- {1, 210}
	},
	[1005] = {
		id = 1005,
		itemMap = {[22431] = 1, __size = 1},
		costMap = __data_t__costMap[1005],
		-- {['coin14'] = 5000, __size = 1}
		levelRange = __data_t__levelRange[1005],
		-- {1, 210}
		limitType = 3,
		limitTimes = 5
	},
	[1006] = {
		id = 1006,
		itemMap = {[23671] = 2, __size = 1},
		costMap = __data_t__costMap[1006],
		-- {['coin14'] = 2000, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1006]
		-- {1, 210}
	},
	[1007] = {
		id = 1007,
		itemMap = {[23681] = 2, __size = 1},
		costMap = __data_t__costMap[1007],
		-- {['coin14'] = 2000, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1007]
		-- {1, 210}
	},
	[1008] = {
		id = 1008,
		itemMap = {[23961] = 2, __size = 1},
		costMap = __data_t__costMap[1008],
		-- {['coin14'] = 2000, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1008]
		-- {1, 210}
	},
	[1009] = {
		id = 1009,
		itemMap = {[24031] = 2, __size = 1},
		costMap = __data_t__costMap[1009],
		-- {['coin14'] = 2000, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1009]
		-- {1, 210}
	},
	[1010] = {
		id = 1010,
		itemMap = {[24051] = 2, __size = 1},
		costMap = __data_t__costMap[1010],
		-- {['coin14'] = 2000, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1010]
		-- {1, 210}
	},
	[1011] = {
		id = 1011,
		itemMap = {[24071] = 2, __size = 1},
		costMap = __data_t__costMap[1011],
		-- {['coin14'] = 2000, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1011]
		-- {1, 210}
	},
	[1012] = {
		id = 1012,
		itemMap = {[24081] = 2, __size = 1},
		costMap = __data_t__costMap[1012],
		-- {['coin14'] = 2000, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1012]
		-- {1, 210}
	},
	[1013] = {
		id = 1013,
		itemMap = {[24131] = 2, __size = 1},
		costMap = __data_t__costMap[1013],
		-- {['coin14'] = 2000, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1013]
		-- {1, 210}
	},
	[1014] = {
		id = 1014,
		itemMap = {[24141] = 2, __size = 1},
		costMap = __data_t__costMap[1014],
		-- {['coin14'] = 2000, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1014]
		-- {1, 210}
	},
	[1015] = {
		id = 1015,
		itemMap = {[24151] = 2, __size = 1},
		costMap = __data_t__costMap[1015],
		-- {['coin14'] = 2000, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1015]
		-- {1, 210}
	},
	[1016] = {
		id = 1016,
		itemMap = {[21641] = 2, __size = 1},
		costMap = __data_t__costMap[1016],
		-- {['coin14'] = 1000, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1016]
		-- {1, 210}
	},
	[1017] = {
		id = 1017,
		itemMap = {[22831] = 2, __size = 1},
		costMap = __data_t__costMap[1017],
		-- {['coin14'] = 1000, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1017]
		-- {1, 210}
	},
	[1101] = {
		id = 1101,
		itemMap = {[5000] = 10, __size = 1},
		costMap = __data_t__costMap[1101],
		-- {['coin14'] = 2000, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1101]
		-- {1, 210}
	},
	[1102] = {
		id = 1102,
		itemMap = {[514] = 10, __size = 1},
		costMap = {['coin14'] = 1200, __size = 1},
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1102]
		-- {1, 210}
	},
	[1103] = {
		id = 1103,
		itemMap = {[15] = 5, __size = 1},
		costMap = __data_t__costMap[1103],
		-- {['coin14'] = 1500, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1103]
		-- {1, 210}
	},
	[1104] = {
		id = 1104,
		itemMap = {[7302] = 1, __size = 1},
		costMap = __data_t__costMap[1104],
		-- {['coin14'] = 1000, __size = 1}
		levelRange = __data_t__levelRange[1104],
		-- {1, 210}
		limitType = 2,
		limitTimes = 20
	},
	[1105] = {
		id = 1105,
		itemMap = {[7303] = 1, __size = 1},
		costMap = __data_t__costMap[1105],
		-- {['coin14'] = 5000, __size = 1}
		levelRange = __data_t__levelRange[1105],
		-- {1, 210}
		limitType = 3,
		limitTimes = 40
	},
	[1106] = {
		id = 1106,
		itemMap = {[7304] = 1, __size = 1},
		costMap = {['coin14'] = 15000, __size = 1},
		levelRange = __data_t__levelRange[1106],
		-- {1, 210}
		limitType = 3,
		limitTimes = 40
	},
	[1107] = {
		id = 1107,
		itemMap = {[121] = 1, __size = 1},
		costMap = __data_t__costMap[1107],
		-- {['coin14'] = 1500, __size = 1}
		levelRange = __data_t__levelRange[1107],
		-- {1, 210}
		limitType = 2,
		limitTimes = 20
	},
	[1108] = {
		id = 1108,
		itemMap = {[122] = 1, __size = 1},
		costMap = {['coin14'] = 100, __size = 1},
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1108]
		-- {1, 210}
	},
	[1109] = {
		id = 1109,
		itemMap = {[123] = 1, __size = 1},
		costMap = {['coin14'] = 500, __size = 1},
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1109]
		-- {1, 210}
	},
	[1110] = {
		id = 1110,
		itemMap = {[124] = 1, __size = 1},
		costMap = __data_t__costMap[1110],
		-- {['coin14'] = 1500, __size = 1}
		exchangeLimit = 5,
		regainHour = 24,
		levelRange = __data_t__levelRange[1110]
		-- {1, 210}
	},
	[1111] = {
		id = 1111,
		itemMap = {[538] = 1, __size = 1},
		costMap = __data_t__costMap[1111],
		-- {['coin14'] = 5000, __size = 1}
		exchangeLimit = 1,
		regainHour = 24,
		levelRange = {120, 210}
	},

	__size = 28,
	__default = {
		__index = {
			itemMap = __data_t__itemMap["default"]	--[[ {__size = 0}]],
			costMap = __data_t__costMap["default"]	--[[ {__size = 0}]],
			exchangeLimit = -1,
			regainHour = 0,
			beginDate = 0,
			endDate = 20990101,
			vipStart = 0,
			levelRange = {1, 150},
			limitType = 0,
			limitTimes = 0,
			showUnable = false,
			sortValue = 0,
			languages = {'cn', 'en', 'tw', 'vn', 'kr', 'pt', 'th'}
		}
	}
}
return csv.cross.hunting.shop