--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[2] = {__size = 0}, 
	[3] = {['gold'] = 50000, __size = 1}, 
	[4] = {['rmb'] = 30, __size = 1}, 
	[5] = {[503] = 1, __size = 1}, 
	[6] = {[519] = 1, __size = 1}, 
	[7] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, 
	[8] = {[20591] = 5, __size = 1}, 
	[9] = {[21311] = 5, __size = 1}, 
	[10] = {[20261] = 5, __size = 1}, 
	[11] = {[23141] = 5, __size = 1}, 
	[12] = {[20391] = 5, __size = 1}, 
	[13] = {[21501] = 5, __size = 1}, 
	[14] = {[23021] = 5, __size = 1}, 
	[15] = {[23001] = 5, __size = 1}, 
	[16] = {[23591] = 5, __size = 1}, 
	[17] = {[21421] = 5, __size = 1}, 
	[18] = {[21231] = 5, __size = 1}, 
	[19] = {[20491] = 5, __size = 1}, 
	[20] = {['gold'] = 60000, __size = 1}, 
	[21] = {['rmb'] = 35, __size = 1}, 
	[22] = {['gold'] = 70000, __size = 1}, 
	[23] = {['rmb'] = 40, __size = 1}, 
	[24] = {['gold'] = 80000, __size = 1}, 
	[25] = {['rmb'] = 45, __size = 1}, 
	[26] = {[20591] = 8, __size = 1}, 
	[27] = {[21311] = 8, __size = 1}, 
	[28] = {[20261] = 8, __size = 1}, 
	[29] = {[23141] = 8, __size = 1}, 
	[30] = {[20391] = 8, __size = 1}, 
	[31] = {[21501] = 8, __size = 1}, 
	[32] = {[23021] = 8, __size = 1}, 
	[33] = {[23001] = 8, __size = 1}, 
	[34] = {[23591] = 8, __size = 1}, 
	[35] = {[21421] = 8, __size = 1}, 
	[36] = {[21231] = 8, __size = 1}, 
	[37] = {[20491] = 8, __size = 1}, 
	[38] = {['gold'] = 90000, __size = 1}, 
	[39] = {['rmb'] = 50, __size = 1}, 
	[40] = {['gold'] = 100000, __size = 1}, 
	[53] = {[19] = 5, ['gold'] = 200000, __size = 2}, 
	[54] = {['rmb'] = 150, [502] = 3, __size = 2}, 
	[55] = {[521] = 3, [501] = 2, __size = 2}, __size = 42}
local __data_t__months = {
	[10] = __predefine_t__[7],
	[15] = __predefine_t__[7],
	[14] = __predefine_t__[7],
	[25] = __predefine_t__[7],
	[30] = __predefine_t__[7],
	[5] = __predefine_t__[7],
	[20] = __predefine_t__[7]
}
local __data_t__month12 = {
	["default"] = __predefine_t__[2],
	[24] = __predefine_t__[6],
	[25] = __predefine_t__[37],
	[26] = __predefine_t__[40],
	[27] = __predefine_t__[39],
	[20] = __predefine_t__[37],
	[21] = __predefine_t__[38],
	[22] = __predefine_t__[39],
	[23] = __predefine_t__[5],
	[28] = __predefine_t__[5],
	[29] = __predefine_t__[6],
	[1] = __predefine_t__[3],
	[3] = __predefine_t__[5],
	[2] = __predefine_t__[4],
	[5] = __predefine_t__[19],
	[4] = __predefine_t__[6],
	[7] = __predefine_t__[21],
	[6] = __predefine_t__[20],
	[9] = __predefine_t__[6],
	[8] = __predefine_t__[5],
	[102] = __predefine_t__[54],
	[103] = __predefine_t__[55],
	[101] = __predefine_t__[53],
	[11] = __predefine_t__[22],
	[10] = __predefine_t__[19],
	[13] = __predefine_t__[5],
	[12] = __predefine_t__[23],
	[15] = __predefine_t__[19],
	[14] = __predefine_t__[6],
	[17] = __predefine_t__[25],
	[16] = __predefine_t__[24],
	[19] = __predefine_t__[6],
	[18] = __predefine_t__[5],
	[31] = __predefine_t__[40]
}
local __data_t__month11 = {
	["default"] = __predefine_t__[2],
	[24] = __predefine_t__[6],
	[25] = __predefine_t__[36],
	[26] = __predefine_t__[40],
	[27] = __predefine_t__[39],
	[20] = __predefine_t__[36],
	[21] = __predefine_t__[38],
	[22] = __predefine_t__[39],
	[23] = __predefine_t__[5],
	[28] = __predefine_t__[5],
	[29] = __predefine_t__[6],
	[1] = __predefine_t__[3],
	[3] = __predefine_t__[5],
	[2] = __predefine_t__[4],
	[5] = __predefine_t__[18],
	[4] = __predefine_t__[6],
	[7] = __predefine_t__[21],
	[6] = __predefine_t__[20],
	[9] = __predefine_t__[6],
	[8] = __predefine_t__[5],
	[102] = __predefine_t__[54],
	[103] = __predefine_t__[55],
	[101] = __predefine_t__[53],
	[11] = __predefine_t__[22],
	[10] = __predefine_t__[18],
	[13] = __predefine_t__[5],
	[12] = __predefine_t__[23],
	[15] = __predefine_t__[18],
	[14] = __predefine_t__[6],
	[17] = __predefine_t__[25],
	[16] = __predefine_t__[24],
	[19] = __predefine_t__[6],
	[18] = __predefine_t__[5],
	[31] = __predefine_t__[40]
}
local __data_t__month10 = {
	["default"] = __predefine_t__[2],
	[24] = __predefine_t__[6],
	[25] = __predefine_t__[35],
	[26] = __predefine_t__[40],
	[27] = __predefine_t__[39],
	[20] = __predefine_t__[35],
	[21] = __predefine_t__[38],
	[22] = __predefine_t__[39],
	[23] = __predefine_t__[5],
	[28] = __predefine_t__[5],
	[29] = __predefine_t__[6],
	[1] = __predefine_t__[3],
	[3] = __predefine_t__[5],
	[2] = __predefine_t__[4],
	[5] = __predefine_t__[17],
	[4] = __predefine_t__[6],
	[7] = __predefine_t__[21],
	[6] = __predefine_t__[20],
	[9] = __predefine_t__[6],
	[8] = __predefine_t__[5],
	[102] = __predefine_t__[54],
	[103] = __predefine_t__[55],
	[101] = __predefine_t__[53],
	[11] = __predefine_t__[22],
	[10] = __predefine_t__[17],
	[13] = __predefine_t__[5],
	[12] = __predefine_t__[23],
	[15] = __predefine_t__[17],
	[14] = __predefine_t__[6],
	[17] = __predefine_t__[25],
	[16] = __predefine_t__[24],
	[19] = __predefine_t__[6],
	[18] = __predefine_t__[5],
	[31] = __predefine_t__[40]
}
local __data_t__month9 = {
	["default"] = __predefine_t__[2],
	[24] = __predefine_t__[6],
	[25] = __predefine_t__[34],
	[26] = __predefine_t__[40],
	[27] = __predefine_t__[39],
	[20] = __predefine_t__[34],
	[21] = __predefine_t__[38],
	[22] = __predefine_t__[39],
	[23] = __predefine_t__[5],
	[28] = __predefine_t__[5],
	[29] = __predefine_t__[6],
	[1] = __predefine_t__[3],
	[3] = __predefine_t__[5],
	[2] = __predefine_t__[4],
	[5] = __predefine_t__[16],
	[4] = __predefine_t__[6],
	[7] = __predefine_t__[21],
	[6] = __predefine_t__[20],
	[9] = __predefine_t__[6],
	[8] = __predefine_t__[5],
	[102] = __predefine_t__[54],
	[103] = __predefine_t__[55],
	[101] = __predefine_t__[53],
	[11] = __predefine_t__[22],
	[10] = __predefine_t__[16],
	[13] = __predefine_t__[5],
	[12] = __predefine_t__[23],
	[15] = __predefine_t__[16],
	[14] = __predefine_t__[6],
	[17] = __predefine_t__[25],
	[16] = __predefine_t__[24],
	[19] = __predefine_t__[6],
	[18] = __predefine_t__[5],
	[31] = __predefine_t__[40]
}
local __data_t__month8 = {
	["default"] = __predefine_t__[2],
	[24] = __predefine_t__[6],
	[25] = __predefine_t__[33],
	[26] = __predefine_t__[40],
	[27] = __predefine_t__[39],
	[20] = __predefine_t__[33],
	[21] = __predefine_t__[38],
	[22] = __predefine_t__[39],
	[23] = __predefine_t__[5],
	[28] = __predefine_t__[5],
	[29] = __predefine_t__[6],
	[1] = __predefine_t__[3],
	[3] = __predefine_t__[5],
	[2] = __predefine_t__[4],
	[5] = __predefine_t__[15],
	[4] = __predefine_t__[6],
	[7] = __predefine_t__[21],
	[6] = __predefine_t__[20],
	[9] = __predefine_t__[6],
	[8] = __predefine_t__[5],
	[102] = __predefine_t__[54],
	[103] = __predefine_t__[55],
	[101] = __predefine_t__[53],
	[11] = __predefine_t__[22],
	[10] = __predefine_t__[15],
	[13] = __predefine_t__[5],
	[12] = __predefine_t__[23],
	[15] = __predefine_t__[15],
	[14] = __predefine_t__[6],
	[17] = __predefine_t__[25],
	[16] = __predefine_t__[24],
	[19] = __predefine_t__[6],
	[18] = __predefine_t__[5],
	[31] = __predefine_t__[40]
}
local __data_t__month7 = {
	["default"] = __predefine_t__[2],
	[24] = __predefine_t__[6],
	[25] = __predefine_t__[32],
	[26] = __predefine_t__[40],
	[27] = __predefine_t__[39],
	[20] = __predefine_t__[32],
	[21] = __predefine_t__[38],
	[22] = __predefine_t__[39],
	[23] = __predefine_t__[5],
	[28] = __predefine_t__[5],
	[29] = __predefine_t__[6],
	[1] = __predefine_t__[3],
	[3] = __predefine_t__[5],
	[2] = __predefine_t__[4],
	[5] = __predefine_t__[14],
	[4] = __predefine_t__[6],
	[7] = __predefine_t__[21],
	[6] = __predefine_t__[20],
	[9] = __predefine_t__[6],
	[8] = __predefine_t__[5],
	[102] = __predefine_t__[54],
	[103] = __predefine_t__[55],
	[101] = __predefine_t__[53],
	[11] = __predefine_t__[22],
	[10] = __predefine_t__[14],
	[13] = __predefine_t__[5],
	[12] = __predefine_t__[23],
	[15] = __predefine_t__[14],
	[14] = __predefine_t__[6],
	[17] = __predefine_t__[25],
	[16] = __predefine_t__[24],
	[19] = __predefine_t__[6],
	[18] = __predefine_t__[5],
	[31] = __predefine_t__[40]
}
local __data_t__month6 = {
	["default"] = __predefine_t__[2],
	[24] = __predefine_t__[6],
	[25] = __predefine_t__[31],
	[26] = __predefine_t__[40],
	[27] = __predefine_t__[39],
	[20] = __predefine_t__[31],
	[21] = __predefine_t__[38],
	[22] = __predefine_t__[39],
	[23] = __predefine_t__[5],
	[28] = __predefine_t__[5],
	[29] = __predefine_t__[6],
	[1] = __predefine_t__[3],
	[3] = __predefine_t__[5],
	[2] = __predefine_t__[4],
	[5] = __predefine_t__[13],
	[4] = __predefine_t__[6],
	[7] = __predefine_t__[21],
	[6] = __predefine_t__[20],
	[9] = __predefine_t__[6],
	[8] = __predefine_t__[5],
	[102] = __predefine_t__[54],
	[103] = __predefine_t__[55],
	[101] = __predefine_t__[53],
	[11] = __predefine_t__[22],
	[10] = __predefine_t__[13],
	[13] = __predefine_t__[5],
	[12] = __predefine_t__[23],
	[15] = __predefine_t__[13],
	[14] = __predefine_t__[6],
	[17] = __predefine_t__[25],
	[16] = __predefine_t__[24],
	[19] = __predefine_t__[6],
	[18] = __predefine_t__[5],
	[31] = __predefine_t__[40]
}
local __data_t__month5 = {
	["default"] = __predefine_t__[2],
	[24] = __predefine_t__[6],
	[25] = __predefine_t__[30],
	[26] = __predefine_t__[40],
	[27] = __predefine_t__[39],
	[20] = __predefine_t__[30],
	[21] = __predefine_t__[38],
	[22] = __predefine_t__[39],
	[23] = __predefine_t__[5],
	[28] = __predefine_t__[5],
	[29] = __predefine_t__[6],
	[1] = __predefine_t__[3],
	[3] = __predefine_t__[5],
	[2] = __predefine_t__[4],
	[5] = __predefine_t__[12],
	[4] = __predefine_t__[6],
	[7] = __predefine_t__[21],
	[6] = __predefine_t__[20],
	[9] = __predefine_t__[6],
	[8] = __predefine_t__[5],
	[102] = __predefine_t__[54],
	[103] = __predefine_t__[55],
	[101] = __predefine_t__[53],
	[11] = __predefine_t__[22],
	[10] = __predefine_t__[12],
	[13] = __predefine_t__[5],
	[12] = __predefine_t__[23],
	[15] = __predefine_t__[12],
	[14] = __predefine_t__[6],
	[17] = __predefine_t__[25],
	[16] = __predefine_t__[24],
	[19] = __predefine_t__[6],
	[18] = __predefine_t__[5],
	[31] = __predefine_t__[40]
}
local __data_t__month4 = {
	["default"] = __predefine_t__[2],
	[24] = __predefine_t__[6],
	[25] = __predefine_t__[29],
	[26] = __predefine_t__[40],
	[27] = __predefine_t__[39],
	[20] = __predefine_t__[29],
	[21] = __predefine_t__[38],
	[22] = __predefine_t__[39],
	[23] = __predefine_t__[5],
	[28] = __predefine_t__[5],
	[29] = __predefine_t__[6],
	[1] = __predefine_t__[3],
	[3] = __predefine_t__[5],
	[2] = __predefine_t__[4],
	[5] = __predefine_t__[11],
	[4] = __predefine_t__[6],
	[7] = __predefine_t__[21],
	[6] = __predefine_t__[20],
	[9] = __predefine_t__[6],
	[8] = __predefine_t__[5],
	[102] = __predefine_t__[54],
	[103] = __predefine_t__[55],
	[101] = __predefine_t__[53],
	[11] = __predefine_t__[22],
	[10] = __predefine_t__[11],
	[13] = __predefine_t__[5],
	[12] = __predefine_t__[23],
	[15] = __predefine_t__[11],
	[14] = __predefine_t__[6],
	[17] = __predefine_t__[25],
	[16] = __predefine_t__[24],
	[19] = __predefine_t__[6],
	[18] = __predefine_t__[5],
	[31] = __predefine_t__[40]
}
local __data_t__month3 = {
	["default"] = __predefine_t__[2],
	[24] = __predefine_t__[6],
	[25] = __predefine_t__[28],
	[26] = __predefine_t__[40],
	[27] = __predefine_t__[39],
	[20] = __predefine_t__[28],
	[21] = __predefine_t__[38],
	[22] = __predefine_t__[39],
	[23] = __predefine_t__[5],
	[28] = __predefine_t__[5],
	[29] = __predefine_t__[6],
	[1] = __predefine_t__[3],
	[3] = __predefine_t__[5],
	[2] = __predefine_t__[4],
	[5] = __predefine_t__[10],
	[4] = __predefine_t__[6],
	[7] = __predefine_t__[21],
	[6] = __predefine_t__[20],
	[9] = __predefine_t__[6],
	[8] = __predefine_t__[5],
	[102] = __predefine_t__[54],
	[103] = __predefine_t__[55],
	[101] = __predefine_t__[53],
	[11] = __predefine_t__[22],
	[10] = __predefine_t__[10],
	[13] = __predefine_t__[5],
	[12] = __predefine_t__[23],
	[15] = __predefine_t__[10],
	[14] = __predefine_t__[6],
	[17] = __predefine_t__[25],
	[16] = __predefine_t__[24],
	[19] = __predefine_t__[6],
	[18] = __predefine_t__[5],
	[31] = __predefine_t__[40]
}
local __data_t__month2 = {
	["default"] = __predefine_t__[2],
	[24] = __predefine_t__[6],
	[25] = __predefine_t__[27],
	[26] = __predefine_t__[40],
	[27] = __predefine_t__[39],
	[20] = __predefine_t__[27],
	[21] = __predefine_t__[38],
	[22] = __predefine_t__[39],
	[23] = __predefine_t__[5],
	[28] = __predefine_t__[5],
	[29] = __predefine_t__[6],
	[1] = __predefine_t__[3],
	[3] = __predefine_t__[5],
	[2] = __predefine_t__[4],
	[5] = __predefine_t__[9],
	[4] = __predefine_t__[6],
	[7] = __predefine_t__[21],
	[6] = __predefine_t__[20],
	[9] = __predefine_t__[6],
	[8] = __predefine_t__[5],
	[102] = __predefine_t__[54],
	[103] = __predefine_t__[55],
	[101] = __predefine_t__[53],
	[11] = __predefine_t__[22],
	[10] = __predefine_t__[9],
	[13] = __predefine_t__[5],
	[12] = __predefine_t__[23],
	[15] = __predefine_t__[9],
	[14] = __predefine_t__[6],
	[17] = __predefine_t__[25],
	[16] = __predefine_t__[24],
	[19] = __predefine_t__[6],
	[18] = __predefine_t__[5],
	[31] = __predefine_t__[40]
}
local __data_t__month1 = {
	["default"] = __predefine_t__[2],
	[24] = __predefine_t__[6],
	[25] = __predefine_t__[26],
	[26] = __predefine_t__[40],
	[27] = __predefine_t__[39],
	[20] = __predefine_t__[26],
	[21] = __predefine_t__[38],
	[22] = __predefine_t__[39],
	[23] = __predefine_t__[5],
	[28] = __predefine_t__[5],
	[29] = __predefine_t__[6],
	[1] = __predefine_t__[3],
	[3] = __predefine_t__[5],
	[2] = __predefine_t__[4],
	[5] = __predefine_t__[8],
	[4] = __predefine_t__[6],
	[7] = __predefine_t__[21],
	[6] = __predefine_t__[20],
	[9] = __predefine_t__[6],
	[8] = __predefine_t__[5],
	[102] = __predefine_t__[54],
	[103] = __predefine_t__[55],
	[101] = __predefine_t__[53],
	[11] = __predefine_t__[22],
	[10] = __predefine_t__[8],
	[13] = __predefine_t__[5],
	[12] = __predefine_t__[23],
	[15] = __predefine_t__[8],
	[14] = __predefine_t__[6],
	[17] = __predefine_t__[25],
	[16] = __predefine_t__[24],
	[19] = __predefine_t__[6],
	[18] = __predefine_t__[5],
	[31] = __predefine_t__[40]
}

csv['signin'] = {
	[1] = {
		id = 1,
		vipDouble = 1,
		month1 = __data_t__month1[1],
		-- {['gold'] = 50000, __size = 1}
		month2 = __data_t__month2[1],
		-- {['gold'] = 50000, __size = 1}
		month3 = __data_t__month3[1],
		-- {['gold'] = 50000, __size = 1}
		month4 = __data_t__month4[1],
		-- {['gold'] = 50000, __size = 1}
		month5 = __data_t__month5[1],
		-- {['gold'] = 50000, __size = 1}
		month6 = __data_t__month6[1],
		-- {['gold'] = 50000, __size = 1}
		month7 = __data_t__month7[1],
		-- {['gold'] = 50000, __size = 1}
		month8 = __data_t__month8[1],
		-- {['gold'] = 50000, __size = 1}
		month9 = __data_t__month9[1],
		-- {['gold'] = 50000, __size = 1}
		month10 = __data_t__month10[1],
		-- {['gold'] = 50000, __size = 1}
		month11 = __data_t__month11[1],
		-- {['gold'] = 50000, __size = 1}
		month12 = __data_t__month12[1]
		-- {['gold'] = 50000, __size = 1}
	},
	[2] = {
		id = 2,
		month1 = __data_t__month1[2],
		-- {['rmb'] = 30, __size = 1}
		month2 = __data_t__month2[2],
		-- {['rmb'] = 30, __size = 1}
		month3 = __data_t__month3[2],
		-- {['rmb'] = 30, __size = 1}
		month4 = __data_t__month4[2],
		-- {['rmb'] = 30, __size = 1}
		month5 = __data_t__month5[2],
		-- {['rmb'] = 30, __size = 1}
		month6 = __data_t__month6[2],
		-- {['rmb'] = 30, __size = 1}
		month7 = __data_t__month7[2],
		-- {['rmb'] = 30, __size = 1}
		month8 = __data_t__month8[2],
		-- {['rmb'] = 30, __size = 1}
		month9 = __data_t__month9[2],
		-- {['rmb'] = 30, __size = 1}
		month10 = __data_t__month10[2],
		-- {['rmb'] = 30, __size = 1}
		month11 = __data_t__month11[2],
		-- {['rmb'] = 30, __size = 1}
		month12 = __data_t__month12[2]
		-- {['rmb'] = 30, __size = 1}
	},
	[3] = {
		id = 3,
		vipDouble = 2,
		month1 = __data_t__month1[3],
		-- {[503] = 1, __size = 1}
		month2 = __data_t__month2[3],
		-- {[503] = 1, __size = 1}
		month3 = __data_t__month3[3],
		-- {[503] = 1, __size = 1}
		month4 = __data_t__month4[3],
		-- {[503] = 1, __size = 1}
		month5 = __data_t__month5[3],
		-- {[503] = 1, __size = 1}
		month6 = __data_t__month6[3],
		-- {[503] = 1, __size = 1}
		month7 = __data_t__month7[3],
		-- {[503] = 1, __size = 1}
		month8 = __data_t__month8[3],
		-- {[503] = 1, __size = 1}
		month9 = __data_t__month9[3],
		-- {[503] = 1, __size = 1}
		month10 = __data_t__month10[3],
		-- {[503] = 1, __size = 1}
		month11 = __data_t__month11[3],
		-- {[503] = 1, __size = 1}
		month12 = __data_t__month12[3]
		-- {[503] = 1, __size = 1}
	},
	[4] = {
		id = 4,
		month1 = __data_t__month1[4],
		-- {[519] = 1, __size = 1}
		month2 = __data_t__month2[4],
		-- {[519] = 1, __size = 1}
		month3 = __data_t__month3[4],
		-- {[519] = 1, __size = 1}
		month4 = __data_t__month4[4],
		-- {[519] = 1, __size = 1}
		month5 = __data_t__month5[4],
		-- {[519] = 1, __size = 1}
		month6 = __data_t__month6[4],
		-- {[519] = 1, __size = 1}
		month7 = __data_t__month7[4],
		-- {[519] = 1, __size = 1}
		month8 = __data_t__month8[4],
		-- {[519] = 1, __size = 1}
		month9 = __data_t__month9[4],
		-- {[519] = 1, __size = 1}
		month10 = __data_t__month10[4],
		-- {[519] = 1, __size = 1}
		month11 = __data_t__month11[4],
		-- {[519] = 1, __size = 1}
		month12 = __data_t__month12[4]
		-- {[519] = 1, __size = 1}
	},
	[5] = {
		id = 5,
		vipDouble = 3,
		months = __data_t__months[5],
		-- {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
		month1 = __data_t__month1[5],
		-- {[20591] = 5, __size = 1}
		month2 = __data_t__month2[5],
		-- {[21311] = 5, __size = 1}
		month3 = __data_t__month3[5],
		-- {[20261] = 5, __size = 1}
		month4 = __data_t__month4[5],
		-- {[23141] = 5, __size = 1}
		month5 = __data_t__month5[5],
		-- {[20391] = 5, __size = 1}
		month6 = __data_t__month6[5],
		-- {[21501] = 5, __size = 1}
		month7 = __data_t__month7[5],
		-- {[23021] = 5, __size = 1}
		month8 = __data_t__month8[5],
		-- {[23001] = 5, __size = 1}
		month9 = __data_t__month9[5],
		-- {[23591] = 5, __size = 1}
		month10 = __data_t__month10[5],
		-- {[21421] = 5, __size = 1}
		month11 = __data_t__month11[5],
		-- {[21231] = 5, __size = 1}
		month12 = __data_t__month12[5]
		-- {[20491] = 5, __size = 1}
	},
	[6] = {
		id = 6,
		vipDouble = 3,
		month1 = __data_t__month1[6],
		-- {['gold'] = 60000, __size = 1}
		month2 = __data_t__month2[6],
		-- {['gold'] = 60000, __size = 1}
		month3 = __data_t__month3[6],
		-- {['gold'] = 60000, __size = 1}
		month4 = __data_t__month4[6],
		-- {['gold'] = 60000, __size = 1}
		month5 = __data_t__month5[6],
		-- {['gold'] = 60000, __size = 1}
		month6 = __data_t__month6[6],
		-- {['gold'] = 60000, __size = 1}
		month7 = __data_t__month7[6],
		-- {['gold'] = 60000, __size = 1}
		month8 = __data_t__month8[6],
		-- {['gold'] = 60000, __size = 1}
		month9 = __data_t__month9[6],
		-- {['gold'] = 60000, __size = 1}
		month10 = __data_t__month10[6],
		-- {['gold'] = 60000, __size = 1}
		month11 = __data_t__month11[6],
		-- {['gold'] = 60000, __size = 1}
		month12 = __data_t__month12[6]
		-- {['gold'] = 60000, __size = 1}
	},
	[7] = {
		id = 7,
		month1 = __data_t__month1[7],
		-- {['rmb'] = 35, __size = 1}
		month2 = __data_t__month2[7],
		-- {['rmb'] = 35, __size = 1}
		month3 = __data_t__month3[7],
		-- {['rmb'] = 35, __size = 1}
		month4 = __data_t__month4[7],
		-- {['rmb'] = 35, __size = 1}
		month5 = __data_t__month5[7],
		-- {['rmb'] = 35, __size = 1}
		month6 = __data_t__month6[7],
		-- {['rmb'] = 35, __size = 1}
		month7 = __data_t__month7[7],
		-- {['rmb'] = 35, __size = 1}
		month8 = __data_t__month8[7],
		-- {['rmb'] = 35, __size = 1}
		month9 = __data_t__month9[7],
		-- {['rmb'] = 35, __size = 1}
		month10 = __data_t__month10[7],
		-- {['rmb'] = 35, __size = 1}
		month11 = __data_t__month11[7],
		-- {['rmb'] = 35, __size = 1}
		month12 = __data_t__month12[7]
		-- {['rmb'] = 35, __size = 1}
	},
	[8] = {
		id = 8,
		vipDouble = 4,
		month1 = __data_t__month1[8],
		-- {[503] = 1, __size = 1}
		month2 = __data_t__month2[8],
		-- {[503] = 1, __size = 1}
		month3 = __data_t__month3[8],
		-- {[503] = 1, __size = 1}
		month4 = __data_t__month4[8],
		-- {[503] = 1, __size = 1}
		month5 = __data_t__month5[8],
		-- {[503] = 1, __size = 1}
		month6 = __data_t__month6[8],
		-- {[503] = 1, __size = 1}
		month7 = __data_t__month7[8],
		-- {[503] = 1, __size = 1}
		month8 = __data_t__month8[8],
		-- {[503] = 1, __size = 1}
		month9 = __data_t__month9[8],
		-- {[503] = 1, __size = 1}
		month10 = __data_t__month10[8],
		-- {[503] = 1, __size = 1}
		month11 = __data_t__month11[8],
		-- {[503] = 1, __size = 1}
		month12 = __data_t__month12[8]
		-- {[503] = 1, __size = 1}
	},
	[9] = {
		id = 9,
		month1 = __data_t__month1[9],
		-- {[519] = 1, __size = 1}
		month2 = __data_t__month2[9],
		-- {[519] = 1, __size = 1}
		month3 = __data_t__month3[9],
		-- {[519] = 1, __size = 1}
		month4 = __data_t__month4[9],
		-- {[519] = 1, __size = 1}
		month5 = __data_t__month5[9],
		-- {[519] = 1, __size = 1}
		month6 = __data_t__month6[9],
		-- {[519] = 1, __size = 1}
		month7 = __data_t__month7[9],
		-- {[519] = 1, __size = 1}
		month8 = __data_t__month8[9],
		-- {[519] = 1, __size = 1}
		month9 = __data_t__month9[9],
		-- {[519] = 1, __size = 1}
		month10 = __data_t__month10[9],
		-- {[519] = 1, __size = 1}
		month11 = __data_t__month11[9],
		-- {[519] = 1, __size = 1}
		month12 = __data_t__month12[9]
		-- {[519] = 1, __size = 1}
	},
	[10] = {
		id = 10,
		vipDouble = 4,
		months = __data_t__months[10],
		-- {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
		month1 = __data_t__month1[10],
		-- {[20591] = 5, __size = 1}
		month2 = __data_t__month2[10],
		-- {[21311] = 5, __size = 1}
		month3 = __data_t__month3[10],
		-- {[20261] = 5, __size = 1}
		month4 = __data_t__month4[10],
		-- {[23141] = 5, __size = 1}
		month5 = __data_t__month5[10],
		-- {[20391] = 5, __size = 1}
		month6 = __data_t__month6[10],
		-- {[21501] = 5, __size = 1}
		month7 = __data_t__month7[10],
		-- {[23021] = 5, __size = 1}
		month8 = __data_t__month8[10],
		-- {[23001] = 5, __size = 1}
		month9 = __data_t__month9[10],
		-- {[23591] = 5, __size = 1}
		month10 = __data_t__month10[10],
		-- {[21421] = 5, __size = 1}
		month11 = __data_t__month11[10],
		-- {[21231] = 5, __size = 1}
		month12 = __data_t__month12[10]
		-- {[20491] = 5, __size = 1}
	},
	[11] = {
		id = 11,
		vipDouble = 5,
		month1 = __data_t__month1[11],
		-- {['gold'] = 70000, __size = 1}
		month2 = __data_t__month2[11],
		-- {['gold'] = 70000, __size = 1}
		month3 = __data_t__month3[11],
		-- {['gold'] = 70000, __size = 1}
		month4 = __data_t__month4[11],
		-- {['gold'] = 70000, __size = 1}
		month5 = __data_t__month5[11],
		-- {['gold'] = 70000, __size = 1}
		month6 = __data_t__month6[11],
		-- {['gold'] = 70000, __size = 1}
		month7 = __data_t__month7[11],
		-- {['gold'] = 70000, __size = 1}
		month8 = __data_t__month8[11],
		-- {['gold'] = 70000, __size = 1}
		month9 = __data_t__month9[11],
		-- {['gold'] = 70000, __size = 1}
		month10 = __data_t__month10[11],
		-- {['gold'] = 70000, __size = 1}
		month11 = __data_t__month11[11],
		-- {['gold'] = 70000, __size = 1}
		month12 = __data_t__month12[11]
		-- {['gold'] = 70000, __size = 1}
	},
	[12] = {
		id = 12,
		month1 = __data_t__month1[12],
		-- {['rmb'] = 40, __size = 1}
		month2 = __data_t__month2[12],
		-- {['rmb'] = 40, __size = 1}
		month3 = __data_t__month3[12],
		-- {['rmb'] = 40, __size = 1}
		month4 = __data_t__month4[12],
		-- {['rmb'] = 40, __size = 1}
		month5 = __data_t__month5[12],
		-- {['rmb'] = 40, __size = 1}
		month6 = __data_t__month6[12],
		-- {['rmb'] = 40, __size = 1}
		month7 = __data_t__month7[12],
		-- {['rmb'] = 40, __size = 1}
		month8 = __data_t__month8[12],
		-- {['rmb'] = 40, __size = 1}
		month9 = __data_t__month9[12],
		-- {['rmb'] = 40, __size = 1}
		month10 = __data_t__month10[12],
		-- {['rmb'] = 40, __size = 1}
		month11 = __data_t__month11[12],
		-- {['rmb'] = 40, __size = 1}
		month12 = __data_t__month12[12]
		-- {['rmb'] = 40, __size = 1}
	},
	[13] = {
		id = 13,
		vipDouble = 6,
		month1 = __data_t__month1[13],
		-- {[503] = 1, __size = 1}
		month2 = __data_t__month2[13],
		-- {[503] = 1, __size = 1}
		month3 = __data_t__month3[13],
		-- {[503] = 1, __size = 1}
		month4 = __data_t__month4[13],
		-- {[503] = 1, __size = 1}
		month5 = __data_t__month5[13],
		-- {[503] = 1, __size = 1}
		month6 = __data_t__month6[13],
		-- {[503] = 1, __size = 1}
		month7 = __data_t__month7[13],
		-- {[503] = 1, __size = 1}
		month8 = __data_t__month8[13],
		-- {[503] = 1, __size = 1}
		month9 = __data_t__month9[13],
		-- {[503] = 1, __size = 1}
		month10 = __data_t__month10[13],
		-- {[503] = 1, __size = 1}
		month11 = __data_t__month11[13],
		-- {[503] = 1, __size = 1}
		month12 = __data_t__month12[13]
		-- {[503] = 1, __size = 1}
	},
	[14] = {
		id = 14,
		months = __data_t__months[14],
		-- {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
		month1 = __data_t__month1[14],
		-- {[519] = 1, __size = 1}
		month2 = __data_t__month2[14],
		-- {[519] = 1, __size = 1}
		month3 = __data_t__month3[14],
		-- {[519] = 1, __size = 1}
		month4 = __data_t__month4[14],
		-- {[519] = 1, __size = 1}
		month5 = __data_t__month5[14],
		-- {[519] = 1, __size = 1}
		month6 = __data_t__month6[14],
		-- {[519] = 1, __size = 1}
		month7 = __data_t__month7[14],
		-- {[519] = 1, __size = 1}
		month8 = __data_t__month8[14],
		-- {[519] = 1, __size = 1}
		month9 = __data_t__month9[14],
		-- {[519] = 1, __size = 1}
		month10 = __data_t__month10[14],
		-- {[519] = 1, __size = 1}
		month11 = __data_t__month11[14],
		-- {[519] = 1, __size = 1}
		month12 = __data_t__month12[14]
		-- {[519] = 1, __size = 1}
	},
	[15] = {
		id = 15,
		vipDouble = 7,
		months = __data_t__months[15],
		-- {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
		month1 = __data_t__month1[15],
		-- {[20591] = 5, __size = 1}
		month2 = __data_t__month2[15],
		-- {[21311] = 5, __size = 1}
		month3 = __data_t__month3[15],
		-- {[20261] = 5, __size = 1}
		month4 = __data_t__month4[15],
		-- {[23141] = 5, __size = 1}
		month5 = __data_t__month5[15],
		-- {[20391] = 5, __size = 1}
		month6 = __data_t__month6[15],
		-- {[21501] = 5, __size = 1}
		month7 = __data_t__month7[15],
		-- {[23021] = 5, __size = 1}
		month8 = __data_t__month8[15],
		-- {[23001] = 5, __size = 1}
		month9 = __data_t__month9[15],
		-- {[23591] = 5, __size = 1}
		month10 = __data_t__month10[15],
		-- {[21421] = 5, __size = 1}
		month11 = __data_t__month11[15],
		-- {[21231] = 5, __size = 1}
		month12 = __data_t__month12[15]
		-- {[20491] = 5, __size = 1}
	},
	[16] = {
		id = 16,
		vipDouble = 8,
		month1 = __data_t__month1[16],
		-- {['gold'] = 80000, __size = 1}
		month2 = __data_t__month2[16],
		-- {['gold'] = 80000, __size = 1}
		month3 = __data_t__month3[16],
		-- {['gold'] = 80000, __size = 1}
		month4 = __data_t__month4[16],
		-- {['gold'] = 80000, __size = 1}
		month5 = __data_t__month5[16],
		-- {['gold'] = 80000, __size = 1}
		month6 = __data_t__month6[16],
		-- {['gold'] = 80000, __size = 1}
		month7 = __data_t__month7[16],
		-- {['gold'] = 80000, __size = 1}
		month8 = __data_t__month8[16],
		-- {['gold'] = 80000, __size = 1}
		month9 = __data_t__month9[16],
		-- {['gold'] = 80000, __size = 1}
		month10 = __data_t__month10[16],
		-- {['gold'] = 80000, __size = 1}
		month11 = __data_t__month11[16],
		-- {['gold'] = 80000, __size = 1}
		month12 = __data_t__month12[16]
		-- {['gold'] = 80000, __size = 1}
	},
	[17] = {
		id = 17,
		month1 = __data_t__month1[17],
		-- {['rmb'] = 45, __size = 1}
		month2 = __data_t__month2[17],
		-- {['rmb'] = 45, __size = 1}
		month3 = __data_t__month3[17],
		-- {['rmb'] = 45, __size = 1}
		month4 = __data_t__month4[17],
		-- {['rmb'] = 45, __size = 1}
		month5 = __data_t__month5[17],
		-- {['rmb'] = 45, __size = 1}
		month6 = __data_t__month6[17],
		-- {['rmb'] = 45, __size = 1}
		month7 = __data_t__month7[17],
		-- {['rmb'] = 45, __size = 1}
		month8 = __data_t__month8[17],
		-- {['rmb'] = 45, __size = 1}
		month9 = __data_t__month9[17],
		-- {['rmb'] = 45, __size = 1}
		month10 = __data_t__month10[17],
		-- {['rmb'] = 45, __size = 1}
		month11 = __data_t__month11[17],
		-- {['rmb'] = 45, __size = 1}
		month12 = __data_t__month12[17]
		-- {['rmb'] = 45, __size = 1}
	},
	[18] = {
		id = 18,
		vipDouble = 9,
		month1 = __data_t__month1[18],
		-- {[503] = 1, __size = 1}
		month2 = __data_t__month2[18],
		-- {[503] = 1, __size = 1}
		month3 = __data_t__month3[18],
		-- {[503] = 1, __size = 1}
		month4 = __data_t__month4[18],
		-- {[503] = 1, __size = 1}
		month5 = __data_t__month5[18],
		-- {[503] = 1, __size = 1}
		month6 = __data_t__month6[18],
		-- {[503] = 1, __size = 1}
		month7 = __data_t__month7[18],
		-- {[503] = 1, __size = 1}
		month8 = __data_t__month8[18],
		-- {[503] = 1, __size = 1}
		month9 = __data_t__month9[18],
		-- {[503] = 1, __size = 1}
		month10 = __data_t__month10[18],
		-- {[503] = 1, __size = 1}
		month11 = __data_t__month11[18],
		-- {[503] = 1, __size = 1}
		month12 = __data_t__month12[18]
		-- {[503] = 1, __size = 1}
	},
	[19] = {
		id = 19,
		month1 = __data_t__month1[19],
		-- {[519] = 1, __size = 1}
		month2 = __data_t__month2[19],
		-- {[519] = 1, __size = 1}
		month3 = __data_t__month3[19],
		-- {[519] = 1, __size = 1}
		month4 = __data_t__month4[19],
		-- {[519] = 1, __size = 1}
		month5 = __data_t__month5[19],
		-- {[519] = 1, __size = 1}
		month6 = __data_t__month6[19],
		-- {[519] = 1, __size = 1}
		month7 = __data_t__month7[19],
		-- {[519] = 1, __size = 1}
		month8 = __data_t__month8[19],
		-- {[519] = 1, __size = 1}
		month9 = __data_t__month9[19],
		-- {[519] = 1, __size = 1}
		month10 = __data_t__month10[19],
		-- {[519] = 1, __size = 1}
		month11 = __data_t__month11[19],
		-- {[519] = 1, __size = 1}
		month12 = __data_t__month12[19]
		-- {[519] = 1, __size = 1}
	},
	[20] = {
		id = 20,
		vipDouble = 10,
		months = __data_t__months[20],
		-- {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
		month1 = __data_t__month1[20],
		-- {[20591] = 8, __size = 1}
		month2 = __data_t__month2[20],
		-- {[21311] = 8, __size = 1}
		month3 = __data_t__month3[20],
		-- {[20261] = 8, __size = 1}
		month4 = __data_t__month4[20],
		-- {[23141] = 8, __size = 1}
		month5 = __data_t__month5[20],
		-- {[20391] = 8, __size = 1}
		month6 = __data_t__month6[20],
		-- {[21501] = 8, __size = 1}
		month7 = __data_t__month7[20],
		-- {[23021] = 8, __size = 1}
		month8 = __data_t__month8[20],
		-- {[23001] = 8, __size = 1}
		month9 = __data_t__month9[20],
		-- {[23591] = 8, __size = 1}
		month10 = __data_t__month10[20],
		-- {[21421] = 8, __size = 1}
		month11 = __data_t__month11[20],
		-- {[21231] = 8, __size = 1}
		month12 = __data_t__month12[20]
		-- {[20491] = 8, __size = 1}
	},
	[21] = {
		id = 21,
		vipDouble = 10,
		month1 = __data_t__month1[21],
		-- {['gold'] = 90000, __size = 1}
		month2 = __data_t__month2[21],
		-- {['gold'] = 90000, __size = 1}
		month3 = __data_t__month3[21],
		-- {['gold'] = 90000, __size = 1}
		month4 = __data_t__month4[21],
		-- {['gold'] = 90000, __size = 1}
		month5 = __data_t__month5[21],
		-- {['gold'] = 90000, __size = 1}
		month6 = __data_t__month6[21],
		-- {['gold'] = 90000, __size = 1}
		month7 = __data_t__month7[21],
		-- {['gold'] = 90000, __size = 1}
		month8 = __data_t__month8[21],
		-- {['gold'] = 90000, __size = 1}
		month9 = __data_t__month9[21],
		-- {['gold'] = 90000, __size = 1}
		month10 = __data_t__month10[21],
		-- {['gold'] = 90000, __size = 1}
		month11 = __data_t__month11[21],
		-- {['gold'] = 90000, __size = 1}
		month12 = __data_t__month12[21]
		-- {['gold'] = 90000, __size = 1}
	},
	[22] = {
		id = 22,
		month1 = __data_t__month1[22],
		-- {['rmb'] = 50, __size = 1}
		month2 = __data_t__month2[22],
		-- {['rmb'] = 50, __size = 1}
		month3 = __data_t__month3[22],
		-- {['rmb'] = 50, __size = 1}
		month4 = __data_t__month4[22],
		-- {['rmb'] = 50, __size = 1}
		month5 = __data_t__month5[22],
		-- {['rmb'] = 50, __size = 1}
		month6 = __data_t__month6[22],
		-- {['rmb'] = 50, __size = 1}
		month7 = __data_t__month7[22],
		-- {['rmb'] = 50, __size = 1}
		month8 = __data_t__month8[22],
		-- {['rmb'] = 50, __size = 1}
		month9 = __data_t__month9[22],
		-- {['rmb'] = 50, __size = 1}
		month10 = __data_t__month10[22],
		-- {['rmb'] = 50, __size = 1}
		month11 = __data_t__month11[22],
		-- {['rmb'] = 50, __size = 1}
		month12 = __data_t__month12[22]
		-- {['rmb'] = 50, __size = 1}
	},
	[23] = {
		id = 23,
		vipDouble = 11,
		month1 = __data_t__month1[23],
		-- {[503] = 1, __size = 1}
		month2 = __data_t__month2[23],
		-- {[503] = 1, __size = 1}
		month3 = __data_t__month3[23],
		-- {[503] = 1, __size = 1}
		month4 = __data_t__month4[23],
		-- {[503] = 1, __size = 1}
		month5 = __data_t__month5[23],
		-- {[503] = 1, __size = 1}
		month6 = __data_t__month6[23],
		-- {[503] = 1, __size = 1}
		month7 = __data_t__month7[23],
		-- {[503] = 1, __size = 1}
		month8 = __data_t__month8[23],
		-- {[503] = 1, __size = 1}
		month9 = __data_t__month9[23],
		-- {[503] = 1, __size = 1}
		month10 = __data_t__month10[23],
		-- {[503] = 1, __size = 1}
		month11 = __data_t__month11[23],
		-- {[503] = 1, __size = 1}
		month12 = __data_t__month12[23]
		-- {[503] = 1, __size = 1}
	},
	[24] = {
		id = 24,
		month1 = __data_t__month1[24],
		-- {[519] = 1, __size = 1}
		month2 = __data_t__month2[24],
		-- {[519] = 1, __size = 1}
		month3 = __data_t__month3[24],
		-- {[519] = 1, __size = 1}
		month4 = __data_t__month4[24],
		-- {[519] = 1, __size = 1}
		month5 = __data_t__month5[24],
		-- {[519] = 1, __size = 1}
		month6 = __data_t__month6[24],
		-- {[519] = 1, __size = 1}
		month7 = __data_t__month7[24],
		-- {[519] = 1, __size = 1}
		month8 = __data_t__month8[24],
		-- {[519] = 1, __size = 1}
		month9 = __data_t__month9[24],
		-- {[519] = 1, __size = 1}
		month10 = __data_t__month10[24],
		-- {[519] = 1, __size = 1}
		month11 = __data_t__month11[24],
		-- {[519] = 1, __size = 1}
		month12 = __data_t__month12[24]
		-- {[519] = 1, __size = 1}
	},
	[25] = {
		id = 25,
		vipDouble = 12,
		months = __data_t__months[25],
		-- {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
		month1 = __data_t__month1[25],
		-- {[20591] = 8, __size = 1}
		month2 = __data_t__month2[25],
		-- {[21311] = 8, __size = 1}
		month3 = __data_t__month3[25],
		-- {[20261] = 8, __size = 1}
		month4 = __data_t__month4[25],
		-- {[23141] = 8, __size = 1}
		month5 = __data_t__month5[25],
		-- {[20391] = 8, __size = 1}
		month6 = __data_t__month6[25],
		-- {[21501] = 8, __size = 1}
		month7 = __data_t__month7[25],
		-- {[23021] = 8, __size = 1}
		month8 = __data_t__month8[25],
		-- {[23001] = 8, __size = 1}
		month9 = __data_t__month9[25],
		-- {[23591] = 8, __size = 1}
		month10 = __data_t__month10[25],
		-- {[21421] = 8, __size = 1}
		month11 = __data_t__month11[25],
		-- {[21231] = 8, __size = 1}
		month12 = __data_t__month12[25]
		-- {[20491] = 8, __size = 1}
	},
	[26] = {
		id = 26,
		vipDouble = 13,
		month1 = __data_t__month1[26],
		-- {['gold'] = 100000, __size = 1}
		month2 = __data_t__month2[26],
		-- {['gold'] = 100000, __size = 1}
		month3 = __data_t__month3[26],
		-- {['gold'] = 100000, __size = 1}
		month4 = __data_t__month4[26],
		-- {['gold'] = 100000, __size = 1}
		month5 = __data_t__month5[26],
		-- {['gold'] = 100000, __size = 1}
		month6 = __data_t__month6[26],
		-- {['gold'] = 100000, __size = 1}
		month7 = __data_t__month7[26],
		-- {['gold'] = 100000, __size = 1}
		month8 = __data_t__month8[26],
		-- {['gold'] = 100000, __size = 1}
		month9 = __data_t__month9[26],
		-- {['gold'] = 100000, __size = 1}
		month10 = __data_t__month10[26],
		-- {['gold'] = 100000, __size = 1}
		month11 = __data_t__month11[26],
		-- {['gold'] = 100000, __size = 1}
		month12 = __data_t__month12[26]
		-- {['gold'] = 100000, __size = 1}
	},
	[27] = {
		id = 27,
		month1 = __data_t__month1[27],
		-- {['rmb'] = 50, __size = 1}
		month2 = __data_t__month2[27],
		-- {['rmb'] = 50, __size = 1}
		month3 = __data_t__month3[27],
		-- {['rmb'] = 50, __size = 1}
		month4 = __data_t__month4[27],
		-- {['rmb'] = 50, __size = 1}
		month5 = __data_t__month5[27],
		-- {['rmb'] = 50, __size = 1}
		month6 = __data_t__month6[27],
		-- {['rmb'] = 50, __size = 1}
		month7 = __data_t__month7[27],
		-- {['rmb'] = 50, __size = 1}
		month8 = __data_t__month8[27],
		-- {['rmb'] = 50, __size = 1}
		month9 = __data_t__month9[27],
		-- {['rmb'] = 50, __size = 1}
		month10 = __data_t__month10[27],
		-- {['rmb'] = 50, __size = 1}
		month11 = __data_t__month11[27],
		-- {['rmb'] = 50, __size = 1}
		month12 = __data_t__month12[27]
		-- {['rmb'] = 50, __size = 1}
	},
	[28] = {
		id = 28,
		vipDouble = 14,
		month1 = __data_t__month1[28],
		-- {[503] = 1, __size = 1}
		month2 = __data_t__month2[28],
		-- {[503] = 1, __size = 1}
		month3 = __data_t__month3[28],
		-- {[503] = 1, __size = 1}
		month4 = __data_t__month4[28],
		-- {[503] = 1, __size = 1}
		month5 = __data_t__month5[28],
		-- {[503] = 1, __size = 1}
		month6 = __data_t__month6[28],
		-- {[503] = 1, __size = 1}
		month7 = __data_t__month7[28],
		-- {[503] = 1, __size = 1}
		month8 = __data_t__month8[28],
		-- {[503] = 1, __size = 1}
		month9 = __data_t__month9[28],
		-- {[503] = 1, __size = 1}
		month10 = __data_t__month10[28],
		-- {[503] = 1, __size = 1}
		month11 = __data_t__month11[28],
		-- {[503] = 1, __size = 1}
		month12 = __data_t__month12[28]
		-- {[503] = 1, __size = 1}
	},
	[29] = {
		id = 29,
		month1 = __data_t__month1[29],
		-- {[519] = 1, __size = 1}
		month2 = __data_t__month2[29],
		-- {[519] = 1, __size = 1}
		month3 = __data_t__month3[29],
		-- {[519] = 1, __size = 1}
		month4 = __data_t__month4[29],
		-- {[519] = 1, __size = 1}
		month5 = __data_t__month5[29],
		-- {[519] = 1, __size = 1}
		month6 = __data_t__month6[29],
		-- {[519] = 1, __size = 1}
		month7 = __data_t__month7[29],
		-- {[519] = 1, __size = 1}
		month8 = __data_t__month8[29],
		-- {[519] = 1, __size = 1}
		month9 = __data_t__month9[29],
		-- {[519] = 1, __size = 1}
		month10 = __data_t__month10[29],
		-- {[519] = 1, __size = 1}
		month11 = __data_t__month11[29],
		-- {[519] = 1, __size = 1}
		month12 = __data_t__month12[29]
		-- {[519] = 1, __size = 1}
	},
	[30] = {
		id = 30,
		vipDouble = 15,
		months = __data_t__months[30],
		-- {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
		month1 = {[20591] = 10, __size = 1},
		month2 = {[21311] = 10, __size = 1},
		month3 = {[20261] = 10, __size = 1},
		month4 = {[23141] = 10, __size = 1},
		month5 = {[20391] = 10, __size = 1},
		month6 = {[21501] = 10, __size = 1},
		month7 = {[23021] = 10, __size = 1},
		month8 = {[23001] = 10, __size = 1},
		month9 = {[23591] = 10, __size = 1},
		month10 = {[21421] = 10, __size = 1},
		month11 = {[21231] = 10, __size = 1},
		month12 = {[20491] = 10, __size = 1}
	},
	[31] = {
		id = 31,
		vipDouble = 15,
		month1 = __data_t__month1[31],
		-- {['gold'] = 100000, __size = 1}
		month2 = __data_t__month2[31],
		-- {['gold'] = 100000, __size = 1}
		month3 = __data_t__month3[31],
		-- {['gold'] = 100000, __size = 1}
		month4 = __data_t__month4[31],
		-- {['gold'] = 100000, __size = 1}
		month5 = __data_t__month5[31],
		-- {['gold'] = 100000, __size = 1}
		month6 = __data_t__month6[31],
		-- {['gold'] = 100000, __size = 1}
		month7 = __data_t__month7[31],
		-- {['gold'] = 100000, __size = 1}
		month8 = __data_t__month8[31],
		-- {['gold'] = 100000, __size = 1}
		month9 = __data_t__month9[31],
		-- {['gold'] = 100000, __size = 1}
		month10 = __data_t__month10[31],
		-- {['gold'] = 100000, __size = 1}
		month11 = __data_t__month11[31],
		-- {['gold'] = 100000, __size = 1}
		month12 = __data_t__month12[31]
		-- {['gold'] = 100000, __size = 1}
	},
	[101] = {
		id = 101,
		month1 = __data_t__month1[101],
		-- {[19] = 5, ['gold'] = 200000, __size = 2}
		month2 = __data_t__month2[101],
		-- {[19] = 5, ['gold'] = 200000, __size = 2}
		month3 = __data_t__month3[101],
		-- {[19] = 5, ['gold'] = 200000, __size = 2}
		month4 = __data_t__month4[101],
		-- {[19] = 5, ['gold'] = 200000, __size = 2}
		month5 = __data_t__month5[101],
		-- {[19] = 5, ['gold'] = 200000, __size = 2}
		month6 = __data_t__month6[101],
		-- {[19] = 5, ['gold'] = 200000, __size = 2}
		month7 = __data_t__month7[101],
		-- {[19] = 5, ['gold'] = 200000, __size = 2}
		month8 = __data_t__month8[101],
		-- {[19] = 5, ['gold'] = 200000, __size = 2}
		month9 = __data_t__month9[101],
		-- {[19] = 5, ['gold'] = 200000, __size = 2}
		month10 = __data_t__month10[101],
		-- {[19] = 5, ['gold'] = 200000, __size = 2}
		month11 = __data_t__month11[101],
		-- {[19] = 5, ['gold'] = 200000, __size = 2}
		month12 = __data_t__month12[101]
		-- {[19] = 5, ['gold'] = 200000, __size = 2}
	},
	[102] = {
		id = 102,
		month1 = __data_t__month1[102],
		-- {['rmb'] = 150, [502] = 3, __size = 2}
		month2 = __data_t__month2[102],
		-- {['rmb'] = 150, [502] = 3, __size = 2}
		month3 = __data_t__month3[102],
		-- {['rmb'] = 150, [502] = 3, __size = 2}
		month4 = __data_t__month4[102],
		-- {['rmb'] = 150, [502] = 3, __size = 2}
		month5 = __data_t__month5[102],
		-- {['rmb'] = 150, [502] = 3, __size = 2}
		month6 = __data_t__month6[102],
		-- {['rmb'] = 150, [502] = 3, __size = 2}
		month7 = __data_t__month7[102],
		-- {['rmb'] = 150, [502] = 3, __size = 2}
		month8 = __data_t__month8[102],
		-- {['rmb'] = 150, [502] = 3, __size = 2}
		month9 = __data_t__month9[102],
		-- {['rmb'] = 150, [502] = 3, __size = 2}
		month10 = __data_t__month10[102],
		-- {['rmb'] = 150, [502] = 3, __size = 2}
		month11 = __data_t__month11[102],
		-- {['rmb'] = 150, [502] = 3, __size = 2}
		month12 = __data_t__month12[102]
		-- {['rmb'] = 150, [502] = 3, __size = 2}
	},
	[103] = {
		id = 103,
		month1 = __data_t__month1[103],
		-- {[521] = 3, [501] = 2, __size = 2}
		month2 = __data_t__month2[103],
		-- {[521] = 3, [501] = 2, __size = 2}
		month3 = __data_t__month3[103],
		-- {[521] = 3, [501] = 2, __size = 2}
		month4 = __data_t__month4[103],
		-- {[521] = 3, [501] = 2, __size = 2}
		month5 = __data_t__month5[103],
		-- {[521] = 3, [501] = 2, __size = 2}
		month6 = __data_t__month6[103],
		-- {[521] = 3, [501] = 2, __size = 2}
		month7 = __data_t__month7[103],
		-- {[521] = 3, [501] = 2, __size = 2}
		month8 = __data_t__month8[103],
		-- {[521] = 3, [501] = 2, __size = 2}
		month9 = __data_t__month9[103],
		-- {[521] = 3, [501] = 2, __size = 2}
		month10 = __data_t__month10[103],
		-- {[521] = 3, [501] = 2, __size = 2}
		month11 = __data_t__month11[103],
		-- {[521] = 3, [501] = 2, __size = 2}
		month12 = __data_t__month12[103]
		-- {[521] = 3, [501] = 2, __size = 2}
	},
	[1000] = {
		id = 1000,
		month1 = {['card'] = 593, __size = 1},
		month2 = {['card'] = 1313, __size = 1},
		month3 = {['card'] = 263, __size = 1},
		month4 = {['card'] = 3143, __size = 1},
		month5 = {['card'] = 393, __size = 1},
		month6 = {['card'] = 1503, __size = 1},
		month7 = {['card'] = 3021, __size = 1},
		month8 = {['card'] = 3003, __size = 1},
		month9 = {['card'] = 3592, __size = 1},
		month10 = {['card'] = 1423, __size = 1},
		month11 = {['card'] = 1231, __size = 1},
		month12 = {['card'] = 493, __size = 1}
	},
	__size = 35,
	__default = {
		__index = {
			vipDouble = 9999,
			months = {},
			month1 = __data_t__month1["default"]	--[[ {__size = 0}]],
			month2 = __data_t__month2["default"]	--[[ {__size = 0}]],
			month3 = __data_t__month3["default"]	--[[ {__size = 0}]],
			month4 = __data_t__month4["default"]	--[[ {__size = 0}]],
			month5 = __data_t__month5["default"]	--[[ {__size = 0}]],
			month6 = __data_t__month6["default"]	--[[ {__size = 0}]],
			month7 = __data_t__month7["default"]	--[[ {__size = 0}]],
			month8 = __data_t__month8["default"]	--[[ {__size = 0}]],
			month9 = __data_t__month9["default"]	--[[ {__size = 0}]],
			month10 = __data_t__month10["default"]	--[[ {__size = 0}]],
			month11 = __data_t__month11["default"]	--[[ {__size = 0}]],
			month12 = __data_t__month12["default"]	--[[ {__size = 0}]]
		}
	}
}
return csv.signin