--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[3] = {1, 100}, 
	[7] = {250, 250}, 
	[8] = {[5000] = 10, __size = 1}, 
	[10] = {[514] = 10, __size = 1}, 
	[15] = {['coin3'] = 1500, __size = 1}, 
	[18] = {['coin3'] = 900, __size = 1}, 
	[26] = {[535] = 2500, __size = 1}, 
	[27] = {1, 250}, 
	[32] = {[535] = 1800, __size = 1}, 
	[36] = {[535] = 1000, __size = 1}, 
	[42] = {[535] = 600, __size = 1}, __size = 11}
local __data_t__itemWeightMap = {
	[26] = __predefine_t__[8],
	[27] = __predefine_t__[10],
	[3021] = __predefine_t__[10],
	[3011] = __predefine_t__[8]
}
local __data_t__levelRange = {
	[3011] = __predefine_t__[27],
	[10001] = __predefine_t__[27],
	["default"] = __predefine_t__[3],
	[3001] = __predefine_t__[27],
	[2051] = __predefine_t__[27],
	[25] = __predefine_t__[7],
	[26] = __predefine_t__[7],
	[27] = __predefine_t__[7],
	[42] = __predefine_t__[7],
	[43] = __predefine_t__[7],
	[3021] = __predefine_t__[27],
	[41] = __predefine_t__[7],
	[2035] = __predefine_t__[27],
	[2031] = __predefine_t__[27],
	[2071] = __predefine_t__[27],
	[2011] = __predefine_t__[27],
	[2041] = __predefine_t__[27],
	[33] = __predefine_t__[7],
	[32] = __predefine_t__[7],
	[31] = __predefine_t__[7],
	[2081] = __predefine_t__[27],
	[37] = __predefine_t__[7],
	[36] = __predefine_t__[7],
	[35] = __predefine_t__[7],
	[34] = __predefine_t__[7],
	[3012] = __predefine_t__[27],
	[2001] = __predefine_t__[27],
	[2021] = __predefine_t__[27],
	[2061] = __predefine_t__[27]
}
local __data_t__costMap = {
	[2051] = __predefine_t__[36],
	[3011] = __predefine_t__[36],
	[43] = __predefine_t__[15],
	[2041] = __predefine_t__[32],
	[33] = __predefine_t__[15],
	[32] = __predefine_t__[15],
	[42] = __predefine_t__[15],
	[37] = __predefine_t__[18],
	[36] = __predefine_t__[18],
	[35] = __predefine_t__[18],
	[34] = __predefine_t__[18],
	[3012] = __predefine_t__[36],
	[2035] = __predefine_t__[32],
	[2001] = __predefine_t__[26],
	[3001] = __predefine_t__[42],
	[3021] = __predefine_t__[42],
	[2031] = __predefine_t__[32],
	[2061] = __predefine_t__[36],
	[2071] = __predefine_t__[36],
	[41] = __predefine_t__[15],
	[2011] = __predefine_t__[26]
}
local __data_t__fishingLevelRange = {
	[2051] = __predefine_t__[27],
	[3011] = __predefine_t__[27],
	[10001] = __predefine_t__[27],
	[2041] = __predefine_t__[27],
	[3012] = __predefine_t__[27],
	[2081] = __predefine_t__[27],
	[3021] = __predefine_t__[27],
	["default"] = __predefine_t__[3],
	[2035] = __predefine_t__[27],
	[2001] = __predefine_t__[27],
	[3001] = __predefine_t__[27],
	[2021] = __predefine_t__[27],
	[2031] = __predefine_t__[27],
	[2061] = __predefine_t__[27],
	[2071] = __predefine_t__[27],
	[2011] = __predefine_t__[27]
}

csv['fishing']['shop'] = {
	[25] = {
		id = 25,
		itemWeightMap = {[452] = 10, __size = 1},
		itemCount = 10,
		costMap = {['coin3'] = 500, __size = 1},
		vipWeight = 0,
		position = 12,
		levelRange = __data_t__levelRange[25]
		-- {250, 250}
	},
	[26] = {
		id = 26,
		itemWeightMap = __data_t__itemWeightMap[26],
		-- {[5000] = 10, __size = 1}
		itemCount = 20,
		costMap = {['coin3'] = 400, __size = 1},
		vipWeight = 0,
		position = 13,
		levelRange = __data_t__levelRange[26]
		-- {250, 250}
	},
	[27] = {
		id = 27,
		itemWeightMap = __data_t__itemWeightMap[27],
		-- {[514] = 10, __size = 1}
		itemCount = 5,
		costMap = {['coin3'] = 200, __size = 1},
		vipWeight = 0,
		position = 14,
		levelRange = __data_t__levelRange[27]
		-- {250, 250}
	},
	[31] = {
		id = 31,
		itemWeightMap = {[23541] = 10, __size = 1},
		itemCount = 5,
		costMap = {['coin3'] = 2000, __size = 1},
		vipWeight = 0,
		levelRange = __data_t__levelRange[31]
		-- {250, 250}
	},
	[32] = {
		id = 32,
		itemWeightMap = {[23021] = 10, __size = 1},
		itemCount = 5,
		costMap = __data_t__costMap[32],
		-- {['coin3'] = 1500, __size = 1}
		vipWeight = 0,
		position = 1,
		levelRange = __data_t__levelRange[32]
		-- {250, 250}
	},
	[33] = {
		id = 33,
		itemWeightMap = {[20491] = 10, __size = 1},
		itemCount = 5,
		costMap = __data_t__costMap[33],
		-- {['coin3'] = 1500, __size = 1}
		vipWeight = 0,
		position = 2,
		levelRange = __data_t__levelRange[33]
		-- {250, 250}
	},
	[34] = {
		id = 34,
		itemWeightMap = {[20271] = 10, __size = 1},
		itemCount = 5,
		costMap = __data_t__costMap[34],
		-- {['coin3'] = 900, __size = 1}
		vipWeight = 0,
		position = 6,
		levelRange = __data_t__levelRange[34]
		-- {250, 250}
	},
	[35] = {
		id = 35,
		itemWeightMap = {[22011] = 10, __size = 1},
		itemCount = 5,
		costMap = __data_t__costMap[35],
		-- {['coin3'] = 900, __size = 1}
		vipWeight = 0,
		position = 7,
		levelRange = __data_t__levelRange[35]
		-- {250, 250}
	},
	[36] = {
		id = 36,
		itemWeightMap = {[20471] = 10, __size = 1},
		itemCount = 5,
		costMap = __data_t__costMap[36],
		-- {['coin3'] = 900, __size = 1}
		vipWeight = 0,
		position = 8,
		levelRange = __data_t__levelRange[36]
		-- {250, 250}
	},
	[37] = {
		id = 37,
		itemWeightMap = {[20001] = 10, __size = 1},
		itemCount = 5,
		costMap = __data_t__costMap[37],
		-- {['coin3'] = 900, __size = 1}
		vipWeight = 0,
		position = 9,
		levelRange = __data_t__levelRange[37]
		-- {250, 250}
	},
	[41] = {
		id = 41,
		itemWeightMap = {[21311] = 10, __size = 1},
		itemCount = 5,
		costMap = __data_t__costMap[41],
		-- {['coin3'] = 1500, __size = 1}
		vipWeight = 0,
		position = 3,
		levelRange = __data_t__levelRange[41]
		-- {250, 250}
	},
	[42] = {
		id = 42,
		itemWeightMap = {[20731] = 10, __size = 1},
		itemCount = 5,
		costMap = __data_t__costMap[42],
		-- {['coin3'] = 1500, __size = 1}
		vipWeight = 0,
		position = 4,
		levelRange = __data_t__levelRange[42]
		-- {250, 250}
	},
	[43] = {
		id = 43,
		itemWeightMap = {[21081] = 10, __size = 1},
		itemCount = 5,
		costMap = __data_t__costMap[43],
		-- {['coin3'] = 1500, __size = 1}
		vipWeight = 0,
		position = 5,
		levelRange = __data_t__levelRange[43]
		-- {250, 250}
	},
	[2001] = {
		id = 2001,
		itemWeightMap = {[21931] = 10, __size = 1},
		itemCount = 5,
		costMap = __data_t__costMap[2001],
		-- {[535] = 2500, __size = 1}
		vipWeight = 100,
		levelRange = __data_t__levelRange[2001],
		-- {1, 250}
		fishingLevelRange = __data_t__fishingLevelRange[2001]
		-- {1, 250}
	},
	[2011] = {
		id = 2011,
		itemWeightMap = {[21911] = 10, __size = 1},
		itemCount = 5,
		costMap = __data_t__costMap[2011],
		-- {[535] = 2500, __size = 1}
		vipWeight = 100,
		position = 1,
		levelRange = __data_t__levelRange[2011],
		-- {1, 250}
		fishingLevelRange = __data_t__fishingLevelRange[2011],
		-- {1, 250}
		showUnable = true
	},
	[2021] = {
		id = 2021,
		itemWeightMap = {[21921] = 10, __size = 1},
		itemCount = 5,
		costMap = {[535] = 3200, __size = 1},
		vipWeight = 100,
		position = 2,
		levelRange = __data_t__levelRange[2021],
		-- {1, 250}
		fishingLevelRange = __data_t__fishingLevelRange[2021],
		-- {1, 250}
		showUnable = true
	},
	[2031] = {
		id = 2031,
		itemWeightMap = {[23591] = 10, __size = 1},
		itemCount = 5,
		costMap = __data_t__costMap[2031],
		-- {[535] = 1800, __size = 1}
		vipWeight = 100,
		position = 3,
		levelRange = __data_t__levelRange[2031],
		-- {1, 250}
		fishingLevelRange = __data_t__fishingLevelRange[2031]
		-- {1, 250}
	},
	[2035] = {
		id = 2035,
		itemWeightMap = {[20161] = 10, __size = 1},
		itemCount = 5,
		costMap = __data_t__costMap[2035],
		-- {[535] = 1800, __size = 1}
		vipWeight = 100,
		position = 4,
		levelRange = __data_t__levelRange[2035],
		-- {1, 250}
		fishingLevelRange = __data_t__fishingLevelRange[2035],
		-- {1, 250}
		showUnable = true
	},
	[2041] = {
		id = 2041,
		itemWeightMap = {[22991] = 10, __size = 1},
		itemCount = 5,
		costMap = __data_t__costMap[2041],
		-- {[535] = 1800, __size = 1}
		vipWeight = 100,
		position = 5,
		levelRange = __data_t__levelRange[2041],
		-- {1, 250}
		fishingLevelRange = __data_t__fishingLevelRange[2041],
		-- {1, 250}
		showUnable = true
	},
	[2051] = {
		id = 2051,
		itemWeightMap = {[22841] = 10, __size = 1},
		itemCount = 5,
		costMap = __data_t__costMap[2051],
		-- {[535] = 1000, __size = 1}
		vipWeight = 100,
		position = 6,
		levelRange = __data_t__levelRange[2051],
		-- {1, 250}
		fishingLevelRange = __data_t__fishingLevelRange[2051]
		-- {1, 250}
	},
	[2061] = {
		id = 2061,
		itemWeightMap = {[20341] = 10, __size = 1},
		itemCount = 5,
		costMap = __data_t__costMap[2061],
		-- {[535] = 1000, __size = 1}
		vipWeight = 100,
		position = 7,
		levelRange = __data_t__levelRange[2061],
		-- {1, 250}
		fishingLevelRange = __data_t__fishingLevelRange[2061]
		-- {1, 250}
	},
	[2071] = {
		id = 2071,
		itemWeightMap = {[20221] = 10, __size = 1},
		itemCount = 5,
		costMap = __data_t__costMap[2071],
		-- {[535] = 1000, __size = 1}
		vipWeight = 100,
		position = 8,
		levelRange = __data_t__levelRange[2071],
		-- {1, 250}
		fishingLevelRange = __data_t__fishingLevelRange[2071]
		-- {1, 250}
	},
	[2081] = {
		id = 2081,
		itemWeightMap = {[21961] = 1, __size = 1},
		itemCount = 1,
		costMap = {[535] = 5000, __size = 1},
		vipWeight = 100,
		position = 9,
		levelRange = __data_t__levelRange[2081],
		-- {1, 250}
		fishingLevelRange = __data_t__fishingLevelRange[2081],
		-- {1, 250}
		limitType = 3,
		limitTimes = 20,
		showUnable = true
	},
	[3001] = {
		id = 3001,
		itemWeightMap = {[529] = 10, __size = 1},
		itemCount = 100,
		costMap = __data_t__costMap[3001],
		-- {[535] = 600, __size = 1}
		vipWeight = 100,
		position = 10,
		levelRange = __data_t__levelRange[3001],
		-- {1, 250}
		fishingLevelRange = __data_t__fishingLevelRange[3001]
		-- {1, 250}
	},
	[3011] = {
		id = 3011,
		itemWeightMap = __data_t__itemWeightMap[3011],
		-- {[5000] = 10, __size = 1}
		itemCount = 20,
		costMap = __data_t__costMap[3011],
		-- {[535] = 1000, __size = 1}
		vipWeight = 100,
		position = 11,
		levelRange = __data_t__levelRange[3011],
		-- {1, 250}
		fishingLevelRange = __data_t__fishingLevelRange[3011]
		-- {1, 250}
	},
	[3012] = {
		id = 3012,
		itemWeightMap = {[930] = 10, __size = 1},
		itemCount = 20,
		costMap = __data_t__costMap[3012],
		-- {[535] = 1000, __size = 1}
		vipWeight = 100,
		position = 13,
		levelRange = __data_t__levelRange[3012],
		-- {1, 250}
		fishingLevelRange = __data_t__fishingLevelRange[3012]
		-- {1, 250}
	},
	[3021] = {
		id = 3021,
		itemWeightMap = __data_t__itemWeightMap[3021],
		-- {[514] = 10, __size = 1}
		itemCount = 10,
		costMap = __data_t__costMap[3021],
		-- {[535] = 600, __size = 1}
		vipWeight = 100,
		position = 14,
		levelRange = __data_t__levelRange[3021],
		-- {1, 250}
		fishingLevelRange = __data_t__fishingLevelRange[3021]
		-- {1, 250}
	},
	[10001] = {
		id = 10001,
		itemWeightMap = {[2225] = 1, __size = 1},
		itemCount = 1,
		costMap = {[535] = 30000, __size = 1},
		vipWeight = 100,
		position = 12,
		levelRange = __data_t__levelRange[10001],
		-- {1, 250}
		fishingLevelRange = __data_t__fishingLevelRange[10001],
		-- {1, 250}
		limitType = 4,
		limitTimes = 1
	},

	__size = 28,
	__default = {
		__index = {
			itemWeightMap = {__size = 0},
			itemCount = 0,
			costMap = {['coin3'] = 0, __size = 1},
			vipStart = 0,
			vipWeight = 1,
			beginDate = 0,
			endDate = 20990101,
			position = 0,
			levelRange = __data_t__levelRange["default"]	--[[ {1, 100}]],
			fishingLevelRange = __data_t__fishingLevelRange["default"]	--[[ {1, 100}]],
			limitType = 0,
			limitTimes = 0,
			showUnable = false,
			languages = {'cn', 'tw', 'en', 'vn', 'th', 'kr', 'pt'}
		}
	}
}
return csv.fishing.shop