--
-- auto generated by csv2lua
-- date: 
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['held_item']['level'] = {
	[1] = {
		id = 1,
		levelExp1 = 80,
		levelExp2 = 96,
		levelExp3 = 120,
		levelExp4 = 160,
		levelExp5 = 200,
		levelExp6 = 260,
		levelExp7 = 260
	},
	[2] = {
		id = 2,
		levelExp1 = 120,
		levelExp2 = 144,
		levelExp3 = 180,
		levelExp4 = 240,
		levelExp5 = 300,
		levelExp6 = 500,
		levelExp7 = 500
	},
	[3] = {
		id = 3,
		levelExp1 = 160,
		levelExp2 = 192,
		levelExp3 = 240,
		levelExp4 = 320,
		levelExp5 = 400,
		levelExp6 = 740,
		levelExp7 = 740
	},
	[4] = {
		id = 4,
		levelExp1 = 200,
		levelExp2 = 240,
		levelExp3 = 300,
		levelExp4 = 400,
		levelExp5 = 500,
		levelExp6 = 980,
		levelExp7 = 980
	},
	[5] = {
		id = 5,
		levelExp1 = 240,
		levelExp2 = 288,
		levelExp3 = 360,
		levelExp4 = 480,
		levelExp5 = 600,
		levelExp6 = 1220,
		levelExp7 = 1220
	},
	[6] = {
		id = 6,
		levelExp1 = 280,
		levelExp2 = 336,
		levelExp3 = 420,
		levelExp4 = 560,
		levelExp5 = 700,
		levelExp6 = 1460,
		levelExp7 = 1460
	},
	[7] = {
		id = 7,
		levelExp1 = 320,
		levelExp2 = 384,
		levelExp3 = 480,
		levelExp4 = 640,
		levelExp5 = 800,
		levelExp6 = 1700,
		levelExp7 = 1700
	},
	[8] = {
		id = 8,
		levelExp1 = 360,
		levelExp2 = 432,
		levelExp3 = 540,
		levelExp4 = 720,
		levelExp5 = 900,
		levelExp6 = 1940,
		levelExp7 = 1940
	},
	[9] = {
		id = 9,
		levelExp1 = 400,
		levelExp2 = 480,
		levelExp3 = 600,
		levelExp4 = 800,
		levelExp5 = 1000,
		levelExp6 = 2180,
		levelExp7 = 2180
	},
	[10] = {
		id = 10,
		levelExp1 = 440,
		levelExp2 = 528,
		levelExp3 = 660,
		levelExp4 = 880,
		levelExp5 = 1100,
		levelExp6 = 2420,
		levelExp7 = 2420
	},
	[11] = {
		id = 11,
		levelExp1 = 500,
		levelExp2 = 600,
		levelExp3 = 750,
		levelExp4 = 1000,
		levelExp5 = 1250,
		levelExp6 = 2660,
		levelExp7 = 2660
	},
	[12] = {
		id = 12,
		levelExp1 = 560,
		levelExp2 = 672,
		levelExp3 = 840,
		levelExp4 = 1120,
		levelExp5 = 1400,
		levelExp6 = 2900,
		levelExp7 = 2900
	},
	[13] = {
		id = 13,
		levelExp1 = 620,
		levelExp2 = 744,
		levelExp3 = 930,
		levelExp4 = 1240,
		levelExp5 = 1550,
		levelExp6 = 3140,
		levelExp7 = 3140
	},
	[14] = {
		id = 14,
		levelExp1 = 680,
		levelExp2 = 816,
		levelExp3 = 1020,
		levelExp4 = 1360,
		levelExp5 = 1700,
		levelExp6 = 3380,
		levelExp7 = 3380
	},
	[15] = {
		id = 15,
		levelExp1 = 740,
		levelExp2 = 888,
		levelExp3 = 1110,
		levelExp4 = 1480,
		levelExp5 = 1850,
		levelExp6 = 3620,
		levelExp7 = 3620
	},
	[16] = {
		id = 16,
		levelExp1 = 800,
		levelExp2 = 960,
		levelExp3 = 1200,
		levelExp4 = 1600,
		levelExp5 = 2000,
		levelExp6 = 3860,
		levelExp7 = 3860
	},
	[17] = {
		id = 17,
		levelExp1 = 860,
		levelExp2 = 1032,
		levelExp3 = 1290,
		levelExp4 = 1720,
		levelExp5 = 2150,
		levelExp6 = 4100,
		levelExp7 = 4100
	},
	[18] = {
		id = 18,
		levelExp1 = 920,
		levelExp2 = 1104,
		levelExp3 = 1380,
		levelExp4 = 1840,
		levelExp5 = 2300,
		levelExp6 = 4340,
		levelExp7 = 4340
	},
	[19] = {
		id = 19,
		levelExp1 = 980,
		levelExp2 = 1176,
		levelExp3 = 1470,
		levelExp4 = 1960,
		levelExp5 = 2450,
		levelExp6 = 4580,
		levelExp7 = 4580
	},
	[20] = {
		id = 20,
		levelExp1 = 1040,
		levelExp2 = 1248,
		levelExp3 = 1560,
		levelExp4 = 2080,
		levelExp5 = 2600,
		levelExp6 = 4820,
		levelExp7 = 4820
	},
	[21] = {
		id = 21,
		levelExp1 = 1120,
		levelExp2 = 1344,
		levelExp3 = 1680,
		levelExp4 = 2240,
		levelExp5 = 2800,
		levelExp6 = 5060,
		levelExp7 = 5060
	},
	[22] = {
		id = 22,
		levelExp1 = 1200,
		levelExp2 = 1440,
		levelExp3 = 1800,
		levelExp4 = 2400,
		levelExp5 = 3000,
		levelExp6 = 5300,
		levelExp7 = 5300
	},
	[23] = {
		id = 23,
		levelExp1 = 1280,
		levelExp2 = 1536,
		levelExp3 = 1920,
		levelExp4 = 2560,
		levelExp5 = 3200,
		levelExp6 = 5540,
		levelExp7 = 5540
	},
	[24] = {
		id = 24,
		levelExp1 = 1360,
		levelExp2 = 1632,
		levelExp3 = 2040,
		levelExp4 = 2720,
		levelExp5 = 3400,
		levelExp6 = 5780,
		levelExp7 = 5780
	},
	[25] = {
		id = 25,
		levelExp1 = 1440,
		levelExp2 = 1728,
		levelExp3 = 2160,
		levelExp4 = 2880,
		levelExp5 = 3600,
		levelExp6 = 6020,
		levelExp7 = 6020
	},
	[26] = {
		id = 26,
		levelExp1 = 1520,
		levelExp2 = 1824,
		levelExp3 = 2280,
		levelExp4 = 3040,
		levelExp5 = 3800,
		levelExp6 = 6260,
		levelExp7 = 6260
	},
	[27] = {
		id = 27,
		levelExp1 = 1600,
		levelExp2 = 1920,
		levelExp3 = 2400,
		levelExp4 = 3200,
		levelExp5 = 4000,
		levelExp6 = 6500,
		levelExp7 = 6500
	},
	[28] = {
		id = 28,
		levelExp1 = 1680,
		levelExp2 = 2016,
		levelExp3 = 2520,
		levelExp4 = 3360,
		levelExp5 = 4200,
		levelExp6 = 6740,
		levelExp7 = 6740
	},
	[29] = {
		id = 29,
		levelExp1 = 1760,
		levelExp2 = 2112,
		levelExp3 = 2640,
		levelExp4 = 3520,
		levelExp5 = 4400,
		levelExp6 = 6980,
		levelExp7 = 6980
	},
	[30] = {
		id = 30,
		levelExp1 = 1840,
		levelExp2 = 2208,
		levelExp3 = 2760,
		levelExp4 = 3680,
		levelExp5 = 4600,
		levelExp6 = 7220,
		levelExp7 = 7220
	},
	[31] = {
		id = 31,
		levelExp1 = 1920,
		levelExp2 = 2304,
		levelExp3 = 2880,
		levelExp4 = 3840,
		levelExp5 = 4800,
		levelExp6 = 7460,
		levelExp7 = 7460
	},
	[32] = {
		id = 32,
		levelExp1 = 2020,
		levelExp2 = 2424,
		levelExp3 = 3030,
		levelExp4 = 4040,
		levelExp5 = 5050,
		levelExp6 = 7700,
		levelExp7 = 7700
	},
	[33] = {
		id = 33,
		levelExp1 = 2120,
		levelExp2 = 2544,
		levelExp3 = 3180,
		levelExp4 = 4240,
		levelExp5 = 5300,
		levelExp6 = 7940,
		levelExp7 = 7940
	},
	[34] = {
		id = 34,
		levelExp1 = 2220,
		levelExp2 = 2664,
		levelExp3 = 3330,
		levelExp4 = 4440,
		levelExp5 = 5550,
		levelExp6 = 8180,
		levelExp7 = 8180
	},
	[35] = {
		id = 35,
		levelExp1 = 2320,
		levelExp2 = 2784,
		levelExp3 = 3480,
		levelExp4 = 4640,
		levelExp5 = 5800,
		levelExp6 = 8420,
		levelExp7 = 8420
	},
	[36] = {
		id = 36,
		levelExp1 = 2420,
		levelExp2 = 2904,
		levelExp3 = 3630,
		levelExp4 = 4840,
		levelExp5 = 6050,
		levelExp6 = 8660,
		levelExp7 = 8660
	},
	[37] = {
		id = 37,
		levelExp1 = 2520,
		levelExp2 = 3024,
		levelExp3 = 3780,
		levelExp4 = 5040,
		levelExp5 = 6300,
		levelExp6 = 8900,
		levelExp7 = 8900
	},
	[38] = {
		id = 38,
		levelExp1 = 2620,
		levelExp2 = 3144,
		levelExp3 = 3930,
		levelExp4 = 5240,
		levelExp5 = 6550,
		levelExp6 = 9140,
		levelExp7 = 9140
	},
	[39] = {
		id = 39,
		levelExp1 = 2720,
		levelExp2 = 3264,
		levelExp3 = 4080,
		levelExp4 = 5440,
		levelExp5 = 6800,
		levelExp6 = 9380,
		levelExp7 = 9380
	},
	[40] = {
		id = 40,
		levelExp1 = 2820,
		levelExp2 = 3384,
		levelExp3 = 4230,
		levelExp4 = 5640,
		levelExp5 = 7050,
		levelExp6 = 9620,
		levelExp7 = 9620
	},
	[41] = {
		id = 41,
		levelExp1 = 2920,
		levelExp2 = 3504,
		levelExp3 = 4380,
		levelExp4 = 5840,
		levelExp5 = 7300,
		levelExp6 = 9860,
		levelExp7 = 9860
	},
	[42] = {
		id = 42,
		levelExp1 = 3040,
		levelExp2 = 3648,
		levelExp3 = 4560,
		levelExp4 = 6080,
		levelExp5 = 7600,
		levelExp6 = 10100,
		levelExp7 = 10100
	},
	[43] = {
		id = 43,
		levelExp1 = 3160,
		levelExp2 = 3792,
		levelExp3 = 4740,
		levelExp4 = 6320,
		levelExp5 = 7900,
		levelExp6 = 10340,
		levelExp7 = 10340
	},
	[44] = {
		id = 44,
		levelExp1 = 3280,
		levelExp2 = 3936,
		levelExp3 = 4920,
		levelExp4 = 6560,
		levelExp5 = 8200,
		levelExp6 = 10580,
		levelExp7 = 10580
	},
	[45] = {
		id = 45,
		levelExp1 = 3400,
		levelExp2 = 4080,
		levelExp3 = 5100,
		levelExp4 = 6800,
		levelExp5 = 8500,
		levelExp6 = 10820,
		levelExp7 = 10820
	},
	[46] = {
		id = 46,
		levelExp1 = 3520,
		levelExp2 = 4224,
		levelExp3 = 5280,
		levelExp4 = 7040,
		levelExp5 = 8800,
		levelExp6 = 11060,
		levelExp7 = 11060
	},
	[47] = {
		id = 47,
		levelExp1 = 3640,
		levelExp2 = 4368,
		levelExp3 = 5460,
		levelExp4 = 7280,
		levelExp5 = 9100,
		levelExp6 = 11300,
		levelExp7 = 11300
	},
	[48] = {
		id = 48,
		levelExp1 = 3760,
		levelExp2 = 4512,
		levelExp3 = 5640,
		levelExp4 = 7520,
		levelExp5 = 9400,
		levelExp6 = 11540,
		levelExp7 = 11540
	},
	[49] = {
		id = 49,
		levelExp1 = 3880,
		levelExp2 = 4656,
		levelExp3 = 5820,
		levelExp4 = 7760,
		levelExp5 = 9700,
		levelExp6 = 11780,
		levelExp7 = 11780
	},
	[50] = {
		id = 50,
		levelExp1 = 4000,
		levelExp2 = 4800,
		levelExp3 = 6000,
		levelExp4 = 8000,
		levelExp5 = 10000,
		levelExp6 = 12020,
		levelExp7 = 12020
	},
	[51] = {
		id = 51,
		levelExp1 = 4150,
		levelExp2 = 4980,
		levelExp3 = 6225,
		levelExp4 = 8300,
		levelExp5 = 10375,
		levelExp6 = 12260,
		levelExp7 = 12260
	},
	[52] = {
		id = 52,
		levelExp1 = 4300,
		levelExp2 = 5160,
		levelExp3 = 6450,
		levelExp4 = 8600,
		levelExp5 = 10750,
		levelExp6 = 12500,
		levelExp7 = 12500
	},
	[53] = {
		id = 53,
		levelExp1 = 4450,
		levelExp2 = 5340,
		levelExp3 = 6675,
		levelExp4 = 8900,
		levelExp5 = 11125,
		levelExp6 = 12740,
		levelExp7 = 12740
	},
	[54] = {
		id = 54,
		levelExp1 = 4600,
		levelExp2 = 5520,
		levelExp3 = 6900,
		levelExp4 = 9200,
		levelExp5 = 11500,
		levelExp6 = 12980,
		levelExp7 = 12980
	},
	[55] = {
		id = 55,
		levelExp1 = 4750,
		levelExp2 = 5700,
		levelExp3 = 7125,
		levelExp4 = 9500,
		levelExp5 = 11875,
		levelExp6 = 13220,
		levelExp7 = 13220
	},
	[56] = {
		id = 56,
		levelExp1 = 4900,
		levelExp2 = 5880,
		levelExp3 = 7350,
		levelExp4 = 9800,
		levelExp5 = 12250,
		levelExp6 = 13460,
		levelExp7 = 13460
	},
	[57] = {
		id = 57,
		levelExp1 = 5050,
		levelExp2 = 6060,
		levelExp3 = 7575,
		levelExp4 = 10100,
		levelExp5 = 12625,
		levelExp6 = 13700,
		levelExp7 = 13700
	},
	[58] = {
		id = 58,
		levelExp1 = 5200,
		levelExp2 = 6240,
		levelExp3 = 7800,
		levelExp4 = 10400,
		levelExp5 = 13000,
		levelExp6 = 13940,
		levelExp7 = 13940
	},
	[59] = {
		id = 59,
		levelExp1 = 5350,
		levelExp2 = 6420,
		levelExp3 = 8025,
		levelExp4 = 10700,
		levelExp5 = 13375,
		levelExp6 = 14180,
		levelExp7 = 14180
	},
	[60] = {
		id = 60,
		levelExp1 = 5500,
		levelExp2 = 6600,
		levelExp3 = 8250,
		levelExp4 = 11000,
		levelExp5 = 13750,
		levelExp6 = 14420,
		levelExp7 = 14420
	},
	[61] = {
		id = 61,
		levelExp1 = 5775,
		levelExp2 = 6930,
		levelExp3 = 8663,
		levelExp4 = 11550,
		levelExp5 = 14438,
		levelExp6 = 15141,
		levelExp7 = 15141
	},
	[62] = {
		id = 62,
		levelExp1 = 6064,
		levelExp2 = 7277,
		levelExp3 = 9096,
		levelExp4 = 12128,
		levelExp5 = 15159,
		levelExp6 = 15898,
		levelExp7 = 15898
	},
	[63] = {
		id = 63,
		levelExp1 = 6367,
		levelExp2 = 7640,
		levelExp3 = 9550,
		levelExp4 = 12734,
		levelExp5 = 15917,
		levelExp6 = 16693,
		levelExp7 = 16693
	},
	[64] = {
		id = 64,
		levelExp1 = 6685,
		levelExp2 = 8022,
		levelExp3 = 10028,
		levelExp4 = 13371,
		levelExp5 = 16713,
		levelExp6 = 17528,
		levelExp7 = 17528
	},
	[65] = {
		id = 65,
		levelExp1 = 7020,
		levelExp2 = 8423,
		levelExp3 = 10529,
		levelExp4 = 14039,
		levelExp5 = 17549,
		levelExp6 = 18404,
		levelExp7 = 18404
	},
	[66] = {
		id = 66,
		levelExp1 = 7371,
		levelExp2 = 8845,
		levelExp3 = 11056,
		levelExp4 = 14741,
		levelExp5 = 18426,
		levelExp6 = 19324,
		levelExp7 = 19324
	},
	[67] = {
		id = 67,
		levelExp1 = 7739,
		levelExp2 = 9287,
		levelExp3 = 11609,
		levelExp4 = 15478,
		levelExp5 = 19348,
		levelExp6 = 20290,
		levelExp7 = 20290
	},
	[68] = {
		id = 68,
		levelExp1 = 8126,
		levelExp2 = 9751,
		levelExp3 = 12189,
		levelExp4 = 16252,
		levelExp5 = 20315,
		levelExp6 = 21305,
		levelExp7 = 21305
	},
	[69] = {
		id = 69,
		levelExp1 = 8532,
		levelExp2 = 10239,
		levelExp3 = 12798,
		levelExp4 = 17065,
		levelExp5 = 21331,
		levelExp6 = 22370,
		levelExp7 = 22370
	},
	[70] = {
		id = 70,
		levelExp1 = 8959,
		levelExp2 = 10751,
		levelExp3 = 13438,
		levelExp4 = 17918,
		levelExp5 = 22397,
		levelExp6 = 23489,
		levelExp7 = 23489
	},
	[71] = {
		id = 71,
		levelExp1 = 9407,
		levelExp2 = 11288,
		levelExp3 = 14110,
		levelExp4 = 18814,
		levelExp5 = 23517,
		levelExp6 = 24663,
		levelExp7 = 24663
	},
	[72] = {
		id = 72,
		levelExp1 = 9877,
		levelExp2 = 11853,
		levelExp3 = 14816,
		levelExp4 = 19754,
		levelExp5 = 24693,
		levelExp6 = 25896,
		levelExp7 = 25896
	},
	[73] = {
		id = 73,
		levelExp1 = 10371,
		levelExp2 = 12445,
		levelExp3 = 15557,
		levelExp4 = 20742,
		levelExp5 = 25928,
		levelExp6 = 27191,
		levelExp7 = 27191
	},
	[74] = {
		id = 74,
		levelExp1 = 10890,
		levelExp2 = 13068,
		levelExp3 = 16334,
		levelExp4 = 21779,
		levelExp5 = 27224,
		levelExp6 = 28551,
		levelExp7 = 28551
	},
	[75] = {
		id = 75,
		levelExp1 = 11434,
		levelExp2 = 13721,
		levelExp3 = 17151,
		levelExp4 = 22868,
		levelExp5 = 28585,
		levelExp6 = 29978,
		levelExp7 = 29978
	},
	[76] = {
		id = 76,
		levelExp1 = 12006,
		levelExp2 = 14407,
		levelExp3 = 18009,
		levelExp4 = 24012,
		levelExp5 = 30015,
		levelExp6 = 31477,
		levelExp7 = 31477
	},
	[77] = {
		id = 77,
		levelExp1 = 12606,
		levelExp2 = 15127,
		levelExp3 = 18909,
		levelExp4 = 25212,
		levelExp5 = 31515,
		levelExp6 = 33051,
		levelExp7 = 33051
	},
	[78] = {
		id = 78,
		levelExp1 = 13236,
		levelExp2 = 15884,
		levelExp3 = 19855,
		levelExp4 = 26473,
		levelExp5 = 33091,
		levelExp6 = 34703,
		levelExp7 = 34703
	},
	[79] = {
		id = 79,
		levelExp1 = 13898,
		levelExp2 = 16678,
		levelExp3 = 20847,
		levelExp4 = 27796,
		levelExp5 = 34746,
		levelExp6 = 36439,
		levelExp7 = 36439
	},
	[80] = {
		id = 80,
		levelExp1 = 14593,
		levelExp2 = 17512,
		levelExp3 = 21890,
		levelExp4 = 29186,
		levelExp5 = 36483,
		levelExp6 = 38261,
		levelExp7 = 38261
	},
	[81] = {
		id = 81,
		levelExp1 = 15323,
		levelExp2 = 18387,
		levelExp3 = 22984,
		levelExp4 = 30646,
		levelExp5 = 38307,
		levelExp6 = 40174,
		levelExp7 = 40174
	},
	[82] = {
		id = 82,
		levelExp1 = 16089,
		levelExp2 = 19307,
		levelExp3 = 24133,
		levelExp4 = 32178,
		levelExp5 = 40222,
		levelExp6 = 42182,
		levelExp7 = 42182
	},
	[83] = {
		id = 83,
		levelExp1 = 16893,
		levelExp2 = 20272,
		levelExp3 = 25340,
		levelExp4 = 33787,
		levelExp5 = 42233,
		levelExp6 = 44291,
		levelExp7 = 44291
	},
	[84] = {
		id = 84,
		levelExp1 = 17738,
		levelExp2 = 21286,
		levelExp3 = 26607,
		levelExp4 = 35476,
		levelExp5 = 44345,
		levelExp6 = 46506,
		levelExp7 = 46506
	},
	[85] = {
		id = 85,
		levelExp1 = 18625,
		levelExp2 = 22350,
		levelExp3 = 27937,
		levelExp4 = 37250,
		levelExp5 = 46562,
		levelExp6 = 48831,
		levelExp7 = 48831
	},
	[86] = {
		id = 86,
		levelExp1 = 19556,
		levelExp2 = 23467,
		levelExp3 = 29334,
		levelExp4 = 39112,
		levelExp5 = 48890,
		levelExp6 = 51273,
		levelExp7 = 51273
	},
	[87] = {
		id = 87,
		levelExp1 = 20534,
		levelExp2 = 24641,
		levelExp3 = 30801,
		levelExp4 = 41068,
		levelExp5 = 51335,
		levelExp6 = 53836,
		levelExp7 = 53836
	},
	[88] = {
		id = 88,
		levelExp1 = 21561,
		levelExp2 = 25873,
		levelExp3 = 32341,
		levelExp4 = 43121,
		levelExp5 = 53902,
		levelExp6 = 56528,
		levelExp7 = 56528
	},
	[89] = {
		id = 89,
		levelExp1 = 22639,
		levelExp2 = 27166,
		levelExp3 = 33958,
		levelExp4 = 45277,
		levelExp5 = 56597,
		levelExp6 = 59355,
		levelExp7 = 59355
	},
	[90] = {
		id = 90,
		levelExp1 = 23771,
		levelExp2 = 28525,
		levelExp3 = 35656,
		levelExp4 = 47541,
		levelExp5 = 59427,
		levelExp6 = 62322,
		levelExp7 = 62322
	},
	[91] = {
		id = 91,
		levelExp1 = 24009,
		levelExp2 = 28810,
		levelExp3 = 36013,
		levelExp4 = 48016,
		levelExp5 = 60021,
		levelExp6 = 62945,
		levelExp7 = 62945
	},
	[92] = {
		id = 92,
		levelExp1 = 24249,
		levelExp2 = 29098,
		levelExp3 = 36373,
		levelExp4 = 48497,
		levelExp5 = 60621,
		levelExp6 = 63575,
		levelExp7 = 63575
	},
	[93] = {
		id = 93,
		levelExp1 = 24491,
		levelExp2 = 29389,
		levelExp3 = 36736,
		levelExp4 = 48982,
		levelExp5 = 61228,
		levelExp6 = 64210,
		levelExp7 = 64210
	},
	[94] = {
		id = 94,
		levelExp1 = 24736,
		levelExp2 = 29683,
		levelExp3 = 37104,
		levelExp4 = 49471,
		levelExp5 = 61840,
		levelExp6 = 64853,
		levelExp7 = 64853
	},
	[95] = {
		id = 95,
		levelExp1 = 24984,
		levelExp2 = 29980,
		levelExp3 = 37475,
		levelExp4 = 49966,
		levelExp5 = 62458,
		levelExp6 = 65501,
		levelExp7 = 65501
	},
	[96] = {
		id = 96,
		levelExp1 = 25233,
		levelExp2 = 30280,
		levelExp3 = 37850,
		levelExp4 = 50466,
		levelExp5 = 63083,
		levelExp6 = 66156,
		levelExp7 = 66156
	},
	[97] = {
		id = 97,
		levelExp1 = 25486,
		levelExp2 = 30583,
		levelExp3 = 38228,
		levelExp4 = 50970,
		levelExp5 = 63714,
		levelExp6 = 66818,
		levelExp7 = 66818
	},
	[98] = {
		id = 98,
		levelExp1 = 25741,
		levelExp2 = 30888,
		levelExp3 = 38610,
		levelExp4 = 51480,
		levelExp5 = 64351,
		levelExp6 = 67486,
		levelExp7 = 67486
	},
	[99] = {
		id = 99,
		levelExp1 = 25998,
		levelExp2 = 31197,
		levelExp3 = 38996,
		levelExp4 = 51995,
		levelExp5 = 64994,
		levelExp6 = 68161,
		levelExp7 = 68161
	},
	[100] = {
		id = 100,
		levelExp1 = 26258,
		levelExp2 = 31509,
		levelExp3 = 39386,
		levelExp4 = 52515,
		levelExp5 = 65644,
		levelExp6 = 68842,
		levelExp7 = 68842
	},
	[101] = {
		id = 101,
		levelExp1 = 26521,
		levelExp2 = 31824,
		levelExp3 = 39780,
		levelExp4 = 53040,
		levelExp5 = 66301,
		levelExp6 = 69531,
		levelExp7 = 69531
	},
	[102] = {
		id = 102,
		levelExp1 = 26786,
		levelExp2 = 32143,
		levelExp3 = 40178,
		levelExp4 = 53570,
		levelExp5 = 66964,
		levelExp6 = 70226,
		levelExp7 = 70226
	},
	[103] = {
		id = 103,
		levelExp1 = 27054,
		levelExp2 = 32464,
		levelExp3 = 40580,
		levelExp4 = 54106,
		levelExp5 = 67633,
		levelExp6 = 70928,
		levelExp7 = 70928
	},
	[104] = {
		id = 104,
		levelExp1 = 27324,
		levelExp2 = 32789,
		levelExp3 = 40986,
		levelExp4 = 54647,
		levelExp5 = 68310,
		levelExp6 = 71638,
		levelExp7 = 71638
	},
	[105] = {
		id = 105,
		levelExp1 = 27597,
		levelExp2 = 33117,
		levelExp3 = 41396,
		levelExp4 = 55194,
		levelExp5 = 68993,
		levelExp6 = 72354,
		levelExp7 = 72354
	},
	[106] = {
		id = 106,
		levelExp1 = 27873,
		levelExp2 = 33448,
		levelExp3 = 41809,
		levelExp4 = 55746,
		levelExp5 = 69683,
		levelExp6 = 73077,
		levelExp7 = 73077
	},
	[107] = {
		id = 107,
		levelExp1 = 28152,
		levelExp2 = 33782,
		levelExp3 = 42228,
		levelExp4 = 56303,
		levelExp5 = 70380,
		levelExp6 = 73808,
		levelExp7 = 73808
	},
	[108] = {
		id = 108,
		levelExp1 = 28434,
		levelExp2 = 34120,
		levelExp3 = 42650,
		levelExp4 = 56866,
		levelExp5 = 71083,
		levelExp6 = 74546,
		levelExp7 = 74546
	},
	[109] = {
		id = 109,
		levelExp1 = 28718,
		levelExp2 = 34461,
		levelExp3 = 43076,
		levelExp4 = 57435,
		levelExp5 = 71794,
		levelExp6 = 75292,
		levelExp7 = 75292
	},
	[110] = {
		id = 110,
		levelExp1 = 29005,
		levelExp2 = 34806,
		levelExp3 = 43507,
		levelExp4 = 58009,
		levelExp5 = 72512,
		levelExp6 = 76045,
		levelExp7 = 76045
	},
	[111] = {
		id = 111,
		levelExp1 = 29295,
		levelExp2 = 35154,
		levelExp3 = 43942,
		levelExp4 = 58589,
		levelExp5 = 73237,
		levelExp6 = 76805,
		levelExp7 = 76805
	},
	[112] = {
		id = 112,
		levelExp1 = 29588,
		levelExp2 = 35506,
		levelExp3 = 44382,
		levelExp4 = 59175,
		levelExp5 = 73970,
		levelExp6 = 77573,
		levelExp7 = 77573
	},
	[113] = {
		id = 113,
		levelExp1 = 29884,
		levelExp2 = 35861,
		levelExp3 = 44825,
		levelExp4 = 59767,
		levelExp5 = 74709,
		levelExp6 = 78349,
		levelExp7 = 78349
	},
	[114] = {
		id = 114,
		levelExp1 = 30183,
		levelExp2 = 36219,
		levelExp3 = 45274,
		levelExp4 = 60364,
		levelExp5 = 75457,
		levelExp6 = 79132,
		levelExp7 = 79132
	},
	[115] = {
		id = 115,
		levelExp1 = 30485,
		levelExp2 = 36581,
		levelExp3 = 45726,
		levelExp4 = 60968,
		levelExp5 = 76211,
		levelExp6 = 79924,
		levelExp7 = 79924
	},
	[116] = {
		id = 116,
		levelExp1 = 30790,
		levelExp2 = 36947,
		levelExp3 = 46184,
		levelExp4 = 61578,
		levelExp5 = 76973,
		levelExp6 = 80723,
		levelExp7 = 80723
	},
	[117] = {
		id = 117,
		levelExp1 = 31097,
		levelExp2 = 37317,
		levelExp3 = 46645,
		levelExp4 = 62194,
		levelExp5 = 77743,
		levelExp6 = 81530,
		levelExp7 = 81530
	},
	[118] = {
		id = 118,
		levelExp1 = 31408,
		levelExp2 = 37690,
		levelExp3 = 47112,
		levelExp4 = 62815,
		levelExp5 = 78520,
		levelExp6 = 82345,
		levelExp7 = 82345
	},
	[119] = {
		id = 119,
		levelExp1 = 31722,
		levelExp2 = 38067,
		levelExp3 = 47583,
		levelExp4 = 63444,
		levelExp5 = 79306,
		levelExp6 = 83169,
		levelExp7 = 83169
	},
	[120] = {
		id = 120,
		levelExp1 = 32040,
		levelExp2 = 38447,
		levelExp3 = 48059,
		levelExp4 = 64078,
		levelExp5 = 80099,
		levelExp6 = 84001,
		levelExp7 = 84001
	},
	[121] = {
		id = 121,
		levelExp1 = 32360,
		levelExp2 = 38832,
		levelExp3 = 48539,
		levelExp4 = 64719,
		levelExp5 = 80900,
		levelExp6 = 84841,
		levelExp7 = 84841
	},
	[122] = {
		id = 122,
		levelExp1 = 32684,
		levelExp2 = 39220,
		levelExp3 = 49025,
		levelExp4 = 65366,
		levelExp5 = 81709,
		levelExp6 = 85689,
		levelExp7 = 85689
	},
	[123] = {
		id = 123,
		levelExp1 = 33011,
		levelExp2 = 39612,
		levelExp3 = 49515,
		levelExp4 = 66020,
		levelExp5 = 82526,
		levelExp6 = 86546,
		levelExp7 = 86546
	},
	[124] = {
		id = 124,
		levelExp1 = 33341,
		levelExp2 = 40009,
		levelExp3 = 50010,
		levelExp4 = 66680,
		levelExp5 = 83351,
		levelExp6 = 87411,
		levelExp7 = 87411
	},
	[125] = {
		id = 125,
		levelExp1 = 33674,
		levelExp2 = 40409,
		levelExp3 = 50510,
		levelExp4 = 67347,
		levelExp5 = 84184,
		levelExp6 = 88286,
		levelExp7 = 88286
	},
	[126] = {
		id = 126,
		levelExp1 = 34011,
		levelExp2 = 40813,
		levelExp3 = 51015,
		levelExp4 = 68020,
		levelExp5 = 85026,
		levelExp6 = 89168,
		levelExp7 = 89168
	},
	[127] = {
		id = 127,
		levelExp1 = 34351,
		levelExp2 = 41221,
		levelExp3 = 51526,
		levelExp4 = 68700,
		levelExp5 = 85877,
		levelExp6 = 90060,
		levelExp7 = 90060
	},
	[128] = {
		id = 128,
		levelExp1 = 34694,
		levelExp2 = 41633,
		levelExp3 = 52041,
		levelExp4 = 69387,
		levelExp5 = 86735,
		levelExp6 = 90961,
		levelExp7 = 90961
	},
	[129] = {
		id = 129,
		levelExp1 = 35041,
		levelExp2 = 42049,
		levelExp3 = 52561,
		levelExp4 = 70081,
		levelExp5 = 87603,
		levelExp6 = 91870,
		levelExp7 = 91870
	},
	[130] = {
		id = 130,
		levelExp1 = 35392,
		levelExp2 = 42470,
		levelExp3 = 53087,
		levelExp4 = 70782,
		levelExp5 = 88479,
		levelExp6 = 92789,
		levelExp7 = 92789
	},
	[131] = {
		id = 131,
		levelExp1 = 35746,
		levelExp2 = 42895,
		levelExp3 = 53618,
		levelExp4 = 71490,
		levelExp5 = 89363,
		levelExp6 = 93717,
		levelExp7 = 93717
	},
	[132] = {
		id = 132,
		levelExp1 = 36103,
		levelExp2 = 43323,
		levelExp3 = 54154,
		levelExp4 = 72205,
		levelExp5 = 90257,
		levelExp6 = 94654,
		levelExp7 = 94654
	},
	[133] = {
		id = 133,
		levelExp1 = 36464,
		levelExp2 = 43757,
		levelExp3 = 54696,
		levelExp4 = 72927,
		levelExp5 = 91160,
		levelExp6 = 95601,
		levelExp7 = 95601
	},
	[134] = {
		id = 134,
		levelExp1 = 36829,
		levelExp2 = 44194,
		levelExp3 = 55242,
		levelExp4 = 73656,
		levelExp5 = 92071,
		levelExp6 = 96557,
		levelExp7 = 96557
	},
	[135] = {
		id = 135,
		levelExp1 = 37197,
		levelExp2 = 44636,
		levelExp3 = 55795,
		levelExp4 = 74393,
		levelExp5 = 92992,
		levelExp6 = 97522,
		levelExp7 = 97522
	},
	[136] = {
		id = 136,
		levelExp1 = 37569,
		levelExp2 = 45083,
		levelExp3 = 56353,
		levelExp4 = 75137,
		levelExp5 = 93922,
		levelExp6 = 98497,
		levelExp7 = 98497
	},
	[137] = {
		id = 137,
		levelExp1 = 37945,
		levelExp2 = 45533,
		levelExp3 = 56916,
		levelExp4 = 75888,
		levelExp5 = 94861,
		levelExp6 = 99482,
		levelExp7 = 99482
	},
	[138] = {
		id = 138,
		levelExp1 = 38324,
		levelExp2 = 45989,
		levelExp3 = 57486,
		levelExp4 = 76647,
		levelExp5 = 95810,
		levelExp6 = 100477,
		levelExp7 = 100477
	},
	[139] = {
		id = 139,
		levelExp1 = 38707,
		levelExp2 = 46449,
		levelExp3 = 58060,
		levelExp4 = 77413,
		levelExp5 = 96768,
		levelExp6 = 101482,
		levelExp7 = 101482
	},
	[140] = {
		id = 140,
		levelExp1 = 39095,
		levelExp2 = 46913,
		levelExp3 = 58641,
		levelExp4 = 78187,
		levelExp5 = 97736,
		levelExp6 = 102497,
		levelExp7 = 102497
	},
	[141] = {
		id = 141,
		levelExp1 = 39485,
		levelExp2 = 47382,
		levelExp3 = 59227,
		levelExp4 = 78969,
		levelExp5 = 98713,
		levelExp6 = 103522,
		levelExp7 = 103522
	},
	[142] = {
		id = 142,
		levelExp1 = 39880,
		levelExp2 = 47856,
		levelExp3 = 59820,
		levelExp4 = 79759,
		levelExp5 = 99700,
		levelExp6 = 104557,
		levelExp7 = 104557
	},
	[143] = {
		id = 143,
		levelExp1 = 40279,
		levelExp2 = 48335,
		levelExp3 = 60418,
		levelExp4 = 80557,
		levelExp5 = 100697,
		levelExp6 = 105602,
		levelExp7 = 105602
	},
	[144] = {
		id = 144,
		levelExp1 = 40682,
		levelExp2 = 48818,
		levelExp3 = 61022,
		levelExp4 = 81362,
		levelExp5 = 101704,
		levelExp6 = 106659,
		levelExp7 = 106659
	},
	[145] = {
		id = 145,
		levelExp1 = 41089,
		levelExp2 = 49306,
		levelExp3 = 61632,
		levelExp4 = 82176,
		levelExp5 = 102721,
		levelExp6 = 107725,
		levelExp7 = 107725
	},
	[146] = {
		id = 146,
		levelExp1 = 41500,
		levelExp2 = 49799,
		levelExp3 = 62249,
		levelExp4 = 82998,
		levelExp5 = 103748,
		levelExp6 = 108802,
		levelExp7 = 108802
	},
	[147] = {
		id = 147,
		levelExp1 = 41915,
		levelExp2 = 50297,
		levelExp3 = 62871,
		levelExp4 = 83828,
		levelExp5 = 104786,
		levelExp6 = 109890,
		levelExp7 = 109890
	},
	[148] = {
		id = 148,
		levelExp1 = 42334,
		levelExp2 = 50800,
		levelExp3 = 63500,
		levelExp4 = 84666,
		levelExp5 = 105834,
		levelExp6 = 110989,
		levelExp7 = 110989
	},
	[149] = {
		id = 149,
		levelExp1 = 42757,
		levelExp2 = 51308,
		levelExp3 = 64135,
		levelExp4 = 85512,
		levelExp5 = 106892,
		levelExp6 = 112099,
		levelExp7 = 112099
	},
	[150] = {
		id = 150,
		levelExp1 = 43185,
		levelExp2 = 51821,
		levelExp3 = 64776,
		levelExp4 = 86368,
		levelExp5 = 107961,
		levelExp6 = 113220,
		levelExp7 = 113220
	},
	[151] = {
		id = 151,
		levelExp1 = 43617,
		levelExp2 = 52339,
		levelExp3 = 65424,
		levelExp4 = 87231,
		levelExp5 = 109040,
		levelExp6 = 114352,
		levelExp7 = 114352
	},
	[152] = {
		id = 152,
		levelExp1 = 44053,
		levelExp2 = 52863,
		levelExp3 = 66078,
		levelExp4 = 88104,
		levelExp5 = 110131,
		levelExp6 = 115496,
		levelExp7 = 115496
	},
	[153] = {
		id = 153,
		levelExp1 = 44493,
		levelExp2 = 53392,
		levelExp3 = 66739,
		levelExp4 = 88985,
		levelExp5 = 111232,
		levelExp6 = 116651,
		levelExp7 = 116651
	},
	[154] = {
		id = 154,
		levelExp1 = 44938,
		levelExp2 = 53925,
		levelExp3 = 67406,
		levelExp4 = 89874,
		levelExp5 = 112344,
		levelExp6 = 117817,
		levelExp7 = 117817
	},
	[155] = {
		id = 155,
		levelExp1 = 45388,
		levelExp2 = 54465,
		levelExp3 = 68080,
		levelExp4 = 90773,
		levelExp5 = 113468,
		levelExp6 = 118996,
		levelExp7 = 118996
	},
	[156] = {
		id = 156,
		levelExp1 = 45841,
		levelExp2 = 55009,
		levelExp3 = 68761,
		levelExp4 = 91681,
		levelExp5 = 114603,
		levelExp6 = 120185,
		levelExp7 = 120185
	},
	[157] = {
		id = 157,
		levelExp1 = 46300,
		levelExp2 = 55559,
		levelExp3 = 69449,
		levelExp4 = 92598,
		levelExp5 = 115749,
		levelExp6 = 121387,
		levelExp7 = 121387
	},
	[158] = {
		id = 158,
		levelExp1 = 46763,
		levelExp2 = 56115,
		levelExp3 = 70143,
		levelExp4 = 93524,
		levelExp5 = 116906,
		levelExp6 = 122601,
		levelExp7 = 122601
	},
	[159] = {
		id = 159,
		levelExp1 = 47230,
		levelExp2 = 56676,
		levelExp3 = 70845,
		levelExp4 = 94459,
		levelExp5 = 118075,
		levelExp6 = 123827,
		levelExp7 = 123827
	},
	[160] = {
		id = 160,
		levelExp1 = 47703,
		levelExp2 = 57243,
		levelExp3 = 71553,
		levelExp4 = 95404,
		levelExp5 = 119256,
		levelExp6 = 125066,
		levelExp7 = 125066
	},
	[161] = {
		id = 161,
		levelExp1 = 48180,
		levelExp2 = 57815,
		levelExp3 = 72269,
		levelExp4 = 96358,
		levelExp5 = 120448,
		levelExp6 = 126316,
		levelExp7 = 126316
	},
	[162] = {
		id = 162,
		levelExp1 = 48662,
		levelExp2 = 58394,
		levelExp3 = 72991,
		levelExp4 = 97321,
		levelExp5 = 121653,
		levelExp6 = 127579,
		levelExp7 = 127579
	},
	[163] = {
		id = 163,
		levelExp1 = 49148,
		levelExp2 = 58977,
		levelExp3 = 73721,
		levelExp4 = 98294,
		levelExp5 = 122870,
		levelExp6 = 128855,
		levelExp7 = 128855
	},
	[164] = {
		id = 164,
		levelExp1 = 49640,
		levelExp2 = 59567,
		levelExp3 = 74458,
		levelExp4 = 99277,
		levelExp5 = 124098,
		levelExp6 = 130144,
		levelExp7 = 130144
	},
	[165] = {
		id = 165,
		levelExp1 = 50136,
		levelExp2 = 60163,
		levelExp3 = 75203,
		levelExp4 = 100270,
		levelExp5 = 125339,
		levelExp6 = 131445,
		levelExp7 = 131445
	},
	[166] = {
		id = 166,
		levelExp1 = 50637,
		levelExp2 = 60765,
		levelExp3 = 75955,
		levelExp4 = 101273,
		levelExp5 = 126593,
		levelExp6 = 132760,
		levelExp7 = 132760
	},
	[167] = {
		id = 167,
		levelExp1 = 51144,
		levelExp2 = 61372,
		levelExp3 = 76715,
		levelExp4 = 102286,
		levelExp5 = 127858,
		levelExp6 = 134087,
		levelExp7 = 134087
	},
	[168] = {
		id = 168,
		levelExp1 = 51655,
		levelExp2 = 61986,
		levelExp3 = 77482,
		levelExp4 = 103308,
		levelExp5 = 129137,
		levelExp6 = 135428,
		levelExp7 = 135428
	},
	[169] = {
		id = 169,
		levelExp1 = 52172,
		levelExp2 = 62606,
		levelExp3 = 78257,
		levelExp4 = 104341,
		levelExp5 = 130428,
		levelExp6 = 136782,
		levelExp7 = 136782
	},
	[170] = {
		id = 170,
		levelExp1 = 52694,
		levelExp2 = 63232,
		levelExp3 = 79039,
		levelExp4 = 105385,
		levelExp5 = 131733,
		levelExp6 = 138150,
		levelExp7 = 138150
	},
	[171] = {
		id = 171,
		levelExp1 = 53220,
		levelExp2 = 63864,
		levelExp3 = 79830,
		levelExp4 = 106439,
		levelExp5 = 133050,
		levelExp6 = 139532,
		levelExp7 = 139532
	},
	[172] = {
		id = 172,
		levelExp1 = 53753,
		levelExp2 = 64503,
		levelExp3 = 80628,
		levelExp4 = 107503,
		levelExp5 = 134381,
		levelExp6 = 140927,
		levelExp7 = 140927
	},
	[173] = {
		id = 173,
		levelExp1 = 54290,
		levelExp2 = 65148,
		levelExp3 = 81434,
		levelExp4 = 108578,
		levelExp5 = 135724,
		levelExp6 = 142336,
		levelExp7 = 142336
	},
	[174] = {
		id = 174,
		levelExp1 = 54833,
		levelExp2 = 65799,
		levelExp3 = 82249,
		levelExp4 = 109664,
		levelExp5 = 137082,
		levelExp6 = 143760,
		levelExp7 = 143760
	},
	[175] = {
		id = 175,
		levelExp1 = 55381,
		levelExp2 = 66457,
		levelExp3 = 83071,
		levelExp4 = 110761,
		levelExp5 = 138452,
		levelExp6 = 145197,
		levelExp7 = 145197
	},
	[176] = {
		id = 176,
		levelExp1 = 55935,
		levelExp2 = 67122,
		levelExp3 = 83902,
		levelExp4 = 111868,
		levelExp5 = 139837,
		levelExp6 = 146649,
		levelExp7 = 146649
	},
	[177] = {
		id = 177,
		levelExp1 = 56495,
		levelExp2 = 67793,
		levelExp3 = 84741,
		levelExp4 = 112987,
		levelExp5 = 141235,
		levelExp6 = 148116,
		levelExp7 = 148116
	},
	[178] = {
		id = 178,
		levelExp1 = 57060,
		levelExp2 = 68471,
		levelExp3 = 85588,
		levelExp4 = 114117,
		levelExp5 = 142648,
		levelExp6 = 149597,
		levelExp7 = 149597
	},
	[179] = {
		id = 179,
		levelExp1 = 57630,
		levelExp2 = 69156,
		levelExp3 = 86444,
		levelExp4 = 115258,
		levelExp5 = 144074,
		levelExp6 = 151093,
		levelExp7 = 151093
	},
	[180] = {
		id = 180,
		levelExp1 = 58206,
		levelExp2 = 69847,
		levelExp3 = 87308,
		levelExp4 = 116410,
		levelExp5 = 145515,
		levelExp6 = 152604,
		levelExp7 = 152604
	},
	[181] = {
		id = 181,
		levelExp1 = 58789,
		levelExp2 = 70546,
		levelExp3 = 88182,
		levelExp4 = 117575,
		levelExp5 = 146970,
		levelExp6 = 154130,
		levelExp7 = 154130
	},
	[182] = {
		id = 182,
		levelExp1 = 59376,
		levelExp2 = 71251,
		levelExp3 = 89063,
		levelExp4 = 118750,
		levelExp5 = 148440,
		levelExp6 = 155671,
		levelExp7 = 155671
	},
	[183] = {
		id = 183,
		levelExp1 = 59970,
		levelExp2 = 71964,
		levelExp3 = 89954,
		levelExp4 = 119938,
		levelExp5 = 149924,
		levelExp6 = 157228,
		levelExp7 = 157228
	},
	[184] = {
		id = 184,
		levelExp1 = 60570,
		levelExp2 = 72683,
		levelExp3 = 90854,
		levelExp4 = 121137,
		levelExp5 = 151423,
		levelExp6 = 158800,
		levelExp7 = 158800
	},
	[185] = {
		id = 185,
		levelExp1 = 61176,
		levelExp2 = 73410,
		levelExp3 = 91762,
		levelExp4 = 122349,
		levelExp5 = 152938,
		levelExp6 = 160388,
		levelExp7 = 160388
	},
	[186] = {
		id = 186,
		levelExp1 = 61787,
		levelExp2 = 74144,
		levelExp3 = 92680,
		levelExp4 = 123572,
		levelExp5 = 154467,
		levelExp6 = 161992,
		levelExp7 = 161992
	},
	[187] = {
		id = 187,
		levelExp1 = 62405,
		levelExp2 = 74886,
		levelExp3 = 93606,
		levelExp4 = 124808,
		levelExp5 = 156012,
		levelExp6 = 163612,
		levelExp7 = 163612
	},
	[188] = {
		id = 188,
		levelExp1 = 63029,
		levelExp2 = 75635,
		levelExp3 = 94543,
		levelExp4 = 126056,
		levelExp5 = 157572,
		levelExp6 = 165248,
		levelExp7 = 165248
	},
	[189] = {
		id = 189,
		levelExp1 = 63660,
		levelExp2 = 76391,
		levelExp3 = 95488,
		levelExp4 = 127316,
		levelExp5 = 159147,
		levelExp6 = 166900,
		levelExp7 = 166900
	},
	[190] = {
		id = 190,
		levelExp1 = 64296,
		levelExp2 = 77155,
		levelExp3 = 96443,
		levelExp4 = 128590,
		levelExp5 = 160739,
		levelExp6 = 168569,
		levelExp7 = 168569
	},
	[191] = {
		id = 191,
		levelExp1 = 64939,
		levelExp2 = 77926,
		levelExp3 = 97407,
		levelExp4 = 129875,
		levelExp5 = 162346,
		levelExp6 = 170255,
		levelExp7 = 170255
	},
	[192] = {
		id = 192,
		levelExp1 = 65588,
		levelExp2 = 78706,
		levelExp3 = 98381,
		levelExp4 = 131174,
		levelExp5 = 163970,
		levelExp6 = 171958,
		levelExp7 = 171958
	},
	[193] = {
		id = 193,
		levelExp1 = 66244,
		levelExp2 = 79493,
		levelExp3 = 99365,
		levelExp4 = 132486,
		levelExp5 = 165610,
		levelExp6 = 173677,
		levelExp7 = 173677
	},
	[194] = {
		id = 194,
		levelExp1 = 66907,
		levelExp2 = 80288,
		levelExp3 = 100359,
		levelExp4 = 133811,
		levelExp5 = 167266,
		levelExp6 = 175414,
		levelExp7 = 175414
	},
	[195] = {
		id = 195,
		levelExp1 = 67576,
		levelExp2 = 81090,
		levelExp3 = 101362,
		levelExp4 = 135149,
		levelExp5 = 168938,
		levelExp6 = 177168,
		levelExp7 = 177168
	},
	[196] = {
		id = 196,
		levelExp1 = 68252,
		levelExp2 = 81901,
		levelExp3 = 102376,
		levelExp4 = 136500,
		levelExp5 = 170628,
		levelExp6 = 178940,
		levelExp7 = 178940
	},
	[197] = {
		id = 197,
		levelExp1 = 68934,
		levelExp2 = 82720,
		levelExp3 = 103400,
		levelExp4 = 137865,
		levelExp5 = 172334,
		levelExp6 = 180729,
		levelExp7 = 180729
	},
	[198] = {
		id = 198,
		levelExp1 = 69623,
		levelExp2 = 83548,
		levelExp3 = 104434,
		levelExp4 = 139244,
		levelExp5 = 174057,
		levelExp6 = 182537,
		levelExp7 = 182537
	},
	[199] = {
		id = 199,
		levelExp1 = 70320,
		levelExp2 = 84383,
		levelExp3 = 105478,
		levelExp4 = 140637,
		levelExp5 = 175798,
		levelExp6 = 184362,
		levelExp7 = 184362
	},
	[200] = {
		id = 200,
		levelExp1 = 71023,
		levelExp2 = 85227,
		levelExp3 = 106533,
		levelExp4 = 142043,
		levelExp5 = 177556,
		levelExp6 = 186205,
		levelExp7 = 186205
	},

	__size = 200,
	__default = {
		__index = {
			
		}
	}
}
return csv.held_item.level