--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {__size = 0}, 
	[4] = {[90261] = 50, ['gold'] = 600000, [501] = 5, __size = 3}, 
	[10] = {['gold'] = 600000, [90881] = 50, [501] = 5, __size = 3}, 
	[11] = {[91171] = 50, ['gold'] = 600000, [501] = 5, __size = 3}, 
	[19] = {['gold'] = 600000, [91311] = 50, [501] = 5, __size = 3}, 
	[23] = {[92241] = 50, ['gold'] = 600000, [501] = 5, __size = 3}, __size = 6}
local __data_t__activeCost = {
	[881] = __predefine_t__[10],
	[1314] = __predefine_t__[19],
	[1173] = __predefine_t__[11],
	[1311] = __predefine_t__[19],
	[1171] = __predefine_t__[11],
	[884] = __predefine_t__[10],
	["default"] = __predefine_t__[1],
	[261] = __predefine_t__[4],
	[264] = __predefine_t__[4],
	[2241] = __predefine_t__[23],
	[2243] = __predefine_t__[23]
}
local __data_t__awakeCost = {
	["default"] = __predefine_t__[1]
}

csv['aid']['aid'] = {
	[161] = {
		id = 161,
		fightPointFactor = 0.003,
		stageMaterialID = 90161,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {['gold'] = 600000, [90161] = 50, [501] = 5, __size = 3}
	},
	[241] = {
		id = 241,
		fightPointFactor = 0.003,
		stageMaterialID = 90241,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {['gold'] = 600000, [90241] = 50, [501] = 5, __size = 3}
	},
	[261] = {
		id = 261,
		fightPointFactor = 0.003,
		stageMaterialID = 90261,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = __data_t__activeCost[261]
		-- {[90261] = 50, ['gold'] = 600000, [501] = 5, __size = 3}
	},
	[264] = {
		id = 264,
		fightPointFactor = 0.003,
		stageMaterialID = 90261,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = __data_t__activeCost[264]
		-- {[90261] = 50, ['gold'] = 600000, [501] = 5, __size = 3}
	},
	[381] = {
		id = 381,
		fightPointFactor = 0.003,
		stageMaterialID = 90381,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {['gold'] = 600000, [90381] = 50, [501] = 5, __size = 3}
	},
	[601] = {
		id = 601,
		fightPointFactor = 0.003,
		stageMaterialID = 90601,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {['gold'] = 600000, [90601] = 50, [501] = 5, __size = 3}
	},
	[721] = {
		id = 721,
		fightPointFactor = 0.003,
		stageMaterialID = 90721,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {['gold'] = 600000, [90721] = 50, [501] = 5, __size = 3}
	},
	[731] = {
		id = 731,
		fightPointFactor = 0.003,
		stageMaterialID = 90731,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {['gold'] = 600000, [90731] = 50, [501] = 5, __size = 3}
	},
	[741] = {
		id = 741,
		fightPointFactor = 0.003,
		stageMaterialID = 90741,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {['gold'] = 600000, [90741] = 50, [501] = 5, __size = 3}
	},
	[881] = {
		id = 881,
		fightPointFactor = 0.003,
		stageMaterialID = 90881,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = __data_t__activeCost[881]
		-- {['gold'] = 600000, [90881] = 50, [501] = 5, __size = 3}
	},
	[884] = {
		id = 884,
		fightPointFactor = 0.003,
		stageMaterialID = 90881,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = __data_t__activeCost[884]
		-- {['gold'] = 600000, [90881] = 50, [501] = 5, __size = 3}
	},
	[1171] = {
		id = 1171,
		fightPointFactor = 0.003,
		stageMaterialID = 91171,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = __data_t__activeCost[1171]
		-- {[91171] = 50, ['gold'] = 600000, [501] = 5, __size = 3}
	},
	[1173] = {
		id = 1173,
		fightPointFactor = 0.003,
		stageMaterialID = 91171,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = __data_t__activeCost[1173]
		-- {[91171] = 50, ['gold'] = 600000, [501] = 5, __size = 3}
	},
	[1221] = {
		id = 1221,
		fightPointFactor = 0.003,
		stageMaterialID = 91221,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {['gold'] = 600000, [91221] = 50, [501] = 5, __size = 3}
	},
	[1231] = {
		id = 1231,
		fightPointFactor = 0.003,
		stageMaterialID = 91231,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {[91231] = 50, ['gold'] = 600000, [501] = 5, __size = 3}
	},
	[1241] = {
		id = 1241,
		fightPointFactor = 0.003,
		stageMaterialID = 91241,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {['gold'] = 600000, [91241] = 50, [501] = 5, __size = 3}
	},
	[1261] = {
		id = 1261,
		awakeDemandAidLevel = 30,
		awakeSequenceID = 1,
		fightPointFactor = 0.003,
		stageMaterialID = 91261,
		stageSequenceID = 2,
		levelSequenceID = 2,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		awakeMaterialID = 98002,
		awakeDemandAidStage = 3,
		activeCost = {['gold'] = 1200000, [91261] = 100, [501] = 10, __size = 3},
		awakeCost = {['gold'] = 2000000, [521] = 10, [98002] = 1, [501] = 5, __size = 4}
	},
	[1271] = {
		id = 1271,
		awakeDemandAidLevel = 30,
		awakeSequenceID = 1,
		fightPointFactor = 0.003,
		stageMaterialID = 91271,
		stageSequenceID = 2,
		levelSequenceID = 2,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		awakeMaterialID = 98003,
		awakeDemandAidStage = 3,
		activeCost = {['gold'] = 1200000, [91271] = 100, [501] = 10, __size = 3},
		awakeCost = {['gold'] = 2000000, [98003] = 1, [521] = 10, [501] = 5, __size = 4}
	},
	[1311] = {
		id = 1311,
		fightPointFactor = 0.003,
		stageMaterialID = 91311,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = __data_t__activeCost[1311]
		-- {['gold'] = 600000, [91311] = 50, [501] = 5, __size = 3}
	},
	[1314] = {
		id = 1314,
		fightPointFactor = 0.003,
		stageMaterialID = 91311,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = __data_t__activeCost[1314]
		-- {['gold'] = 600000, [91311] = 50, [501] = 5, __size = 3}
	},
	[1911] = {
		id = 1911,
		fightPointFactor = 0.003,
		stageMaterialID = 91911,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {[91911] = 50, ['gold'] = 600000, [501] = 5, __size = 3}
	},
	[1921] = {
		id = 1921,
		fightPointFactor = 0.003,
		stageMaterialID = 91921,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {[91921] = 50, ['gold'] = 600000, [501] = 5, __size = 3}
	},
	[1931] = {
		id = 1931,
		fightPointFactor = 0.003,
		stageMaterialID = 91931,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {['gold'] = 600000, [91931] = 50, [501] = 5, __size = 3}
	},
	[2241] = {
		id = 2241,
		fightPointFactor = 0.003,
		stageMaterialID = 92241,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = __data_t__activeCost[2241]
		-- {[92241] = 50, ['gold'] = 600000, [501] = 5, __size = 3}
	},
	[2243] = {
		id = 2243,
		fightPointFactor = 0.003,
		stageMaterialID = 92241,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = __data_t__activeCost[2243]
		-- {[92241] = 50, ['gold'] = 600000, [501] = 5, __size = 3}
	},
	[2351] = {
		id = 2351,
		awakeDemandAidLevel = 30,
		awakeSequenceID = 1,
		fightPointFactor = 0.003,
		stageMaterialID = 92351,
		stageSequenceID = 2,
		levelSequenceID = 2,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		awakeMaterialID = 98009,
		awakeDemandAidStage = 3,
		activeCost = {['gold'] = 1200000, [92351] = 100, [501] = 10, __size = 3},
		awakeCost = {['gold'] = 2000000, [501] = 5, [98009] = 1, [521] = 10, __size = 4}
	},
	[2361] = {
		id = 2361,
		awakeDemandAidLevel = 30,
		awakeSequenceID = 1,
		fightPointFactor = 0.003,
		stageMaterialID = 92361,
		stageSequenceID = 2,
		levelSequenceID = 2,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		awakeMaterialID = 98010,
		awakeDemandAidStage = 3,
		activeCost = {['gold'] = 1200000, [92361] = 100, [501] = 10, __size = 3},
		awakeCost = {['gold'] = 2000000, [98010] = 1, [521] = 10, [501] = 5, __size = 4}
	},
	[2381] = {
		id = 2381,
		awakeDemandAidLevel = 30,
		awakeSequenceID = 1,
		fightPointFactor = 0.003,
		stageMaterialID = 92381,
		stageSequenceID = 2,
		levelSequenceID = 2,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		awakeMaterialID = 98011,
		awakeDemandAidStage = 3,
		activeCost = {['gold'] = 1200000, [92381] = 100, [501] = 10, __size = 3},
		awakeCost = {[98011] = 1, ['gold'] = 2000000, [521] = 10, [501] = 5, __size = 4}
	},
	[2391] = {
		id = 2391,
		awakeDemandAidLevel = 30,
		awakeSequenceID = 1,
		fightPointFactor = 0.003,
		stageMaterialID = 92391,
		stageSequenceID = 2,
		levelSequenceID = 2,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		awakeMaterialID = 98012,
		awakeDemandAidStage = 3,
		activeCost = {['gold'] = 1200000, [501] = 10, [92391] = 100, __size = 3},
		awakeCost = {[98012] = 1, ['gold'] = 2000000, [521] = 10, [501] = 5, __size = 4}
	},
	[2431] = {
		id = 2431,
		awakeDemandAidLevel = 30,
		awakeSequenceID = 1,
		fightPointFactor = 0.003,
		stageMaterialID = 92431,
		stageSequenceID = 2,
		levelSequenceID = 2,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		awakeMaterialID = 98014,
		awakeDemandAidStage = 3,
		activeCost = {['gold'] = 1200000, [92431] = 100, [501] = 10, __size = 3},
		awakeCost = {['gold'] = 2000000, [501] = 5, [521] = 10, [98014] = 1, __size = 4}
	},
	[2471] = {
		id = 2471,
		fightPointFactor = 0.003,
		stageMaterialID = 92471,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {['gold'] = 600000, [92471] = 50, [501] = 5, __size = 3}
	},
	[2721] = {
		id = 2721,
		fightPointFactor = 0.003,
		stageMaterialID = 92721,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {['gold'] = 600000, [92721] = 50, [501] = 5, __size = 3}
	},
	[3151] = {
		id = 3151,
		fightPointFactor = 0.003,
		stageMaterialID = 93151,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {['gold'] = 600000, [93151] = 50, [501] = 5, __size = 3}
	},
	[3351] = {
		id = 3351,
		fightPointFactor = 0.003,
		stageMaterialID = 93351,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {[93351] = 50, ['gold'] = 600000, [501] = 5, __size = 3}
	},
	[3661] = {
		id = 3661,
		fightPointFactor = 0.003,
		stageMaterialID = 93661,
		stageSequenceID = 1,
		levelSequenceID = 1,
		activeDemandStar = 11,
		activeDemandAdvance = 14,
		activeDemandLevel = 75,
		activeCost = {[93661] = 50, ['gold'] = 600000, [501] = 5, __size = 3}
	},
	__size = 35,
	__default = {
		__index = {
			awakeDemandAidLevel = 60,
			awakeSequenceID = 0,
			fightPointFactor = 0,
			stageMaterialID = 0,
			stageSequenceID = 0,
			levelSequenceID = 0,
			activeDemandStar = 8,
			activeDemandAdvance = 10,
			activeDemandLevel = 90,
			awakeMaterialID = 0,
			awakeDemandAidStage = 7,
			activeCost = __data_t__activeCost["default"]	--[[ {__size = 0}]],
			awakeCost = __data_t__awakeCost["default"]	--[[ {__size = 0}]]
		}
	}
}
return csv.aid.aid