--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {__size = 0}

csv['cross']['supremacy']['division'] = {
	[1] = {
		id = 1,
		servers = {'game.dev.14'},
		division = 1,
		serviceCSVID = 34
	},
	[2] = {
		id = 2,
		servers = {'game.dev.13'},
		division = 2,
		serviceCSVID = 34
	},
	__size = 2,
	__default = {
		__index = {
			servers = {},
			division = 0,
			serviceCSVID = 0
		}
	}
}
return csv.cross.supremacy.division