--
-- auto generated by csv2lua
-- date: datetime.now()
--
-- DON'T EDIT THIS FILE !!!
--
local __predefine_t__ = {
	[1] = {['coin7'] = 200, ['gold'] = 200000, ['coin8'] = 3000, __size = 3}, 
	[2] = {['gold'] = 200000, [611] = 50, ['coin8'] = 3000, __size = 3}, 
	[3] = {['gold'] = 200000, [5000] = 100, ['coin8'] = 3000, __size = 3}, 
	[4] = {['gold'] = 600000, ['coin8'] = 9000, [501] = 1, __size = 3}, __size = 4}
local __data_t__weekAward = {
	[1] = __predefine_t__[1],
	[3] = __predefine_t__[3],
	[2] = __predefine_t__[2],
	[5] = __predefine_t__[1],
	[4] = __predefine_t__[4],
	[7] = __predefine_t__[3],
	[6] = __predefine_t__[2],
	[8] = __predefine_t__[4]
}

csv['cross']['supremacy']['week_award'] = {
	[1] = {
		id = 1,
		fightTimes = 3,
		weekAward = __data_t__weekAward[1]
		-- {['coin7'] = 200, ['gold'] = 200000, ['coin8'] = 3000, __size = 3}
	},
	[2] = {
		id = 2,
		fightTimes = 6,
		weekAward = __data_t__weekAward[2]
		-- {['gold'] = 200000, [611] = 50, ['coin8'] = 3000, __size = 3}
	},
	[3] = {
		id = 3,
		fightTimes = 9,
		weekAward = __data_t__weekAward[3]
		-- {['gold'] = 200000, [5000] = 100, ['coin8'] = 3000, __size = 3}
	},
	[4] = {
		id = 4,
		fightTimes = 12,
		weekAward = __data_t__weekAward[4]
		-- {['gold'] = 600000, ['coin8'] = 9000, [501] = 1, __size = 3}
	},
	[5] = {
		id = 5,
		fightTimes = 15,
		weekAward = __data_t__weekAward[5]
		-- {['coin7'] = 200, ['gold'] = 200000, ['coin8'] = 3000, __size = 3}
	},
	[6] = {
		id = 6,
		fightTimes = 18,
		weekAward = __data_t__weekAward[6]
		-- {['gold'] = 200000, [611] = 50, ['coin8'] = 3000, __size = 3}
	},
	[7] = {
		id = 7,
		fightTimes = 21,
		weekAward = __data_t__weekAward[7]
		-- {['gold'] = 200000, [5000] = 100, ['coin8'] = 3000, __size = 3}
	},
	[8] = {
		id = 8,
		fightTimes = 24,
		weekAward = __data_t__weekAward[8]
		-- {['gold'] = 600000, ['coin8'] = 9000, [501] = 1, __size = 3}
	},
	__size = 8,
	__default = {
		__index = {
			
		}
	}
}
return csv.cross.supremacy.week_award